### ISSUE TITLE
DelayRecoveryException

### ISSUE THREAD

**Issue by floragunncom** [floragunncom/search-guard#101]
Sometimes we see an DelayRecoveryException

<pre>[ERROR][com.floragunn.searchguard.ssl.transport.SearchGuardSSLTransportService$Interceptor] Unexpected SSL exception (SG 14) due to DelayRecoveryException[source node does not have the shard listed in its state as allocated on the node]
mar 04 17:05:06 eshost elasticsearch[3114]: DelayRecoveryException[source node does not have the shard listed in its state as allocated on the node]
mar 04 17:05:06 eshost elasticsearch[3114]: at org.elasticsearch.indices.recovery.RecoverySource.recover(RecoverySource.java:109)
mar 04 17:05:06 eshost elasticsearch[3114]: at org.elasticsearch.indices.recovery.RecoverySource.access$200(RecoverySource.java:52)
mar 04 17:05:06 eshost elasticsearch[3114]: at org.elasticsearch.indices.recovery.RecoverySource$StartRecoveryTransportRequestHandler.messageReceived(RecoverySource.java:135)
mar 04 17:05:06 eshost elasticsearch[3114]: at org.elasticsearch.indices.recovery.RecoverySource$StartRecoveryTransportRequestHandler.messageReceived(RecoverySource.java:132)
mar 04 17:05:06 eshost elasticsearch[3114]: at com.floragunn.searchguard.ssl.transport.SearchGuardSSLTransportService.messageReceivedDecorate(SearchGuardSSLTransportService.java:137)
mar 04 17:05:06 eshost elasticsearch[3114]: at com.floragunn.searchguard.transport.SearchGuardTransportService.messageReceivedDecorate(SearchGuardTransportService.java:180)
mar 04 17:05:06 eshost elasticsearch[3114]: at com.floragunn.searchguard.ssl.transport.SearchGuardSSLTransportService$Interceptor.messageReceived(SearchGuardSSLTransportService.java:107)
mar 04 17:05:06 eshost elasticsearch[3114]: at org.elasticsearch.transport.netty.MessageChannelHandler$RequestHandler.doRun(MessageChannelHandler.java:299)
mar 04 17:05:06 eshost elasticsearch[3114]: at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
mar 04 17:05:06 eshost elasticsearch[3114]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
mar 04 17:05:06 eshost elasticsearch[3114]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
mar 04 17:05:06 eshost elasticsearch[3114]: at java.lang.Thread.run(Thread.java:745)
</pre>

**Comment by floragunncom** [comment]
see this when creating an index
