### ISSUE TITLE
Spark is unable to write to Elasticsearch

### ISSUE THREAD

**Issue by vinayakakr** [floragunncom/search-guard#120]
Hello,

We are  using  SG 1.7  .  authorized users are able to create indexes manually .

We  have spark jobs that will create indexes every day and  those jobs are failing by not able to create indexes. we are getting below exception. Is this the issue with search Guard?

[RemoteTransportException[[es-test-master][inet[/hostname:9300]][indices:admin/create]]; nested: RuntimeException[Unauthenticated request (SEARCHGUARD_UNAUTH_REQ) for action indices:admin/create]; ]]
	at com.xxx.spark.ElasticsearchClientLib.ESClient.call(ESClient.java:136)
	at com.xxx.spark.ElasticsearchClientLib.ESClient.call(ESClient.java:17)
	at org.apache.spark.api.java.JavaRDDLike$$anonfun$foreachPartitionAsync$1.apply(JavaRDDLike.scala:678)
	at org.apache.spark.api.java.JavaRDDLike$$anonfun$foreachPartitionAsync$1.apply(JavaRDDLike.scala:678)
	at org.apache.spark.SparkContext$$anonfun$37.apply(SparkContext.scala:1992)
	at org.apache.spark.SparkContext$$anonfun$37.apply(SparkContext.scala:1992)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
	at org.apache.spark.scheduler.Task.run(Task.scala:89)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:214)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by floragunncom** [comment]
Auto close this issue because it refers to Search Guard 1 which is decommissioned now. For details pls. see https://github.com/floragunncom/search-guard-attic/wiki . If this issue is still valid for Search Guard 2 (for elasticsearch 2.x) feel free to reopen it (or to file a new one). Pls. do not longer report issues for Search Guard 1 (for elasticsearch 1.x). We sincerely apologize for the inconvenience this may have caused. Thanks for contributing!
