### ISSUE TITLE
SSLv2Hello is disabled

### ISSUE THREAD

**Issue by PKFresher** [floragunncom/search-guard#121]
I  use  setup_sg.sh  sg_init.sh to   init SG SSL

  I run  ES, then curl -Ss  \
  --insecure \
  -E /vagrant/ch.pem \
  --key  /vagrant/search-guard-ssl/example-pki-scripts/kirk.key.pem \
  https://localhost:9200/_searchguard/sslinfo?pretty

ESlog show  ：
             [2016-04-19 15:16:55,355][WARN ][com.floragunn.searchguard.ssl.http.netty.SearchGuardSSLNettyHttpServerTransport] [Nico Minoru] Caught exception while handling client http traffic, closing connection [id: 0x78ef59c0, /127.0.0.1:39458 => /127.0.0.1:9200]
javax.net.ssl.SSLHandshakeException: SSLv2Hello is disabled
  I do not know  how to solve it.

**Comment by floragunncom** [comment]
try adding ``--tlsv1`` to the curl command

**Comment by PKFresher** [comment]
I try this

curl -Ss  \
  --insecure \
  -E /vagrant/ch.pem \
  --key  /vagrant/search-guard-ssl/example-pki-scripts/kirk.key.pem \
  --tlsv \
  https://localhost:9200/_searchguard/sslinfo?pretty

ES log:
Caused by: javax.net.ssl.SSLHandshakeException: Client requested protocol TLSv1 not enabled or not supported

I try --tlsv1.2
   reply  --tlsv1.2  is unknow

**Comment by floragunncom** [comment]
curl seems too old and/or is not compiled with tls 1.1 or 1.2 support. tls 1.0 and SSL 2/3 is disabled due to security issues.

What does ``curl --version`` and ``curl --help | grep TLS`` version show? For the latter one you should see something like
``` 
-1, --tlsv1         Use => TLSv1 (SSL)
     --tlsv1.0       Use TLSv1.0 (SSL)
     --tlsv1.1       Use TLSv1.1 (SSL)
     --tlsv1.2       Use TLSv1.2 (SSL)
```

curl should be at least >= 7.43.0

**Comment by PKFresher** [comment]
curl --version :
    curl 7.15.5 (x86_64-redhat-linux-gnu) libcurl/7.15.5 OpenSSL/0.9.8b zlib/1.2.3 libidn/0.6.5
Protocols: tftp ftp telnet dict ldap http file https ftps 
Features: GSS-Negotiate IDN IPv6 Largefile NTLM SSL libz

curl --help | grep TLS:
   
   --ftp-ssl       Try SSL/TLS for the ftp transfer (F)
    --ftp-ssl-reqd  Require SSL/TLS for the ftp transfer (F)
 -1/--tlsv1         Use TLSv1 (SSL)

**Comment by PKFresher** [comment]
I am very grateful for your help   but  It does not work..
I update curl to 7.48.0
 curl   -V
curl 7.48.0 (x86_64-pc-linux-gnu) libcurl/7.48.0 OpenSSL/0.9.8b zlib/1.2.3
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: IPv6 Largefile NTLM NTLM_WB SSL libz UnixSockets 

Should I  update OpenSSL ?




I try   again
--tlsv1.1   --tlsv1.2  respone    curl: (35) Unsupported SSL protocol version   
--tlsv1.0  --tlsv1       curl: (35) error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure
AND  ES log :Caused by: javax.net.ssl.SSLHandshakeException: Client requested protocol TLSv1 not enabled or not supported

**Comment by floragunncom** [comment]
Pls do also update OpenSSL, 0.9.8b is very old. 
``curl --help | grep TLS`` 
should show 
``--tlsv1.2       Use TLSv1.2 (SSL)``

**Comment by PKFresher** [comment]
curl --help | grep TLS

     show:-1, --tlsv1         Use >= TLSv1 (SSL)
     --tlsv1.0       Use TLSv1.0 (SSL)
     --tlsv1.1       Use TLSv1.1 (SSL)
     --tlsv1.2       Use TLSv1.2 (SSL)
     --tlsuser USER  TLS username
     --tlspassword STRING  TLS password
     --tlsauthtype STRING  TLS authentication type (default: SRP)

when I use--tlsv1.2 or --tlsv1.1  \   respone   curl: (35) Unsupported SSL protocol version

when  use  ----tlsv1   
                Pis :

[2016-04-20 14:03:01,886][WARN ][com.floragunn.searchguard.ssl.http.netty.SearchGuardSSLNettyHttpServerTransport] [Phil Urich] Caught exception while handling client http traffic, closing connection [id: 0x68c18564, /127.0.0.1:51968 => /127.0.0.1:9200]
javax.net.ssl.SSLHandshakeException: Client requested protocol TLSv1 not enabled or not supported
	at sun.security.ssl.Handshaker.checkThrown(Handshaker.java:1364)
	at sun.security.ssl.SSLEngineImpl.checkTaskThrown(SSLEngineImpl.java:513)
	at sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:790)
	at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:758)
	at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:624)
	at org.jboss.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1218)
	at org.jboss.netty.handler.ssl.SslHandler.decode(SslHandler.java:852)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:425)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
	at java.lang.Thread.run(Thread.java:722)
Caused by: javax.net.ssl.SSLHandshakeException: Client requested protocol TLSv1 not enabled or not supported
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1639)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:278)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:266)
	at sun.security.ssl.ServerHandshaker.clientHello(ServerHandshaker.java:422)
	at sun.security.ssl.ServerHandshaker.processMessage(ServerHandshaker.java:167)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:868)
	at sun.security.ssl.Handshaker$1.run(Handshaker.java:808)
	at sun.security.ssl.Handshaker$1.run(Handshaker.java:806)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.security.ssl.Handshaker$DelegatedTask.run(Handshaker.java:1301)
	at org.jboss.netty.handler.ssl.SslHandler.runDelegatedTasks(SslHandler.java:1392)
	at org.jboss.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1255)
	... 18 more
java version "1.7.0_07"
Need I open a new issues ?

**Comment by floragunncom** [comment]
pls do not open a issue, thats not a bug or a SG problem. It's clearly a problem with your curl.
If you can't get curl to work pls try wget or a similar tool which has TLS 1.1 or TLS 1.2 support.
Its als0 possible to use openssl for this like ``openssl s_client -connect localhost:9200``

And btw you should also upgrade oracle java to 1.8 (1.7 is old and there are no public security updates any more)

**Comment by PKFresher** [comment]
get it .
thank you very much
