### ISSUE TITLE
[TransportClient with search-guard] Impersonation not works

### ISSUE THREAD

**Issue by liangxibing** [floragunncom/search-guard#129]
* Search Guard search-guard-2-2.3.2.0-beta2, search-guard-ssl-2.3.2.9, Elasticsearch version 2.3.2 and TransportClient version 2.3.2(org.elasticsearch 2.3.2)

* Java 1.7.0_79 & Ubuntu 12.04 for TransportClient's environment and Java 1.7.0_80 & CentOS 7 for Elasticsearch + Search Guard's environment.

* 2 nodes in my cluster

* Bug description: 

I use below codes to insert some logs into ES e.g.:

```
        final Settings settings = Settings.settingsBuilder()
                .put("path.home", ".")
                .put("cluster.name", "my-application")
                .put("searchguard.ssl.transport.enabled", true)
                .put("searchguard.ssl.transport.keystore_filepath", "spock-keystore.jks")
                .put("searchguard.ssl.transport.truststore_filepath", "truststore.jks")
                .put("searchguard.ssl.transport.enforce_hostname_verification", false)
                .build();
        try (TransportClient tc = TransportClient.builder().settings(settings).addPlugin(SearchGuardSSLPlugin.class).build()) {

            tc.addTransportAddress(new InetSocketTransportAddress(new InetSocketAddress(nodeHost1, nodePort)));
            tc.addTransportAddress(new InetSocketTransportAddress(new InetSocketAddress(nodeHost2, nodePort)));
            String json = "{" +
                    "\"user\":\"liangxibing\"," +
                    "\"postDate\":\"2016-05-16\"," +
                    "\"message\":\"liangxibing trying out Elasticsearch\"" +
            "}";
            IndexResponse response = tc.prepareIndex("liangxibing", "test")
                    .putHeader("sg.impersonate.as", "spock")
                    .setSource(json)
                    .get();
            System.out.println(response.toString());
        }
```

However exception happens when TransportClient calls **addTransportAddress** (Before we put header of sg.impersonate.as):

```
信息: [Baphomet] Using [com.floragunn.searchguard.ssl.transport.SearchGuardSSLNettyTransport] as transport, overridden by [search-guard-ssl]
五月 17, 2016 6:55:14 下午 org.elasticsearch.client.transport.TransportClientNodesService$SimpleNodeSampler doSample
信息: [Baphomet] failed to get node info for {#transport#-1}{172.16.64.113}{172.16.64.113:9300}, disconnecting...
RemoteTransportException[[node-0][172.16.64.113:9300][cluster:monitor/nodes/liveness]]; nested: ElasticsearchSecurityException[Cannot authenticate User [name=CN=spock,OU=client,O=client,L=Test,C=DE, roles=[]]];
Caused by: ElasticsearchSecurityException[Cannot authenticate User [name=CN=spock,OU=client,O=client,L=Test,C=DE, roles=[]]]
	at com.floragunn.searchguard.transport.SearchGuardTransportService.messageReceivedDecorate(SearchGuardTransportService.java:304)
	at com.floragunn.searchguard.ssl.transport.SearchGuardSSLTransportService$Interceptor.messageReceived(SearchGuardSSLTransportService.java:129)
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:75)
	at org.elasticsearch.transport.netty.MessageChannelHandler.handleRequest(MessageChannelHandler.java:245)
	at com.floragunn.searchguard.ssl.transport.SearchGuardMessageChannelHandler.handleRequest(SearchGuardMessageChannelHandler.java:57)
	at org.elasticsearch.transport.netty.MessageChannelHandler.messageReceived(MessageChannelHandler.java:114)
	at com.floragunn.searchguard.ssl.transport.SearchGuardMessageChannelHandler.messageReceived(SearchGuardMessageChannelHandler.java:45)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:462)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:443)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.elasticsearch.common.netty.OpenChannelsHandler.handleUpstream(OpenChannelsHandler.java:75)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:462)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:443)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by floragunncom** [comment]
Thats not how impersonation works. The transport client itself connects with the DN of the certificate (``CN=spock,OU=client,O=client,L=Test,C=DE``). That needs to be a valid user (means: must be authenticated via one of the authentication_backends). Then in elasticsearch.yml you have to define that this user can impersonate to another user.

For example allow ``CN=spock,OU=client,O=client,L=Test,C=DE`` to impersonate as every other user:

<pre>
searchguard.authcz.impersonation_dn:
  "CN=spock,OU=client,O=client,L=Test,C=DE":
     - '*'
</pre>

But keep in mind that the user to which should be impersonated as (for example "worf") needs also to be a valid user (means: must exists in one of the authentication/authorization backends)

**Comment by liangxibing** [comment]
@floragunncom Thanks for your quickly response.
When I meet the problem, the situation likes below:
1. I generated truststore.jks by "./gen_root_ca.sh capass changeit", and I generated spock-keystore.jks by "./gen_client_node_cert.sh spock changeit capass", does it mean "CN=spock,OU=client,O=client,L=Test,C=DE" is already authenticated?
2. I have already set searchguard.authcz.impersonation_dn in elasticsearch.yml as below:
searchguard.authcz.impersonation_dn:
  "CN=spock,OU=client,O=client,L=Test,C=DE":
     - 'spock'
3. When TransportClient calls "addTransportAddress" function, will it begin to communicate with ES nodes? If so, whether it will meet some certificate problems as it doesn't include the headers "sg.impersonate.as" to tell the nodes which user it wants to impersonate?

**Comment by floragunncom** [comment]
have a look [here](https://github.com/floragunncom/search-guard/blob/master/src/test/java/com/floragunn/searchguard/SGTests.java#L971), this should give you a hint how it works

**Comment by liangxibing** [comment]
@floragunncom Thanks for your feedback.

I have already taken a look at your codes. I found that you use below way to fix the problem, right?

```
        tcSettings = Settings.builder().put("cluster.name", clustername)
                .put(settings)
                .put("searchguard.ssl.transport.keystore_filepath", getAbsoluteFilePathFromClassPath("spock-keystore.jks"))
                .put(SSLConfigConstants.SEARCHGUARD_SSL_TRANSPORT_KEYSTORE_ALIAS,"spock")
                .put("path.home", ".")
                **.put("request.headers.sg_impersonate_as", "worf")**
                .build();
```

If I understand correctly, I need use the newest codes to test this functionality as you change sg.impersonate.as to sg_impersonate_as. 
Could you kindly give the information that how can I install the search-guard plugin with this changes, or whether you release a new plugin such as search-guard-2-2.3.2.0-beta3?

Thanks again!

**Comment by floragunncom** [comment]
will be released within the next two hours

**Comment by floragunncom** [comment]
@liangxibing does it work for you with beta3?

**Comment by liangxibing** [comment]
@floragunncom 
Thanks for your support! We will test beta3 and give you feedback next Monday :)

**Comment by liangxibing** [comment]
@floragunncom 
Sorry for late reply.Basically it works now:
I have upgrade elasticsearch to 2.3.3, search-guard to 2.3.3-beta3, search-guard-ssl to 2.3.3.10. 
At first, I config elasticsearch.yml to let "CN=spock,OU=client,O=client,L=Test,C=DE" can impersonate spock, and when it impersonates spock, it indeed has no right to write documents.
Secondly, I config elasticsearch.yml to let "CN=spock,OU=client,O=client,L=Test,C=DE" can impersonate admin, and when it impersonates admin, it can wirte documents with authorization.
So I think this issue itself can be **closed**.

BTW:
Some days ago you mentioned:
For example allow CN=spock,OU=client,O=client,L=Test,C=DE to impersonate as every other user:

searchguard.authcz.impersonation_dn:
  "CN=spock,OU=client,O=client,L=Test,C=DE":
     - '*'

I have tried on elasticsearch2.3.3+search-guard2.3.3-bete3+search-guard-ssl2.3.3.10 however it doesn't work:

```
信息: [Harry Leland] failed to get node info for {#transport#-1}{172.16.64.131}{172.16.64.131:9300}, disconnecting...
RemoteTransportException[[node-0][172.16.64.131:9300][cluster:monitor/nodes/liveness]]; nested: ElasticsearchSecurityException[CN=spock,OU=client,O=client,L=Test,C=DE is not allowed to impersonate as admin];
Caused by: ElasticsearchSecurityException[CN=spock,OU=client,O=client,L=Test,C=DE is not allowed to impersonate as admin]
	at com.floragunn.searchguard.auth.BackendRegistry.impersonate(BackendRegistry.java:472)
	at com.floragunn.searchguard.transport.SearchGuardTransportService.messageReceivedDecorate(SearchGuardTransportService.java:300)
	at com.floragunn.searchguard.ssl.transport.SearchGuardSSLTransportService$Interceptor.messageReceived(SearchGuardSSLTransportService.java:128)
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:75)
	at org.elasticsearch.transport.netty.MessageChannelHandler.handleRequest(MessageChannelHandler.java:245)
	at com.floragunn.searchguard.ssl.transport.SearchGuardMessageChannelHandler.handleRequest(SearchGuardMessageChannelHandler.java:62)
	at org.elasticsearch.transport.netty.MessageChannelHandler.messageReceived(MessageChannelHandler.java:114)
	at com.floragunn.searchguard.ssl.transport.SearchGuardMessageChannelHandler.messageReceived(SearchGuardMessageChannelHandler.java:50)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:462)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:443)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.elasticsearch.common.netty.OpenChannelsHandler.handleUpstream(OpenChannelsHandler.java:75)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:462)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:443)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by floragunncom** [comment]
"CN=spock,OU=client,O=client,L=Test,C=DE is not allowed to impersonate as admin" fixed with https://github.com/floragunncom/search-guard/commit/63866f941dfe35c67da7d7e64ceb7bb1a4cc075b

**Comment by tingking23** [comment]
@liangxibing 您好，我用的是es2.3.4版本，能不能把您的怎么通过java连接到search-gurad加密的ES的方法告诉我下？谢谢！

**Comment by liangxibing** [comment]
@tingking23 Please take a look at https://github.com/floragunncom/search-guard/blob/master/src/test/java/com/floragunn/searchguard/SGTests.java

**Comment by tingking23** [comment]
@liangxibing thanks
