### ISSUE TITLE
The problem with the client node configuration

### ISSUE THREAD

**Issue by LazyerHong** [floragunncom/search-guard#139]
Here is my version:
	elasticsearch2.2.0
	search-guard-2-2.2.0.0-alpha2
	search-guard-ssl-2.2.0.6
	
Before the installed sg2, the elasticsearch is green.
I have installed the sg2 in the 3 data nodes. 1 data node is used as the client node.

the client node's elasticsearch yml is:
--------------------------------------------------
searchguard.authcz.admin_dn:
  - "CN=kirk,OU=client,O=client,l=tEst, C=De"

#SSL
searchguard.ssl.transport.enabled: true
searchguard.ssl.transport.keystore_filepath: kirk-keystore.jks
searchguard.ssl.transport.truststore_filepath: truststore.jks
searchguard.ssl.transport.enforce_hostname_verification: false
searchguard.ssl.http.enabled: true
searchguard.ssl.http.keystore_filepath: kirk-keystore.jks
searchguard.ssl.http.truststore_filepath: truststore.jks
searchguard.ssl.http.enable_openssl_if_available: true
searchguard.ssl.transport.enable_openssl_if_available: true
security.manager.enabled: false

------------------------------------------------

the other two nodes elasticsearch yml is:
--------------------------------------------------
#SSL
searchguard.ssl.transport.enabled: true
searchguard.ssl.transport.keystore_filepath: node-1-keystore.jks
searchguard.ssl.transport.truststore_filepath: truststore.jks
searchguard.ssl.transport.enforce_hostname_verification: false
searchguard.ssl.http.enabled: true
searchguard.ssl.http.keystore_filepath: node-1-keystore.jks
searchguard.ssl.http.truststore_filepath: truststore.jks
searchguard.ssl.http.enable_openssl_if_available: true
searchguard.ssl.transport.enable_openssl_if_available: true
security.manager.enabled: false

--------------------------------------------------

When i finished the configuration, I run the elasticsearch. There are some errors in the client node:
[internal:discovery/zen/unicast]]; nested: ElasticsearchSecurityException[Internal or shard requests not allowed from a client node];
Caused by: ElasticsearchSecurityException[Internal or shard requests not allowed from a client node]
	at com.floragunn.searchguard.transport.SearchGuardTransportService.messageReceivedDecorate(SearchGuardTransportService.java:183)
	at com.floragunn.searchguard.ssl.transport.SearchGuardSSLTransportService$Interceptor.messageReceived(SearchGuardSSLTransportService.java:107)
	at org.elasticsearch.transport.netty.MessageChannelHandler.handleRequest(MessageChannelHandler.java:244)
	at com.floragunn.searchguard.ssl.transport.SearchGuardMessageChannelHandler.handleRequest(SearchGuardMessageChannelHandler.java:57)
	at org.elasticsearch.transport.netty.MessageChannelHandler.messageReceived(MessageChannelHandler.java:114)
	at com.floragunn.searchguard.ssl.transport.SearchGuardMessageChannelHandler.messageReceived(SearchGuardMessageChannelHandler.java:45)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:462)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:443)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.elasticsearch.common.netty.OpenChannelsHandler.handleUpstream(OpenChannelsHandler.java:75)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:462)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:443)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
	
And there are some errors in the other node of cluster:
[2016-06-13 11:48:56,523][ERROR][com.floragunn.searchguard.ssl.transport.SearchGuardSSLTransportService$Interceptor]Unexpected SSL exception (SG 14) due to DelayRecoveryException[source node does not have the shard listed in its state as allocated on the node]
DelayRecoveryException[source node does not have the shard listed in its state as allocated on the node]
	at org.elasticsearch.indices.recovery.RecoverySource.recover(RecoverySource.java:109)
	at org.elasticsearch.indices.recovery.RecoverySource.access$200(RecoverySource.java:52)
	at org.elasticsearch.indices.recovery.RecoverySource$StartRecoveryTransportRequestHandler.messageReceived(RecoverySource.java:135)
	at org.elasticsearch.indices.recovery.RecoverySource$StartRecoveryTransportRequestHandler.messageReceived(RecoverySource.java:132)
	at com.floragunn.searchguard.ssl.transport.SearchGuardSSLTransportService.messageReceivedDecorate(SearchGuardSSLTransportService.java:137)
	at com.floragunn.searchguard.transport.SearchGuardTransportService.messageReceivedDecorate(SearchGuardTransportService.java:180)
	at com.floragunn.searchguard.ssl.transport.SearchGuardSSLTransportService$Interceptor.messageReceived(SearchGuardSSLTransportService.java:107)
	at org.elasticsearch.transport.netty.MessageChannelHandler$RequestHandler.doRun(MessageChannelHandler.java:299)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
	
	
Can you help me to how to solve the problem? thanks very much!

What is more, i also want to ask a question about the gen_node_cert.sh.  When i generate the keystore file, the ip is 10.0.0.1 in the gen_node_cert.sh script. Does the value need change to my node ip.

**Comment by floragunncom** [comment]
Java Node Client is not supported yet (https://github.com/floragunncom/search-guard/issues/128)
See  also https://github.com/floragunncom/search-guard/wiki/Terminology

**Comment by floragunncom** [comment]
In gen_node_cert.sh you need to add you server names or ip addresses (or both) to the SAN list to make hostname verifycation work: 
```-ext san=dns:$NODE_NAME.example.com,dns:localhost,ip:127.0.0.1,oid:1.2.3.4.5.5```. 
Pls see also https://github.com/floragunncom/search-guard-ssl-docs/blob/master/troubleshooting.md

**Comment by floragunncom** [comment]
Pls. consider updating to ES 2.3.3 and SG 2.3.3.0-rc1 and SG SSL 2.3.3.11.

**Comment by LazyerHong** [comment]
Thanks！

**Comment by LazyerHong** [comment]
Sorry, i can't understand one point :What is the mean of "Java Node Client is not support“? In my example, Did i use the Node Client? There are something i don't understand clearly. Thanks for your reply！

**Comment by floragunncom** [comment]
I guess you use a client certificate instead of a node certificate (the one with the oid), see https://github.com/floragunncom/search-guard/wiki/What-means-oid:1.2.3.4.5.5

**Comment by LazyerHong** [comment]
Is the client node necessary?   In my example, i have 3 data node, so i ran the example.sh and generated the kirk-keystore.jks, node-0-keystore.jks and node-1-keystore.jks.
The kirk-keystore is put under the one data node(192.26.97.112) which is regard as the client node. The node-0-keystore and node-1-keystore are put under the other two nodes(192.26.97.113 and 192.26.97.114).
Is the distribution right? Or can you tell me how the set in my three node? I have been confused for two weeks. Thank you very much!
