### ISSUE TITLE
3 node cluster SSL issue

### ISSUE THREAD

**Issue by twatson83** [floragunncom/search-guard#145]
Im having issues setting up SSL on a 3 node cluster.  

Here is the config used.

```
cluster.name: test
network.host: Test01
http.cors.enabled: true
http.cors.allow-origin: /.*/
http.cors.allow-credentials: true
discovery.zen.ping.unicast.hosts: ["Test01:9300", "Test02:9300", "Test03:9300"]
discovery.zen.minimum_master_nodes: 2

security.manager.enabled: false
searchguard.ssl.transport.keystore_filepath: node.jks
searchguard.ssl.transport.keystore_password: "xxx"
searchguard.ssl.transport.truststore_filepath: truststore.jks
searchguard.ssl.transport.truststore_password: "xxx"
searchguard.ssl.transport.enforce_hostname_verification: false
searchguard.ssl.transport.keystore_alias: node

searchguard.ssl.http.enabled: true
searchguard.ssl.http.keystore_filepath: node.jks
searchguard.ssl.http.keystore_password: "xxx"
searchguard.ssl.http.truststore_filepath: truststore.jks
searchguard.ssl.http.truststore_password: "xxx"
searchguard.ssl.http.keystore_alias: node

searchguard.authcz.admin_dn:
  - "CN=xxx, OU=xxx, O=xxx, L=xxx, ST=xxx, C=xxx"
```

And here is the error message.

```
[2016-06-21 16:16:12,157][WARN ][discovery.zen.ping.unicast] [Xavin] failed to send ping to [{#zen_unicast_1#}{xxx}{xxx/xxx:9300}]
RemoteTransportException[[Anything][xxx:9300][internal:discovery/zen/unicast]]; nested: ElasticsearchSecurityException[Internal or shard requests not allowed from a non-server node for transport type netty];
Caused by: ElasticsearchSecurityException[Internal or shard requests not allowed from a non-server node for transport type netty]
	at com.floragunn.searchguard.transport.SearchGuardTransportService.messageReceivedDecorate(SearchGuardTransportService.java:199)
	at com.floragunn.searchguard.ssl.transport.SearchGuardSSLTransportService$Interceptor.messageReceived(SearchGuardSSLTransportService.java:128)
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:75)
	at org.elasticsearch.transport.netty.MessageChannelHandler.handleRequest(MessageChannelHandler.java:245)
	at com.floragunn.searchguard.ssl.transport.SearchGuardMessageChannelHandler.handleRequest(SearchGuardMessageChannelHandler.java:62)
	at org.elasticsearch.transport.netty.MessageChannelHandler.messageReceived(MessageChannelHandler.java:114)
	at com.floragunn.searchguard.ssl.transport.SearchGuardMessageChannelHandler.messageReceived(SearchGuardMessageChannelHandler.java:50)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:462)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:443)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.elasticsearch.common.netty.OpenChannelsHandler.handleUpstream(OpenChannelsHandler.java:75)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:462)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:443)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by floragunncom** [comment]
Your node.jks need to contain a server node certificate (one with [OID 1.2.3.4.5.5](https://github.com/floragunncom/search-guard-docs/blob/9a3fa1e6faa8c69722708734af84ea03d80f1963/architecture.md)). Pls. see also 
* https://github.com/floragunncom/search-guard-docs/blob/master/installation.md and 
* https://github.com/floragunncom/search-guard-ssl/blob/master/example-pki-scripts/gen_node_cert.sh#L35

**Comment by dopey** [comment]
Hi, I've got the same issue. I added the OID so that now my cert contains the identifier as a SAN:

    output of keytool -printcert 
    ...
    #5: ObjectId: 2.5.29.17 Criticality=false
    SubjectAlternativeName [
      DNSName: elasticsearch-server
      Other-Name: Unrecognized ObjectIdentifier: 1.2.3.4.5.5
      IPAddress: 1.1.1.1
      IPAddress: 1.1.1.2
      IPAddress: 1.1.1.3
    ]
    ...

Before I added in the IPAdress entries searchguard was throwing the error: 

    java.security.cert.CertificateException: No subject alternative names matching IP address 1.1.1.1 found

Now that I have both IPAddresses and the otherName entry, I'm back to getting the `non-server netty transport error`.

I have both `search-guard-2` and `search-guard-ssl` installed, and below is the relevant portion of my elasticsearch.yml file.

    # Enable or disable node-to-node ssl encryption (default: true)
    #searchguard.ssl.transport.enabled: true
    # JKS or PKCS12 (default: JKS)
    searchguard.ssl.transport.keystore_type: JKS
    # Relative path to the keystore file (mandatory, this stores the server certificates), must be placed under the config/ dir
    searchguard.ssl.transport.keystore_filepath: "/etc/path/server-keystore"
    # Alias name (default: first alias which could be found)
    #searchguard.ssl.transport.keystore_alias: my_alias
    # Keystore password (default: changeit)
    searchguard.ssl.transport.keystore_password: XXX
    #
    # JKS or PKCS12 (default: JKS)
    searchguard.ssl.transport.truststore_type: JKS
    # Relative path to the truststore file (mandatory, this stores the client/root certificates), must be placed under the config/ dir
    searchguard.ssl.transport.truststore_filepath: "/etc/path/server-truststore"
    # Alias name (default: trust all aliases)
    #searchguard.ssl.transport.truststore_alias: my_alias
    # Truststore password (default: changeit)
    searchguard.ssl.transport.truststore_password: XXX
    # Enforce hostname verification (default: true)
    #searchguard.ssl.transport.enforce_hostname_verification: false
    # If hostname verification specify if hostname should be resolved (default: true)
    #searchguard.ssl.transport.resolve_hostname: true
    # Use native Open SSL instead of JDK SSL if available (default: true)
    #searchguard.ssl.transport.enable_openssl_if_available: false

Any advice on how to continue debugging would be much appreciated :)

**Comment by floragunncom** [comment]
@dopey 
For me the output looks like:
```
output of keytool -printcert 
#5: ObjectId: 2.5.29.17 Criticality=false
SubjectAlternativeName [
  DNSName: node-1.example.com
  DNSName: localhost
  IPAddress: 127.0.0.1
  OIDName: 1.2.3.4.5.5  <-------------
]
```

Do you generated the certificates with our scripts? If not pls share the command you used.

**Comment by dopey** [comment]
I use an open source library to generate the certs and manage my PKI. The library is called `certified` (https://github.com/rcrowley/certified) and the main differences are that it uses `openssl` instead of `keytool`, and it also manages my PKI and signs every new certificate using my CA. So when I generate a new cert, the process encapsulated in certified is:

    1) generate an openssl.cnf file
    2) generate a csr file
    3) generate a cert from the csr signed by my certificate authority 

The format of the SAN section in the `openssl.cnf` file is as follows:

    [san]
    DNS.1 = staging-elasticsearch-server
    DNS.2 = *.es.my-domain.com
    otherName.1 = 1.2.3.4.5.5;UTF8:some other identifier

I cribbed this format from a `stackexchange` question (http://stackoverflow.com/questions/38030893/how-to-format-an-oid-subject-alt-name-entry-in-a-openssl-cnf-file/38031068#38031068) I asked a few days ago -- the question being: how to correctly format an OID type SAN entry in an openssl.cnf file.

The response in the question cites the `openssl.cnf` documentation which says to use `othername` as the keyword for this sort of entry. So as far as I can tell, either there is another keyword that I should be using in the `openssl.cnf` file, or the comment section ("some other identifier") needs to be something specific that is being set by default by keytool. 

Given that `keytool -printcert` gives a different value for the OID SAN in our separate cases:

    OIDName: 1.2.3.4.5.5 ---> for you
    and 
    otherName.1 = 1.2.3.4.5.5;UTF8:some other identifier  -----> for me

Im thinking its an encoding issue.

**Comment by floragunncom** [comment]
Looking into the [openssl conf docs](https://www.openssl.org/docs/manmaster/apps/x509v3_config.html) maybe ```RID``is what you looking for. Can you try this?

**Comment by dopey** [comment]
@floragunncom that worked. Thanks a ton!

**Comment by floragunncom** [comment]
@twatson83 solved for you too?

**Comment by floragunncom** [comment]
no response from reporter, assume solved. If not pls. feel free to reopen.
