### ISSUE TITLE
Elasticsearch fails to start up with SG 2.3.3

### ISSUE THREAD

**Issue by ewolinetz** [floragunncom/search-guard#148]
This is with a single node within a container.  Currently when using Searchguard I am unable to start up ES -- am met with exception that the key specified is not able to be read however as the same user that is running Elasticsearch I am able to open the key successfully.  Generating key/truststores in same manner that I had done when using Searchguard v0.5.

I had tried with different permissions on the keyfile and even with a+rwx I receive this exception.

sh-4.2$ java -version
openjdk version "1.8.0_91"
OpenJDK Runtime Environment (build 1.8.0_91-b14)
OpenJDK 64-Bit Server VM (build 25.91-b14, mixed mode)

sh-4.2$ cat /etc/system-release
CentOS Linux release 7.2.1511 (Core)

ES Version 2.3.3-1
SG Versions:
com.floragunn/search-guard-ssl/2.3.3.13
com.floragunn/search-guard-2/2.3.3.1

```
sh-4.2$ ./run.sh 
+ secret_dir=/etc/elasticsearch/secret
+ regex='^([[:digit:]]+)([GgMm])$'
+ [[ 8G =~ ^([[:digit:]]+)([GgMm])$ ]]
+ num=8
+ unit=G
+ [[ G =~ [Gg] ]]
+ (( num = num * 1024 ))
+ [[ 8192 -lt 256 ]]
+ export 'ES_JAVA_OPTS= -Xms128M -Xmx4096m'
+ ES_JAVA_OPTS=' -Xms128M -Xmx4096m'
+ export ES_USER=elasticsearch
+ ES_USER=elasticsearch
+ export ES_GROUP=elasticsearch
+ ES_GROUP=elasticsearch
+ /usr/share/elasticsearch/bin/elasticsearch
[2016-06-24 22:02:18,423][INFO ][node                     ] [Surtur] version[2.3.3], pid[181], build[218bdf1/2016-05-17T15:40:04Z]
[2016-06-24 22:02:18,424][INFO ][node                     ] [Surtur] initializing ...
[2016-06-24 22:02:18,972][INFO ][plugins                  ] [Surtur] modules [reindex, lang-expression, lang-groovy], plugins [search-guard-ssl, cloud-kubernetes, search-guard-2], sites []
[2016-06-24 22:02:18,994][INFO ][env                      ] [Surtur] using [1] data paths, mounts [[/elasticsearch/persistent (/dev/xvda2)]], net usable_space [17.4gb], net total_space [24.9gb], spins? [possibly], types [xfs]
[2016-06-24 22:02:18,995][INFO ][env                      ] [Surtur] heap size [3.9gb], compressed ordinary object pointers [true]
Exception in thread "main" java.security.AccessControlException: access denied ("java.io.FilePermission" "/elasticsearch/searchguard.key" "read")
	at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
	at java.security.AccessController.checkPermission(AccessController.java:884)
	at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
	at java.lang.SecurityManager.checkRead(SecurityManager.java:888)
	at sun.nio.fs.UnixPath.checkRead(UnixPath.java:795)
	at sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:49)
	at sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:144)
	at sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
	at java.nio.file.Files.readAttributes(Files.java:1737)
	at java.nio.file.Files.isDirectory(Files.java:2192)
	at com.floragunn.searchguard.ssl.SearchGuardKeyStore.checkStorePath(SearchGuardKeyStore.java:526)
	at com.floragunn.searchguard.ssl.SearchGuardKeyStore.initSSLConfig(SearchGuardKeyStore.java:192)
	at com.floragunn.searchguard.ssl.SearchGuardKeyStore.<init>(SearchGuardKeyStore.java:139)
	at com.floragunn.searchguard.ssl.SearchGuardSSLModule.<init>(SearchGuardSSLModule.java:29)
	at com.floragunn.searchguard.ssl.SearchGuardSSLPlugin.nodeModules(SearchGuardSSLPlugin.java:127)
	at org.elasticsearch.plugins.PluginsService.nodeModules(PluginsService.java:263)
	at org.elasticsearch.node.Node.<init>(Node.java:179)
	at org.elasticsearch.node.Node.<init>(Node.java:140)
	at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:143)
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:178)
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:270)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
Refer to the log for complete error details.
```

sh-4.2$ ls -ld /elasticsearch/
drwxrwxrwx. 4 root root 91 Jun 24 21:56 /elasticsearch/

sh-4.2$ ls -l /elasticsearch/
total 8
drwxr-xr-x. 4 1000 root   31 Jun 24 21:56 logging-es
drwxrwxrwx. 3 root root   23 Jun 24 21:56 persistent
-r--r--r--. 1 1000 root 3828 Jun 24 21:56 searchguard.key
-r--r--r--. 1 1000 root  817 Jun 24 21:56 searchguard.truststore

sh-4.2$ whoami
whoami: cannot find name for user ID 1000

```
sh-4.2$ keytool -list -keystore /elasticsearch/searchguard.key -storepass kspass

Keystore type: JKS
Keystore provider: SUN

Your keystore contains 2 entries

elasticsearch, Jun 24, 2016, PrivateKeyEntry, 
Certificate fingerprint (SHA1): FF:3A:58:D8:45:59:79:C8:AB:3D:EF:6B:96:51:3E:20:DA:8D:D5:BD
sig-ca, Jun 24, 2016, trustedCertEntry, 
Certificate fingerprint (SHA1): AB:45:10:CA:11:7C:64:92:27:83:29:20:32:FE:D8:26:83:B5:D6:F3
```

**Comment by floragunncom** [comment]
you need to place the file into the config/ dir of elasticsearch (/etc/elasticsearch if you installed it via rpm/deb or the config/ folder when unpacked from a zip/tar.gz)

**Comment by ewolinetz** [comment]
Thanks!  Putting it in my config dir resolved my issue... did I miss this in the documentation,  or is this an Elasticsearch specific gotcha?

**Comment by floragunncom** [comment]
Hi Eric - it's mentioned in the config chapter and the quickstart chapter of the SSL docs:

https://github.com/floragunncom/search-guard-ssl-docs/blob/master/configuration.md
https://github.com/floragunncom/search-guard-ssl-docs/blob/master/quickstart.md

"Path to the keystore file, relative to the config/ directory (mandatory)"

We'll make this a little bit more obvious in the docs.

Thanks!
