### ISSUE TITLE
ElasticSearch failed to list shard for shard_store after restarting nodes.

### ISSUE THREAD

**Issue by nguyenmv2** [floragunncom/search-guard#164]
I noticed ElasticSearch taking a long time to initialize/allocate shards after a full restart( all nodes are restarted), and the load on my master node goes through the roof. Upon checking the log file, I encountered this error:

`[2016-07-06 19:23:47,526][WARN ][gateway                  ] [apple] [filebeat-2016.07.06][1]: failed to list shard for shard_store on node [Bt3e6PzcQ06OGaEN3-ay-w]                                                                      FailedNodeException[total failure in fetching]; nested: ElasticsearchException[unauthenticated request internal:cluster/nodes/indices/shard/store for user User [name=_sg_internal, roles=[]]];                                                  at org.elasticsearch.gateway.AsyncShardFetch$1.onFailure(AsyncShardFetch.java:277)                                                                                                                                                       at org.elasticsearch.action.support.TransportAction$1.onFailure(TransportAction.java:95)                                                                                                                                                 at com.floragunn.searchguard.filter.SearchGuardFilter.apply(SearchGuardFilter.java:135)                                                                                                                                                  at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:170)                                                                                                                                 at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:144)                                                                                                                                                    at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:85)                                                                                                                                                     at org.elasticsearch.indices.store.TransportNodesListShardStoreMetaData.list(TransportNodesListShardStoreMetaData.java:88)                                                                                                               at org.elasticsearch.gateway.AsyncShardFetch.asyncFetch(AsyncShardFetch.java:267)                                                                                                                                                        at org.elasticsearch.gateway.AsyncShardFetch.fetchData(AsyncShardFetch.java:117)                                                                                                                                                         at org.elasticsearch.gateway.GatewayAllocator$InternalReplicaShardAllocator.fetchData(GatewayAllocator.java:183)                                                                                                                         at org.elasticsearch.gateway.ReplicaShardAllocator.allocateUnassigned(ReplicaShardAllocator.java:137)                                                                                                                                    at org.elasticsearch.gateway.GatewayAllocator.allocateUnassigned(GatewayAllocator.java:123)                                                                                                                                              at org.elasticsearch.cluster.routing.allocation.allocator.ShardsAllocators.allocateUnassigned(ShardsAllocators.java:70)                                                                                                                  at org.elasticsearch.cluster.routing.allocation.AllocationService.reroute(AllocationService.java:258)                                                                                                                                    at org.elasticsearch.cluster.routing.allocation.AllocationService.reroute(AllocationService.java:221)                                                                                                                                    at org.elasticsearch.cluster.routing.allocation.AllocationService.reroute(AllocationService.java:207)                                                                                                                                    at org.elasticsearch.cluster.routing.RoutingService$2.execute(RoutingService.java:154)                                                                                                                                                   at org.elasticsearch.cluster.ClusterStateUpdateTask.execute(ClusterStateUpdateTask.java:45)                                                                                                                                              at org.elasticsearch.cluster.service.InternalClusterService.runTasksForExecutor(InternalClusterService.java:468)                                                                                                                         at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:772)                                                                                                                              at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:231)                                                                         at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:194)                                                                                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)                                                                                                                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)                                                                                                                                                       at java.lang.Thread.run(Thread.java:745)                                                                                                                                                                                         Caused by: ElasticsearchException[unauthenticated request internal:cluster/nodes/indices/shard/store for user User [name=_sg_internal, roles=[]]]                                                                                                ... 23 more`

It appears that ElasticSearch is trying to fetch shard_stores with a public role ( hence USER), however I do not see anywhere that I can declare the login info in elasticsearch yml. Here is what I have on my config file:
`cluster.name:                 <redacted>
node.name:                    apple
node.master:                  true

network.host:                 _ec2:privateIpv4_
http.port:                         9200

bootstrap.mlockall:           true

discovery:
  type:                       "ec2"
  ec2.groups:                 "<redacted>"
  ec2.host_type:              "private_ip"
  ec2.availability:           "us-east-1c"
  ec2.tag.tag:               <redacted>
  zen.ping.multicast.enabled: true
  zen.minimum_master_nodes:   1
  zen.ping.unicast.hosts:     ["<redacted>"]

cloud:
  node.auto_attributes:       true
  aws.protocol:               "http"
  aws.access_key:             <redacted>"
  aws.secret_key:             <redacted>"
  aws.region:                 "<redacted>"

searchguard.ssl:
  transport:
    keystore_filepath:        apple-keystore.jks
    keystore_password:        <redacted>"
    truststore_filepath:      truststore.jks
    truststore_password:      <redacted>"
  http:
    enabled:                  true
    keystore_filepath:        apple-keystore.jks
    keystore_password:        <redacted>"
    truststore_filepath:      truststore.jks
    truststore_password:      <redacted>"

searchguard.authcz.admin_dn:
    - cn=Admin,ou=client,o=client,l=LR,c=AR
`

Thank you very much for your help

**Comment by floragunncom** [comment]
This is fixed in Search Guard 2.3.3.2, pls update

**Comment by nguyenmv2** [comment]
Updating SearchGuard fixed this. Thank you for your help

**Comment by DivyaMalini** [comment]
Hi,
We are using ES5.4.1. In one of our production environment, a node left out of cluster and after it rejoining we are seeing master nodes giving these warning messages. Could anyone please take a look and clarify how it might affect the index/search operations ?

> "Caused by: java.io.FileNotFoundException: no segments* file found in store(mmapfs(F:\data\nodes\0\indices\LnsZ8z0iQHCsfbnVc1OtxQ\1\index)):"


FullException -

[es-m03-rm] [sharedindex][1]: failed to list shard for shard_store on node [6xSE_CzOSXiig0Ehr-3r8A]
org.elasticsearch.action.FailedNodeException: Failed node [6xSE_CzOSXiig0Ehr-3r8A]
	at org.elasticsearch.action.support.nodes.TransportNodesAction$AsyncAction.onFailure(TransportNodesAction.java:246) ~[elasticsearch-5.4.1-SNAPSHOT.jar:5.4.1-SNAPSHOT]
	at org.elasticsearch.action.support.nodes.TransportNodesAction$AsyncAction.access$200(TransportNodesAction.java:160) ~[elasticsearch-5.4.1-SNAPSHOT.jar:5.4.1-SNAPSHOT]
	at org.elasticsearch.action.support.nodes.TransportNodesAction$AsyncAction$1.handleException(TransportNodesAction.java:218) ~[elasticsearch-5.4.1-SNAPSHOT.jar:5.4.1-SNAPSHOT]
	at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1050) ~[elasticsearch-5.4.1-SNAPSHOT.jar:5.4.1-SNAPSHOT]
	at org.elasticsearch.transport.TcpTransport.lambda$handleException$17(TcpTransport.java:1451) ~[elasticsearch-5.4.1-SNAPSHOT.jar:5.4.1-SNAPSHOT]
	at org.elasticsearch.common.util.concurrent.EsExecutors$1.execute(EsExecutors.java:110) [elasticsearch-5.4.1-SNAPSHOT.jar:5.4.1-SNAPSHOT]
	at org.elasticsearch.transport.TcpTransport.handleException(TcpTransport.java:1449) [elasticsearch-5.4.1-SNAPSHOT.jar:5.4.1-SNAPSHOT]
	at org.elasticsearch.transport.TcpTransport.handlerResponseError(TcpTransport.java:1441) [elasticsearch-5.4.1-SNAPSHOT.jar:5.4.1-SNAPSHOT]
	at org.elasticsearch.transport.TcpTransport.messageReceived(TcpTransport.java:1385) [elasticsearch-5.4.1-SNAPSHOT.jar:5.4.1-SNAPSHOT]
	at org.elasticsearch.transport.netty4.Netty4MessageChannelHandler.channelRead(Netty4MessageChannelHandler.java:74) [transport-netty4-5.4.1.jar:5.4.1]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) [netty-codec-4.1.11.Final.jar:4.1.11.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:297) [netty-codec-4.1.11.Final.jar:4.1.11.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:413) [netty-codec-4.1.11.Final.jar:4.1.11.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) [netty-codec-4.1.11.Final.jar:4.1.11.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:544) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:498) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-common-4.1.11.Final.jar:4.1.11.Final]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
Caused by: org.elasticsearch.transport.RemoteTransportException: [es-d06-rm][20.0.0.156:9300][internal:cluster/nodes/indices/shard/store[n]]
Caused by: org.elasticsearch.ElasticsearchException: Failed to list store metadata for shard [[sharedindex][1]]
	at org.elasticsearch.indices.store.TransportNodesListShardStoreMetaData.nodeOperation(TransportNodesListShardStoreMetaData.java:114) ~[elasticsearch-5.4.1-SNAPSHOT.jar:5.4.1-SNAPSHOT]
	at org.elasticsearch.indices.store.TransportNodesListShardStoreMetaData.nodeOperation(TransportNodesListShardStoreMetaData.java:64) ~[elasticsearch-5.4.1-SNAPSHOT.jar:5.4.1-SNAPSHOT]
	at org.elasticsearch.action.support.nodes.TransportNodesAction.nodeOperation(TransportNodesAction.java:145) ~[elasticsearch-5.4.1-SNAPSHOT.jar:5.4.1-SNAPSHOT]
	at org.elasticsearch.action.support.nodes.TransportNodesAction$NodeTransportHandler.messageReceived(TransportNodesAction.java:269) ~[elasticsearch-5.4.1-SNAPSHOT.jar:5.4.1-SNAPSHOT]
	at org.elasticsearch.action.support.nodes.TransportNodesAction$NodeTransportHandler.messageReceived(TransportNodesAction.java:265) ~[elasticsearch-5.4.1-SNAPSHOT.jar:5.4.1-SNAPSHOT]
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69) ~[elasticsearch-5.4.1-SNAPSHOT.jar:5.4.1-SNAPSHOT]
	at org.elasticsearch.transport.TcpTransport$RequestHandler.doRun(TcpTransport.java:1528) ~[elasticsearch-5.4.1-SNAPSHOT.jar:5.4.1-SNAPSHOT]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:638) ~[elasticsearch-5.4.1-SNAPSHOT.jar:5.4.1-SNAPSHOT]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-5.4.1-SNAPSHOT.jar:5.4.1-SNAPSHOT]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[?:1.8.0_72]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[?:1.8.0_72]
	... 1 more
Caused by: java.io.FileNotFoundException: no segments* file found in store(mmapfs(F:\data\nodes\0\indices\LnsZ8z0iQHCsfbnVc1OtxQ\1\index)): files: [recovery.AV_YJEaSvIUUWZcP9zci._1fea.dii, recovery.AV_YJEaSvIUUWZcP9zci._1fea.dim, recovery.AV_YJEaSvIUUWZcP9zci._1fea.fdx, recovery.AV_YJEaSvIUUWZcP9zci._1fea.fnm, recovery.AV_YJEaSvIUUWZcP9zci._1fea.nvd, recovery.AV_YJEaSvIUUWZcP9zci._1fea.nvm, recovery.AV_YJEaSvIUUWZcP9zci._1fea.si, recovery.AV_YJEaSvIUUWZcP9zci._1fea_5s.liv, recovery.AV_YJEaSvIUUWZcP9zci._1fea_Lucene50_0.doc, recovery.AV_YJEaSvIUUWZcP9zci._1fea_Lucene50_0.tim, recovery.AV_YJEaSvIUUWZcP9zci._1fea_Lucene50_0.tip, recovery.AV_YJEaSvIUUWZcP9zci._1fea_Lucene54_0.dvd, recovery.AV_YJEaSvIUUWZcP9zci._1fea_Lucene54_0.dvm, recovery.AV_YJEaSvIUUWZcP9zci._1fyw.cfe, recovery.AV_YJEaSvIUUWZcP9zci._1fyw.cfs, recovery.AV_YJEaSvIUUWZcP9zci._1fyw.si, recovery.AV_YJEaSvIUUWZcP9zci._1g81.cfe, recovery.AV_YJEaSvIUUWZcP9zci._1g81.cfs, recovery.AV_YJEaSvIUUWZcP9zci._1g81.si, recovery.AV_YJEaSvIUUWZcP9zci._1g81_10.liv, recovery.AV_YJEaSvIUUWZcP9zci._1gbm.cfe, recovery.AV_YJEaSvIUUWZcP9zci._1gbm.cfs, recovery.AV_YJEaSvIUUWZcP9zci._1gbm.si, recovery.AV_YJEaSvIUUWZcP9zci._1gbm_2g.liv, recovery.AV_YJEaSvIUUWZcP9zci._1hvc.cfe, recovery.AV_YJEaSvIUUWZcP9zci._1hvc.cfs, recovery.AV_YJEaSvIUUWZcP9zci._1hvc.si, recovery.AV_YJEaSvIUUWZcP9zci._1hvc_17.liv, recovery.AV_YJEaSvIUUWZcP9zci._1ine.cfe, recovery.AV_YJEaSvIUUWZcP9zci._1ine.cfs, recovery.AV_YJEaSvIUUWZcP9zci._1ine.si, recovery.AV_YJEaSvIUUWZcP9zci._1ine_1v.liv, recovery.AV_YJEaSvIUUWZcP9zci._1khw.cfe, recovery.AV_YJEaSvIUUWZcP9zci._1khw.cfs, recovery.AV_YJEaSvIUUWZcP9zci._1khw.si, recovery.AV_YJEaSvIUUWZcP9zci._1khw_11.liv, recovery.AV_YJEaSvIUUWZcP9zci._1l6b.cfe, recovery.AV_YJEaSvIUUWZcP9zci._1l6b.cfs, recovery.AV_YJEaSvIUUWZcP9zci._1l6b.si, recovery.AV_YJEaSvIUUWZcP9zci._1l6b_p.liv, recovery.AV_YJEaSvIUUWZcP9zci._1m32.cfe, recovery.AV_YJEaSvIUUWZcP9zci._1m32.cfs, recovery.AV_YJEaSvIUUWZcP9zci._1m32.si, recovery.AV_YJEaSvIUUWZcP9zci._1m32_t.liv, recovery.AV_YJEaSvIUUWZcP9zci._1mtd.cfe, recovery.AV_YJEaSvIUUWZcP9zci._1mtd.cfs, recovery.AV_YJEaSvIUUWZcP9zci._1mtd.si, recovery.AV_YJEaSvIUUWZcP9zci._1mtd_i.liv, recovery.AV_YJEaSvIUUWZcP9zci._1ncd.cfe, recovery.AV_YJEaSvIUUWZcP9zci._1ncd.cfs, recovery.AV_YJEaSvIUUWZcP9zci._1ncd.si, recovery.AV_YJEaSvIUUWZcP9zci._1ncd_t.liv, recovery.AV_YJEaSvIUUWZcP9zci._1o4o.cfe, recovery.AV_YJEaSvIUUWZcP9zci._1o4o.cfs, recovery.AV_YJEaSvIUUWZcP9zci._1o4o.si, recovery.AV_YJEaSvIUUWZcP9zci._1o4o_r.liv, recovery.AV_YJEaSvIUUWZcP9zci._1obt.cfe, recovery.AV_YJEaSvIUUWZcP9zci._1obt.cfs, recovery.AV_YJEaSvIUUWZcP9zci._1obt.si, recovery.AV_YJEaSvIUUWZcP9zci._1obt_2.liv, recovery.AV_YJEaSvIUUWZcP9zci._1otq.cfe, recovery.AV_YJEaSvIUUWZcP9zci._1otq.cfs, recovery.AV_YJEaSvIUUWZcP9zci._1otq.si, recovery.AV_YJEaSvIUUWZcP9zci._1otq_l.liv, recovery.AV_YJEaSvIUUWZcP9zci._1pgg.cfe, recovery.AV_YJEaSvIUUWZcP9zci._1pgg.cfs, recovery.AV_YJEaSvIUUWZcP9zci._1pgg.si, recovery.AV_YJEaSvIUUWZcP9zci._1pgg_q.liv, recovery.AV_YJEaSvIUUWZcP9zci._1pyp.cfe, recovery.AV_YJEaSvIUUWZcP9zci._1pyp.cfs, recovery.AV_YJEaSvIUUWZcP9zci._1pyp.si, recovery.AV_YJEaSvIUUWZcP9zci._1pyp_e.liv, recovery.AV_YJEaSvIUUWZcP9zci._1q5n.cfe, recovery.AV_YJEaSvIUUWZcP9zci._1q5n.cfs, recovery.AV_YJEaSvIUUWZcP9zci._1q5n.si, recovery.AV_YJEaSvIUUWZcP9zci._1q5n_1.liv, recovery.AV_YJEaSvIUUWZcP9zci._1q6e.cfe, recovery.AV_YJEaSvIUUWZcP9zci._1q6e.cfs, recovery.AV_YJEaSvIUUWZcP9zci._1q6e.si, recovery.AV_YJEaSvIUUWZcP9zci._1q6j.cfe, recovery.AV_YJEaSvIUUWZcP9zci._1q6j.cfs, recovery.AV_YJEaSvIUUWZcP9zci._1q6j.si, recovery.AV_YJEaSvIUUWZcP9zci._1q6j_1.liv, recovery.AV_YJEaSvIUUWZcP9zci._1q6m.cfe, recovery.AV_YJEaSvIUUWZcP9zci._1q6m.cfs, recovery.AV_YJEaSvIUUWZcP9zci._1q6m.si, recovery.AV_YJEaSvIUUWZcP9zci._1q6n.cfe, recovery.AV_YJEaSvIUUWZcP9zci._1q6n.cfs, recovery.AV_YJEaSvIUUWZcP9zci._1q6n.si, recovery.AV_YJEaSvIUUWZcP9zci._1q6o.cfe, recovery.AV_YJEaSvIUUWZcP9zci._1q6o.cfs, recovery.AV_YJEaSvIUUWZcP9zci._1q6o.si, recovery.AV_YJEaSvIUUWZcP9zci._1q6p.cfe, recovery.AV_YJEaSvIUUWZcP9zci._1q6p.cfs, recovery.AV_YJEaSvIUUWZcP9zci._1q6p.si, recovery.AV_YJEaSvIUUWZcP9zci._1q6s.cfe, recovery.AV_YJEaSvIUUWZcP9zci._1q6s.cfs, recovery.AV_YJEaSvIUUWZcP9zci._1q6s.si, recovery.AV_YJEaSvIUUWZcP9zci._mo.dii, recovery.AV_YJEaSvIUUWZcP9zci._mo.dim, recovery.AV_YJEaSvIUUWZcP9zci._mo.fdx, recovery.AV_YJEaSvIUUWZcP9zci._mo.fnm, recovery.AV_YJEaSvIUUWZcP9zci._mo.nvm, recovery.AV_YJEaSvIUUWZcP9zci._mo.si, recovery.AV_YJEaSvIUUWZcP9zci._mo_Lucene50_0.tim, recovery.AV_YJEaSvIUUWZcP9zci._mo_Lucene50_0.tip, recovery.AV_YJEaSvIUUWZcP9zci._mo_Lucene54_0.dvd, recovery.AV_YJEaSvIUUWZcP9zci._mo_Lucene54_0.dvm, recovery.AV_YJEaSvIUUWZcP9zci._mo_cn.liv, recovery.AV_YJEaSvIUUWZcP9zci._om.dii, recovery.AV_YJEaSvIUUWZcP9zci._om.dim, recovery.AV_YJEaSvIUUWZcP9zci._om.fdt, recovery.AV_YJEaSvIUUWZcP9zci._om.fdx, recovery.AV_YJEaSvIUUWZcP9zci._om.fnm, recovery.AV_YJEaSvIUUWZcP9zci._om.nvd, recovery.AV_YJEaSvIUUWZcP9zci._om.nvm, recovery.AV_YJEaSvIUUWZcP9zci._om.si, recovery.AV_YJEaSvIUUWZcP9zci._om_8h.liv, recovery.AV_YJEaSvIUUWZcP9zci._om_Lucene50_0.doc, recovery.AV_YJEaSvIUUWZcP9zci._om_Lucene50_0.pay, recovery.AV_YJEaSvIUUWZcP9zci._om_Lucene50_0.pos, recovery.AV_YJEaSvIUUWZcP9zci._om_Lucene50_0.tim, recovery.AV_YJEaSvIUUWZcP9zci._om_Lucene50_0.tip, recovery.AV_YJEaSvIUUWZcP9zci._om_Lucene54_0.dvd, recovery.AV_YJEaSvIUUWZcP9zci._om_Lucene54_0.dvm, recovery.AV_YJEaSvIUUWZcP9zci._t6.dii, recovery.AV_YJEaSvIUUWZcP9zci._t6.dim, recovery.AV_YJEaSvIUUWZcP9zci._t6.fdt, recovery.AV_YJEaSvIUUWZcP9zci._t6.fdx, recovery.AV_YJEaSvIUUWZcP9zci._t6.fnm, recovery.AV_YJEaSvIUUWZcP9zci._t6.nvd, recovery.AV_YJEaSvIUUWZcP9zci._t6.nvm, recovery.AV_YJEaSvIUUWZcP9zci._t6.si, recovery.AV_YJEaSvIUUWZcP9zci._t6_4h.liv, recovery.AV_YJEaSvIUUWZcP9zci._t6_Lucene50_0.doc, recovery.AV_YJEaSvIUUWZcP9zci._t6_Lucene50_0.pay, recovery.AV_YJEaSvIUUWZcP9zci._t6_Lucene50_0.pos, recovery.AV_YJEaSvIUUWZcP9zci._t6_Lucene50_0.tim, recovery.AV_YJEaSvIUUWZcP9zci._t6_Lucene50_0.tip, recovery.AV_YJEaSvIUUWZcP9zci._t6_Lucene54_0.dvd, recovery.AV_YJEaSvIUUWZcP9zci._t6_Lucene54_0.dvm, recovery.AV_YJEaSvIUUWZcP9zci._wn.dii, recovery.AV_YJEaSvIUUWZcP9zci._wn.dim, recovery.AV_YJEaSvIUUWZcP9zci._wn.fdt, recovery.AV_YJEaSvIUUWZcP9zci._wn.fdx, recovery.AV_YJEaSvIUUWZcP9zci._wn.fnm, recovery.AV_YJEaSvIUUWZcP9zci._wn.nvd, recovery.AV_YJEaSvIUUWZcP9zci._wn.nvm, recovery.AV_YJEaSvIUUWZcP9zci._wn.si, recovery.AV_YJEaSvIUUWZcP9zci._wn_7w.liv, recovery.AV_YJEaSvIUUWZcP9zci._wn_Lucene50_0.doc, recovery.AV_YJEaSvIUUWZcP9zci._wn_Lucene50_0.pay, recovery.AV_YJEaSvIUUWZcP9zci._wn_Lucene50_0.pos, recovery.AV_YJEaSvIUUWZcP9zci._wn_Lucene50_0.tim, recovery.AV_YJEaSvIUUWZcP9zci._wn_Lucene50_0.tip, recovery.AV_YJEaSvIUUWZcP9zci._wn_Lucene54_0.dvd, recovery.AV_YJEaSvIUUWZcP9zci._wn_Lucene54_0.dvm, recovery.AV_YJEaSvIUUWZcP9zci.segments_2d4, write.lock]
	at org.apache.lucene.index.SegmentInfos$FindSegmentsFile.run(SegmentInfos.java:687) ~[lucene-core-6.5.1.jar:6.5.1 cd1f23c63abe03ae650c75ec8ccb37762806cc75 - jimczi - 2017-04-21 12:17:15]
	at org.apache.lucene.index.SegmentInfos$FindSegmentsFile.run(SegmentInfos.java:644) ~[lucene-core-6.5.1.jar:6.5.1 cd1f23c63abe03ae650c75ec8ccb37762806cc75 - jimczi - 2017-04-21 12:17:15]
	at org.apache.lucene.index.SegmentInfos.readLatestCommit(SegmentInfos.java:450) ~[lucene-core-6.5.1.jar:6.5.1 cd1f23c63abe03ae650c75ec8ccb37762806cc75 - jimczi - 2017-04-21 12:17:15]
	at org.elasticsearch.common.lucene.Lucene.readSegmentInfos(Lucene.java:129) ~[elasticsearch-5.4.1-SNAPSHOT.jar:5.4.1-SNAPSHOT]
	at org.elasticsearch.index.store.Store.readSegmentsInfo(Store.java:199) ~[elasticsearch-5.4.1-SNAPSHOT.jar:5.4.1-SNAPSHOT]
	at org.elasticsearch.index.store.Store.access$200(Store.java:127) ~[elasticsearch-5.4.1-SNAPSHOT.jar:5.4.1-SNAPSHOT]
	at org.elasticsearch.index.store.Store$MetadataSnapshot.loadMetadata(Store.java:818) ~[elasticsearch-5.4.1-SNAPSHOT.jar:5.4.1-SNAPSHOT]
	at org.elasticsearch.index.store.Store$MetadataSnapshot.<init>(Store.java:751) ~[elasticsearch-5.4.1-SNAPSHOT.jar:5.4.1-SNAPSHOT]
	at org.elasticsearch.index.store.Store.getMetadata(Store.java:273) ~[elasticsearch-5.4.1-SNAPSHOT.jar:5.4.1-SNAPSHOT]
	at org.elasticsearch.index.shard.IndexShard.snapshotStoreMetadata(IndexShard.java:873) ~[elasticsearch-5.4.1-SNAPSHOT.jar:5.4.1-SNAPSHOT]
	at org.elasticsearch.indices.store.TransportNodesListShardStoreMetaData.listStoreMetaData(TransportNodesListShardStoreMetaData.java:128) ~[elasticsearch-5.4.1-SNAPSHOT.jar:5.4.1-SNAPSHOT]
	at org.elasticsearch.indices.store.TransportNodesListShardStoreMetaData.nodeOperation(TransportNodesListShardStoreMetaData.java:112) ~[elasticsearch-5.4.1-SNAPSHOT.jar:5.4.1-SNAPSHOT]
	at org.elasticsearch.indices.store.TransportNodesListShardStoreMetaData.nodeOperation(TransportNodesListShardStoreMetaData.java:64) ~[elasticsearch-5.4.1-SNAPSHOT.jar:5.4.1-SNAPSHOT]
	at org.elasticsearch.action.support.nodes.TransportNodesAction.nodeOperation(TransportNodesAction.java:145) ~[elasticsearch-5.4.1-SNAPSHOT.jar:5.4.1-SNAPSHOT]
	at org.elasticsearch.action.support.nodes.TransportNodesAction$NodeTransportHandler.messageReceived(TransportNodesAction.java:269) ~[elasticsearch-5.4.1-SNAPSHOT.jar:5.4.1-SNAPSHOT]
	at org.elasticsearch.action.support.nodes.TransportNodesAction$NodeTransportHandler.messageReceived(TransportNodesAction.java:265) ~[elasticsearch-5.4.1-SNAPSHOT.jar:5.4.1-SNAPSHOT]
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69) ~[elasticsearch-5.4.1-SNAPSHOT.jar:5.4.1-SNAPSHOT]
	at org.elasticsearch.transport.TcpTransport$RequestHandler.doRun(TcpTransport.java:1528) ~[elasticsearch-5.4.1-SNAPSHOT.jar:5.4.1-SNAPSHOT]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:638) ~[elasticsearch-5.4.1-SNAPSHOT.jar:5.4.1-SNAPSHOT]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-5.4.1-SNAPSHOT.jar:5.4.1-SNAPSHOT]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[?:1.8.0_72]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[?:1.8.0_72]
	... 1 more

Thanks, 
Divya

**Comment by floragunncom** [comment]
This is the Search Guard issue tracker, not Elasticsearch. Please ask Elasticsearch questions on the Elasticsearch form: https://discuss.elastic.co/
