### ISSUE TITLE
use search-guard and install marvel then error 

### ISSUE THREAD

**Issue by tingking23** [floragunncom/search-guard#177]
esversion: 2.3.4

[2016-07-22 11:21:58,221][ERROR][marvel.agent             ] [Lionheart] background thread had an uncaught exception
ElasticsearchException[failed to flush exporter bulks]
	at org.elasticsearch.marvel.agent.exporter.ExportBulk$Compound.flush(ExportBulk.java:104)
	at org.elasticsearch.marvel.agent.exporter.ExportBulk.close(ExportBulk.java:53)
	at org.elasticsearch.marvel.agent.AgentService$ExportingWorker.run(AgentService.java:201)
	at java.lang.Thread.run(Thread.java:745)
	Suppressed: ElasticsearchException[failed to flush [default_local] exporter bulk]; nested: ElasticsearchException[unauthenticated request indices:data/write/bulk for user User [name=_sg_internal, roles=[]]];
		at org.elasticsearch.marvel.agent.exporter.ExportBulk$Compound.flush(ExportBulk.java:106)
		... 3 more
	Caused by: ElasticsearchException[unauthenticated request indices:data/write/bulk for user User [name=_sg_internal, roles=[]]]
		at com.floragunn.searchguard.filter.SearchGuardFilter.apply(SearchGuardFilter.java:135)
		at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:170)
		at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:144)
		at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:85)
		at org.elasticsearch.client.node.NodeClient.doExecute(NodeClient.java:58)
		at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:359)
		at org.elasticsearch.client.FilterClient.doExecute(FilterClient.java:52)
		at org.elasticsearch.marvel.shield.SecuredClient.doExecute(SecuredClient.java:45)
		at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:359)
		at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:86)
		at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:56)
		at org.elasticsearch.action.ActionRequestBuilder.get(ActionRequestBuilder.java:64)
		at org.elasticsearch.marvel.agent.exporter.local.LocalBulk.flush(LocalBulk.java:116)
		at org.elasticsearch.marvel.agent.exporter.ExportBulk$Compound.flush(ExportBulk.java:101)
		... 3 more

**Comment by mzamora717** [comment]
Did you find a solution for this? I'm running into the same issue.

**Comment by floragunncom** [comment]
see https://github.com/floragunncom/search-guard/issues/274 
and https://github.com/floragunncom/search-guard-ssl/issues/43
