### ISSUE TITLE
kopf plugin with Chrome browser creates ERROR level logging

### ISSUE THREAD

**Issue by brdaugherty** [floragunncom/search-guard#183]
SearchGuard version 2.3.3.3
ElasticSearch version 2.3.3
openjdk version 1.8.0_91
Operating System: CentOS 7
Three Node Cluster
Chrome Browser Version 51.0.2704.106 (64-bit)

** Description **

SG may be logging info/warn exceptions at error level.

In my setup SG is configured with transport and http ssl enabled and the kopf plugin installed.
This also works great with logstash, kibana, curl, etc.   So thank you to the SG team!

When accessing kopf using the Chrome browser SG successfully establishes the https connection and works perfectly. 

However, while kopf+browser remain active the included error message is logged over and over. 
It is quickly drowning my es indices with a repeated ERROR level messages.

At the least it seems this is not really an error. 
It is not helpful due to confusion and sheer frequency and number of repeated error messages.

**Log output**

`[2016-07-26 01:28:10,064][ERROR][com.floragunn.searchguard.http.SearchGuardHttpServerTransport] [foobaz] SSL Problem no cipher suites in common
javax.net.ssl.SSLHandshakeException: no cipher suites in common
	at sun.security.ssl.Handshaker.checkThrown(Handshaker.java:1431)
	at sun.security.ssl.SSLEngineImpl.checkTaskThrown(SSLEngineImpl.java:535)
	at sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:813)
	at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:781)
	at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:624)
	at org.jboss.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1218)
	at org.jboss.netty.handler.ssl.SslHandler.decode(SslHandler.java:852)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:425)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: javax.net.ssl.SSLHandshakeException: no cipher suites in common
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1666)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:304)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:292)
	at sun.security.ssl.ServerHandshaker.chooseCipherSuite(ServerHandshaker.java:1035)
	at sun.security.ssl.ServerHandshaker.clientHello(ServerHandshaker.java:738)
	at sun.security.ssl.ServerHandshaker.processMessage(ServerHandshaker.java:221)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979)
	at sun.security.ssl.Handshaker$1.run(Handshaker.java:919)
	at sun.security.ssl.Handshaker$1.run(Handshaker.java:916)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.security.ssl.Handshaker$DelegatedTask.run(Handshaker.java:1369)
	at org.jboss.netty.handler.ssl.SslHandler.runDelegatedTasks(SslHandler.java:1392)
	at org.jboss.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1255)
	... 18 more`

**Comment by floragunncom** [comment]
Do you get this "ERROR" also when you use Oracle JDK instead of OpenJDK and please post you elasticsearch.yml. 

I think this **is** an error and suppressing it would hide a possible security risk. Maybe there are other HTTP clients which connect to elasticsearch at the same time and which do not support the cipher suites we enforce. 

If you want debug SSL try starting elasticsearch with "-Djavax.net.debug=ssl" and see if there are some helpful logs on stdout.

Finally we recommend usage of OpenSSL instead of Java's SSL implementation. Its slow and it does support not the most recent cipher suites. And especially OpenJDK (opposed to Oracle Java) is susceptible  for SSL problems.

**Comment by brdaugherty** [comment]
Apologies for the delay.

I'm limited to using OpenJDK--OpenSSL and Oracle's JDK are not options due
to software and management requirements. I may be able to debug at some
point with them but it will be awhile due to schedule.

I've confirmed that only Chrome is connecting to kopf and generating the
logging errors.

elasticsearch.yaml   (names, credentials are fake)


---
bootstrap:
  mlockall: true
cloud:
  aws:
    access_key: 'jellystonepark'
    secret_key: 'helpmyhovercraftisfullofeels'
cluster:
  name: fillibuster
discovery:
  ec2:
    tag:
      designation: karl
      environment: marx
      role: promogulation
  type: ec2
network:
  host: 192.168.192.168
node:
  name: skippy
path:
  data: /mnt/skippy
  logs: /var/log/elasticsearch/
searchguard:
  authcz:
    admin_dn: cn=admin,ou=Wonderland,ou=ou,dc=internal,dc=marx
  ssl:
    http:
      enabled: true
      keystore_filepath: es-node-0-keystore.jks
      keystore_password: 'letmein'
      truststore_filepath: es-truststore.jks
      truststore_password: 'letmein'
    transport:
      enabled: true
      enforce_hostname_verification: false
      keystore_filepath: es-node-0-keystore.jks
      keystore_password: 'letmein'
      truststore_filepath: es-truststore.jks
      truststore_password: 'letmein'

**Comment by floragunncom** [comment]
Maybe not a solution, but an explanation. If it is Chrome-only, then the reason is that Chrome deprecated DHE-based cipher suites, I think from v49 onwards. However, they did not disable them completely, but changed the negotiation mechanism:

1. Chrome does not offer DHE-based ciphers in the first handhshake it makes - that's whats causing the log entry
2. If the initial handshake fails, a second handshake is initiated, now including DHE-based ciphers - this is the one that succeeds

Here's an article about it: https://blog.digicert.com/google-plans-to-deprecate-dhe-cipher-suites/

That's why everything seems to work (because of 2.), but your logfile is spammed with entries (because of 1.)

So, if OpenJDK does not offer any modern ciphers out of the box, you need to somehow enable strong encryption. I'm no OpenJDK expert, but maybe installing Bouncycastle as JCE provider can help. I guess there's nothing we can do from our side.

**Comment by floragunncom** [comment]
Closing, related to Chrome + OpenJDK + DHE ciphers
