### ISSUE TITLE
Using Search Guard with logstash faild

### ISSUE THREAD

**Issue by Lengchuan** [floragunncom/search-guard#184]
ES:2.3.3
logstash:2.3.3
SG SSL:2.3.3.14
SG : 2.3.3.3
jdk :1.7
os:centos6

logstash output:

output {
  elasticsearch {
        user => "logstash"
        password => "logstash"
        ssl => true
        ssl_certificate_verification => true
        truststore => "/opt/ELK/logstash-2.3.3/config/keys/truststore.jks"
        truststore_password => "123456"
        action => "index"          #The operation on ES
        hosts  => ["192.168.1.251:9200"]   #ElasticSearch host, can be array.
        index => "logstash-test1-%{type}-%{+YYYY.MM.dd}"
        document_type => "%{type}"        #The index to write data to.
  }
}

and the ES log output:

[ERROR][com.floragunn.searchguard.http.SearchGuardHttpServerTransport] [test1] SSL Problem Client requested protocol TLSv1 not enabled or not support
ed
javax.net.ssl.SSLHandshakeException: Client requested protocol TLSv1 not enabled or not supported
        at sun.security.ssl.Handshaker.checkThrown(Handshaker.java:1336)
        at sun.security.ssl.SSLEngineImpl.checkTaskThrown(SSLEngineImpl.java:519)
        at sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:796)
        at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:764)
        at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:624)
        at org.jboss.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1218)
        at org.jboss.netty.handler.ssl.SslHandler.decode(SslHandler.java:852)
        at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:425)
        at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
        at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
        at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: javax.net.ssl.SSLHandshakeException: Client requested protocol TLSv1 not enabled or not supported
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
        at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1639)

Any idea on how to resolve this problem?

**Comment by floragunncom** [comment]
Use Oracle JDK 8 or allow TLSv1 in [elasticsearch.yml](https://github.com/floragunncom/search-guard-ssl/blob/master/searchguard-ssl-config-template.yml). 

<pre>
# Enabled SSL protocols for http protocol (only Java format is supported)
# WARNING: Expert setting, do only use if you know what you are doing
# If you set wrong values here this this could be a security risk 
searchguard.ssl.http.enabled_protocols:
  - "TLSv1"
  - "TLSv1.1"  
  - "TLSv1.2"
</pre>

*We do not recommend allowing TLSv1 because its considered to be unsafe*
