### ISSUE TITLE
LDAP authentication doesn't work!

### ISSUE THREAD

**Issue by woodkan** [floragunncom/search-guard#213]
ES version is :  2.4.0
search-guard-ssL : 2.4.0.16
search-guard-2    : 2.4.0.6

I am trying to integrate SG with Windows AD. I download `dlic-search-guard-authbackend-ldap-2.4-4-jar-with-dependencies.jar` and copy it to search-guard-2 directory:
below is file list on search-guard-2 folder:

> 
[root@tk-mgr-elk224 search-guard-2]# ls -l
total 980
-rw-r--r-- 1 elasticsearch elasticsearch 832362 Oct  8 15:50 dlic-search-guard-authbackend-ldap-2.4-4-jar-with-dependencies.jar
-rw-rw-r-- 1 elasticsearch elasticsearch   2643 Oct  6 20:23 plugin-descriptor.properties
-rw-rw-r-- 1 elasticsearch elasticsearch   1026 Oct  6 20:23 plugin-security.policy
-rw-rw-r-- 1 elasticsearch elasticsearch 154218 Oct  6 20:23 search-guard-2-2.4.0.6.jar
drwxrwxr-x 2 elasticsearch elasticsearch   4096 Oct  9 11:32 sgconfig
drwxrwxr-x 2 elasticsearch elasticsearch    119 Oct  8 17:28 tools

I also cofigure sg_config.yml for LDAP as below

>       ldap:
        enabled: true
        order: 3
        http_authenticator:
          type: basic
          challenge: true
        authentication_backend:
          type: ldap # NOT FREE FOR COMMERCIAL USE
          config:
            enable_ssl: false
            enable_start_tls: false
            enable_ssl_client_auth: false
            verify_hostnames: false
            hosts:
              - 192.168.10.4:389
            bind_dn: 'cn=.....'
            password: 'xxxxxxxxx'
            userbase: 'ou=.....'
            usersearch: '(sAMAccountName={0})'
            username_attribute: sAMAccountName
>

I try to get something with a AD account, but meet below errors: 

> 
{
  "error" : {
    "root_cause" : [ {
      "type" : "class_not_found_exception",
      "reason" : "class_not_found_exception: com.floragunn.dlic.auth.ldap.LdapUser"
    } ],
    "type" : "exception",
    "reason" : "java.lang.ClassNotFoundException: com.floragunn.dlic.auth.ldap.LdapUser",
    "caused_by" : {
      "type" : "class_not_found_exception",
      "reason" : "class_not_found_exception: com.floragunn.dlic.auth.ldap.LdapUser"
    }
  },
  "status" : 500
}   

below are error messages in Elasticsearch log

> 
[2016-10-09 12:00:28,098][WARN ][com.floragunn.searchguard.transport.SearchGuardTransportService] [tk-mgr-elk224] Transport response handler not found of id [244430]
[2016-10-09 12:00:28,098][WARN ][rest.suppressed          ] path: /_cat/health, params: {pretty=}
RemoteTransportException[[tk-mgr-elk220][192.168.7.220:9300][cluster:monitor/health]]; nested: ElasticsearchException[java.lang.ClassNotFoundException: com.floragunn.dlic.auth.ldap.LdapUser]; nested: NotSerializableExceptionWrapper[class_not_found_exception: com.floragunn.dlic.auth.ldap.LdapUser];
Caused by: ElasticsearchException[java.lang.ClassNotFoundException: com.floragunn.dlic.auth.ldap.LdapUser]; nested: NotSerializableExceptionWrapper[class_not_found_exception: com.floragunn.dlic.auth.ldap.LdapUser];
        at com.floragunn.searchguard.support.Base64Helper.deserializeObject(Base64Helper.java:75)
        at com.floragunn.searchguard.transport.SearchGuardTransportService.messageReceivedDecorate(SearchGuardTransportService.java:228)
        at com.floragunn.searchguard.ssl.transport.SearchGuardSSLTransportService$Interceptor.messageReceived(SearchGuardSSLTransportService.java:138)
        at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:77)
        at org.elasticsearch.transport.netty.MessageChannelHandler.handleRequest(MessageChannelHandler.java:227)
        at com.floragunn.searchguard.ssl.transport.SearchGuardMessageChannelHandler.handleRequest(SearchGuardMessageChannelHandler.java:62)
        at org.elasticsearch.transport.netty.MessageChannelHandler.messageReceived(MessageChannelHandler.java:116)
        at com.floragunn.searchguard.ssl.transport.SearchGuardMessageChannelHandler.messageReceived(SearchGuardMessageChannelHandler.java:50)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
        at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:462)
        at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:443)
        at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.elasticsearch.common.netty.OpenChannelsHandler.handleUpstream(OpenChannelsHandler.java:75)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
        at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:462)
        at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:443)
        at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
        at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
        at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: NotSerializableExceptionWrapper[class_not_found_exception: com.floragunn.dlic.auth.ldap.LdapUser]
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:814)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at java.io.ObjectInputStream.resolveClass(ObjectInputStream.java:626)
        at com.floragunn.searchguard.support.Base64Helper$SafeObjectInputStream.resolveClass(Base64Helper.java:107)
        at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1613)
        at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1518)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1774)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:371)
        at com.floragunn.searchguard.support.Base64Helper.deserializeObject(Base64Helper.java:73)
        ... 39 more

**Comment by floragunncom** [comment]
Are you sure that you have the ldap jar copied to search-guard-2/ folder on every node in your cluster?

**Comment by woodkan** [comment]
Yes. I just checked it again. LDAP jar have been copied to sg2 folder on every node.

**Comment by floragunncom** [comment]
Did you also restart all nodes? From the exception it looks strongly like one node sendet and LdapUser object over the network and another node tries to deserialize it but cannot load the class. That can only happen if the jar is missing or was not loaded properly.

**Comment by woodkan** [comment]
Yes. After I restart all ES nodes. The Ldap authentication works well. Thanks a lot!
