### ISSUE TITLE
Elasticsearch cluster never goes (at least) yellow with Search Guard

### ISSUE THREAD

**Issue by cfoutstd** [floragunncom/search-guard#218]
ES v2.4.0
SG-SSL v2.4.0.16
SG v2.4.0.7

I don't know if this related to #182.

I had a 3-node ES cluster running, then installed the SG-SSL plugin, and still successfully ran. Now I installed the SG-2 plugin, and ES does not run. I see

```
[2016-10-13 16:01:02,975][INFO ][node                     ] [ip-10-22-9-26] version[2.4.0], pid[17742], build[ce9f0c7/2016-08-29T09:14:17Z]
[2016-10-13 16:01:02,975][INFO ][node                     ] [ip-10-22-9-26] initializing ...
[2016-10-13 16:01:03,661][INFO ][com.floragunn.searchguard.ssl.SearchGuardSSLPlugin] Search Guard 2 plugin also available
[2016-10-13 16:01:03,668][INFO ][com.floragunn.searchguard.SearchGuardPlugin] Node [ip-10-22-9-26] is a transportClient: false/tribeNode: false/tribeNodeClient: false
[2016-10-13 16:01:03,734][INFO ][plugins                  ] [ip-10-22-9-26] modules [reindex, lang-expression, lang-groovy], plugins [head, search-guard-ssl, kopf, search-guard-2], sites [head, kopf]
[2016-10-13 16:01:03,867][INFO ][env                      ] [ip-10-22-9-26] using [1] data paths, mounts [[/mnt/efs/elasticsearch (us-east-1c.fs-612cfy56.efs.us-east-1.amazonaws.com:/)]], net usable_space [-9.2E18b], net total_space [-9.2E18b], spins? [possibly], types [nfs4]
[2016-10-13 16:01:03,867][INFO ][env                      ] [ip-10-22-9-26] heap size [1007.3mb], compressed ordinary object pointers [true]
[2016-10-13 16:01:03,921][INFO ][com.floragunn.searchguard.ssl.SearchGuardKeyStore] Open SSL not available (this is not an error, we simply fallback to built-in JDK SSL) because of java.lang.ClassNotFoundException: org.apache.tomcat.jni.SSL
[2016-10-13 16:01:03,921][INFO ][com.floragunn.searchguard.ssl.SearchGuardKeyStore] Open SSL not available (this is not an error, we simply fallback to built-in JDK SSL) because of java.lang.ClassNotFoundException: org.apache.tomcat.jni.SSL
[2016-10-13 16:01:04,406][INFO ][com.floragunn.searchguard.ssl.SearchGuardKeyStore] Config directory is /etc/elasticsearch/, from there the key- and truststore files are resolved relatively
[2016-10-13 16:01:04,438][INFO ][com.floragunn.searchguard.ssl.SearchGuardKeyStore] HTTPS client auth mode OPTIONAL
[2016-10-13 16:01:04,445][INFO ][com.floragunn.searchguard.ssl.SearchGuardKeyStore] AES-256 not supported, max key length for AES is 128 bit.. That is not an issue, it just limits possible encryption strength. To enable AES 256 install 'Java Cryptography Extension (JCE) Unlimited Strength Jurisdiction Policy Files'
[2016-10-13 16:01:04,445][INFO ][com.floragunn.searchguard.ssl.SearchGuardKeyStore] sslTransportClientProvider:JDK with ciphers [TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256, TLS_DHE_RSA_WITH_AES_128_CBC_SHA256, TLS_DHE_DSS_WITH_AES_128_CBC_SHA256, TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA, TLS_DHE_RSA_WITH_AES_128_CBC_SHA, TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, TLS_DHE_RSA_WITH_AES_128_GCM_SHA256, TLS_DHE_DSS_WITH_AES_128_GCM_SHA256]
[2016-10-13 16:01:04,445][INFO ][com.floragunn.searchguard.ssl.SearchGuardKeyStore] sslTransportServerProvider:JDK with ciphers [TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256, TLS_DHE_RSA_WITH_AES_128_CBC_SHA256, TLS_DHE_DSS_WITH_AES_128_CBC_SHA256, TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA, TLS_DHE_RSA_WITH_AES_128_CBC_SHA, TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, TLS_DHE_RSA_WITH_AES_128_GCM_SHA256, TLS_DHE_DSS_WITH_AES_128_GCM_SHA256]
[2016-10-13 16:01:04,445][INFO ][com.floragunn.searchguard.ssl.SearchGuardKeyStore] sslHTTPProvider:JDK with ciphers [TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256, TLS_DHE_RSA_WITH_AES_128_CBC_SHA256, TLS_DHE_DSS_WITH_AES_128_CBC_SHA256, TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA, TLS_DHE_RSA_WITH_AES_128_CBC_SHA, TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, TLS_DHE_RSA_WITH_AES_128_GCM_SHA256, TLS_DHE_DSS_WITH_AES_128_GCM_SHA256]
[2016-10-13 16:01:04,445][INFO ][com.floragunn.searchguard.ssl.SearchGuardKeyStore] sslTransport protocols [TLSv1.2, TLSv1.1]
[2016-10-13 16:01:04,446][INFO ][com.floragunn.searchguard.ssl.SearchGuardKeyStore] sslHTTP protocols [TLSv1.2, TLSv1.1]
[2016-10-13 16:01:04,676][INFO ][http                     ] [ip-10-22-9-26] Using [org.elasticsearch.http.netty.NettyHttpServerTransport] as http transport, overridden by [search-guard2]
[2016-10-13 16:01:04,783][INFO ][com.floragunn.searchguard.configuration.ConfigurationModule] FLS/DLS valve not bound (noop)
[2016-10-13 16:01:04,785][INFO ][com.floragunn.searchguard.auditlog.AuditLogModule] Auditlog not available
[2016-10-13 16:01:04,887][INFO ][transport                ] [ip-10-22-9-26] Using [com.floragunn.searchguard.transport.SearchGuardTransportService] as transport service, overridden by [search-guard2]
[2016-10-13 16:01:04,888][INFO ][transport                ] [ip-10-22-9-26] Using [com.floragunn.searchguard.ssl.transport.SearchGuardSSLNettyTransport] as transport, overridden by [search-guard-ssl]
[2016-10-13 16:01:07,058][INFO ][node                     ] [ip-10-22-9-26] initialized
[2016-10-13 16:01:07,058][INFO ][node                     ] [ip-10-22-9-26] starting ...
[2016-10-13 16:01:07,176][INFO ][com.floragunn.searchguard.transport.SearchGuardTransportService] [ip-10-22-9-26] publish_address {10.22.9.26:9300}, bound_addresses {[::1]:9300}, {127.0.0.1:9300}, {10.22.9.26:9300}
[2016-10-13 16:01:07,181][INFO ][com.floragunn.searchguard.action.configupdate.TransportConfigUpdateAction] [ip-10-22-9-26] Check if searchguard index exists ...
[2016-10-13 16:01:07,189][DEBUG][action.admin.indices.exists.indices] [ip-10-22-9-26] no known master node, scheduling a retry
[2016-10-13 16:01:07,195][INFO ][discovery                ] [ip-10-22-9-26] elk-nova-devops/sJmxVvBEQvm6fjM1s1PCRA
[2016-10-13 16:01:37,196][WARN ][discovery                ] [ip-10-22-9-26] waited for 30s and no initial state was set by the discovery
[2016-10-13 16:01:37,205][INFO ][http                     ] [ip-10-22-9-26] publish_address {10.22.9.26:9200}, bound_addresses {[::1]:9200}, {127.0.0.1:9200}, {10.22.9.26:9200}
[2016-10-13 16:01:37,206][INFO ][node                     ] [ip-10-22-9-26] started
[2016-10-13 16:02:07,197][DEBUG][action.admin.indices.exists.indices] [ip-10-22-9-26] timed out while retrying [indices:admin/exists] after failure (timeout [1m])
[2016-10-13 16:02:07,200][ERROR][com.floragunn.searchguard.action.configupdate.TransportConfigUpdateAction] [ip-10-22-9-26] Failure while checking searchguard index MasterNotDiscoveredException[null]
MasterNotDiscoveredException[null]
        at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction$5.onTimeout(TransportMasterNodeAction.java:234)
        at org.elasticsearch.cluster.ClusterStateObserver$ObserverClusterStateListener.onTimeout(ClusterStateObserver.java:236)
        at org.elasticsearch.cluster.service.InternalClusterService$NotifyTimeout.run(InternalClusterService.java:804)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
[2016-10-13 16:02:07,204][DEBUG][action.admin.cluster.health] [ip-10-22-9-26] no known master node, scheduling a retry
[2016-10-13 16:02:07,902][INFO ][cluster.service          ] [ip-10-22-9-26] detected_master {ip-10-22-9-25}{QY76R-5sTUqIO3Mr5uiblg}{10.22.9.25}{10.22.9.25:9300}, added {{ip-10-22-9-25}{QY76R-5sTUqIO3Mr5uiblg}{10.22.9.25}{10.22.9.25:9300},}, reason: zen-disco-receive(from master [{ip-10-22-9-25}{QY76R-5sTUqIO3Mr5uiblg}{10.22.9.25}{10.22.9.25:9300}])
[2016-10-13 16:02:38,304][WARN ][com.floragunn.searchguard.action.configupdate.TransportConfigUpdateAction] [ip-10-22-9-26] index 'searchguard' not healthy yet, we try again ... (Reason: timeout)
                                                                                                                51,1          Bot
```

Running sgadmin.sh just of course hangs since the ES nodes never go at least yellow.

**Comment by floragunncom** [comment]
is this on aws? then you might want to install also cloud-aws plugin, see https://www.elastic.co/blog/running-elasticsearch-on-aws or https://www.elastic.co/guide/en/elasticsearch/plugins/2.4/cloud-aws.html

**Comment by cfoutstd** [comment]
Thanks, I'll install the cloud-aws plugin. How does it alleviate the issue?

**Comment by floragunncom** [comment]
Its about how discovery works. This is not a SG topic, its general to ES.

**Comment by cfoutstd** [comment]
Thanks. I read more about the cloud-aws plugin. For now (until I get this issue resolved), I'll stick with the zen discovery so I don't "cloud" the issue. :)

**Comment by cfoutstd** [comment]
Here is my elasticsearch.yml file, with comments removed for ease.

```
Last login: Mon Oct 17 09:28:37 on ttys004
MUSCF186025-714:~ cf186025$ ssh 10.22.9.4
-------------------------------------------------------------------------------
# This image has been automatically created with ComodIT - http://comodit.com #
-------------------------------------------------------------------------------

X11 forwarding request failed on channel 0
Last login: Mon Oct 17 13:33:22 2016 from ip-10-22-1-31.ec2.internal
[cf186025@ip-10-22-9-4 ~]$ sudo -i
[root@ip-10-22-9-4 ~]# ls
anaconda-ks.cfg          kibana.yml             sg_roles_mapping.yml
elasticsearch            sg_action_groups.yml   sg_roles.yml
elasticsearch_no_sg.log  sg_config.yml          test.py
elasticsearch_sg.log     sg_internal_users.yml
[root@ip-10-22-9-4 ~]# vim /var/log/elasticsearch/elk-nova-devops.log
[root@ip-10-22-9-4 ~]# vim /var/log/elasticsearch/elk-nova-devops.log
You have new mail in /var/spool/mail/root
[root@ip-10-22-9-4 ~]# cd /etc/elasticsearch/
[root@ip-10-22-9-4 elasticsearch]# ls
elasticsearch.yml          node-0-keystore.jks   sg_internal_users.yml
elasticsearch.yml.rpmnew   node-1-keystore.jks   sg_roles_mapping.yml
elasticsearch.yml.rpmsave  node-2-keystore.jks   sg_roles.yml
kirk-keystore.jks          scripts               spock-keystore.jks
logging.yml                sg_action_groups.yml  truststore.jks
logging.yml.rpmsave        sg_config.yml
[root@ip-10-22-9-4 elasticsearch]# vim elasticsearch.yml
[root@ip-10-22-9-4 elasticsearch]# cp elasticsearch.yml ~/mod_elasticsearch.yml
[root@ip-10-22-9-4 elasticsearch]# cd
[root@ip-10-22-9-4 ~]# vim mod_elasticsearch.yml 












cluster.name: elk-nova-devops
node.name: ip-10-22-9-4
path.logs: /var/log/elasticsearch/
bootstrap.mlockall: true

network.host: [ _site_, _local_ ]
http.port: 9200
discovery.zen.ping.multicast.enabled: false
discovery.zen.ping.unicast.hosts: [ "10.22.9.4" ]
discovery.zen.minimum_master_nodes: 1
discovery.zen.ping_timeout: 60s
action.auto_create_index: .marvel-*,.marvel_*,.security
action.auto_create_index: true

script.inline: on
script.indexed: on
index.number_of_shards: 1

index.number_of_replicas: 1

index.routing.allocation.disable_allocation: false

marvel.agent.enabled: False
marvel.agent.interval: 1m
marvel.history.duration: 1

searchguard.ssl.http.enabled: true
searchguard.ssl.http.keystore_filepath: node-0-keystore.jks
searchguard.ssl.http.keystore_password: pw
searchguard.ssl.http.truststore_filepath: truststore.jks
searchguard.ssl.http.truststore_password: pw
searchguard.ssl.http.enable_openssl_if_available: true

searchguard.ssl.transport.keystore_filepath: node-0-keystore.jks
searchguard.ssl.transport.keystore_password: pw
searchguard.ssl.transport.truststore_filepath: truststore.jks
searchguard.ssl.transport.truststore_password: pw
searchguard.ssl.transport.enforce_hostname_verification: false
searchguard.ssl.transport.enable_openssl_if_available: true

searchguard.authcz.admin_dn:
  - cn=kirk, ou=client, o=client, l=Test, c=DE

```

**Comment by cfoutstd** [comment]
With SG removed, and ES restarted, I get

```
# curl -I https://127.0.0.1:9200 --cacert /tmp/certs/ca/chain-ca.pem 
HTTP/1.1 200 OK
Content-Type: text/plain; charset=UTF-8
Content-Length: 0

# curl -vv https://127.0.0.1:9200 --cacert /tmp/certs/ca/chain-ca.pem 
* About to connect() to 127.0.0.1 port 9200 (#0)
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 9200 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: /tmp/certs/ca/chain-ca.pem
  CApath: none
* NSS: client certificate not found (nickname not specified)
* SSL connection using TLS_DHE_RSA_WITH_AES_128_CBC_SHA256
* Server certificate:
* 	subject: CN=node-0.td.teradata.com,OU=Teradata,O=DevOps,L=Raleigh,C=US
* 	start date: Oct 12 17:49:23 2016 GMT
* 	expire date: Oct 12 17:49:23 2018 GMT
* 	common name: node-0.td.teradata.com
* 	issuer: CN=Example Com Inc. Signing CA,OU=Example Com Inc. Signing CA,O=Example Com Inc.,DC=example,DC=com
> GET / HTTP/1.1
> User-Agent: curl/7.29.0
> Host: 127.0.0.1:9200
> Accept: */*
> 
< HTTP/1.1 200 OK
< Content-Type: application/json; charset=UTF-8
< Content-Length: 323
< 
{
  "name" : "ip-10-22-9-4",
  "cluster_name" : "elk-nova-devops",
  "version" : {
    "number" : "2.4.0",
    "build_hash" : "ce9f0c7394dee074091dd1bc4e9469251181fc55",
    "build_timestamp" : "2016-08-29T09:14:17Z",
    "build_snapshot" : false,
    "lucene_version" : "5.5.2"
  },
  "tagline" : "You Know, for Search"
}
* Connection #0 to host 127.0.0.1 left intact
```

**Comment by floragunncom** [comment]
On AWS right?

Do you use a kind of automated installation which you can provide so we can try to reproduce this on aws? If not can you elaborate how you installed ES on AWS/EC2?

**Comment by cfoutstd** [comment]
I created the AWS instances manually with a CentOS 7 image, which I then ran a yum update on to update to CentOS 7.2. I do NOT use scripts nor CloudFormation to create my instances.

I do use Ansible to install ES, SG-SSL and SG, but have also installed them manually and gotten the same error. So I do this process for my manual installation
- Created AWS instance from CentOS7.x image, and updated to 7.2
- Installed ES, and modified config files (e.g., ES_HEAP_SIZE, ES_JAVA_OPTS, etc)
- Ran ES - Ok
- Stopped ES
- Installed SG-SSL
- Generated certs/keys per SG scripts, and copied JKS files in /etc/elasticsearch
- Added SSL-specific lines in ES YML file, see YML file in previous post.
- Started ES - ES runs OK (per curl in last post)
- Stopped ES
- Installed SG
- Copied sg_*.yml files in /etc/elasticsearch, with NO modifications
- Started ES - ES stays RED! curl get HTTP 503 - Service unavailable, SG is not initialied

**Comment by floragunncom** [comment]
do you have the elasticsearch license plugin installed? if yes pls. deinstall it and try again

**Comment by floragunncom** [comment]
I tried on AWS with Ubuntu 14.04 and Elasticsearch 2.4.1 with SG 2.4.1.7 and SG SSL 2.4.1.16 and your config but without the license plugin or Marvel installed and it worked flawlessly.

Note: You have two issues in your config:

This an invalid config (same key):
<pre>
action.auto_create_index: .marvel-*,.marvel_*,.security
action.auto_create_index: true
</pre>

Pls. change the last line to (quotes)
<pre>
searchguard.authcz.admin_dn:
  - "cn=kirk, ou=client, o=client, l=Test, c=DE"
</pre>

**Comment by cfoutstd** [comment]
Thanks, I'll make the changes. What's the "license" plugin? I don't have Marvel installed so that's an entry in an existing file I'm using, and I'll remove it.

**Comment by cfoutstd** [comment]
Thanks for ALL your help! This turned out to be an AWS security group issue with port 9300 being locked. Once our AWS admin added a rule to allow port 9300 access to our AWS VPC, the cluster came up.
