### ISSUE TITLE
java.lang.IllegalStateException: path.home is not configured

### ISSUE THREAD

**Issue by rsmilyanov** [floragunncom/search-guard#234]
### Version Information
* Search Guard - 5.0.0-17
* Elasticsearch - 5.0.0
* JVM version - Oracle 64-Bit 1.8.0_111
* OS - Ubuntu 16.04
* Number of nodes in your cluster - 1

### Description of the bug
I am trying to attach a TransportClient to my local ElasticSearch server (thus the number of nodes is 1) with the following code:

```
Settings settings = Settings.builder()
                .put("cluster.name", "<cluster_name>")
                .put("client.transport.sniff", true)
                .put(SSLConfigConstants.SEARCHGUARD_SSL_TRANSPORT_KEYSTORE_FILEPATH, "<key_store_full_path>")
                .put(SSLConfigConstants.SEARCHGUARD_SSL_TRANSPORT_TRUSTSTORE_FILEPATH, "<truststore_full_path>")
                .put(SSLConfigConstants.SEARCHGUARD_SSL_TRANSPORT_KEYSTORE_PASSWORD, "<keystore_password>")
                .put(SSLConfigConstants.SEARCHGUARD_SSL_TRANSPORT_TRUSTSTORE_PASSWORD, "<truststore_passwrod")
                .build();

this.client = new PreBuiltTransportClient(settings, SearchGuardSSLPlugin.class)
			.addTransportAddress(new InetSocketTransportAddress(new InetSocketAddress("localhost", 9300)));
```

Whenever I run this code I get the following exception:
```
java.lang.IllegalStateException: path.home is not configured

	at org.elasticsearch.env.Environment.<init>(Environment.java:115)
	at com.floragunn.searchguard.ssl.SearchGuardKeyStore.initSSLConfig(SearchGuardKeyStore.java:172)
	at com.floragunn.searchguard.ssl.SearchGuardKeyStore.<init>(SearchGuardKeyStore.java:139)
	at com.floragunn.searchguard.ssl.SearchGuardSSLModule.<init>(SearchGuardSSLModule.java:29)
	at com.floragunn.searchguard.ssl.SearchGuardSSLPlugin.createGuiceModules(SearchGuardSSLPlugin.java:125)
	at org.elasticsearch.plugins.PluginsService.createGuiceModules(PluginsService.java:280)
	at org.elasticsearch.client.transport.TransportClient.buildTemplate(TransportClient.java:134)
	at org.elasticsearch.client.transport.TransportClient.<init>(TransportClient.java:228)
	at org.elasticsearch.transport.client.PreBuiltTransportClient.<init>(PreBuiltTransportClient.java:69)
	at org.elasticsearch.transport.client.PreBuiltTransportClient.<init>(PreBuiltTransportClient.java:65)
```

If I add "path.home" settings the TransportClient gets initialized successfully. Is it necessary to provide "path.home" settings during initialization of a TransportClient? I do not see any reason to init my TransportClient as passing "path.home" setting. Am I missing something?

Thanks,
Radoslav

**Comment by floragunncom** [comment]
"path.home" is enforced by elasticsearch core, so this is not Search Guard related

**Comment by floragunncom** [comment]
Here is an example how to make transport client work: https://github.com/floragunncom/search-guard/blob/5.0.0/src/test/java/com/floragunn/searchguard/SGTests.java#L2156

**Comment by rsmilyanov** [comment]
@floragunncom thanks you!
