### ISSUE TITLE
Curl returned "You are attempting to import a cert with the same issuer/serial as an existing cert" when enabled HTTPS on ES 5.0.2 with SG 5.0.2-8 plugin 

### ISSUE THREAD

**Issue by r0c** [floragunncom/search-guard#249]
The testing environment is same as mentioned in https://github.com/floragunncom/search-guard/issues/246. 

Node-to-Node transport TLS encryption worked fine. After enabling HTTPS I got the following error with curl.

```
# curl -kv https://10.99.1.217:9200/_cluster/health
* About to connect() to 10.99.1.217 port 9200 (#0)
*   Trying 10.99.1.217...
* Connected to 10.99.1.217 (10.99.1.217) port 9200 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
* NSS error -8054 (SEC_ERROR_REUSED_ISSUER_AND_SERIAL)
* You are attempting to import a cert with the same issuer/serial as an existing cert, but that is not the same cert.
* Closing connection 0
curl: (35) You are attempting to import a cert with the same issuer/serial as an existing cert, but that is not the same cert.
```

elasticsearch.yml:
```
cluster.name: dev-es-e20-cluster
node.name: ip-10-99-1-217
node.attr.rack: us-west-2c
node.master: false
node.data: true
node.ingest: false
path.data: /es_data/data
path.logs: /es_data/logs
bootstrap.memory_lock: true
network.bind_host: 10.99.1.217
network.publish_host: xx.yy.235.234
http.port: 9200
transport.tcp.port: 9300
transport.tcp.compress: true
discovery.zen.ping.unicast.hosts:
  - xx.yy.40.96
  - xx.zz.235.234
discovery.zen.minimum_master_nodes: 1
node.max_local_storage_nodes: 1
searchguard.ssl.transport.keystore_filepath: es-worker01.e20.dev.jks
searchguard.ssl.transport.keystore_password: changeit
searchguard.ssl.transport.truststore_filepath: truststore.jks
searchguard.ssl.transport.truststore_password: changeit
searchguard.ssl.transport.enforce_hostname_verification: false

searchguard.ssl.http.keystore_filepath: es-worker01.e20.dev.jks
searchguard.ssl.http.keystore_password: changeit
searchguard.ssl.http.truststore_filepath: truststore.jks
searchguard.ssl.http.truststore_password: changeit

searchguard.authcz.admin_dn:
  - cn=admin,o=xxx xxx Com Inc.
```

ES logs:
```
[2016-12-08T11:00:39,129][WARN ][c.f.s.h.SearchGuardHttpServerTransport] [ip-10-99-1-217] caught exception while handling client http traffic, closing connection [id: 0xfa3e8624, L.]
io.netty.handler.codec.DecoderException: javax.net.ssl.SSLException: Received fatal alert: bad_certificate
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:442) ~[netty-codec-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248) ~[netty-codec-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:129) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:610) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:513) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:467) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:437) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873) [netty-common-4.1.5.Final.jar:4.1.5.Final]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_102]
Caused by: javax.net.ssl.SSLException: Received fatal alert: bad_certificate
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:208) ~[?:?]
        at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1666) ~[?:?]
        at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1634) ~[?:?]
        at sun.security.ssl.SSLEngineImpl.recvAlert(SSLEngineImpl.java:1800) ~[?:?]
        at sun.security.ssl.SSLEngineImpl.readRecord(SSLEngineImpl.java:1083) ~[?:?]
        at sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:907) ~[?:?]
        at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:781) ~[?:?]
        at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:624) ~[?:1.8.0_102]
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1094) ~[?:?]
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:966) ~[?:?]
        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:900) ~[?:?]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411) ~[?:?]
        ... 15 more
```

@floragunncom has a clue?

**Comment by floragunncom** [comment]
Your curl is compiled with NSS support and by default it sends SSL certificated stored in /etc/pki/nssd. We recommend to use curl which is linked against openssl (see https://gist.github.com/floragunncom/4eecb1586b426a19b77457228d331c43) or make sure your certs in /etc/pki/nssd are sufficient (or your server truststore does accept them).

If you do not need two way ssl for HTTP you can add 
`searchguard.ssl.http.clientauth_mode: NONE`
to elasticsearch.yml

**Comment by floragunncom** [comment]
Can you also post the output of
`certutil -L -d /etc/pki/nssdb ` and
`curl -V`

Maybe also `-k` (`--insecure`) is not working correctly with NSS?

**Comment by r0c** [comment]
Change searchguard.ssl.http.clientauth_mode To NONE ends up with the same error. 

certutil & curl info:
```
[root@ip-10-99-1-212 ~]# certutil -L -d /etc/pki/nssdb

Certificate Nickname                                         Trust Attributes
                                                             SSL,S/MIME,JAR/XPI

[root@ip-10-99-1-212 ~]# curl -V
curl 7.29.0 (x86_64-redhat-linux-gnu) libcurl/7.29.0 NSS/3.19.1 Basic ECC zlib/1.2.7 libidn/1.28 libssh2/1.4.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smtp smtps telnet tftp
Features: AsynchDNS GSS-Negotiate IDN IPv6 Largefile NTLM NTLM_WB SSL libz
[root@ip-10-99-1-212 ~]#
```

**Comment by r0c** [comment]
Also tried NSS backed curl with feeding '--cert', '--cacert' , '-k' params, but failed:
```
curl -v --cert /home/centos/admin.crt.pem --key /home/centos/admin.key.pem --cacert siging_ca_and_root_ca https://10.99.1.212:9200/

* About to connect() to 10.99.1.212 port 9200 (#0)
*   Trying 10.99.1.212...
* Connected to 10.99.1.212 (10.99.1.212) port 9200 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: /home/centos/siging_ca_and_root_ca
  CApath: none
* NSS error -8054 (SEC_ERROR_REUSED_ISSUER_AND_SERIAL)
* You are attempting to import a cert with the same issuer/serial as an existing cert, but that is not the same cert.
* Closing connection 0
curl: (35) You are attempting to import a cert with the same issuer/serial as an existing cert, but that is not the same cert.

# curl  -k https://10.99.1.212:9200/_cluster/health?pretty
curl: (35) You are attempting to import a cert with the same issuer/serial as an existing cert, but that is not the same cert.

```

Good news is when I turned to [curl-openssl](http://rpm.pbone.net/index.php3/stat/4/idpl/33795969/dir/centos_7/com/curl-openssl-7.43.0-1.1.x86_64.rpm.html), it worked like a charm.

```
[root@ip-10-99-1-212 bin]#  LD_LIBRARY_PATH=/opt/shibboleth/lib64 ./curl  --cacert /home/centos/admin.all.pem  https://10.99.1.212:9200/_cluster/health?pretty --user admin:secret
{
  "cluster_name" : "dev-es-e20-cluster",
  "status" : "green",
  "timed_out" : false,
  "number_of_nodes" : 2,
  "number_of_data_nodes" : 1,
  "active_primary_shards" : 1,
  "active_shards" : 1,
  "relocating_shards" : 0,
  "initializing_shards" : 0,
  "unassigned_shards" : 0,
  "delayed_unassigned_shards" : 0,
  "number_of_pending_tasks" : 0,
  "number_of_in_flight_fetch" : 0,
  "task_max_waiting_in_queue_millis" : 0,
  "active_shards_percent_as_number" : 100.0
}
```

Quite weird. Dunno how to make it work with NSS.

**Comment by floragunncom** [comment]
curl 7.29.0 is really outdated as well as NSS 3.19. Maybe you can try to compiling recent curl with recent NSS and try again. Current curl version is 7.51 and NSS is 3.27.1 (as the time of writing).

**Comment by r0c** [comment]
Tried to build curl(latest) with nss (3.27.2) met some wired errors, but never mind I can use curl/openssl. 

Thanks.

**Comment by floragunncom** [comment]
Will close this issue because it seems its curl and not SG related.
