### ISSUE TITLE
Unable to install 5.1.1

### ISSUE THREAD

**Issue by kiblik** [floragunncom/search-guard#251]
I tried install last version of search-guard but downloading failed

```
sudo bin/elasticsearch-plugin install -b com.floragunn:search-guard-5:5.1.1-9
-> Downloading com.floragunn:search-guard-5:5.1.1-9 from maven central
Exception in thread "main" java.io.FileNotFoundException: https://repo1.maven.org/maven2/com/floragunn/search-guard-5/5.1.1-9/search-guard-5-5.1.1-9.zip
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1926)
        at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1921)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1920)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1490)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
        at org.elasticsearch.plugins.InstallPluginCommand.downloadZip(InstallPluginCommand.java:279)
        at org.elasticsearch.plugins.InstallPluginCommand.downloadZipAndChecksum(InstallPluginCommand.java:322)
        at org.elasticsearch.plugins.InstallPluginCommand.download(InstallPluginCommand.java:240)
        at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:210)
        at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:195)
        at org.elasticsearch.cli.SettingCommand.execute(SettingCommand.java:54)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:96)
        at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:69)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:96)
        at org.elasticsearch.cli.Command.main(Command.java:62)
        at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:42)
Caused by: java.io.FileNotFoundException: https://repo1.maven.org/maven2/com/floragunn/search-guard-5/5.1.1-9/search-guard-5-5.1.1-9.zip
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1872)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
        at sun.net.www.protocol.http.HttpURLConnection.getHeaderField(HttpURLConnection.java:2982)
        at java.net.URLConnection.getHeaderFieldLong(URLConnection.java:629)
        at java.net.URLConnection.getContentLengthLong(URLConnection.java:501)
        at java.net.URLConnection.getContentLength(URLConnection.java:485)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getContentLength(HttpsURLConnectionImpl.java:398)
        at org.elasticsearch.plugins.InstallPluginCommand.downloadZip(InstallPluginCommand.java:278)
        ... 10 more

```

**Comment by floragunncom** [comment]
this is not released yet, see https://github.com/floragunncom/search-guard/wiki for the current released versions
