### ISSUE TITLE
Authorization Headers doesnt work in SearchGuard

### ISSUE THREAD

**Issue by shashanka981** [floragunncom/search-guard#264]
ES version : 2.4.0 , OS:Windows
I have these settings
Settings settings = Settings.settingsBuilder()
				.put("cluster.name", "mycluster")
				.put("path.home", ".")
				.put("searchguard.ssl.transport.enabled","true")
				.put("searchguard.ssl.transport.keystore_filepath", "E:\\ElasticSearch\\certis\\kirk-keystore.jks")
				.put("searchguard.ssl.transport.keystore_password", "changeit")
				.put("searchguard.ssl.transport.truststore_filepath", "E:\\ElasticSearch\\certis\\truststore.jks")
				.put("searchguard.ssl.transport.enforce_hostname_verification",false)
				.put("searchguard.ssl.transport.truststore_password", "changeit")
				.build();

I have a Transport client which makes use of the above settings
TransportClient  client = TransportClient.builder().settings(settings)
				.addPlugin(SearchGuardSSLPlugin.class)
				.build()
		        .addTransportAddress(new InetSocketTransportAddress(InetAddress.getByName("127.0.0.1"), 9300));				System.out.println(client.admin().indices().prepareExists("index1080").putHeader("Authorization", "basic "+encodeBasicHeader("spock", "wrongpassword")));

I expect the about sysout should return ElasticSearchSecurity Exception as i have specifiec a wrong password, but authentication passes thorugh
My requirement here is to validate the username and password from every request from the transport client.. These username and password will differ for every request as we have the same client being used by many users..

I am not very sure how the below 2 would work in tandem
1) put("request.headers.sg_impersonate_as", "myuser")
2) putHeader("Authorization", "Basic "+encodeBasicHeader("admin","admin"))

Do i even have to use the impersonate_as setting as all the users will have same privileges for my use case...I just needed Authntication of user credentials passed as Authorization headers..Can i set the Authorization Header while constructing the settings object using put("Authorization","Basic "+ encode-------------------).. Is this expected to work ?Am i rightly setting the Authorization header

Thanks in advance

**Comment by floragunncom** [comment]
This was already asked in the google groups community mailing list. Please provide more informations, especially the SG version you are using and logfiles on DEBUG level.

Impersonation and basic authentication are to supposed to work together, choose one of both. If you have the clear text password use basic authentication, if not choose impersonation. Your above example pass through (despite the wrong password) because you use am admin ssl certificate (kirk) which always grant unlimited access.

**Comment by shashanka981** [comment]
SG Version is 2.4.0, 

Thanks for the clarification on Impersonation part. However I wanted to use the username/password authentication. And i now removed all the impersonation settings from elasticSearch.yml and i am trying to add Authorization Headers for the transport client in the following way

Settings settings = Settings.settingsBuilder()
.put("cluster.name", "mycluster")
.put("path.home", ".")
.put("searchguard.ssl.transport.enabled","true")
.put("searchguard.ssl.transport.keystore_filepath", "E:\ElasticSearch\certis\spock-keystore.jks")
.put("searchguard.ssl.transport.keystore_password", "changeit")
.put("searchguard.ssl.transport.truststore_filepath", "E:\ElasticSearch\certis\truststore.jks")
.put("searchguard.ssl.transport.enforce_hostname_verification",false)
.put("searchguard.ssl.transport.truststore_password", "changeit")
.put("Authorization","Basic "+encodeBasicHeader("admins", "wrongpassword"))
.build();

System.out.println(client.admin().indices().prepareCreate("index212")
						.putHeader("Authorization", "Basic "+encodeBasicHeader("myuser","myuser"))
						.execute().actionGet());

Still i see the below exception.  Why would it take the user to be "CN=spock,OU=----------" ?
Am i correctly setting authorization headers

[2016-12-25 19:28:46,006][ERROR][com.floragunn.searchguard.auth.BackendRegistry] Unexpected exception java.util.concurrent.ExecutionException: java.lang.Exception: no such user CN=spock,OU=client,O=client,L=Test,C=DE 
java.util.concurrent.ExecutionException: java.lang.Exception: no such user CN=spock,OU=client,O=client,L=Test,C=DE
	at com.google.common.util.concurrent.AbstractFuture$Sync.getValue(AbstractFuture.java:299)
	at com.google.common.util.concurrent.AbstractFuture$Sync.get(AbstractFuture.java:286)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:116)
	at com.google.common.util.concurrent.Uninterruptibles.getUninterruptibly(Uninterruptibles.java:137)
	at com.google.common.cache.LocalCache$Segment.getAndRecordStats(LocalCache.java:2348)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2320)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2282)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2197)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3937)
	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4739)
	at com.floragunn.searchguard.auth.BackendRegistry.authenticate(BackendRegistry.java:277)
	at com.floragunn.searchguard.transport.SearchGuardTransportService.messageReceivedDecorate(SearchGuardTransportService.java:255)
	at com.floragunn.searchguard.ssl.transport.SearchGuardSSLTransportService$Interceptor.messageReceived(SearchGuardSSLTransportService.java:139)
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:77)
	at org.elasticsearch.transport.netty.MessageChannelHandler.handleRequest(MessageChannelHandler.java:227)
	at com.floragunn.searchguard.ssl.transport.SearchGuardMessageChannelHandler.handleRequest(SearchGuardMessageChannelHandler.java:62)
	at org.elasticsearch.transport.netty.MessageChannelHandler.messageReceived(MessageChannelHandler.java:116)
	at com.floragunn.searchguard.ssl.transport.SearchGuardMessageChannelHandler.messageReceived(SearchGuardMessageChannelHandler.java:50)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:462)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:443)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.elasticsearch.common.netty.OpenChannelsHandler.handleUpstream(OpenChannelsHandler.java:75)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:462)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:443)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:722)
Caused by: java.lang.Exception: no such user CN=spock,OU=client,O=client,L=Test,C=DE
	at com.floragunn.searchguard.auth.BackendRegistry$4.call(BackendRegistry.java:298)
	at com.floragunn.searchguard.auth.BackendRegistry$4.call(BackendRegistry.java:277)
	at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4742)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2319)
	... 44 more

**Comment by shashanka981** [comment]
Sorry, I did not define the user in sg_internal. It works fine now

**Comment by shashanka981** [comment]
Sorry, I did not define the user in sg_internal_users. It works fine now
