### ISSUE TITLE
Version 5.2.0-10 fails with NoSuchMethodError

### ISSUE THREAD

**Issue by dorony** [floragunncom/search-guard#293]
Elasticsearch version: 5.2.0
Searchguard version: 5.2-10
JVM version: 1.8.0_121
OS version: Ubuntu 14.04.5
Number of nodes: 8

When starting Elastic I'm getting the following error:
```
java.lang.NoSuchMethodError: org.apache.tomcat.jni.SSLContext.setCACertificateBio(JJ)Z
	at io.netty.handler.ssl.ReferenceCountedOpenSslServerContext.newSessionContext(ReferenceCountedOpenSslServerContext.java:162) ~[?:?]
	at io.netty.handler.ssl.OpenSslServerContext.<init>(OpenSslServerContext.java:349) ~[?:?]
	at io.netty.handler.ssl.OpenSslServerContext.<init>(OpenSslServerContext.java:334) ~[?:?]
	at io.netty.handler.ssl.SslContext.newServerContextInternal(SslContext.java:414) ~[?:?]
	at io.netty.handler.ssl.SslContextBuilder.build(SslContextBuilder.java:402) ~[?:?]
	at com.floragunn.searchguard.ssl.DefaultSearchGuardKeyStore$1.run(DefaultSearchGuardKeyStore.java:500) ~[?:?]
	at com.floragunn.searchguard.ssl.DefaultSearchGuardKeyStore$1.run(DefaultSearchGuardKeyStore.java:497) ~[?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_121]
	at com.floragunn.searchguard.ssl.DefaultSearchGuardKeyStore.buildSSLContext(DefaultSearchGuardKeyStore.java:497) ~[?:?]
	at com.floragunn.searchguard.ssl.DefaultSearchGuardKeyStore.initSSLConfig(DefaultSearchGuardKeyStore.java:238) ~[?:?]
	at com.floragunn.searchguard.ssl.DefaultSearchGuardKeyStore.<init>(DefaultSearchGuardKeyStore.java:139) ~[?:?]
	at com.floragunn.searchguard.SearchGuardPlugin.<init>(SearchGuardPlugin.java:183) ~[?:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_121]
	at org.elasticsearch.plugins.PluginsService.loadPlugin(PluginsService.java:373) ~[elasticsearch-5.2.0.jar:5.2.0]
	at org.elasticsearch.plugins.PluginsService.loadBundles(PluginsService.java:336) ~[elasticsearch-5.2.0.jar:5.2.0]
	at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:132) ~[elasticsearch-5.2.0.jar:5.2.0]
	at org.elasticsearch.node.Node.<init>(Node.java:297) ~[elasticsearch-5.2.0.jar:5.2.0]
	at org.elasticsearch.node.Node.<init>(Node.java:232) ~[elasticsearch-5.2.0.jar:5.2.0]
	at org.elasticsearch.bootstrap.Bootstrap$6.<init>(Bootstrap.java:241) ~[elasticsearch-5.2.0.jar:5.2.0]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:241) ~[elasticsearch-5.2.0.jar:5.2.0]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:333) ~[elasticsearch-5.2.0.jar:5.2.0]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:121) ~[elasticsearch-5.2.0.jar:5.2.0]
```
The previous version (5.1.2-10) was working OK for me.

**Comment by floragunncom** [comment]
seems to be a duplicate of https://github.com/floragunncom/search-guard/issues/291

**Comment by dorony** [comment]
Thanks, I have the correct version of the tcnative fork installed (Fork25), but I still get this error.

**Comment by dorony** [comment]
Thanks!
