### ISSUE TITLE
sgadmin.sh not connecting to multiple nodes

### ISSUE THREAD

**Issue by francopeapea** [floragunncom/search-guard#294]
I'm testing in my local machine with
2.4.3 ES version
2.4.3 SG version

I had a resumed copy of my production stack in my local machine and i'm testing the use of search guard with multiple nodes 1 master - 1 data - 1 client

I'm not being able to connect the master and data node before initialize the sgadmin.sh with my command:
`
`/my/elastic/path/plugins/search-guard-2/tools/sgadmin.sh` -cd /my/elastic/path/plugins/search-guard-2/sgconfig/ -icl -ks /my/elastic/path/config/xxxxx-keystore.jks -kspass xxxx -ts /my/elastic/path/config/truststore.jks -tspass xxxx -nhnv`

that on the master node, and when i run it i have this in the log:

[INFO ][com.floragunn.searchguard.action.configupdate.TransportConfigUpdateAction] [xxxxx] searchguard index does not exist yet, so no need to load config on node startup. Use sgadmin to initialize cluster
[2017-02-09 13:40:23,453][ERROR][com.floragunn.searchguard.configuration.ConfigurationLoader] Failure no such index retrieving configuration for [config, roles, rolesmapping, internalusers, actiongroups] (index=searchguard)

If i try to initiate the data node at same time with the same certificate i just get this error in the master node:

[INFO ][com.floragunn.searchguard.action.configupdate.TransportConfigUpdateAction] [xxxx] searchguard index does not exist yet, so no need to load config on node startup. Use sgadmin to initialize cluster
[2017-02-09 13:53:39,026][ERROR][com.floragunn.searchguard.transport.SearchGuardTransportService] Internal or shard requests not allowed from a non-server node for transport type netty

and this in the data-node:

[WARN ][discovery.zen.ping.unicast] [xxxx-1] failed to send ping to [{#zen_unicast_1#}{127.0.0.1}{127.0.0.1:9300}]
RemoteTransportException[[xxxx][127.0.0.1:9300][internal:discovery/zen/unicast]]; nested: ElasticsearchSecurityException[Internal or shard requests not allowed from a non-server node for transport type netty];
Caused by: ElasticsearchSecurityException[Internal or shard requests not allowed from a non-server node for transport type netty]
	at com.floragunn.searchguard.transport.SearchGuardTransportService.messageReceivedDecorate(SearchGuardTransportService.java:202)
	at com.floragunn.searchguard.ssl.transport.SearchGuardSSLTransportService$Interceptor.messageReceived(SearchGuardSSLTransportService.java:139)
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:77)
	at org.elasticsearch.transport.netty.MessageChannelHandler.handleRequest(MessageChannelHandler.java:227)
	at com.floragunn.searchguard.ssl.transport.SearchGuardMessageChannelHandler.handleRequest(SearchGuardMessageChannelHandler.java:62)
	at org.elasticsearch.transport.netty.MessageChannelHandler.messageReceived(MessageChannelHandler.java:116)
	at com.floragunn.searchguard.ssl.transport.SearchGuardMessageChannelHandler.messageReceived(SearchGuardMessageChannelHandler.java:50)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:462)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:443)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.elasticsearch.common.netty.OpenChannelsHandler.handleUpstream(OpenChannelsHandler.java:75)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:462)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:443)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)

This is also my master node conf:

 node.master: true
 node.data: false
....
 network.host: [127.0.0.1]

#
 http.port: 9200

#
#--------------------------------- Discovery ----------------------------------

 discovery.zen.ping.multicast.enabled: false
 discovery.zen.ping.unicast.hosts: ["localhost"]
 discovery.zen.minimum_master_nodes: 1

#--------------------------------------Search-Guard-----------------------------------

############Keystore

 searchguard.ssl.transport.keystore_type: JKS
 searchguard.ssl.transport.keystore_filepath: xxxx-keystore.jks
 searchguard.ssl.transport.keystore_password: xxxx
 searchguard.ssl.trasnport.keystore_alias: xxxx

###########Truststore

 searchguard.ssl.transport.truststore_type: JKS
 searchguard.ssl.transport.truststore_filepath: truststore.jks
 searchguard.ssl.transport.truststore_password: xxxx

###########Hostname verification

 searchguard.ssl.transport.enforce_hostname_verification: false
 
##########Transport layer SSL

 searchguard.ssl.transport.enabled: true
 
##########Open SSL

 searchguard.ssl.transport.enable_openssl_if_available: false

 searchguard.authcz.admin_dn:
   - "CN=xxxx,OU=xxxx,O=xxxx,L=xxxx,C=XX"

and my data-node conf:
 node.master: false
 node.data: true
....
#---------------------------------- Network -----------------------------------
#
 network.host: [localhost]

#
 http.port: 9202
#
#--------------------------------- Discovery ----------------------------------

 discovery.zen.ping.multicast.enabled: false
 discovery.zen.ping.unicast.hosts: ["localhost"]
 discovery.zen.minimum_master_nodes: 1
#--------------------------------------Search-Guard-----------------------------------

############Keystore

 searchguard.ssl.transport.keystore_type: JKS
 searchguard.ssl.transport.keystore_filepath: xxxx-keystore.jks
 searchguard.ssl.transport.keystore_password: xxxx
 searchguard.ssl.trasnport.keystore_alias: xxxx

###########Truststore

 searchguard.ssl.transport.truststore_type: JKS
 searchguard.ssl.transport.truststore_filepath: truststore.jks
 searchguard.ssl.transport.truststore_password: xxxx

###########Hostname verification

 searchguard.ssl.transport.enforce_hostname_verification: false
 
##########Transport layer SSL

 searchguard.ssl.transport.enabled: true
 
##########Open SSL

 searchguard.ssl.transport.enable_openssl_if_available: false

 searchguard.authcz.admin_dn:
   - "CN=xxxx,OU=xxxx,O=xxxx,L=xxxx,C=XX"

I generate the certs with the scripts that search guard provide

**Comment by floragunncom** [comment]
I guess you are using wrong ssl certificates. How did you generate them?

Apart from your problem with Search Guard it looks like that you cluster setup consisting of one master, one datanode and one client does not really make sense. Pls. make sure that the Search Guard related configurations are identical on all nodes regardless of it's role.

**Comment by floragunncom** [comment]
Ping

**Comment by floragunncom** [comment]
no feedback, assume issue is solved.
