### ISSUE TITLE
no such user error

### ISSUE THREAD

**Issue by novenzhen** [floragunncom/search-guard#317]
I met an error recently，if I don't set user as admin_dn in elasticsearch.yml but set user as impersention_dn,such as the following setting:
searchguard.authcz.admin_dn:
 - "CN=kirk,OU=client,O=client,L=Test,C=DE"
 

searchguard.authcz.impersonation_dn.CN:
  "spock,OU=client,O=client,L=Test,C=DE":
     - '*' 

when i use tranportclient wtih header("sg_impersonate_as", user) with spock‘s cert ’to communicate with the es  cluster，it will generate the following error:
Caused by: java.lang.Exception: no such user CN=spock,OU=client,O=client,L=Test,C=DE
	at com.floragunn.searchguard.auth.BackendRegistry$4.call(BackendRegistry.java:284) ~[?:?]
	at com.floragunn.searchguard.auth.BackendRegistry$4.call(BackendRegistry.java:263) ~[?:?]
	at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4793) ~[?:?]
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3542) ~[?:?]
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2323) ~[?:?]
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2286) ~[?:?]
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2201) ~[?:?]
	at com.google.common.cache.LocalCache.get(LocalCache.java:3953) ~[?:?]
	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4790) ~[?:?]
	at com.floragunn.searchguard.auth.BackendRegistry.authenticate(BackendRegistry.java:263) ~[?:?]
	... 42 more

**Comment by floragunncom** [comment]
The message "no such user CN=spock,OU=client,O=client,L=Test,C=DE" is pretty much clear and tells you that there is no user known with that name. Do you have such a user in sg_internal_users.yml?

Please do not ask questions here. 
For that refer to https://groups.google.com/forum/#!forum/search-guard

Github is a place **only** for reporting bugs or feature requests.
If you report a bug please include **always** the following informations:

* Search Guard and Elasticsearch version
* JVM version and operating system version
* Number of nodes in your cluster
* Description of the bug

These informations are optional but are very valueable and
typically would lead to get bugs fixed faster:

* Steps to reproduce
* Logfiles on DEBUG level
* A failing unittest
