### ISSUE TITLE
search-guard5+es5.3.0+Java rest client

### ISSUE THREAD

**Issue by jqsl2012** [floragunncom/search-guard#321]
client code: 
(see : https://www.elastic.co/guide/en/elasticsearch/client/java-rest/current/_encrypted_communication.html)
`restClient = RestClient.builder(hosts)
				.setHttpClientConfigCallback(new RestClientBuilder.HttpClientConfigCallback() {
		            @Override
		            public HttpAsyncClientBuilder customizeHttpClient(HttpAsyncClientBuilder httpClientBuilder) {
				        SSLContext sslcontext =null;
						try {
							
							KeyStore keyStore = KeyStore.getInstance("jks");
			            	URI url = new File("d:\\truststore.jks").toURI();
			            	logger.info("url={}",url);
							try (InputStream is = Files.newInputStream(Paths.get(url ))) {
								logger.info("is={}",is);
								keyStore.load(is, "6d20813ca124b0e1a940".toCharArray());
			            	} catch (IOException e) {
								e.printStackTrace();
							}
							
							sslcontext = SSLContexts.custom().loadTrustMaterial(keyStore, null).build();
			                return httpClientBuilder.setSSLContext(sslcontext);
						} catch (KeyStoreException|NoSuchAlgorithmException|KeyManagementException|CertificateException e) {
			                throw new RuntimeException("Error setting up ssl", e);
			            }
		        })
				.setRequestConfigCallback(new RequestConfigCallback() {
					
					@Override
					public Builder customizeRequestConfig(Builder requestConfigBuilder) {
						return requestConfigBuilder.setConnectTimeout(config.getConnectTimeout())
								.setSocketTimeout(config.getSocketTimeout());
					}
				})
				.setMaxRetryTimeoutMillis(config.getMaxRetryTimeoutMillis())
				.build();`

Error : 
`javax.net.ssl.SSLPeerUnverifiedException: Host name '192.168.31.162' does not match the certificate subject provided by the peer (CN=localhost)
	at org.apache.http.nio.conn.ssl.SSLIOSessionStrategy.verifySession(SSLIOSessionStrategy.java:208)
	at org.apache.http.nio.conn.ssl.SSLIOSessionStrategy$1.verify(SSLIOSessionStrategy.java:188)
	at org.apache.http.nio.reactor.ssl.SSLIOSession.doHandshake(SSLIOSession.java:368)
	at org.apache.http.nio.reactor.ssl.SSLIOSession.isAppInputReady(SSLIOSession.java:509)
	at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:120)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:588)
	at java.lang.Thread.run(Unknown Source)`

Can you help me?

Thanks you

**Comment by floragunncom** [comment]
We can help you here https://groups.google.com/forum/#!forum/search-guard

Please do not ask questions here. 
For that refer to https://groups.google.com/forum/#!forum/search-guard

Github is a place **only** for reporting bugs or feature requests.
If you report a bug please include **always** the following informations:

* Search Guard and Elasticsearch version
* JVM version and operating system version
* Number of nodes in your cluster
* Description of the bug

These informations are optional but are very valueable and
typically would lead to get bugs fixed faster:

* Steps to reproduce
* Logfiles on DEBUG level
* A failing unittest
