### ISSUE TITLE
searchguard SSL issues

### ISSUE THREAD

**Issue by hila3000** [floragunncom/search-guard#326]
Hey,

I have ElasticSearch 5.2.2, with search-guard 5-5.2.2-11 plugin.
jdk installed via RPM - jdk-8u121-linux-x64.rpm
OS version Centos 7.3
I have one elastic cluster with 2 nodes that can't join the cluster after searchguard installation (each one thinks he's the master although there's already a master available)

I'm struggling setting search-guard with my company's certificates (works perfectly with the example certificates).

I had several errors until I got to the one I have now, and nothing in google helps me solve it.

the error on elastic cluster log-
Caused by: sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: signature check failed
        at sun.security.validator.PKIXValidator.doValidate(PKIXValidator.java:352) ~[?:?]
        at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:249) ~[?:?]
        at sun.security.validator.Validator.validate(Validator.java:260) ~[?:?]
        at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324) ~[?:?]
        at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:281) ~[?:?]
        at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:136) ~[?:?]
        at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1501) ~[?:?]
        at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216) ~[?:?]
        at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1026) ~[?:?]
        at sun.security.ssl.Handshaker$1.run(Handshaker.java:966) ~[?:?]
        at sun.security.ssl.Handshaker$1.run(Handshaker.java:963) ~[?:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_121]
        at sun.security.ssl.Handshaker$DelegatedTask.run(Handshaker.java:1416) ~[?:?]
        at io.netty.handler.ssl.SslHandler.runDelegatedTasks(SslHandler.java:1167) ~[?:?]
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1080) ~[?:?]
        ... 17 more
Caused by: java.security.cert.CertPathValidatorException: signature check failed
        at sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:135) ~[?:?]
        at sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:219) ~[?:?]
        at sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:140) ~[?:?]
        at sun.security.provider.certpath.PKIXCertPathValidator.engineValidate(PKIXCertPathValidator.java:79) ~[?:?]
        at java.security.cert.CertPathValidator.validate(CertPathValidator.java:292) ~[?:1.8.0_121]
        at sun.security.validator.PKIXValidator.doValidate(PKIXValidator.java:347) ~[?:?]
        at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:249) ~[?:?]
        at sun.security.validator.Validator.validate(Validator.java:260) ~[?:?]
        at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324) ~[?:?]
        at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:281) ~[?:?]
        at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:136) ~[?:?]
        at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1501) ~[?:?]
        at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216) ~[?:?]
        at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1026) ~[?:?]
        at sun.security.ssl.Handshaker$1.run(Handshaker.java:966) ~[?:?]
        at sun.security.ssl.Handshaker$1.run(Handshaker.java:963) ~[?:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_121]
        at sun.security.ssl.Handshaker$DelegatedTask.run(Handshaker.java:1416) ~[?:?]
        at io.netty.handler.ssl.SslHandler.runDelegatedTasks(SslHandler.java:1167) ~[?:?]
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1080) ~[?:?]
        ... 17 more
Caused by: java.security.SignatureException: Signature does not match.
        at sun.security.x509.X509CertImpl.verify(X509CertImpl.java:449) ~[?:?]
        at sun.security.provider.certpath.BasicChecker.verifySignature(BasicChecker.java:166) ~[?:?]
        at sun.security.provider.certpath.BasicChecker.check(BasicChecker.java:147) ~[?:?]
        at sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:125) ~[?:?]
        at sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:219) ~[?:?]
        at sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:140) ~[?:?]
        at sun.security.provider.certpath.PKIXCertPathValidator.engineValidate(PKIXCertPathValidator.java:79) ~[?:?]
        at java.security.cert.CertPathValidator.validate(CertPathValidator.java:292) ~[?:1.8.0_121]
        at sun.security.validator.PKIXValidator.doValidate(PKIXValidator.java:347) ~[?:?]
        at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:249) ~[?:?]
        at sun.security.validator.Validator.validate(Validator.java:260) ~[?:?]
        at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324) ~[?:?]
        at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:281) ~[?:?]
        at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:136) ~[?:?]
        at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1501) ~[?:?]
        at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216) ~[?:?]
        at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1026) ~[?:?]
        at sun.security.ssl.Handshaker$1.run(Handshaker.java:966) ~[?:?]
        at sun.security.ssl.Handshaker$1.run(Handshaker.java:963) ~[?:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_121]
        at sun.security.ssl.Handshaker$DelegatedTask.run(Handshaker.java:1416) ~[?:?]
        at io.netty.handler.ssl.SslHandler.runDelegatedTasks(SslHandler.java:1167) ~[?:?]
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1080) ~[?:?]
        ... 17 more

elasticsearch.yml configuration-
searchguard.ssl.transport.enabled: true
searchguard.ssl.transport.keystore_type: JKS
searchguard.ssl.transport.keystore_filepath: /etc/elasticsearch/srv-ulo-es1-keystore.jks
searchguard.ssl.transport.keystore_password: keystorepass
searchguard.ssl.transport.keystore_alias: srv-ulo-es1.prod.gw-4u.com
searchguard.ssl.transport.truststore_type: JKS
searchguard.ssl.transport.truststore_filepath: /etc/elasticsearch/truststore.jks
searchguard.ssl.transport.truststore_password: truststorepass
searchguard.ssl.transport.enforce_hostname_verification: true
searchguard.ssl.transport.resolve_hostname: true
#
searchguard.authcz.admin_dn:
  - "CN=esadmin.prod.gw-4u.com,OU=IT,O=SC,L=NL,C=NL"

Not sure what does the "signature does not match" refers to.. the node keystore consists of the certificate with the whole chain. the truststore holds the 2 certificates of root-ca and signing ca (tried also only root-ca and only signing-ca - didn't help), and the cacerts of java includes the root-ca, signing-ca and public certs of the 2 nodes.
What am I missing here?

I'd appreciate any help you could give/advise :)

Thanks,
Hila

**Comment by floragunncom** [comment]
This more a question and its very unlikely a bug/issue in Search Guard so pls. ask your question here: https://groups.google.com/forum/#!forum/search-guard

Github is a place **only** for reporting bugs or feature requests.

**Comment by hila3000** [comment]
Hey,

Sorry. Haven't found a discussion board (And I looked..).
I'll post it where you suggested.

Thanks,
Hila
