### ISSUE TITLE
Unable to install Search Guard Bundle for ES 5.3

### ISSUE THREAD

**Issue by nikunjsv** [floragunncom/search-guard#328]
Unable to install Search Guard Bundle 5.3.0-12 for ES 5.3 on RHEL 6.6 having JDK as jdk1.8.0_73

As mentioned in <a href="https://github.com/floragunncom/search-guard/wiki/Search-Guard-Bundle">Search Bundle Installation Page</a>, unable to run ./elasticsearch-<VERSION>-localhost/bin/elasticsearch
 
<B> Case 1 </B>
Steps performed as root user :
1) Downloaed  elasticsearch-5.3.0-12-62A9D172-9440-47FF-ABE3-59B73F7C40B5.tar.gz file from <a href="https://floragunn.com/downloads/elasticsearch-5.3.0-12-62A9D172-9440-47FF-ABE3-59B73F7C40B5.tar.gz"> here </a>
2) extracted tar file.
3)  executed ./elasticsearch-5.3.0-localhost/bin/elasticsearch

Output:

[WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [localhost] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: java.lang.RuntimeException: can not run elasticsearch as root
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:127) ~[elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:114) ~[elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:58) ~[elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122) ~[elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.cli.Command.main(Command.java:88) ~[elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:91) ~[elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:84) ~[elasticsearch-5.3.0.jar:5.3.0]
Caused by: java.lang.RuntimeException: can not run elasticsearch as root
        at org.elasticsearch.bootstrap.Bootstrap.initializeNatives(Bootstrap.java:106) ~[elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:204) ~[elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:360) ~[elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:123) ~[elasticsearch-5.3.0.jar:5.3.0]
        ... 6 more

<B> Case 2 </B>
Steps performed as 502 user:
1) Downloaed  elasticsearch-5.3.0-12-62A9D172-9440-47FF-ABE3-59B73F7C40B5.tar.gz file
2) extracted tar file.
3) created user (502) and group(games) and provided permissions
4) su 502
5) executed ./elasticsearch-5.3.0-localhost/bin/elasticsearch

Output:

Error: Could not find or load main class org.elasticsearch.tools.JavaVersionChecker
Elasticsearch requires at least Java 8 but your Java version from /usr/java/jdk1.8.0_73/jre//bin/java does not meet this requirement

6) executed sudo ./elasticsearch-5.3.0-localhost/bin/elasticsearch

Output:
[WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [localhost] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: java.lang.RuntimeException: can not run elasticsearch as root
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:127) ~[elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:114) ~[elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:58) ~[elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122) ~[elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.cli.Command.main(Command.java:88) ~[elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:91) ~[elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:84) ~[elasticsearch-5.3.0.jar:5.3.0]
Caused by: java.lang.RuntimeException: can not run elasticsearch as root
        at org.elasticsearch.bootstrap.Bootstrap.initializeNatives(Bootstrap.java:106) ~[elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:204) ~[elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:360) ~[elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:123) ~[elasticsearch-5.3.0.jar:5.3.0]
        ... 6 more

**Comment by floragunncom** [comment]
Pls. try

- Download elasticsearch-5.3.0-12-62A9D172-9440-47FF-ABE3-59B73F7C40B5.tar.gz file
- extract tar.gz file
- ./elasticsearch-5.3.0-localhost/bin/elasticsearch

without anything like su/sudo/etc and as a non-root user.

If you want to start it as another user you first need to `chown` all files

**Comment by nikunjsv** [comment]
Thanks @floragunncom for your prompt response.

Found the RCA:- I had downloaded and extracted the tar file as root user.
After downloading, extracting and running elasticsearch as non-root user, elasticsearch runs fine.

But after starting elasticsearch, while running logstash I am getting below error in logstash .

[logstash.outputs.elasticsearch] Attempted to resurrect connection to dead ES instance, but got an error. {:url=>#<URI::HTTP:0x75ed84c4 URL:http://localhost:9200/>, :error_type=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError, :error=>"Elasticsearch Unreachable: [http://localhost:9200/][Manticore::ClientProtocolException] localhost:9200 failed to respond"}
[2017-04-20T02:48:15,993][INFO ][logstash.outputs.elasticsearch] New Elasticsearch output {:class=>"LogStash::Outputs::ElasticSearch", :hosts=>[#<URI::Generic:0x5bf33964 URL://localhost:9200>]}
[2017-04-20T02:48:16,269][INFO ][logstash.pipeline        ] Starting pipeline {"id"=>"main", "pipeline.workers"=>4, "pipeline.batch.size"=>125, "pipeline.batch.delay"=>5, "pipeline.max_inflight"=>500}
[2017-04-20T02:48:16,986][INFO ][logstash.inputs.beats    ] Beats inputs: Starting input listener {:address=>"0.0.0.0:5044"}
[2017-04-20T02:48:17,021][INFO ][logstash.pipeline        ] Pipeline main started
[2017-04-20T02:48:17,141][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600}
[2017-04-20T02:48:19,100][WARN ][logstash.outputs.elasticsearch] Marking url as dead. Last error: [LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError] Elasticsearch Unreachable: [http://localhost:9200/][Manticore::ClientProtocolException] localhost:9200 failed to respond {:url=>http://localhost:9200/, :error_message=>"Elasticsearch Unreachable: [http://localhost:9200/][Manticore::ClientProtocolException] localhost:9200 failed to respond", :error_class=>"LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError"}


**Please help in understanding where is it trying to connect via HTTP (instead of HTTPS) .**

**Comment by floragunncom** [comment]
Try `curl -k -X GET 'https://localhost:9200'` and make sure you have hostname verification disabled in elasticsearch.yml

See https://github.com/floragunncom/search-guard-docs/blob/master/tls_configuration.md

Please ask questions here: For that refer to https://groups.google.com/forum/#!forum/search-guard
