### ISSUE TITLE
Kibana SSL connection

### ISSUE THREAD

**Issue by YonoloX** [floragunncom/search-guard#34]
Hello,

would you mind giving a working example of Kibana with SSL searchguard ?

I tried the following but I get an error,

I used the 'example-pki-scripts' to create certificates, keystore and trustore, then I added the following lines into Kibana.yml : 
```yml
elasticsearch_url: "https://localhost:9200"
ssl_cert_file: /home/user01/ELAST/elasticsearch-1.5.0/plugins/search-guard/ca/root-ca.crt
```
Note that I can connect using SSL searchguard to logstash or Pig

The error I get : 
```java
java.lang.RuntimeException: sun.security.pkcs11.wrapper.PKCS11Exception: CKR_DOMAIN_PARAMS_INVALID
        at sun.security.ssl.Handshaker.checkThrown(Handshaker.java:1359)
        at sun.security.ssl.SSLEngineImpl.checkTaskThrown(SSLEngineImpl.java:513)
        at sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:793)
        at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:761)
        at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:624)
        at org.elasticsearch.common.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1218)
        at org.elasticsearch.common.netty.handler.ssl.SslHandler.decode(SslHandler.java:852)
        at org.elasticsearch.common.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:425)
        at org.elasticsearch.common.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303)
        at org.elasticsearch.common.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
        at org.elasticsearch.common.netty.channel.Channels.fireMessageReceived(Channels.java:268)
        at org.elasticsearch.common.netty.channel.Channels.fireMessageReceived(Channels.java:255)
        at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
        at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
        at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
        at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
        at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
        at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:744)
Caused by: java.security.ProviderException: sun.security.pkcs11.wrapper.PKCS11Exception: CKR_DOMAIN_PARAMS_INVALID
        at sun.security.pkcs11.P11KeyPairGenerator.generateKeyPair(P11KeyPairGenerator.java:323)
        at java.security.KeyPairGenerator$Delegate.generateKeyPair(KeyPairGenerator.java:687)
        at sun.security.ssl.ECDHCrypt.<init>(ECDHCrypt.java:63)
        at sun.security.ssl.ServerHandshaker.setupEphemeralECDHKeys(ServerHandshaker.java:1208)
        at sun.security.ssl.ServerHandshaker.trySetCipherSuite(ServerHandshaker.java:1062)
        at sun.security.ssl.ServerHandshaker.chooseCipherSuite(ServerHandshaker.java:889)
        at sun.security.ssl.ServerHandshaker.clientHello(ServerHandshaker.java:622)
        at sun.security.ssl.ServerHandshaker.processMessage(ServerHandshaker.java:167)
        at sun.security.ssl.Handshaker.processLoop(Handshaker.java:868)
        at sun.security.ssl.Handshaker$1.run(Handshaker.java:808)
        at sun.security.ssl.Handshaker$1.run(Handshaker.java:806)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.security.ssl.Handshaker$DelegatedTask.run(Handshaker.java:1299)
        at org.elasticsearch.common.netty.handler.ssl.SslHandler.runDelegatedTasks(SslHandler.java:1392)
        at org.elasticsearch.common.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1255)
        ... 18 more
Caused by: sun.security.pkcs11.wrapper.PKCS11Exception: CKR_DOMAIN_PARAMS_INVALID
        at sun.security.pkcs11.wrapper.PKCS11.C_GenerateKeyPair(Native Method)
        at sun.security.pkcs11.P11KeyPairGenerator.generateKeyPair(P11KeyPairGenerator.java:314)
        ... 32 more
```

Could you give an minimal example of a working kibana.yml configuration file ?

Thanks in advance !

**Comment by daniel-ruess** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1022017

This seems like it could possibly open up some answers; looks like an issue with OpenJDK.

**Comment by YonoloX** [comment]
Hello,

In fact the jdk has a bug, I changed to jdk1.7.0_79 and that solved the problem.

For information I was using a jre : jre-1.7.0-openjdk.x86_64

Thanks!

**Comment by floragunncom** [comment]
by the way: java 8 is recommended :-)
