### ISSUE TITLE
How to config when i use xpack watcher 

### ISSUE THREAD

**Issue by zhengxin12345** [floragunncom/search-guard#352]
i install searchguard to es cluster.everything is ok.
until i use [xpack watcher](https://www.elastic.co/guide/en/x-pack/5.2/watcher-getting-started.html),the error happens!
i check the log on master node,there are many errors logs.

i try and can not resolve.
please help me..sos~~~

there are the errors:

```
org.elasticsearch.ElasticsearchSecurityException: unauthenticated request indices:data/write/index for user User [name=_sg_internal, roles=[]]
        at com.floragunn.searchguard.filter.SearchGuardFilter.apply(SearchGuardFilter.java:126) [search-guard-5-5.2.2-12.jar:?]
        at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:171) [elasticsearch-5.2.2.jar:5.2.2]
        at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:145) [elasticsearch-5.2.2.jar:5.2.2]
        at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:87) [elasticsearch-5.2.2.jar:5.2.2]
        at org.elasticsearch.client.node.NodeClient.executeLocally(NodeClient.java:75) [elasticsearch-5.2.2.jar:5.2.2]
        at org.elasticsearch.client.node.NodeClient.doExecute(NodeClient.java:64) [elasticsearch-5.2.2.jar:5.2.2]
        at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:403) [elasticsearch-5.2.2.jar:5.2.2]
        at org.elasticsearch.client.FilterClient.doExecute(FilterClient.java:67) [elasticsearch-5.2.2.jar:5.2.2]
        at org.elasticsearch.xpack.security.InternalClient.doExecute(InternalClient.java:83) [x-pack-5.2.2.jar:5.2.2]
        at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:403) [elasticsearch-5.2.2.jar:5.2.2]
        at org.elasticsearch.client.support.AbstractClient.index(AbstractClient.java:415) [elasticsearch-5.2.2.jar:5.2.2]
        at org.elasticsearch.xpack.watcher.support.init.proxy.WatcherClientProxy.index(WatcherClientProxy.java:88) [x-pack-5.2.2.jar:5.2.2]
        at org.elasticsearch.xpack.watcher.execution.TriggeredWatchStore.put(TriggeredWatchStore.java:143) [x-pack-5.2.2.jar:5.2.2]
        at org.elasticsearch.xpack.watcher.execution.TriggeredWatchStore.putAll(TriggeredWatchStore.java:167) [x-pack-5.2.2.jar:5.2.2]
        at org.elasticsearch.xpack.watcher.execution.ExecutionService.processEventsAsync(ExecutionService.java:205) [x-pack-5.2.2.jar:5.2.2]
        at org.elasticsearch.xpack.watcher.execution.AsyncTriggerListener.triggered(AsyncTriggerListener.java:49) [x-pack-5.2.2.jar:5.2.2]
        at org.elasticsearch.xpack.watcher.trigger.TriggerService$Listeners.triggered(TriggerService.java:179) [x-pack-5.2.2.jar:5.2.2]
        at org.elasticsearch.xpack.watcher.trigger.schedule.engine.TickerScheduleTriggerEngine.notifyListeners(TickerScheduleTriggerEngine.java:110) [x-pack-5.2.2.jar:5.2.2]
        at org.elasticsearch.xpack.watcher.trigger.schedule.engine.TickerScheduleTriggerEngine.checkJobs(TickerScheduleTriggerEngine.java:104) [x-pack-5.2.2.jar:5.2.2]
        at org.elasticsearch.xpack.watcher.trigger.schedule.engine.TickerScheduleTriggerEngine$Ticker.run(TickerScheduleTriggerEngine.java:159) [x-pack-5.2.2.jar:5.2.2]
```

**Comment by jochenkressin** [comment]
Running any component from X-Pack, apart from the free monitoring, in conjunction with Search Guard is currently not supported.

Our reasoning behind it is that in order to use any of the X-Pack components, you need to pay for a subscription. (This excludes monitoring, which comes for free, and is supported by Search Guard.) If you already pay for an X-Pack subscription, then you can also use the security feature bundled with it. So, in our view, it would not make very much sense to have X-Pack and Search Guard running at the same time, and pay for both.

I'm curious to know, why you think about using X-Pack (Watcher) and Search Guard at the same time?
