### ISSUE TITLE
Cannot determine types for indices:monitor/stats

### ISSUE THREAD

**Issue by johngilden** [floragunncom/search-guard#36]
- Elasticsearch 1.4.5
- search-guard 0.5
- Trying to access: `curl -u admin:adminpassword -XGET 'localhost:9200/_cat/indices'`
- Returns: 
```
[2015-07-15 18:23:26,895][WARN ][com.floragunn.searchguard.filter.SearchGuardActionFilter] Cannot determine types for indices:monitor/stats (class org.elasticsearch.action.admin.indices.stats.IndicesStatsReques
 t) due to type[s]() method not found
 [2015-07-15 18:23:26,895][ERROR][com.floragunn.searchguard.filter.SearchGuardActionFilter] Error while apply() due to java.lang.NullPointerException for action indices:monitor/stats
 java.lang.NullPointerException
         at java.util.Arrays$ArrayList.<init>(Arrays.java:2842)
         at java.util.Arrays.asList(Arrays.java:2828)
         at com.floragunn.searchguard.filter.SearchGuardActionFilter.apply0(SearchGuardActionFilter.java:187)
         at com.floragunn.searchguard.filter.SearchGuardActionFilter.apply(SearchGuardActionFilter.java:89)
         at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:165)
         at com.floragunn.searchguard.filter.FLSActionFilter.applySecure(FLSActionFilter.java:76)
         at com.floragunn.searchguard.filter.AbstractActionFilter.apply(AbstractActionFilter.java:97)
         at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:165)
         at com.floragunn.searchguard.filter.DLSActionFilter.applySecure(DLSActionFilter.java:73)
         at com.floragunn.searchguard.filter.AbstractActionFilter.apply(AbstractActionFilter.java:97)
         at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:165)
         at com.floragunn.searchguard.filter.RequestActionFilter.applySecure(RequestActionFilter.java:94)
         at com.floragunn.searchguard.filter.AbstractActionFilter.apply(AbstractActionFilter.java:97)
         at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:165)
         at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:82)
         at org.elasticsearch.client.node.NodeIndicesAdminClient.execute(NodeIndicesAdminClient.java:77)
         at org.elasticsearch.client.FilterClient$IndicesAdmin.execute(FilterClient.java:120)
         at org.elasticsearch.rest.BaseRestHandler$HeadersAndContextCopyClient$IndicesAdmin.execute(BaseRestHandler.java:149)
         at org.elasticsearch.client.support.AbstractIndicesAdminClient.stats(AbstractIndicesAdminClient.java:524)
         at org.elasticsearch.rest.action.cat.RestIndicesAction$1$1.processResponse(RestIndicesAction.java:83)
         at org.elasticsearch.rest.action.cat.RestIndicesAction$1$1.processResponse(RestIndicesAction.java:78)
         at org.elasticsearch.rest.action.support.RestActionListener.onResponse(RestActionListener.java:49)
         at org.elasticsearch.action.support.TransportAction$ThreadedActionListener$1.run(TransportAction.java:113)
         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
         at java.lang.Thread.run(Thread.java:745)
```

Relevant ACL:
```
{
  "roles": [ "admin" ],
  "filters_bypass": ["*"],
  "filters_execute": []
},
```

Someones else stumbled over this issue before: http://stackoverflow.com/questions/31366406/search-guard-not-integrating-with-elasticsearch

**Comment by floragunncom** [comment]
seems like a bug, will fix it in the next version, thanks for reporting it

**Comment by faxm0dem** [comment]
also seeing this

**Comment by riton** [comment]
I'm facing this bug also. Is there a workaround or a new version that fixes that ?

**Comment by riton** [comment]
I've just tested with `elasticsearch 1.7.3` and `com.floragunn/search-guard/1.7.3.0`. The bug is not present and everything seems to work as expected.

**Comment by floragunncom** [comment]
Auto close this issue because it refers to Search Guard 1 which is decommissioned now. For details pls. see https://github.com/floragunncom/search-guard-attic/wiki . If this issue is still valid for Search Guard 2 (for elasticsearch 2.x) feel free to reopen it (or to file a new one). Pls. do not longer report issues for Search Guard 1 (for elasticsearch 1.x). We sincerely apologize for the inconvenience this may have caused. Thanks for contributing!
