### ISSUE TITLE
Error while loading searchguard configuration in Elasticsearch

### ISSUE THREAD

**Issue by skmonga** [floragunncom/search-guard#360]
I am testing ES on a single node with SearchGuard. ES version is **5.4.1** and searchguard version is **search-guard-5-5.4.1-12** on **Red Hat Enterprise Linux Server release 7.0 (Maipo)**. The output of java -version is shown below :
openjdk version "1.8.0_91"
OpenJDK Runtime Environment (build 1.8.0_91-b14)
OpenJDK 64-Bit Server VM (build 25.91-b14, mixed mode) 

The following is the configuration I am using for elasticsearch : 

cluster.name: liveCluster
node.name: mainNode
node.master: true
node.data: true
node.max_local_storage_nodes: 1
discovery.zen.ping.unicast.hosts: ["10.1.50.159"]
network.host: 10.1.50.159
http.port: 9200
searchguard.ssl.transport.enable_openssl_if_available: false
searchguard.ssl.http.enable_openssl_if_available: false

searchguard.authcz.admin_dn:
  - CN=sgadmin

searchguard.ssl.transport.enforce_hostname_verification: false

searchguard.nodes_dn:
  - "CN=10.1.50.159"

#Transport layer TLS
searchguard.ssl.transport.keystore_type: JKS
searchguard.ssl.transport.keystore_filepath: ./searchguard_config/client-certificates/CN=demouser-keystore.jks
searchguard.ssl.transport.keystore_password: af8c478f7df5f4e79461
searchguard.ssl.transport.truststore_type: JKS
searchguard.ssl.transport.truststore_filepath: ./searchguard_config/truststore.jks
searchguard.ssl.transport.truststore_password: bf9c1cbcec4ac1e78a0a
#
###REST layer TLS
searchguard.ssl.http.enabled: true
searchguard.ssl.http.keystore_type: JKS
searchguard.ssl.http.keystore_filepath: ./searchguard_config/client-certificates/CN=demouser-keystore.jks
searchguard.ssl.http.keystore_password: af8c478f7df5f4e79461
searchguard.ssl.http.truststore_type: JKS
searchguard.ssl.http.truststore_filepath: ./searchguard_config/truststore.jks
searchguard.ssl.http.truststore_password: bf9c1cbcec4ac1e78a0a
bootstrap.system_call_filter: false

I am using the certificates generated via [SearchGuard TLS Generator](https://floragunn.com/tls-certificate-generator/) . However after starting elasticsearch , when I run the sgadmin.sh script as mentioned below 

**$ ./sgadmin.sh -h 10.1.50.159 -p 9300 -ks /home/rndaxia/live/elasticsearch-5.4.1/config/searchguard_config/client-certificates/CN=sgadmin-keystore.jks -kspass 21ebe94bb22c4ccab2bc -kst JKS -ts /home/rndaxia/live/elasticsearch-5.4.1/config/searchguard_config/truststore.jks -tspass bf9c1cbcec4ac1e78a0a -tst JKS -cd ../sgconfig/ -nhnv -icl --diagnose -cn liveCluster**

I get error on both elasticsearch and searchguard . The error on elasticsearch is  

**[2017-07-04T19:42:06,238][WARN ][c.f.s.s.t.SearchGuardSSLNettyTransport] [mainNode] exception caught on transport layer [[id: 0xa7de19cf, L:0.0.0.0/0.0.0.0:9300 ! R:/10.1.50.159:43721]], closing connection
io.netty.handler.codec.DecoderException: java.lang.RuntimeException: java.security.KeyException
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:459) ~[netty-codec-4.1.11.Final.jar:4.1.11.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) ~[netty-codec-4.1.11.Final.jar:4.1.11.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:544) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:498) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-common-4.1.11.Final.jar:4.1.11.Final]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.RuntimeException: java.security.KeyException
        at sun.security.ssl.Handshaker.checkThrown(Handshaker.java:1429) ~[?:?]
        at sun.security.ssl.SSLEngineImpl.checkTaskThrown(SSLEngineImpl.java:535) ~[?:?]
        at sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:813) ~[?:?]
        at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:781) ~[?:?]
        at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:624) ~[?:1.8.0_91]
        at io.netty.handler.ssl.SslHandler$SslEngineType$3.unwrap(SslHandler.java:254) ~[?:?]
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1156) ~[?:?]
        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1078) ~[?:?]
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489) ~[?:?]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428) ~[?:?]
        ... 15 more
Caused by: java.security.ProviderException: java.security.KeyException
        at sun.security.ec.ECKeyPairGenerator.generateKeyPair(ECKeyPairGenerator.java:147) ~[?:?]
        at java.security.KeyPairGenerator$Delegate.generateKeyPair(KeyPairGenerator.java:703) ~[?:1.8.0_91]
        at sun.security.ssl.ECDHCrypt.<init>(ECDHCrypt.java:64) ~[?:?]
        at sun.security.ssl.ServerHandshaker.setupEphemeralECDHKeys(ServerHandshaker.java:1432) ~[?:?]
        at sun.security.ssl.ServerHandshaker.trySetCipherSuite(ServerHandshaker.java:1219) ~[?:?]
        at sun.security.ssl.ServerHandshaker.chooseCipherSuite(ServerHandshaker.java:1023) ~[?:?]
        at sun.security.ssl.ServerHandshaker.clientHello(ServerHandshaker.java:738) ~[?:?]
        at sun.security.ssl.ServerHandshaker.processMessage(ServerHandshaker.java:221) ~[?:?]
        at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979) ~[?:?]
        at sun.security.ssl.Handshaker$1.run(Handshaker.java:919) ~[?:?]
        at sun.security.ssl.Handshaker$1.run(Handshaker.java:916) ~[?:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_91]
        at sun.security.ssl.Handshaker$DelegatedTask.run(Handshaker.java:1369) ~[?:?]
        at io.netty.handler.ssl.SslHandler.runDelegatedTasks(SslHandler.java:1295) ~[?:?]
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1208) ~[?:?]
        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1078) ~[?:?]
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489) ~[?:?]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428) ~[?:?]
        ... 15 more
Caused by: java.security.KeyException
        at sun.security.ec.ECKeyPairGenerator.generateECKeyPair(Native Method) ~[?:?]
        at sun.security.ec.ECKeyPairGenerator.generateKeyPair(ECKeyPairGenerator.java:128) ~[?:?]
        at java.security.KeyPairGenerator$Delegate.generateKeyPair(KeyPairGenerator.java:703) ~[?:1.8.0_91]
        at sun.security.ssl.ECDHCrypt.<init>(ECDHCrypt.java:64) ~[?:?]
        at sun.security.ssl.ServerHandshaker.setupEphemeralECDHKeys(ServerHandshaker.java:1432) ~[?:?]
        at sun.security.ssl.ServerHandshaker.trySetCipherSuite(ServerHandshaker.java:1219) ~[?:?]
        at sun.security.ssl.ServerHandshaker.chooseCipherSuite(ServerHandshaker.java:1023) ~[?:?]
        at sun.security.ssl.ServerHandshaker.clientHello(ServerHandshaker.java:738) ~[?:?]
        at sun.security.ssl.ServerHandshaker.processMessage(ServerHandshaker.java:221) ~[?:?]
        at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979) ~[?:?]
        at sun.security.ssl.Handshaker$1.run(Handshaker.java:919) ~[?:?]
        at sun.security.ssl.Handshaker$1.run(Handshaker.java:916) ~[?:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_91]
        at sun.security.ssl.Handshaker$DelegatedTask.run(Handshaker.java:1369) ~[?:?]
        at io.netty.handler.ssl.SslHandler.runDelegatedTasks(SslHandler.java:1295) ~[?:?]
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1208) ~[?:?]
        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1078) ~[?:?]
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489) ~[?:?]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428) ~[?:?]
        ... 15 more**

while on searchguard I get the following error 

**19:42:06.423 [elasticsearch[_client_][transport_client_boss][T#1]] ERROR com.floragunn.searchguard.ssl.transport.SearchGuardSSLNettyTransport - SSL Problem Received fatal alert: internal_error
javax.net.ssl.SSLException: Received fatal alert: internal_error
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:208) ~[?:1.8.0_91]
        at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1666) ~[?:1.8.0_91]
        at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1634) ~[?:1.8.0_91]
        at sun.security.ssl.SSLEngineImpl.recvAlert(SSLEngineImpl.java:1800) ~[?:1.8.0_91]
        at sun.security.ssl.SSLEngineImpl.readRecord(SSLEngineImpl.java:1083) ~[?:1.8.0_91]
        at sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:907) ~[?:1.8.0_91]
        at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:781) ~[?:1.8.0_91]
        at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:624) ~[?:1.8.0_91]
        at io.netty.handler.ssl.SslHandler$SslEngineType$3.unwrap(SslHandler.java:254) ~[netty-handler-4.1.11.Final.jar:4.1.11.Final]
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1156) ~[netty-handler-4.1.11.Final.jar:4.1.11.Final]
        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1078) ~[netty-handler-4.1.11.Final.jar:4.1.11.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489) ~[netty-codec-4.1.11.Final.jar:4.1.11.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428) ~[netty-codec-4.1.11.Final.jar:4.1.11.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) ~[netty-codec-4.1.11.Final.jar:4.1.11.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-common-4.1.11.Final.jar:4.1.11.Final]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Diagnostic trace written to: /home/rndaxia/live/elasticsearch-5.4.1/plugins/search-guard-5/tools/sgadmin_diag_trace_2017-Jul-04_19-42-06.txt
Contacting elasticsearch cluster 'liveCluster' and wait for YELLOW clusterstate ...
Cannot retrieve cluster state due to: None of the configured nodes are available: [{#transport#-1}{-qjbCye9SKGq8EpObISgEQ}{10.1.50.159}{10.1.50.159:9300}]. This is not an error, will keep on trying ...
   * Try running sgadmin.sh with -icl and -nhnv (If thats works you need to check your clustername as well as hostnames in your SSL certificates)
   * If this is not working, try running sgadmin.sh with --diagnose and see diagnose trace log file)
Cannot retrieve cluster state due to: None of the configured nodes are available: [{#transport#-1}{-qjbCye9SKGq8EpObISgEQ}{10.1.50.159}{10.1.50.159:9300}]. This is not an error, will keep on trying ...
   * Try running sgadmin.sh with -icl and -nhnv (If thats works you need to check your clustername as well as hostnames in your SSL certificates)
   * If this is not working, try running sgadmin.sh with --diagnose and see diagnose trace log file)**

I have tested the same exact setup on another RedHat machine where everything worked perfectly . The versions of ES and searchguard were also same. The only difference I can note is the java on that machine is not openjdk. The output of java -version there is 

**java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)**

However I cannot come to a conclusion that the java version is the reason for this not working on current setup. So I am stuck at this point .

**Comment by floragunncom** [comment]
Maybe you hit an OpenJDK VM Bug? A quick search brings up https://bugzilla.redhat.com/show_bug.cgi?id=1329342
In general we recommend Oracle JVM and 1.8.0_91 is more than a year old which is pretty old for running a security related product.

**Comment by skmonga** [comment]
Thanks @floragunncom. I will look more into this issue tomorrow.

**Comment by skmonga** [comment]
After installing **Oracle JVM version 1.8.0_131** , searchguard worked perfectly. Thanks @floragunncom for the quick reply. Closing this issue.
