### ISSUE TITLE
TransportClient 5.4.2 can not find TransportClient.builder()

### ISSUE THREAD

**Issue by tianya1988** [floragunncom/search-guard#365]
TransportClient  5.4.2 can not find TransportClient.builder().settings(settings).addPlugin(SearchGuardSSLPlugin.class).build()
how to configure transportclient with search-guard 5.4.2
thanks.
@floragunncom

**Comment by floragunncom** [comment]
Please do not ask questions here. 
For that refer to https://groups.google.com/forum/#!forum/search-guard

Github is a place **only** for reporting bugs or feature requests.
If you report a bug please include **always** the following informations:

* Search Guard and Elasticsearch version
* JVM version and operating system version
* Number of nodes in your cluster
* Description of the bug

These informations are optional but are very valueable and
typically would lead to get bugs fixed faster:

* Steps to reproduce
* Logfiles on DEBUG level
* A failing unittest

**Comment by zqc0512** [comment]
i flow this:  https://floragunn.com/searchguard-elasicsearch-transport-clients/
but in version 5.4.2 
****the "Configure the Transport Client" ,i find it in version 2.3.* but not in 5.4.2****
i can't find "Adding the Search Guard SSL plugin" 
**the  TransportClient .builder() not in 5.4.2**

**Comment by tianya1988** [comment]
@floragunncom @jochenkressin 
**use client output SSL error  ,the DNS name not match.**
SSL Problem General SSLEngine problem
**javax.net.ssl.SSLHandshakeException: General SSLEngine problem**
	at sun.security.ssl.Handshaker.checkThrown(Handshaker.java:1431) ~[?:1.8.0_45]
	at sun.security.ssl.SSLEngineImpl.checkTaskThrown(SSLEngineImpl.java:535) ~[?:1.8.0_45]
	at sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:813) ~[?:1.8.0_45]
	at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:781) ~[?:1.8.0_45]
	at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:624) ~[?:1.8.0_45]
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1097) ~[netty-all-4.0.42.Final.jar:4.0.42.Final]
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:968) ~[netty-all-4.0.42.Final.jar:4.0.42.Final]
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:902) ~[netty-all-4.0.42.Final.jar:4.0.42.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411) ~[netty-all-4.0.42.Final.jar:4.0.42.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248) ~[netty-all-4.0.42.Final.jar:4.0.42.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367) [netty-all-4.0.42.Final.jar:4.0.42.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353) [netty-all-4.0.42.Final.jar:4.0.42.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:346) [netty-all-4.0.42.Final.jar:4.0.42.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294) [netty-all-4.0.42.Final.jar:4.0.42.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367) [netty-all-4.0.42.Final.jar:4.0.42.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353) [netty-all-4.0.42.Final.jar:4.0.42.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911) [netty-all-4.0.42.Final.jar:4.0.42.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131) [netty-all-4.0.42.Final.jar:4.0.42.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:652) [netty-all-4.0.42.Final.jar:4.0.42.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:537) [netty-all-4.0.42.Final.jar:4.0.42.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:491) [netty-all-4.0.42.Final.jar:4.0.42.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:451) [netty-all-4.0.42.Final.jar:4.0.42.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140) [netty-all-4.0.42.Final.jar:4.0.42.Final]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
Caused by: javax.net.ssl.SSLHandshakeException: General SSLEngine problem
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192) ~[?:1.8.0_45]
	at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1728) ~[?:1.8.0_45]
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:304) ~[?:1.8.0_45]
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296) ~[?:1.8.0_45]
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1478) ~[?:1.8.0_45]
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:212) ~[?:1.8.0_45]
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979) ~[?:1.8.0_45]
	at sun.security.ssl.Handshaker$1.run(Handshaker.java:919) ~[?:1.8.0_45]
	at sun.security.ssl.Handshaker$1.run(Handshaker.java:916) ~[?:1.8.0_45]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_45]
	at sun.security.ssl.Handshaker$DelegatedTask.run(Handshaker.java:1369) ~[?:1.8.0_45]
	at io.netty.handler.ssl.SslHandler.runDelegatedTasks(SslHandler.java:1123) ~[netty-all-4.0.42.Final.jar:4.0.42.Final]
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1008) ~[netty-all-4.0.42.Final.jar:4.0.42.Final]
	... 17 more
Caused by: java.security.cert.CertificateException: No subject alternative DNS name matching jason found.
	at sun.security.util.HostnameChecker.matchDNS(HostnameChecker.java:204) ~[?:1.8.0_45]
	at sun.security.util.HostnameChecker.match(HostnameChecker.java:95) ~[?:1.8.0_45]
	at sun.security.ssl.X509TrustManagerImpl.checkIdentity(X509TrustManagerImpl.java:455) ~[?:1.8.0_45]
	at sun.security.ssl.X509TrustManagerImpl.checkIdentity(X509TrustManagerImpl.java:436) ~[?:1.8.0_45]
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:252) ~[?:1.8.0_45]
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:136) ~[?:1.8.0_45]
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1465) ~[?:1.8.0_45]
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:212) ~[?:1.8.0_45]
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979) ~[?:1.8.0_45]
	at sun.security.ssl.Handshaker$1.run(Handshaker.java:919) ~[?:1.8.0_45]
	at sun.security.ssl.Handshaker$1.run(Handshaker.java:916) ~[?:1.8.0_45]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_45]
	at sun.security.ssl.Handshaker$DelegatedTask.run(Handshaker.java:1369) ~[?:1.8.0_45]
	at io.netty.handler.ssl.SslHandler.runDelegatedTasks(SslHandler.java:1123) ~[netty-all-4.0.42.Final.jar:4.0.42.Final]
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1008) ~[netty-all-4.0.42.Final.jar:4.0.42.Final]
	... 17 more
**NoNodeAvailableException[None of the configured nodes are available: [{#transport#-1}{igtFUgGHShGwPENdpEKIfg}{jason}{11.0.44.114:9300}]]**
	at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:348)
	at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:246)
	at org.elasticsearch.client.transport.TransportProxyClient.execute(TransportProxyClient.java:59)
	at org.elasticsearch.client.transport.TransportClient.doExecute(TransportClient.java:366)
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:408)
	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:80)
	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:54)
	at com.cnpc.sa.algorithm.persistence.ElasticsearchTemplateTest.execute(ElasticsearchTemplateTest.scala:163)
	at com.cnpc.sa.algorithm.persistence.ElasticsearchTemplateTest.testAddData(ElasticsearchTemplateTest.scala:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:74)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:211)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:67)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
data save to es error, no available elasticsearch node!, lost size is 1

**Comment by zqc0512** [comment]
i slove it ,can close ,add the hostvalite configure in transport client.
thanks.can cloes it.
@floragunncom @jochenkressin

**Comment by floragunncom** [comment]
Please stop spamming us here!
