### ISSUE TITLE
How to manage search guard 5 installation offline exception issue?

### ISSUE THREAD

**Issue by yusufkaratoprak** [floragunncom/search-guard#375]
Hi;
When I write below code to install searchguard below exception is produced below:How can I do exactly searchguard.
**elasticsearch-plugin install -b file://C://ELK/elasticsearch//bin//search-guard-5-5.5.1.zip
Downloading file://C://ELK/elasticsearch//bin//search-guard-5-5.5.1.zip**

`Exception in thread "main" java.net.UnknownHostException: C
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
        at java.net.Socket.connect(Socket.java:589)
        at java.net.Socket.connect(Socket.java:538)
        at sun.net.ftp.impl.FtpClient.doConnect(FtpClient.java:964)
        at sun.net.ftp.impl.FtpClient.tryConnect(FtpClient.java:924)
        at sun.net.ftp.impl.FtpClient.connect(FtpClient.java:1019)
        at sun.net.ftp.impl.FtpClient.connect(FtpClient.java:1005)
        at sun.net.www.protocol.ftp.FtpURLConnection.connect(FtpURLConnection.java:294)
        at sun.net.www.protocol.ftp.FtpURLConnection.getInputStream(FtpURLConnection.java:400)
        at org.elasticsearch.plugins.InstallPluginCommand.downloadZip(InstallPluginCommand.java:326)
        at org.elasticsearch.plugins.InstallPluginCommand.download(InstallPluginCommand.java:247)
        at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:215)
        at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:201)
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:67)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122)
        at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:69)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122)
        at org.elasticsearch.cli.Command.main(Command.java:88)
        at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:47)
`

**Comment by floragunncom** [comment]
Please do not ask questions here. 
For that refer to https://groups.google.com/forum/#!forum/search-guard

Github is a place **only** for reporting bugs or feature requests.
If you report a bug please include **always** the following informations:

* Search Guard and Elasticsearch version
* JVM version and operating system version
* Number of nodes in your cluster
* Description of the bug

These informations are optional but are very valueable and
typically would lead to get bugs fixed faster:

* Steps to reproduce
* Logfiles on DEBUG level
* A failing unittest
