### ISSUE TITLE
sgadmin stuck at "Contacting elasticsearch cluster 'elasticsearch' ..." on ES version 5.5.0

### ISSUE THREAD

**Issue by gsaxam** [floragunncom/search-guard#376]
Hi,

I have spent almost 3 days in trying to get SearchGuard work inside our cluster. I generated the default certificates using the `example.sh` provided in `search-guard-ssl-5.5.0`. I copied 3 files to my `/etc/elasticsearch/` directory and they are as follows:

1. truststore.jks
2. keystore.jks _(renamed from original node-1-keystore.jks generated by example.sh)_
3. kirk-keystore.jks

All these 3 files are owned by `elasticsearch` user on my node.

My `/etc/elasticsearch/elasticsearch.yml` looks like this:

```
cluster.name: elasticsearch_dev
node.name: myNode1
path.conf: "/etc/elasticsearch"
path.logs: "/var/log/elasticsearch"
discovery.zen.ping.unicast.hosts:
- myNode2
- myNode3
discovery.zen.minimum_master_nodes: 2
network.host: 0.0.0.0
http.cors.enabled: true
http.cors.allow-origin: "*"
http.cors.allow-methods : OPTIONS, HEAD, GET, POST, PUT, DELETE
http.cors.allow-headers : X-Requested-With,X-Auth-Token,Content-Type,Content-Length
http.detailed_errors.enabled : true

######## Start Search Guard Demo Configuration ########
searchguard.ssl.transport.keystore_filepath: keystore.jks
searchguard.ssl.transport.truststore_filepath: truststore.jks
searchguard.ssl.transport.enforce_hostname_verification: false
searchguard.ssl.http.enabled: true
searchguard.ssl.http.keystore_filepath: keystore.jks
searchguard.ssl.http.truststore_filepath: truststore.jks
searchguard.authcz.admin_dn:
  - CN=kirk,OU=client,O=client,L=test, C=de

######## End Search Guard Demo Configuration ########
```

Finally, I run the `sgadmin` command as follows and it does not ever find my cluster.
`cd /usr/share/elasticsearch/plugins/search-guard-5/sgconfig`

`../../search-guard-5/tools/sgadmin.sh --accept-red-cluster -ks /etc/elasticsearch/kirk-keystore.jks -ts /etc/elasticsearch/truststore.jks -icl -nhnv`

Logs:
```
WARNING: JAVA_HOME not set, will use /bin/java
Search Guard Admin v5
Will connect to localhost:9300 ... done

### LICENSE NOTICE Search Guard ###

If you use one or more of the following features in production
make sure you have a valid Search Guard license
(See https://floragunn.com/searchguard-validate-license)

* Kibana Multitenancy
* LDAP authentication/authorization
* Active Directory authentication/authorization
* REST Management API
* JSON Web Token (JWT) authentication/authorization
* Kerberos authentication/authorization
* Document- and Fieldlevel Security (DLS/FLS)
* Auditlogging

In case of any doubt mail to <sales@floragunn.com>
###################################
Contacting elasticsearch cluster 'elasticsearch' ...
Cannot retrieve cluster state due to: null. This is not an error, will keep on trying ...
   * Try running sgadmin.sh with -icl (but no -cl) and -nhnv (If thats works you need to check your clustername as well as hostnames in your SSL certificates)
   * Make also sure that your keystore or cert is a client certificate (not a node certificate) and configured properly in elasticsearch.yml
   * If this is not working, try running sgadmin.sh with --diagnose and see diagnose trace log file)
   * Add --accept-red-cluster to allow sgadmin to operate on a red cluster.
```

**Comment by floragunncom** [comment]
Can you run sgadmin with "--diagnose" and post the diagnose file (or send it via mail). Please provide also the elasticsearch logs (from the beginning when the node starts until sgadmin try to connect the cluster)

**Comment by jochenkressin** [comment]
Please do not ask questions on GitHub. GitHub is for reporting bugs only, for questions please use our Google Group: https://groups.google.com/forum/#!forum/search-guard

From your elasticsearch.yml, it seems you used the install_demo_configuration.sh scripts for the inital setup. This script adds the configuration entries in elasticsearch.yml and places the key- and truststore in the config directory of ES.

You then used the example.sh script to generate another set of certificates. You placed them in the /etc/elasticsearch folder.

Note that due to security settings in Elasticsearch itself, the keystore and truststore files need to be placed in <ES installation directory>/config:

http://floragunncom.github.io/search-guard-docs/tls_configuration.html

"Path to the keystore file, **relative to the config/ directory** (mandatory)"

So in your setup, the ES nodes are using the certificates generated by the installer script. But when you use sgadmin, you use the certificates generated by the example.sh script which you placed in /etc/elasticsearch. This won't work.

Since you've used the install_demo_configuration.sh script, you can simply use sgadmin_demo.sh from the tools directory to make changes.

**Comment by gsaxam** [comment]
Here is the ElasticSearch Logs I extracted from `/var/log/messages`.

```
Aug 22 14:46:44 myNode1 systemd: Stopping Elasticsearch...
Aug 22 14:46:44 myNode1 systemd: Starting Elasticsearch...
Aug 22 14:46:44 myNode1 systemd: Started Elasticsearch.
Aug 22 14:46:54 myNode1 elasticsearch: ### LICENSE NOTICE Search Guard ###
Aug 22 14:46:54 myNode1 elasticsearch: If you use one or more of the following features in production
Aug 22 14:46:54 myNode1 elasticsearch: make sure you have a valid Search Guard license
Aug 22 14:46:54 myNode1 elasticsearch: (See https://floragunn.com/searchguard-validate-license)
Aug 22 14:46:54 myNode1 elasticsearch: * Kibana Multitenancy
Aug 22 14:46:54 myNode1 elasticsearch: * LDAP authentication/authorization
Aug 22 14:46:54 myNode1 elasticsearch: * Active Directory authentication/authorization
Aug 22 14:46:54 myNode1 elasticsearch: * REST Management API
Aug 22 14:46:54 myNode1 elasticsearch: * JSON Web Token (JWT) authentication/authorization
Aug 22 14:46:54 myNode1 elasticsearch: * Kerberos authentication/authorization
Aug 22 14:46:54 myNode1 elasticsearch: * Document- and Fieldlevel Security (DLS/FLS)
Aug 22 14:46:54 myNode1 elasticsearch: * Auditlogging
Aug 22 14:46:54 myNode1 elasticsearch: In case of any doubt mail to <sales@floragunn.com>
Aug 22 14:46:54 myNode1 elasticsearch: ###################################
Aug 22 14:46:54 myNode1 elasticsearch: Consider setting -Djdk.tls.rejectClientInitiatedRenegotiation=true to prevent DoS attacks through client side initiated TLS renegotiation.
```

Here's is the `--diagnose` results:

```
ient properties: {java.runtime.name=Java(TM) SE Runtime Environment, sun.boot.library.path=/usr/java/jdk1.8.0_112/jre/lib/amd64, java.vm.version=25.112-b15, jdk.tls.rejectClientInitiatedRenegotiation=true, java.vm.vendor=Oracle Corporation, java.vendor.url=http://java.oracle.com/, path.separator=:, java.vm.name=Java HotSpot(TM) 64-Bit Server VM, file.encoding.pkg=sun.io, user.country=US, sun.java.launcher=SUN_STANDARD, sun.os.patch.level=unknown, java.vm.specification.name=Java Virtual Machine Specification, user.dir=/usr/share/elasticsearch/plugins/search-guard-5/sgconfig, sg.nowarn.client=true, java.runtime.version=1.8.0_112-b15, java.awt.graphicsenv=sun.awt.X11GraphicsEnvironment, java.endorsed.dirs=/usr/java/jdk1.8.0_112/jre/lib/endorsed, os.arch=amd64, java.io.tmpdir=/tmp, line.separator=
, java.vm.specification.vendor=Oracle Corporation, os.name=Linux, sun.jnu.encoding=UTF-8, org.apache.logging.log4j.simplelog.StatusLogger.level=OFF, java.library.path=/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib, sun.nio.ch.bugLevel=, java.specification.name=Java Platform API Specification, java.class.version=52.0, sun.management.compiler=HotSpot 64-Bit Tiered Compilers, os.version=3.10.0-514.26.2.el7.x86_64, user.home=/root, user.timezone=US/Central, java.awt.printerjob=sun.print.PSPrinterJob, file.encoding=UTF-8, java.specification.version=1.8, java.class.path=/usr/share/elasticsearch/plugins/search-guard-5/tools/../guava-19.0.jar:/usr/share/elasticsearch/plugins/search-guard-5/tools/../netty-transport-4.1.11.Final.jar:/usr/share/elasticsearch/plugins/search-guard-5/tools/../netty-handler-4.1.11.Final.jar:/usr/share/elasticsearch/plugins/search-guard-5/tools/../netty-buffer-4.1.11.Final.jar:/usr/share/elasticsearch/plugins/search-guard-5/tools/../commons-cli-1.3.1.jar:/usr/share/elasticsearch/plugins/search-guard-5/tools/../transport-netty4-client-5.5.0.jar:/usr/share/elasticsearch/plugins/search-guard-5/tools/../netty-common-4.1.11.Final.jar:/usr/share/elasticsearch/plugins/search-guard-5/tools/../search-guard-ssl-5.5.0-23.jar:/usr/share/elasticsearch/plugins/search-guard-5/tools/../netty-resolver-4.1.11.Final.jar:/usr/share/elasticsearch/plugins/search-guard-5/tools/../search-guard-5-5.5.0-15.jar:/usr/share/elasticsearch/plugins/search-guard-5/tools/../netty-codec-4.1.11.Final.jar:/usr/share/elasticsearch/plugins/search-guard-5/tools/../netty-codec-http-4.1.11.Final.jar:/usr/share/elasticsearch/plugins/search-guard-5/tools/../../../lib/HdrHistogram-2.1.9.jar:/usr/share/elasticsearch/plugins/search-guard-5/tools/../../../lib/elasticsearch-5.5.0.jar:/usr/share/elasticsearch/plugins/search-guard-5/tools/../../../lib/hppc-0.7.1.jar:/usr/share/elasticsearch/plugins/search-guard-5/tools/../../../lib/jackson-core-2.8.6.jar:/usr/share/elasticsearch/plugins/search-guard-5/tools/../../../lib/jackson-dataformat-cbor-2.8.6.jar:/usr/share/elasticsearch/plugins/search-guard-5/tools/../../../lib/jackson-dataformat-smile-2.8.6.jar:/usr/share/elasticsearch/plugins/search-guard-5/tools/../../../lib/jackson-dataformat-yaml-2.8.6.jar:/usr/share/elasticsearch/plugins/search-guard-5/tools/../../../lib/java-version-checker-5.5.0.jar:/usr/share/elasticsearch/plugins/search-guard-5/tools/../../../lib/jna-4.4.0.jar:/usr/share/elasticsearch/plugins/search-guard-5/tools/../../../lib/joda-time-2.9.5.jar:/usr/share/elasticsearch/plugins/search-guard-5/tools/../../../lib/jopt-simple-5.0.2.jar:/usr/share/elasticsearch/plugins/search-guard-5/tools/../../../lib/jts-1.13.jar:/usr/share/elasticsearch/plugins/search-guard-5/tools/../../../lib/log4j-1.2-api-2.8.2.jar:/usr/share/elasticsearch/plugins/search-guard-5/tools/../../../lib/log4j-api-2.8.2.jar:/usr/share/elasticsearch/plugins/search-guard-5/tools/../../../lib/log4j-core-2.8.2.jar:/usr/share/elasticsearch/plugins/search-guard-5/tools/../../../lib/lucene-analyzers-common-6.6.0.jar:/usr/share/elasticsearch/plugins/search-guard-5/tools/../../../lib/lucene-backward-codecs-6.6.0.jar:/usr/share/elasticsearch/plugins/search-guard-5/tools/../../../lib/lucene-core-6.6.0.jar:/usr/share/elasticsearch/plugins/search-guard-5/tools/../../../lib/lucene-grouping-6.6.0.jar:/usr/share/elasticsearch/plugins/search-guard-5/tools/../../../lib/lucene-highlighter-6.6.0.jar:/usr/share/elasticsearch/plugins/search-guard-5/tools/../../../lib/lucene-join-6.6.0.jar:/usr/share/elasticsearch/plugins/search-guard-5/tools/../../../lib/lucene-memory-6.6.0.jar:/usr/share/elasticsearch/plugins/search-guard-5/tools/../../../lib/lucene-misc-6.6.0.jar:/usr/share/elasticsearch/plugins/search-guard-5/tools/../../../lib/lucene-queries-6.6.0.jar:/usr/share/elasticsearch/plugins/search-guard-5/tools/../../../lib/lucene-queryparser-6.6.0.jar:/usr/share/elasticsearch/plugins/search-guard-5/tools/../../../lib/lucene-sandbox-6.6.0.jar:/usr/share/elasticsearch/plugins/search-guard-5/tools/../../../lib/lucene-spatial-6.6.0.jar:/usr/share/elasticsearch/plugins/search-guard-5/tools/../../../lib/lucene-spatial-extras-6.6.0.jar:/usr/share/elasticsearch/plugins/search-guard-5/tools/../../../lib/lucene-spatial3d-6.6.0.jar:/usr/share/elasticsearch/plugins/search-guard-5/tools/../../../lib/lucene-suggest-6.6.0.jar:/usr/share/elasticsearch/plugins/search-guard-5/tools/../../../lib/plugin-cli-5.5.0.jar:/usr/share/elasticsearch/plugins/search-guard-5/tools/../../../lib/securesm-1.1.jar:/usr/share/elasticsearch/plugins/search-guard-5/tools/../../../lib/snakeyaml-1.15.jar:/usr/share/elasticsearch/plugins/search-guard-5/tools/../../../lib/spatial4j-0.6.jar:/usr/share/elasticsearch/plugins/search-guard-5/tools/../../../lib/t-digest-3.0.jar:/usr/share/elasticsearch/plugins/search-guard-5/tools/../deps/*, user.name=root, java.vm.specification.version=1.8, sun.java.command=com.floragunn.searchguard.tools.SearchGuardAdmin --accept-red-cluster -ks /etc/elasticsearch/kirk-keystore.jks -ts /etc/elasticsearch/truststore.jks -icl -nhnv --diagnose, java.home=/usr/java/jdk1.8.0_112/jre, sun.arch.data.model=64, user.language=en, java.specification.vendor=Oracle Corporation, es.set.netty.runtime.available.processors=false, awt.toolkit=sun.awt.X11.XToolkit, java.vm.info=mixed mode, java.version=1.8.0_112, java.ext.dirs=/usr/java/jdk1.8.0_112/jre/lib/ext:/usr/java/packages/lib/ext, sun.boot.class.path=/usr/java/jdk1.8.0_112/jre/lib/resources.jar:/usr/java/jdk1.8.0_112/jre/lib/rt.jar:/usr/java/jdk1.8.0_112/jre/lib/sunrsasign.jar:/usr/java/jdk1.8.0_112/jre/lib/jsse.jar:/usr/java/jdk1.8.0_112/jre/lib/jce.jar:/usr/java/jdk1.8.0_112/jre/lib/charsets.jar:/usr/java/jdk1.8.0_112/jre/lib/jfr.jar:/usr/java/jdk1.8.0_112/jre/classes, java.vendor=Oracle Corporation, file.separator=/, java.vendor.url.bug=http://bugreport.sun.com/bugreport/, sun.io.unicode.encoding=UnicodeLittle, sun.cpu.endian=little, sg.display_lic_only_stdout=true, sun.cpu.isalist=}
2017-Aug-22_14-06-17

ClusterHealthRequest:
NoNodeAvailableException[None of the configured nodes are available: [{#transport#-1}{28g6JW0AT8KEJRSxVMtcyQ}{localhost}{127.0.0.1:9300}]]
        at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:347)
        at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:245)
        at org.elasticsearch.client.transport.TransportProxyClient.execute(TransportProxyClient.java:59)
        at org.elasticsearch.client.transport.TransportClient.doExecute(TransportClient.java:363)
        at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:408)
        at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:397)
        at org.elasticsearch.client.support.AbstractClient$ClusterAdmin.execute(AbstractClient.java:724)
        at org.elasticsearch.client.support.AbstractClient$ClusterAdmin.health(AbstractClient.java:746)
        at com.floragunn.searchguard.tools.SearchGuardAdmin.generateDiagnoseTrace(SearchGuardAdmin.java:756)
        at com.floragunn.searchguard.tools.SearchGuardAdmin.main0(SearchGuardAdmin.java:434)
        at com.floragunn.searchguard.tools.SearchGuardAdmin.main(SearchGuardAdmin.java:110)

NodesInfoResponse:
NoNodeAvailableException[None of the configured nodes are available: [{#transport#-1}{28g6JW0AT8KEJRSxVMtcyQ}{localhost}{127.0.0.1:9300}]]
        at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:347)
        at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:245)
        at org.elasticsearch.client.transport.TransportProxyClient.execute(TransportProxyClient.java:59)
        at org.elasticsearch.client.transport.TransportClient.doExecute(TransportClient.java:363)
        at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:408)
        at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:397)
        at org.elasticsearch.client.support.AbstractClient$ClusterAdmin.execute(AbstractClient.java:724)
        at org.elasticsearch.client.support.AbstractClient$ClusterAdmin.nodesInfo(AbstractClient.java:806)
        at com.floragunn.searchguard.tools.SearchGuardAdmin.generateDiagnoseTrace(SearchGuardAdmin.java:764)
        at com.floragunn.searchguard.tools.SearchGuardAdmin.main0(SearchGuardAdmin.java:434)
        at com.floragunn.searchguard.tools.SearchGuardAdmin.main(SearchGuardAdmin.java:110)

NodesStatsRequest:
NoNodeAvailableException[None of the configured nodes are available: [{#transport#-1}{28g6JW0AT8KEJRSxVMtcyQ}{localhost}{127.0.0.1:9300}]]
        at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:347)
        at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:245)
        at org.elasticsearch.client.transport.TransportProxyClient.execute(TransportProxyClient.java:59)
        at org.elasticsearch.client.transport.TransportClient.doExecute(TransportClient.java:363)
Diagnostic sgadmin trace
ES client version: 5.5.0
Client properties: {java.runtime.name=Java(TM) SE Runtime Environment, sun.boot.library.path=/usr/java/jdk1.8.0_112/jre/lib/amd64, java.vm.version=25.112
-b15, jdk.tls.rejectClientInitiatedRenegotiation=true, java.vm.vendor=Oracle Corporation, java.vendor.url=http://java.oracle.com/, path.separator=:, java
.vm.name=Java HotSpot(TM) 64-Bit Server VM, file.encoding.pkg=sun.io, user.country=US, sun.java.launcher=SUN_STANDARD, sun.os.patch.level=unknown, java.v
m.specification.name=Java Virtual Machine Specification, user.dir=/usr/share/elasticsearch/plugins/search-guard-5/sgconfig, sg.nowarn.client=true, java.r
untime.version=1.8.0_112-b15, java.awt.graphicsenv=sun.awt.X11GraphicsEnvironment, java.endorsed.dirs=/usr/java/jdk1.8.0_112/jre/lib/endorsed, os.arch=am
d64, java.io.tmpdir=/tmp, line.separator=
, java.vm.specification.vendor=Oracle Corporation, os.name=Linux, sun.jnu.encoding=UTF-8, org.apache.logging.log4j.simplelog.StatusLogger.level=OFF, java
.library.path=/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib, sun.nio.ch.bugLevel=, java.specification.name=Java Platform API Specification
, java.class.version=52.0, sun.management.compiler=HotSpot 64-Bit Tiered Compilers, os.version=3.10.0-514.26.2.el7.x86_64, user.home=/root, user.timezone
=US/Central, java.awt.printerjob=sun.print.PSPrinterJob, file.encoding=UTF-8, java.specification.version=1.8, java.class.path=/usr/share/elasticsearch/pl
ugins/search-guard-5/tools/../guava-19.0.jar:/usr/share/elasticsearch/plugins/search-guard-5/tools/../netty-transport-4.1.11.Final.jar:/usr/share/elastic
search/plugins/search-guard-5/tools/../netty-handler-4.1.11.Final.jar:/usr/share/elasticsearch/plugins/search-guard-5/tools/../netty-buffer-4.1.11.Final.
jar:/usr/share/elasticsearch/plugins/search-guard-5/tools/../commons-cli-1.3.1.jar:/usr/share/elasticsearch/plugins/search-guard-5/tools/../transport-net
ty4-client-5.5.0.jar:/usr/share/elasticsearch/plugins/search-guard-5/tools/../netty-common-4.1.11.Final.jar:/usr/share/elasticsearch/plugins/search-guard
-5/tools/../search-guard-ssl-5.5.0-23.jar:/usr/share/elasticsearch/plugins/search-guard-5/tools/../netty-resolver-4.1.11.Final.jar:/usr/share/elasticsear
ch/plugins/search-guard-5/tools/../search-guard-5-5.5.0-15.jar:/usr/share/elasticsearch/plugins/search-guard-5/tools/../netty-codec-4.1.11.Final.jar:/usr
/share/elasticsearch/plugins/search-guard-5/tools/../netty-codec-http-4.1.11.Final.jar:/usr/share/elasticsearch/plugins/search-guard-5/tools/../../../lib
/HdrHistogram-2.1.9.jar:/usr/share/elasticsearch/plugins/search-guard-5/tools/../../../lib/elasticsearch-5.5.0.jar:/usr/share/elasticsearch/plugins/searc
h-guard-5/tools/../../../lib/hppc-0.7.1.jar:/usr/share/elasticsearch/plugins/search-guard-5/tools/../../../lib/jackson-core-2.8.6.jar:/usr/share/elastics
earch/plugins/search-guard-5/tools/../../../lib/jackson-dataformat-cbor-2.8.6.jar:/usr/share/elasticsearch/plugins/search-guard-5/tools/../../../lib/jack
son-dataformat-smile-2.8.6.jar:/usr/share/elasticsearch/plugins/search-guard-5/tools/../../../lib/jackson-dataformat-yaml-2.8.6.jar:/usr/share/elasticsea
rch/plugins/search-guard-5/tools/../../../lib/java-version-checker-5.5.0.jar:/usr/share/elasticsearch/plugins/search-guard-5/tools/../../../lib/jna-4.4.0
.jar:/usr/share/elasticsearch/plugins/search-guard-5/tools/../../../lib/joda-time-2.9.5.jar:/usr/share/elasticsearch/plugins/search-guard-5/tools/../../.
./lib/jopt-simple-5.0.2.jar:/usr/share/elasticsearch/plugins/search-guard-5/tools/../../../lib/jts-1.13.jar:/usr/share/elasticsearch/plugins/search-guard
-5/tools/../../../lib/log4j-1.2-api-2.8.2.jar:/usr/share/elasticsearch/plugins/search-guard-5/tools/../../../lib/log4j-api-2.8.2.jar:/usr/share/elasticse
arch/plugins/search-guard-5/tools/../../../lib/log4j-core-2.8.2.jar:/usr/share/elasticsearch/plugins/search-guard-5/tools/../../../lib/lucene-analyzers-c
ommon-6.6.0.jar:/usr/share/elasticsearch/plugins/search-guard-5/tools/../../../lib/lucene-backward-codecs-6.6.0.jar:/usr/share/elasticsearch/plugins/sear
ch-guard-5/tools/../../../lib/lucene-core-6.6.0.jar:/usr/share/elasticsearch/plugins/search-guard-5/tools/../../../lib/lucene-grouping-6.6.0.jar:/usr/sha
re/elasticsearch/plugins/search-guard-5/tools/../../../lib/lucene-highlighter-6.6.0.jar:/usr/share/elasticsearch/plugins/search-guard-5/tools/../../../li
b/lucene-join-6.6.0.jar:/usr/share/elasticsearch/plugins/search-guard-5/tools/../../../lib/lucene-memory-6.6.0.jar:/usr/share/elasticsearch/plugins/searc
h-guard-5/tools/../../../lib/lucene-misc-6.6.0.jar:/usr/share/elasticsearch/plugins/search-guard-5/tools/../../../lib/lucene-queries-6.6.0.jar:/usr/share
/elasticsearch/plugins/search-guard-5/tools/../../../lib/lucene-queryparser-6.6.0.jar:/usr/share/elasticsearch/plugins/search-guard-5/tools/../../../lib/
lucene-sandbox-6.6.0.jar:/usr/share/elasticsearch/plugins/search-guard-5/tools/../../../lib/lucene-spatial-6.6.0.jar:/usr/share/elasticsearch/plugins/sea
rch-guard-5/tools/../../../lib/lucene-spatial-extras-6.6.0.jar:/usr/share/elasticsearch/plugins/search-guard-5/tools/../../../lib/lucene-spatial3d-6.6.0.
jar:/usr/share/elasticsearch/plugins/search-guard-5/tools/../../../lib/lucene-suggest-6.6.0.jar:/usr/share/elasticsearch/plugins/search-guard-5/tools/../
../../lib/plugin-cli-5.5.0.jar:/usr/share/elasticsearch/plugins/search-guard-5/tools/../../../lib/securesm-1.1.jar:/usr/share/elasticsearch/plugins/searc
h-guard-5/tools/../../../lib/snakeyaml-1.15.jar:/usr/share/elasticsearch/plugins/search-guard-5/tools/../../../lib/spatial4j-0.6.jar:/usr/share/elasticse
arch/plugins/search-guard-5/tools/../../../lib/t-digest-3.0.jar:/usr/share/elasticsearch/plugins/search-guard-5/tools/../deps/*, user.name=root, java.vm.
specification.version=1.8, sun.java.command=com.floragunn.searchguard.tools.SearchGuardAdmin --accept-red-cluster -ks /etc/elasticsearch/kirk-keystore.jk
s -ts /etc/elasticsearch/truststore.jks -icl -nhnv --diagnose, java.home=/usr/java/jdk1.8.0_112/jre, sun.arch.data.model=64, user.language=en, java.speci
fication.vendor=Oracle Corporation, es.set.netty.runtime.available.processors=false, awt.toolkit=sun.awt.X11.XToolkit, java.vm.info=mixed mode, java.vers
ion=1.8.0_112, java.ext.dirs=/usr/java/jdk1.8.0_112/jre/lib/ext:/usr/java/packages/lib/ext, sun.boot.class.path=/usr/java/jdk1.8.0_112/jre/lib/resources.
jar:/usr/java/jdk1.8.0_112/jre/lib/rt.jar:/usr/java/jdk1.8.0_112/jre/lib/sunrsasign.jar:/usr/java/jdk1.8.0_112/jre/lib/jsse.jar:/usr/java/jdk1.8.0_112/jr
e/lib/jce.jar:/usr/java/jdk1.8.0_112/jre/lib/charsets.jar:/usr/java/jdk1.8.0_112/jre/lib/jfr.jar:/usr/java/jdk1.8.0_112/jre/classes, java.vendor=Oracle C
orporation, file.separator=/, java.vendor.url.bug=http://bugreport.sun.com/bugreport/, sun.io.unicode.encoding=UnicodeLittle, sun.cpu.endian=little, sg.d
isplay_lic_only_stdout=true, sun.cpu.isalist=}
2017-Aug-22_14-06-17

```

**Comment by gsaxam** [comment]
But, isn't my `/etc/elasticsearch/` my `/config` directory? That's where my `elasticsearch.yml` is stored.

**Comment by gsaxam** [comment]
@jochenkressin I think I am more confused now. When I run `install_demo_configuration.sh`, it places the `.jks` files automatically in the `/etc/elasticsearch` directory. This is also where my `elasticsearch.yml` file lives. Are you suggesting that I need to create a directory called `config` somewhere else specifically? I use elasticsearch as a service and that's where the files are automatically created. Your comments above did not make much sense to me :(

**Comment by jochenkressin** [comment]
Sorry about the confusion, the directory layout depends on how you installed ES in the first place. So if you used the  install_demo_configuration.sh scripts, what is the outcome if you simply execute the sgadmin_demo.sh script from the same directory?

**Comment by gsaxam** [comment]
Actually I was able to fix my issue. I had the minimum number of nodes set to 2 while I was only working with 1 node during troubleshooting. ES was never able to bring the cluster up since there were not enough number of nodes to elect master. Setting that config back to 1 made everything work. I am still placing all `.JKS` files on my '/etc/elasticsearch' directory and it works great! Thanks!
