### ISSUE TITLE
SearchGuardConfigService says it fail to refresh security configuration even though there is

### ISSUE THREAD

**Issue by sanori** [floragunncom/search-guard#38]
On boot time of elastic search, there is following error logs: (and JVM takes VIRT mem, twice of -Xmx setting)
```
[2015-07-16 15:12:11,977][INFO ][node                     ] [Desmond Pitt] started
[2015-07-16 15:12:12,053][INFO ][gateway                  ] [Desmond Pitt] recovered [6] indices into cluster_state
[2015-07-16 15:12:12,877][ERROR][com.floragunn.searchguard.service.SearchGuardConfigService] [Desmond Pitt] Try to refresh security configuration but it failed due to org.elasticsearch.action.NoShardAvailableActionException: [searchguard][4] null
org.elasticsearch.action.NoShardAvailableActionException: [searchguard][4] null
    at org.elasticsearch.action.support.single.shard.TransportShardSingleOperationAction$AsyncSingleAction.perform(TransportShardSingleOperationAction.java:175)
    at org.elasticsearch.action.support.single.shard.TransportShardSingleOperationAction$AsyncSingleAction.start(TransportShardSingleOperationAction.java:155)
    at org.elasticsearch.action.support.single.shard.TransportShardSingleOperationAction.doExecute(TransportShardSingleOperationAction.java:89)
    at org.elasticsearch.action.support.single.shard.TransportShardSingleOperationAction.doExecute(TransportShardSingleOperationAction.java:55)
    at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:167)
    at com.floragunn.searchguard.filter.SearchGuardActionFilter.apply0(SearchGuardActionFilter.java:141)
    at com.floragunn.searchguard.filter.SearchGuardActionFilter.apply(SearchGuardActionFilter.java:89)
    at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:165)
    at com.floragunn.searchguard.filter.AbstractActionFilter.apply(AbstractActionFilter.java:105)
    at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:165)
    at com.floragunn.searchguard.filter.AbstractActionFilter.apply(AbstractActionFilter.java:105)
    at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:165)
    at com.floragunn.searchguard.filter.AbstractActionFilter.apply(AbstractActionFilter.java:105)
    at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:165)
    at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:82)
    at org.elasticsearch.client.node.NodeClient.execute(NodeClient.java:98)
    at org.elasticsearch.client.support.AbstractClient.get(AbstractClient.java:197)
    at org.elasticsearch.action.get.GetRequestBuilder.doExecute(GetRequestBuilder.java:201)
    at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:91)
    at com.floragunn.searchguard.service.SearchGuardConfigService.reloadConfig(SearchGuardConfigService.java:81)
    at com.floragunn.searchguard.service.SearchGuardConfigService.access$500(SearchGuardConfigService.java:41)
    at com.floragunn.searchguard.service.SearchGuardConfigService$Reload.run(SearchGuardConfigService.java:111)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

But, there is http://localhost:9200/searchguard/ac/ac such as following:
```
{
  "_index": "searchguard",
  "_type": "ac",
  "_id": "ac",
  "_version": 3,
  "found": true,
  "_source": {
    "acl": [
      {
        "__Comment__": "By default no filters are executed and no filters a by-passed. In such a case a exception is throws an access will be denied.",
        "filters_bypass": [
          
        ],
        "filters_execute": [
          
        ]
      },
      {
        "__Comment__": "For admin role all filters are bypassed (so none will be executed) for all indices. This means unrestricted access at all for this role.",
        "roles": [
          "admin"
        ],
        "filters_bypass": [
          "*"
        ],
        "filters_execute": [
          
        ]
      },
      {
        "__Comment__": "For logstash role all filters are bypassed (so none will be executed) for index 'logstash-*'. This means unrestricted access to this index for this role.",
        "roles": [
          "logstash"
        ],
        "indices": [
          "logstash-*"
        ],
        "filters_bypass": [
          "*"
        ],
        "filters_execute": [
          
        ]
      },
      {
        "__Comment__": "For kibana role the filters 'actionrequestfilter.readonly' are executed (but no other filters) for index 'logstash-*'",
        "roles": [
          "kibana"
        ],
        "indices": [
          "logstash-*"
        ],
        "filters_bypass": [
          
        ],
        "filters_execute": [
          "actionrequestfilter.readonly"
        ]
      },
      {
        "__Comment__": "For role 'kibana' all filters are bypassed (so none will be executed) for index '.kibana'. This means unrestricted access to this index for this role.",
        "roles": [
          "kibana"
        ],
        "indices": [
          ".kibana"
        ],
        "filters_bypass": [
          "*"
        ],
        "filters_execute": [
          
        ]
      }
    ]
  }
}
```

**Comment by floragunncom** [comment]
Does ES has ever started for you with search guard enabled?

**Comment by madhusudand** [comment]
hi,
i am also getting the same ERROR while i run elasticsearch with search-guard. I am able to run ES without search-guard without any ERROR:


[2015-07-22 01:48:56,884][INFO ][node                     ] [Plunderer] version[1.6.0], pid[28028], build[cdd3ac4/2015-06-09T13:36:34Z]
[2015-07-22 01:48:56,885][INFO ][node                     ] [Plunderer] initializing ...
[2015-07-22 01:48:57,240][INFO ][com.floragunn.searchguard.SearchGuardPlugin] Class enhancements for DLS/FLS successful
[2015-07-22 01:48:57,242][INFO ][plugins                  ] [Plunderer] loaded [searchguard], sites []
[2015-07-22 01:48:57,304][INFO ][env                      ] [Plunderer] using [1] data paths, mounts [[/ (rootfs)]], net usable_space [36.5gb], net total_space [42.8gb], types [rootfs]
[2015-07-22 01:49:02,093][WARN ][com.floragunn.searchguard.util.SecurityUtil] AES 256 not supported, max key length for AES is 128. To enable AES 256 install 'Java Cryptography Extension (JCE) Unlimited Strength Jurisdiction Policy Files'
[2015-07-22 01:49:02,849][WARN ][com.floragunn.searchguard.service.SearchGuardService] You're trying to run elasticsearch as root or Windows Administrator! Thats a potential security issue.
[2015-07-22 01:49:03,259][INFO ][node                     ] [Plunderer] initialized
[2015-07-22 01:49:03,269][INFO ][node                     ] [Plunderer] starting ...
[2015-07-22 01:49:03,495][INFO ][transport                ] [Plunderer] bound_address {inet[/0:0:0:0:0:0:0:0:9300]}, publish_address {inet[/10.63.13.181:9300]}
[2015-07-22 01:49:03,608][INFO ][discovery                ] [Plunderer] elasticsearch/My5zlEnvS5q1VbaHD0tL-g
[2015-07-22 01:49:07,400][INFO ][cluster.service          ] [Plunderer] new_master [Plunderer][My5zlEnvS5q1VbaHD0tL-g][10.63.13.181][inet[/10.63.13.181:9300]], reason: zen-disco-join (elected_as_master)
[2015-07-22 01:49:07,476][INFO ][http                     ] [Plunderer] bound_address {inet[/0:0:0:0:0:0:0:0:9200]}, publish_address {inet[/10.63.13.181:9200]}
[2015-07-22 01:49:07,477][INFO ][node                     ] [Plunderer] started
[2015-07-22 01:49:07,519][INFO ][gateway                  ] [Plunderer] recovered [3] indices into cluster_state
[2015-07-22 01:49:08,279][ERROR][com.floragunn.searchguard.service.SearchGuardConfigService] [Plunderer] Try to refresh security configuration but it failed due to org.elasticsearch.action.NoShardAvailableActionException: [searchguard][4] null
org.elasticsearch.action.NoShardAvailableActionException: [searchguard][4] null
        at org.elasticsearch.action.support.single.shard.TransportShardSingleOperationAction$AsyncSingleAction.perform(TransportShardSingleOperationAction.java:175)
        at org.elasticsearch.action.support.single.shard.TransportShardSingleOperationAction$AsyncSingleAction.start(TransportShardSingleOperationAction.java:155)
        at org.elasticsearch.action.support.single.shard.TransportShardSingleOperationAction.doExecute(TransportShardSingleOperationAction.java:89)
        at org.elasticsearch.action.support.single.shard.TransportShardSingleOperationAction.doExecute(TransportShardSingleOperationAction.java:55)
        at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:167)
        at com.floragunn.searchguard.filter.SearchGuardActionFilter.apply0(SearchGuardActionFilter.java:141)
        at com.floragunn.searchguard.filter.SearchGuardActionFilter.apply(SearchGuardActionFilter.java:89)
        at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:165)
        at com.floragunn.searchguard.filter.AbstractActionFilter.apply(AbstractActionFilter.java:105)
        at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:165)
        at com.floragunn.searchguard.filter.AbstractActionFilter.apply(AbstractActionFilter.java:105)
        at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:165)
        at com.floragunn.searchguard.filter.AbstractActionFilter.apply(AbstractActionFilter.java:105)
        at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:165)
        at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:82)
        at org.elasticsearch.client.node.NodeClient.execute(NodeClient.java:98)
        at org.elasticsearch.client.support.AbstractClient.get(AbstractClient.java:197)
        at org.elasticsearch.action.get.GetRequestBuilder.doExecute(GetRequestBuilder.java:201)
        at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:91)
        at com.floragunn.searchguard.service.SearchGuardConfigService.reloadConfig(SearchGuardConfigService.java:81)
        at com.floragunn.searchguard.service.SearchGuardConfigService.access$500(SearchGuardConfigService.java:41)
        at com.floragunn.searchguard.service.SearchGuardConfigService$Reload.run(SearchGuardConfigService.java:111)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

**Comment by madhusudand** [comment]
Here I would like to add few more observations
*when you start ES with search-guard enabled and  also when search-guard index has not been created for uploading acl(searchguard/ac/ac), then ES will start without any ERROR.
* but once you add acl document, same ERROR will be thrown
*Eventhough ERROR is thrown , ES wont stop.

I am using ES 1.6

Please help me in this regard,

**Comment by sanori** [comment]
@floragunncom 
> Does ES has ever started for you with search guard enabled?

The following line is in elasticsearch.yml: 
```
searchguard.enabled: true
```

Did you ask another thing?

**Comment by madhusudand** [comment]
@floragunncom  @sanori 
Any update for this??

**Comment by slundberg** [comment]
I get the same error now consistently. I think it is a timing issue since my configuration worked fine at first, then started getting this error every once in a while after adding data. Now after adding millions of records I can't get the server to restart with search guard enabled.

**Comment by bilsch** [comment]
I am having the same issue.

elasticsearch-1.6.2-1.noarch

java -version
```
java version "1.7.0_85"
OpenJDK Runtime Environment (rhel-2.6.1.2.el7_1-x86_64 u85-b01)
OpenJDK 64-Bit Server VM (build 24.85-b03, mixed mode)
```

search-guard-16-0.6-SNAPSHOT

I built from the es1.6 branch 8/24 so its fairly recent

```
[2015-08-26 14:57:22,548][DEBUG][com.floragunn.searchguard.filter.FLSActionFilter] REQUEST on node foo-bar: indices:data/read/get (class org.elasticsearch.action.get.GetRequest) from INTRANODE
[2015-08-26 14:57:22,548][DEBUG][com.floragunn.searchguard.filter.FLSActionFilter] Context []
[2015-08-26 14:57:22,548][DEBUG][com.floragunn.searchguard.filter.FLSActionFilter] Headers []
[2015-08-26 14:57:22,548][DEBUG][com.floragunn.searchguard.filter.FLSActionFilter] TYPE: intra node request, skip filters
[2015-08-26 14:57:22,548][ERROR][com.floragunn.searchguard.service.SearchGuardConfigService] [foo-bar] Try to refresh security configuration but it failed due to org.elasticsearch.action.NoShardAvailableActionException: [searchguard][1] null
org.elasticsearch.action.NoShardAvailableActionException: [searchguard][1] null
	at org.elasticsearch.action.support.single.shard.TransportShardSingleOperationAction$AsyncSingleAction.perform(TransportShardSingleOperationAction.java:175)
	at org.elasticsearch.action.support.single.shard.TransportShardSingleOperationAction$AsyncSingleAction.start(TransportShardSingleOperationAction.java:155)
	at org.elasticsearch.action.support.single.shard.TransportShardSingleOperationAction.doExecute(TransportShardSingleOperationAction.java:89)
	at org.elasticsearch.action.support.single.shard.TransportShardSingleOperationAction.doExecute(TransportShardSingleOperationAction.java:55)
	at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:167)
	at com.floragunn.searchguard.filter.SearchGuardActionFilter.apply0(SearchGuardActionFilter.java:141)
	at com.floragunn.searchguard.filter.SearchGuardActionFilter.apply(SearchGuardActionFilter.java:89)
	at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:165)
	at com.floragunn.searchguard.filter.AbstractActionFilter.apply(AbstractActionFilter.java:105)
	at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:165)
	at com.floragunn.searchguard.filter.AbstractActionFilter.apply(AbstractActionFilter.java:105)
	at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:165)
	at com.floragunn.searchguard.filter.AbstractActionFilter.apply(AbstractActionFilter.java:105)
	at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:165)
	at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:82)
	at org.elasticsearch.client.node.NodeClient.execute(NodeClient.java:98)
	at org.elasticsearch.client.support.AbstractClient.get(AbstractClient.java:197)
	at org.elasticsearch.action.get.GetRequestBuilder.doExecute(GetRequestBuilder.java:201)
	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:91)
	at com.floragunn.searchguard.service.SearchGuardConfigService.reloadConfig(SearchGuardConfigService.java:81)
	at com.floragunn.searchguard.service.SearchGuardConfigService.access$500(SearchGuardConfigService.java:41)
	at com.floragunn.searchguard.service.SearchGuardConfigService$Reload.run(SearchGuardConfigService.java:111)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

searchguard settings from elasticsearch.yml:
```
searchguard:
  authentication:
    authorization:
      settingsdb:
        roles:
          admin: ["admin"]
          app: ["bar_app"]
          ro: ["bar_ro"]
    settingsdb:
      user:
        admin: xx
        bar_app: xx
        bar_ro: xx
  enabled: true
  http:
    xforwardedfor:
      trustedproxies: localhost
  key_path: /etc/elasticsearch
  ssl:
    transport:
      http:
        enabled: true
        keystore_filepath: /etc/elasticsearch/keystore.jks
        keystore_password: xx
        truststore_filepath: /etc/elasticsearch/truststore.jks
        truststore_password: xx
      node:
        enabled: true
        keystore_filepath: /etc/elasticsearch/keystore.jks
        keystore_password: xx
        truststore_filepath: /etc/elasticsearch/truststore.jks
        truststore_password: xx
```

acl setup:
```
curl -XPUT "http://$(hostname):9200/searchguard/ac/ac" -d ' { "acl": [ { "__Comment__": "By default no filters are executed and no filters a by-passed. In such a case a exception is throws an access will be denied.", "filters_bypass": [], "filters_execute": [] }, { "__Comment__": "For admin role all filters are bypassed (so none will be executed) for all indices. This means unrestricted access at all for this role.", "roles": [ "admin" ], "filters_bypass": [ "*" ], "filters_execute": [] }, { "__Comment__": "For app role all unrestricted access to the forms index", "roles": [ "app" ], "indices": ["forms"], "filters_bypass": [ "*" ], "filters_execute": [] }, { "__Comment__": "For ro role all read-only access to the forms index", "roles": [ "app" ], "indices": ["forms"], "filters_bypass": [ "*" ], "filters_execute": ["actionrequestfilter.readonly"] } ] }'
```

Order of events:
1. install elasticsearch/deps
1. assemble 2-node cluster
1. populate dummy data
1. populate searchguard acls
1. install search-guard plugin / bounce on node1
1. copy searchguard_node_key.key from node1 => node2
1. install search-guard plugin / bounce on node2

I can see the es cluster is up:
```
[3] pry(main)> $client.info['cluster_name']
=> "bar"
```

Doing a search for the dummy data just hangs/times out while the elasticsearch log file fills up with exceptions like the one above. Seems even the populated dummy data index is invisible ;(

**Comment by bpesics** [comment]
same here, any news on this?

**Comment by qpily** [comment]
This may caused by searchguard trying to get other nodes by multicast. if you don't need the multicast, just add 'discovery.zen.ping.multicast.enabled: false' to close the multicast to solve this problem.

**Comment by sanori** [comment]
@qpily Thank you for your comments. I tried
```
node.master: true
node.data: true

index.number_of_shards: 1
index.number_of_replicas: 0

discovery.zen.ping.multicast.enabled: false

searchguard.enabled: true
```
But, same error continues.

**Comment by qpily** [comment]
@sanori 
Is this error blocks your search engine or just a logger? In my environment it just shows up sometimes.
Anyway, it seems related to the shards numbers of searchguard settings. You may try to modify the shards number of searchguard index into 1 and see if this message shows up again.
{
  "settings": {
    "number_of_shards": 1, 
    "number_of_replicas": 1
  }
}

**Comment by HemaAnusha** [comment]
Hi I even I used to get the same error any findings on this issue?????
If yes please update the solution..........

**Comment by HemaAnusha** [comment]
Hi even I used to get the same error any findings on this issue?????
If yes please update the solution..........

Is this issue related to the mappings or do I need to add any configuration in elasticsearch.yml file???????????

**Comment by schlitzered** [comment]
+1 same issue here

**Comment by vroomvroomvroom** [comment]
same issue here .. but on a single node, so no multicast issues.
ES 1.7.1; search-guard 1.7.3, 

I have found that if i uninstall the plugin, install the ACL, then reinstall the plugin, i can function for a period of time (until elasticsearch needs restart)

[ERROR][com.floragunn.searchguard.service.SearchGuardConfigService] [Desmond Pitt] Try to refresh security configuration but it failed due to org.elasticsearch.action.NoShardAvailableActionException: [searchguard][4] null

searchguard.enabled: true is in elasticsearch.yml

yes, elasticsearch will start; but it doesn't appear that search-guard is providing the expected functionality after it does due to this error.  it seems to be wide open, no auth enabled.

**Comment by floragunncom** [comment]
Auto close this issue because it refers to Search Guard 1 which is decommissioned now. For details pls. see https://github.com/floragunncom/search-guard-attic/wiki . If this issue is still valid for Search Guard 2 (for elasticsearch 2.x) feel free to reopen it (or to file a new one). Pls. do not longer report issues for Search Guard 1 (for elasticsearch 1.x). We sincerely apologize for the inconvenience this may have caused. Thanks for contributing!
