### ISSUE TITLE
elasticsearch 5.6.0-16 fails to start after installation of searchguard

### ISSUE THREAD

**Issue by luvpreetsingh** [floragunncom/search-guard#390]
* Search Guard and Elasticsearch version - 5.6.0
* JVM version and operating system version - ubuntu 16.04 

    server@server:/etc/elasticsearch$ java -version
    openjdk version "1.8.0_131"
    OpenJDK Runtime Environment (build 1.8.0_131-8u131-b11-2ubuntu1.16.04.3-b11)
    OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)

* Number of nodes in your cluster - single node
* Description of the bug - elasticsearch fails after installation of searchguard.

Following this page for installation - https://github.com/floragunncom/search-guard-docs/blob/master/installation.md

I install it, and then I run the `install_demo_configuration.sh` script.
Then after that, when I try to run elasticsearch, it fails to start..

These informations are optional but are very valueable and
typically would lead to get bugs fixed faster:

* Steps to reproduce

stop elasticsearch.
install searchguard 5.6.0-16
start elasticsearch.

It fails to start.

No config directory is being made.

If I remove it, elasticsearch runs fine.

**Comment by luvpreetsingh** [comment]
[2017-09-18T09:07:34,464][ERROR][o.e.b.Bootstrap          ] Exception
    org.elasticsearch.ElasticsearchException: Failed to load plugin class[com.floragunn.searchguard.SearchGuardPlugin]
        at org.elasticsearch.plugins.PluginsService.loadPlugin(PluginsService.java:434) ~[elasticsearch-5.6.0.jar:5.6.0]
        at org.elasticsearch.plugins.PluginsService.loadBundles(PluginsService.java:387) ~[elasticsearch-5.6.0.jar:5.6.0]
        at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:140) ~[elasticsearch-5.6.0.jar:5.6.0]
        at org.elasticsearch.node.Node.<init>(Node.java:313) ~[elasticsearch-5.6.0.jar:5.6.0]
        at org.elasticsearch.node.Node.<init>(Node.java:245) ~[elasticsearch-5.6.0.jar:5.6.0]
        at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:233) ~[elasticsearch-5.6.0.jar:5.6.0]
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:233) ~[elasticsearch-5.6.0.jar:5.6.0]
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:342) [elasticsearch-5.6.0.jar:5.6.0]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:132) [elasticsearch-5.6.0.jar:5.6.0]
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:123) [elasticsearch-5.6.0.jar:5.6.0]
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:67) [elasticsearch-5.6.0.jar:5.6.0]
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:134) [elasticsearch-5.6.0.jar:5.6.0]
        at org.elasticsearch.cli.Command.main(Command.java:90) [elasticsearch-5.6.0.jar:5.6.0]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:91) [elasticsearch-5.6.0.jar:5.6.0]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:84) [elasticsearch-5.6.0.jar:5.6.0]
    Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_131]
        at org.elasticsearch.plugins.PluginsService.loadPlugin(PluginsService.java:423) ~[elasticsearch-5.6.0.jar:5.6.0]
        ... 14 more
    Caused by: org.elasticsearch.ElasticsearchException: searchguard.ssl.transport.keystore_filepath or searchguard.ssl.transport.pemkey_filepath must be set if transport ssl is reqested.
        at com.floragunn.searchguard.ssl.DefaultSearchGuardKeyStore.initSSLConfig(DefaultSearchGuardKeyStore.java:307) ~[?:?]
        at com.floragunn.searchguard.ssl.DefaultSearchGuardKeyStore.<init>(DefaultSearchGuardKeyStore.java:153) ~[?:?]
        at com.floragunn.searchguard.SearchGuardPlugin.<init>(SearchGuardPlugin.java:271) ~[?:?]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_131]
        at org.elasticsearch.plugins.PluginsService.loadPlugin(PluginsService.java:423) ~[elasticsearch-5.6.0.jar:5.6.0]
        ... 14 more

    [2017-09-18T09:07:34,488][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [] uncaught exception in thread [main]
    org.elasticsearch.bootstrap.StartupException: ElasticsearchException[Failed to load plugin class [com.floragunn.searchguard.SearchGuardPlugin]]; nested: InvocationTargetException; nested: ElasticsearchException[searchguard.ssl.transport.keystore_filepath or searchguard.ssl.transport.pemkey_filepath must be set if transport ssl is reqested.];
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:136) ~[elasticsearch-5.6.0.jar:5.6.0]
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:123) ~[elasticsearch-5.6.0.jar:5.6.0]
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:67) ~[elasticsearch-5.6.0.jar:5.6.0]
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:134) ~[elasticsearch-5.6.0.jar:5.6.0]
        at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-5.6.0.jar:5.6.0]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:91) ~[elasticsearch-5.6.0.jar:5.6.0]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:84) ~[elasticsearch-5.6.0.jar:5.6.0]
    Caused by: org.elasticsearch.ElasticsearchException: Failed to load plugin class [com.floragunn.searchguard.SearchGuardPlugin]
        at org.elasticsearch.plugins.PluginsService.loadPlugin(PluginsService.java:434) ~[elasticsearch-5.6.0.jar:5.6.0]
        at org.elasticsearch.plugins.PluginsService.loadBundles(PluginsService.java:387) ~[elasticsearch-5.6.0.jar:5.6.0]
        at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:140) ~[elasticsearch-5.6.0.jar:5.6.0]
        at org.elasticsearch.node.Node.<init>(Node.java:313) ~[elasticsearch-5.6.0.jar:5.6.0]
        at org.elasticsearch.node.Node.<init>(Node.java:245) ~[elasticsearch-5.6.0.jar:5.6.0]
        at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:233) ~[elasticsearch-5.6.0.jar:5.6.0]
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:233) ~[elasticsearch-5.6.0.jar:5.6.0]
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:342) ~[elasticsearch-5.6.0.jar:5.6.0]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:132) ~[elasticsearch-5.6.0.jar:5.6.0]
        ... 6 more
     Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_131]
        at org.elasticsearch.plugins.PluginsService.loadPlugin(PluginsService.java:423) ~[elasticsearch-5.6.0.jar:5.6.0]
        at org.elasticsearch.plugins.PluginsService.loadBundles(PluginsService.java:387) ~[elasticsearch-5.6.0.jar:5.6.0]
        at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:140) ~[elasticsearch-5.6.0.jar:5.6.0]
        at org.elasticsearch.node.Node.<init>(Node.java:313) ~[elasticsearch-5.6.0.jar:5.6.0]
        at org.elasticsearch.node.Node.<init>(Node.java:245) ~[elasticsearch-5.6.0.jar:5.6.0]
        at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:233) ~[elasticsearch-5.6.0.jar:5.6.0]
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:233) ~[elasticsearch-5.6.0.jar:5.6.0]
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:342) ~[elasticsearch-5.6.0.jar:5.6.0]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:132) ~[elasticsearch-5.6.0.jar:5.6.0]
        ... 6 more
    Caused by: org.elasticsearch.ElasticsearchException: searchguard.ssl.transport.keystore_filepath or searchguard.ssl.transport.pemkey_filepath must be set if transport ssl is reqested.
        at com.floragunn.searchguard.ssl.DefaultSearchGuardKeyStore.initSSLConfig(DefaultSearchGuardKeyStore.java:307) ~[?:?]
        at com.floragunn.searchguard.ssl.DefaultSearchGuardKeyStore.<init>(DefaultSearchGuardKeyStore.java:153) ~[?:?]
        at com.floragunn.searchguard.SearchGuardPlugin.<init>(SearchGuardPlugin.java:271) ~[?:?]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_131]
        at org.elasticsearch.plugins.PluginsService.loadPlugin(PluginsService.java:423) ~[elasticsearch-5.6.0.jar:5.6.0]
        at org.elasticsearch.plugins.PluginsService.loadBundles(PluginsService.java:387) ~[elasticsearch-5.6.0.jar:5.6.0]
        at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:140) ~[elasticsearch-5.6.0.jar:5.6.0]
        at org.elasticsearch.node.Node.<init>(Node.java:313) ~[elasticsearch-5.6.0.jar:5.6.0]
        at org.elasticsearch.node.Node.<init>(Node.java:245) ~[elasticsearch-5.6.0.jar:5.6.0]
        at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:233) ~[elasticsearch-5.6.0.jar:5.6.0]
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:233) ~[elasticsearch-5.6.0.jar:5.6.0]
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:342) ~[elasticsearch-5.6.0.jar:5.6.0]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:132) ~[elasticsearch-5.6.0.jar:5.6.0]
        ... 6 more

**Comment by luvpreetsingh** [comment]
Friends I need help here, please reply.

**Comment by floragunncom** [comment]
Can you pls. post your elasticsearch.yml

**Comment by luvpreetsingh** [comment]
network.host: 0.0.0.0

    http.port: 9200


    ######## Start Search Guard Demo Configuration ########
    searchguard.ssl.transport.keystore_filepath: keystore.jks
    searchguard.ssl.transport.truststore_filepath: truststore.jks
    searchguard.ssl.transport.enforce_hostname_verification: false
    searchguard.ssl.http.enabled: true
    searchguard.ssl.http.keystore_filepath: keystore.jks
    searchguard.ssl.http.truststore_filepath: truststore.jks
    searchguard.authcz.admin_dn:
      - CN=kirk,OU=client,O=client,L=test, C=de

    cluster.name: searchguard_demo
    network.host: 0.0.0.0
    ######## End Search Guard Demo Configuration ########


This is the content of the file. Rest are the commented lines.

**Comment by luvpreetsingh** [comment]
elasticsearch/
    |-- elasticsearch.yml
    |-- jvm.options
    |-- keystore.jks
    |-- kirk.jks
    |-- log4j2.properties
    |-- scripts
    `-- truststore.jks

This is the structure of the directory `/etc/elasticsearch/`
1 directory, 6 files

**Comment by floragunncom** [comment]
seems you use an other elasticsearch.yml if you start your node. 
Pls. post the full logs from that time the nodes starts until its fails.

**Comment by luvpreetsingh** [comment]
The logs I have commented above are the only ones.

No logs are produced now.

**Comment by floragunncom** [comment]
Make sure your at least on INFO loglevel, then elasticsearch itself (thats not even SG related) will printout some infos when a node starts. Depending on how you installed elasticsearch (deb package?) your logs may live in /var/log or in the systemd journal. Without logs we cannot help you.

**Comment by luvpreetsingh** [comment]
Okay, this is what I got from `sudo journalctl -u elasticsearch.service`

    Sep 21 13:56:27 monitoring-server systemd[1]: Starting Elasticsearch...
    Sep 21 13:56:27 monitoring-server systemd[1]: Started Elasticsearch.
    Sep 21 13:56:30 monitoring-server elasticsearch[23248]: Exception in thread "main" 2017-09-21 13:56:30,633 main ERROR No log4j2 configuration f
    Sep 21 13:56:30 monitoring-server elasticsearch[23248]: ElasticsearchParseException[duplicate settings key [network.host] found at line number 
    Sep 21 13:56:30 monitoring-server elasticsearch[23248]:         at org.elasticsearch.common.settings.loader.XContentSettingsLoader.serializeVal
    Sep 21 13:56:30 monitoring-server elasticsearch[23248]:         at org.elasticsearch.common.settings.loader.XContentSettingsLoader.serializeObj
    Sep 21 13:56:30 monitoring-server elasticsearch[23248]:         at org.elasticsearch.common.settings.loader.XContentSettingsLoader.load(XConten
    Sep 21 13:56:30 monitoring-server elasticsearch[23248]:         at org.elasticsearch.common.settings.loader.XContentSettingsLoader.load(XConten
    Sep 21 13:56:30 monitoring-server elasticsearch[23248]:         at org.elasticsearch.common.settings.loader.YamlSettingsLoader.load(YamlSetting
    Sep 21 13:56:30 monitoring-server elasticsearch[23248]:         at org.elasticsearch.common.settings.Settings$Builder.loadFromStream(Settings.j
    Sep 21 13:56:30 monitoring-server elasticsearch[23248]:         at org.elasticsearch.common.settings.Settings$Builder.loadFromPath(Settings.jav
    Sep 21 13:56:30 monitoring-server elasticsearch[23248]:         at org.elasticsearch.node.InternalSettingsPreparer.prepareEnvironment(InternalS
    Sep 21 13:56:30 monitoring-server elasticsearch[23248]:         at org.elasticsearch.cli.EnvironmentAwareCommand.createEnv(EnvironmentAwareComm
    Sep 21 13:56:30 monitoring-server elasticsearch[23248]:         at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareComman
    Sep 21 13:56:30 monitoring-server elasticsearch[23248]:         at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:134)
    Sep 21 13:56:30 monitoring-server elasticsearch[23248]:         at org.elasticsearch.cli.Command.main(Command.java:90)
    Sep 21 13:56:30 monitoring-server elasticsearch[23248]:         at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:91)
    Sep 21 13:56:30 monitoring-server elasticsearch[23248]:         at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:84)
    Sep 21 13:56:30 monitoring-server systemd[1]: elasticsearch.service: Main process exited, code=exited, status=1/FAILURE
    Sep 21 13:56:30 monitoring-server systemd[1]: elasticsearch.service: Unit entered failed state.
    Sep 21 13:56:30 monitoring-server systemd[1]: elasticsearch.service: Failed with result 'exit-code'.



Found the issue, commented the line `network.host: 0.0.0.0`. And it started.

**Comment by luvpreetsingh** [comment]
Now I am facing another issue,

    server@server:/usr/share/kibana$ curl --user admin:admin -XGET 'https://localhost:9200/_cat/indices?v&pretty'
    curl: (60) server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
    More details here: http://curl.haxx.se/docs/sslcerts.html

    curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
    If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
    If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.



If I use --insecure ,

    {
      "error" : {
        "root_cause" : [
          {
            "type" : "security_exception",
            "reason" : "no permissions for indices:data/read/search"
          }
        ],
        "type" : "security_exception",
        "reason" : "no permissions for indices:data/read/search"
      },
      "status" : 403 
    }

**Comment by floragunncom** [comment]
so your original issue went away?

**Comment by luvpreetsingh** [comment]
Yes, it went away. I got the solution for that.

But now this curl error is coming .

**Comment by floragunncom** [comment]
pls ask for help here: https://groups.google.com/forum/#!forum/search-guard

**Comment by wybrono** [comment]
@luvpreetsingh 
How is your solution to this problem? Can you help me?
I use ES5.1.1, with install_demo_configuration.sh start the same error

**Comment by wybrono** [comment]
@floragunncom 
How is this problem solved? When I used 5.1.1, I encountered the same mistake

**Comment by MiladHamid** [comment]
I know this issue has been for months ago but in case someone has same issue as i had and as i learnt from this thread to fix this issue. Simply the solution was to comment out the node name and comment the network.host: 0.0.0.0.

**Comment by wybrono** [comment]
I have solved this problem, searchguard will generate a new cluster name, the cluster name in the previous configuration file needs to be commented out.

**Comment by akasranjan005** [comment]
I am also facing the same issue, have tried both the configs, none worked. My ELK Version is 6.4, SG Version is 23.0. Please Help.

**Comment by floragunncom** [comment]
Please do not ask questions here. 
For that refer to https://groups.google.com/forum/#!forum/search-guard or, if you are a paying customer, contact our support.

Github is a place **only** for reporting bugs or feature requests.
If you report a bug please include **always** the following informations or the issue will likely be closed as invalid:

* Search Guard and Elasticsearch version
* Kibana plugin version
* JVM version and operating system version
* Number of nodes in your cluster
* Description of the bug
* sg_*.yml config files
* kibana.yml file
* elasticsearch.yml file

These informations are optional but are very valuable and
typically would lead to get bugs fixed faster:

* Steps to reproduce
* Logfiles on DEBUG level
* A failing unittest
