### ISSUE TITLE
Support for 5.6.2

### ISSUE THREAD

**Issue by myoung34** [floragunncom/search-guard#393]
Will not install on top of ES 5.6.2
Is this by design or is it just untested

```20:29:02     amazon-ebs: [ERROR   ] Command '/usr/share/elasticsearch/bin/elasticsearch-plugin install -b com.floragunn:search-guard-5:5.6.0-16' failed with return code: 1
20:29:02     amazon-ebs: [ERROR   ] stdout: -> Downloading com.floragunn:search-guard-5:5.6.0-16 from maven central
20:29:02     amazon-ebs: [=================================================] 100%??
20:29:02     amazon-ebs: [ERROR   ] stderr: Exception in thread "main" java.lang.IllegalArgumentException: plugin [search-guard-5] is incompatible with version [5.6.2]; was designed for version [5.6.0]
20:29:02     amazon-ebs: 	at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:146)
20:29:02     amazon-ebs: 	at org.elasticsearch.plugins.InstallPluginCommand.verify(InstallPluginCommand.java:501)
20:29:02     amazon-ebs: 	at org.elasticsearch.plugins.InstallPluginCommand.install(InstallPluginCommand.java:570)
20:29:02     amazon-ebs: 	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:218)
20:29:02     amazon-ebs: 	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:202)
20:29:02     amazon-ebs: 	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:67)
20:29:02     amazon-ebs: 	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:134)
20:29:02     amazon-ebs: 	at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:69)
20:29:02     amazon-ebs: 	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:134)
20:29:02     amazon-ebs: 	at org.elasticsearch.cli.Command.main(Command.java:90)
20:29:02     amazon-ebs: 	at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:47)
20:29:02     amazon-ebs: [ERROR   ] retcode: 1
20:29:02     amazon-ebs: [ERROR   ] {'pid': 20261, 'retcode': 1, 'stderr': 'Exception in thread "main" java.lang.IllegalArgumentException: plugin [search-guard-5] is incompatible with version [5.6.2]; was designed for version [5.6.0]\n\tat org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:146)\n\tat org.elasticsearch.plugins.InstallPluginCommand.verify(InstallPluginCommand.java:501)\n\tat org.elasticsearch.plugins.InstallPluginCommand.install(InstallPluginCommand.java:570)\n\tat org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:218)\n\tat org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:202)\n\tat org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:67)\n\tat org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:134)\n\tat org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:69)\n\tat org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:134)\n\tat org.elasticsearch.cli.Command.main(Command.java:90)\n\tat org.elasticsearch.plugins.PluginCli.main(PluginCli.java:47)', 'stdout': '-> Downloading com.floragunn:search-guard-5:5.6.0-16 from maven central\n\r[ ```

**Comment by floragunncom** [comment]
https://groups.google.com/forum/#!forum/search-guard

"Please note: When a new Elasticsearch version is out, it usually takes us only a couple of days to release a matching Search Guard version. 
Don't ask for new versions here, we're releasing them as fast as we can."

**Comment by myoung34** [comment]
Thanks for the quick reply, didnt think to check the forum for a version bump

**Comment by floragunncom** [comment]
np, due to the rigid ES plugin version checks, every plugin has to have the exact same version as the ES version, otherwise, ES won't start. Nothing we can about, unfortunately ...
