### ISSUE TITLE
sgadmin doesn't work with P12/PFX certificates - even from SG Generator

### ISSUE THREAD

**Issue by dkasselmann** [floragunncom/search-guard#441]
System
- Windows Server 2016
- SearchGuard-6.1.1-20.1
- ES 6.1.1

**sgadmin fails, when PKCS12 certificates are used.**

First it was tested with two level (CA + node / CA + sgadmin) self signed certificates chains, which where exported into PFX files. The certificates were created on a Windows system using Powershell.

To cross check this behavior, also certificates from the SG cert generator where taken.
The PEM certificates where working correctly for TLS and sgadmin.
Please contact me, if the SG certificates are required for reproduction.

The PCKS12 certificates
- worked correctly for TLS
- but failed for sgadmin

Calling sgadmin with PKCS12 certificates from the SG generator

```
"C:\Program Files\Elastic\Elasticsearch\6.1.1\plugins\search-guard-6\tools\sgadmin" 
  -dg
  -nhnv 
  -cn ESDR 
  -r 
  -cd "D:\Elasticsearch\backup" 
  -ts CN=sgadmin-keystore.p12 
  -tspass 1e0c6767490e6fc2088e 
  -ks CN=sgadmin-keystore.p12 
  -kspass 1e0c6767490e6fc2088e
```

will fail with following stack trace in the cmd window:

```
Search Guard Admin v6
Will connect to localhost:9300 ... done
ERR: Cannot connect to Elasticsearch. Please refer to elasticsearch logfile for more information
Trace:
NoNodeAvailableException[None of the configured nodes are available: [{#transport#-1}{OqKanB_eRi2MAhlHQ1u2uQ}{localhost}{127.0.0.1:9300}]]
        at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:347)
        at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:245)
        at org.elasticsearch.client.transport.TransportProxyClient.execute(TransportProxyClient.java:60)
        at org.elasticsearch.client.transport.TransportClient.doExecute(TransportClient.java:360)
        at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:405)
        at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:394)
        at com.floragunn.searchguard.tools.SearchGuardAdmin.main0(SearchGuardAdmin.java:406)
        at com.floragunn.searchguard.tools.SearchGuardAdmin.main(SearchGuardAdmin.java:120)
```
The "-dg" was used to force sgadmin to write some error logs.
But no error files where written:-/

Some details regarding TLS / elasticsearch.yml

```
bootstrap.memory_lock: false
cluster.name: ESDR
http.port: 9200
node.data: true
node.ingest: true
node.master: true
node.max_local_storage_nodes: 1
node.name: SERVER001
path.data: D:\Elasticsearch\data
path.logs: D:\Elasticsearch\logs
transport.tcp.port: 9300

searchguard.enterprise_modules_enabled: false
searchguard.ssl.transport.enforce_hostname_verification: false
searchguard.ssl.http.enabled: true

searchguard.authcz.admin_dn:
  - CN=sgadmin

searchguard.ssl.transport.keystore_filepath: CN=agt-ol-dr-keystore.p12
searchguard.ssl.transport.keystore_password: dc520a2e06a483c01d72
searchguard.ssl.transport.truststore_filepath: CN=agt-ol-dr-keystore.p12
searchguard.ssl.transport.truststore_password: dc520a2e06a483c01d72

searchguard.ssl.http.keystore_filepath: CN=agt-ol-dr-keystore.p12
searchguard.ssl.http.keystore_password: dc520a2e06a483c01d72
searchguard.ssl.http.truststore_filepath: CN=agt-ol-dr-keystore.p12
searchguard.ssl.http.truststore_password: dc520a2e06a483c01d72

```

**Comment by floragunncom** [comment]
Would be great if you can attach (or mail) the "CN=agt-ol-dr-keystore.p12" and "CN=sgadmin-keystore.p12"  files (you may want to encrypt them with our pgp key https://floragunn.com/search-guard-public-key/ ). Is there anything related in the log files (on the server side)?

**Comment by floragunncom** [comment]
And we added a truststore.p12 to the SG certificate generator, so this should work:

<pre>
searchguard.ssl.transport.keystore_filepath: CN=hostname-keystore.p12
searchguard.ssl.transport.keystore_type: PKCS12
searchguard.ssl.transport.keystore_password: ...
searchguard.ssl.transport.truststore_filepath: truststore.p12
searchguard.ssl.transport.truststore_type: PKCS12
searchguard.ssl.transport.truststore_password: ...

searchguard.ssl.http.keystore_filepath: CN=hostname-keystore.p12
searchguard.ssl.http.keystore_type: PKCS12
searchguard.ssl.http.keystore_password: ...
searchguard.ssl.http.truststore_type: PKCS12
searchguard.ssl.http.truststore_filepath: truststore.jks
searchguard.ssl.http.truststore_password: ...
</pre>

<pre>
"C:\Program Files\Elastic\Elasticsearch\6.1.1\plugins\search-guard-6\tools\sgadmin" 
  -dg
  -nhnv 
  -cn ESDR 
  -r 
  -cd "D:\Elasticsearch\backup" 
  -ts truststore.p12 
  -tspass ...
  -ks CN=sgadmin-keystore.p12 
  -kspass ...
</pre>

**Comment by dkasselmann** [comment]
Dear SG-Team,

thanks a lot for your fast feedback!
I've created a new set of certs with your fixed generator.

Using sgadmin with truststore.p12 - as described above - works now fine with the p12 certificates from your generator.

Now I'll try to get that working also with Powershell generated certificates.

**Comment by dkasselmann** [comment]
Usage of self-signed certificates using Powershell still failing for sgadmin.
I've created following certificates
- root, 
- intermediate, 
- node and admin 
with a structure like SG certificate generator.
One important difference is, that in the root pfx also the private key is included.
That's not nice - but no issue at moment.

Following Powershell commands are used:

```
$pwdroot = ConvertTo-SecureString -String "changeit" -Force -AsPlainText
$pwdserver = ConvertTo-SecureString -String "changeit" -Force -AsPlainText

$rootcert = New-SelfSignedCertificate -certstorelocation cert:\localmachine\my -dnsname "sg-root" -KeyusageProperty All -KeyUsage CertSign, CRLSign, DigitalSignature -NotAfter (Get-Date).AddYears(10) -TextExtension @("2.5.29.19 = {critical} {text}ca=1&pathlength=3")
$rootcert | Export-PfxCertificate -FilePath SG-root.pfx -Password $pwdroot -Force

$signcert = New-SelfSignedCertificate -certstorelocation cert:\localmachine\my -dnsname "sg-signing" -Signer $rootcert -KeyUsage CertSign, CRLSign -NotAfter (Get-Date).AddYears(10) -TextExtension @("2.5.29.19 = {critical} {text}ca=1&pathlength=0")
$signcert | Export-PfxCertificate -FilePath SG-signing.pfx -Password $pwdserver -Force

$servercert = New-SelfSignedCertificate -certstorelocation cert:\localmachine\my -dnsname "sg-node" -Signer $signcert -KeyUsage KeyEncipherment,DigitalSignature -NotAfter (Get-Date).AddYears(10)
$servercert | Export-PfxCertificate -FilePath SG-node.pfx -Password $pwdserver -Force

$admincert = New-SelfSignedCertificate -certstorelocation cert:\localmachine\my -dnsname "sgadmin" -Signer $signcert -KeyUsage KeyEncipherment,DigitalSignature -NotAfter (Get-Date).AddYears(10)
$admincert | Export-PfxCertificate -FilePath SG-admin.pfx -Password $pwdserver -Force
```
ZIP with certificates:
[Cert-Chain-with-Powershell.zip](https://github.com/floragunncom/search-guard/files/1673855/Cert-Chain-with-Powershell.zip)

TLS is working fine with:

```
searchguard.enterprise_modules_enabled: false
searchguard.ssl.transport.enforce_hostname_verification: false
searchguard.ssl.http.enabled: true
searchguard.authcz.admin_dn:
  - CN=sgadmin

searchguard.ssl.transport.keystore_filepath: SG-node.pfx
searchguard.ssl.transport.keystore_password: changeit
searchguard.ssl.transport.truststore_filepath: SG-root.pfx
searchguard.ssl.transport.truststore_password: changeit

searchguard.ssl.http.keystore_filepath: SG-node.pfx
searchguard.ssl.http.keystore_password: changeit
searchguard.ssl.http.truststore_filepath: SG-root.pfx
searchguard.ssl.http.truststore_password: changeit
```

sgadmin is failing:
`"C:\Program Files\Elastic\Elasticsearch\6.1.1\plugins\search-guard-6\tools\sgadmin"  -dg -nhnv -cn ESDR -w -ts D:\Elasticsearch\config\SG-admin.pfx -tspass changeit -tst PKCS12 -ks D:\Elasticsearch\config\SG-admin.pfx -kspass changeit -kst PKCS12
`
CMD Window:

```
Search Guard Admin v6
Will connect to localhost:9300 ... done
ERR: Cannot connect to Elasticsearch. Please refer to elasticsearch logfile for more information
Trace:
NoNodeAvailableException[None of the configured nodes are available: [{#transport#-1}{36t0-QPNQgWygiB4nGswVA}{localhost}{127.0.0.1:9300}]]
        at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:347)
        at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:245)
        at org.elasticsearch.client.transport.TransportProxyClient.execute(TransportProxyClient.java:60)
        at org.elasticsearch.client.transport.TransportClient.doExecute(TransportClient.java:360)
        at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:405)
        at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:394)
        at com.floragunn.searchguard.tools.SearchGuardAdmin.main0(SearchGuardAdmin.java:406)
        at com.floragunn.searchguard.tools.SearchGuardAdmin.main(SearchGuardAdmin.java:120)
```

ES.log:

```
2018-01-29T15:08:30,420][ERROR][c.f.s.s.t.SearchGuardSSLNettyTransport] [WADOLDR001] SSL Problem Received fatal alert: internal_error
javax.net.ssl.SSLException: Received fatal alert: internal_error
    at sun.security.ssl.Alerts.getSSLException(Unknown Source) ~[?:?]
    at sun.security.ssl.SSLEngineImpl.fatal(Unknown Source) ~[?:?]
    at sun.security.ssl.SSLEngineImpl.fatal(Unknown Source) ~[?:?]
    at sun.security.ssl.SSLEngineImpl.recvAlert(Unknown Source) ~[?:?]
    at sun.security.ssl.SSLEngineImpl.readRecord(Unknown Source) ~[?:?]
    at sun.security.ssl.SSLEngineImpl.readNetRecord(Unknown Source) ~[?:?]
    at sun.security.ssl.SSLEngineImpl.unwrap(Unknown Source) ~[?:?]
    at javax.net.ssl.SSLEngine.unwrap(Unknown Source) ~[?:1.8.0_162]
    at io.netty.handler.ssl.SslHandler$SslEngineType$3.unwrap(SslHandler.java:255) ~[netty-handler-4.1.13.Final.jar:4.1.13.Final]
    at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1162) ~[netty-handler-4.1.13.Final.jar:4.1.13.Final]
    at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1084) ~[netty-handler-4.1.13.Final.jar:4.1.13.Final]
    at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489) ~[netty-codec-4.1.13.Final.jar:4.1.13.Final]
    at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428) ~[netty-codec-4.1.13.Final.jar:4.1.13.Final]
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) ~[netty-codec-4.1.13.Final.jar:4.1.13.Final]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:544) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:498) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-common-4.1.13.Final.jar:4.1.13.Final]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_162]

```

**Whats is missing in the admin certificate to be accepted by sgadmin?**

**Comment by floragunncom** [comment]
* Do you use Oracle JDK or OpenJDK?
* Did you start a single node or more than one node? Because the node certificate seems to lack the SG OID (or nodes_dn must be configured instead) so you should not be able to form a cluster with you certificates.
* Remove the private key SG-root.pfx, the entry in the keystore must be of type "trusted cert", currently its of type "keypair/certificate"

**Comment by dkasselmann** [comment]
>Do you use Oracle JDK or OpenJDK?
JRE 8u162 64 bit

>Did you start a single node or more than one node?
One single node.

>Because the node certificate seems to lack the SG OID (or nodes_dn must be configured instead)
>so you should not be able to form a cluster with you certificates.
That's okay at moment,

>Remove the private key SG-root.pfx, 
Need your help - how can that be done /wo OpenSLL?
Powershell can export certs /wo key only as e.g. CER file. PFX contains always the key.

>the entry in the keystore must be of type "trustedCertEntry", currently its of type "PrivateKeyEntry"
No idea, how this could be done with Powershell.

>check with keytool -list -v -keystore SG-root.pfx
Yes, I can the see value for "Entry Type".

Seems, that SG TLS can work with Powershell generated certs, but sgadmin has more complex requirements regarding its admin certs. Not sure, if this can be reached with Windows default tools.

**Okay, lets go back to then inital idea: what's the easiest and working solution 
- to create a self signed node and admin cert and
- to get this both certs working in SG?
Don't care about any considerations regarding "untrusted" certificate aspects.**

I also tried to use keytool to create self signed certs /wo any chain included - just a simple plain certificates with its key in one JKS file.
This works fine for TLS, but sgadmin don't liked it and failed.

Is there a was to get sgadmin running with such a simple approach?

Maybe SG checks, if admin certificates has the same ca as the TLS certificate.
Would it help to set "admin_dn" to the subject of the TLS certificate?
(Not recommended - but looking for a way to get an easy solution...)

Thanks a lot in advance!

**Comment by floragunncom** [comment]
sgadmin does not have special requirements regarding SSL certificates compared to the rest of Search Guard. I think that with you current SG-root.pfx more than a one node cluster would also not be working.

Maybe the "Export-Certificate" (or "Remove-Item") command can help to only export the certificate but not the private key from  SG-root.pfx and SG-signing.pfx (i have no windows box to test it) like described here http://blog.davidchristiansen.com/2016/09/howto-create-self-signed-certificates-with-powershell/

**Comment by dkasselmann** [comment]
> sgadmin does not have special requirements regarding SSL certificates compared to the rest of Search Guard

very good - promising.

> I think that with you current SG-root.pfx more than a one node cluster would also not be working.

Maybe - but that's an issue at momment

> Maybe the "Export-Certificate" (or "Remove-Item") command can help to only export the certificate but not the private key from SG-root.pfx and SG-signing.pfx

"Export-Certificate" will only export the public parts of the certificate as CRT file.
But SG requires to have a P12 file as truststore, and that means a PFX file had to be exported.
The default definition of PFX contains the public parts as well as the private key.

> (i have no windows box to test it)

I can do the testing. 
But a VM with e. g. WS 2016 could be helpful to observe the different behavior of certs in Windows.

> like described here http://blog.davidchristiansen.com/2016/09/howto-create-self-signed-certificates-with-powershell/

Indeed - this nice blog was also my starting point:-)
The PXF certs where created following that instructions.
Please consider, that here the root cert is exported as CRT file and not as PFX file.

It would be great, if also a CRT file with the root certificate could be used as truststore in SG.
For this case, the password for the truststore file can be omitted in the configutation (like in PEM scenario).

E.g. for TLS:

```
searchguard.ssl.transport.keystore_filepath: SG-node.pfx
searchguard.ssl.transport.keystore_password: changeit
searchguard.ssl.transport.truststore_filepath: SG-root.crt
```

E.g. for sgadmin:

`sgadmin -nhnv -cn ESDR -w -ts SG-root.crt -ks D:\Elasticsearch\config\SG-admin.pfx -kspass changeit`

**Comment by floragunncom** [comment]
@dkasselmann can we close this?

Maybe the new Search Guard offline TLS tool (https://github.com/floragunncom/search-guard-tlstool) can help here.
