### ISSUE TITLE
support dns server name in certificate, IP Address SAN fails

### ISSUE THREAD

**Issue by tbennett6421** [floragunncom/search-guard#442]
Search Guard version
* com.floragunn:search-guard-5:5.6.4-16

Elasticsearch version
* Version: 5.6.4, Build: 8bbedf5/2017-10-31T18:55:38.105Z, JVM: 1.8.0_161

JVM version
* java version "1.8.0_161"
* Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
* Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)

Operating system version
* Distributor ID: Ubuntu
* Description:    Ubuntu 16.04.3 LTS
* Release:        16.04
* Codename:       xenial

Number of nodes in your cluster: 3

Description of the bug
* Cluster will not form when the following options are set
  *  searchguard.ssl.transport.enabled: true
  *  searchguard.ssl.transport.enforce_hostname_verification: true
* this appears to be related to #153 

Turning hostname verification off lets the cluster form and enter a green state. We've added our Root Certificate Authority to the java keystore on all three nodes

Excert from log
```
[2018-01-25T16:37:05,196][ERROR][c.f.s.s.t.SearchGuardSSLNettyTransport] [siem-prod-elk3] SSL Problem General SSLEngine problem
javax.net.ssl.SSLHandshakeException: General SSLEngine problem
        at sun.security.ssl.Handshaker.checkThrown(Handshaker.java:1529) ~[?:?]
        at sun.security.ssl.SSLEngineImpl.checkTaskThrown(SSLEngineImpl.java:535) ~[?:?]
        at sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:813) ~[?:?]
        at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:781) ~[?:?]
        at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:624) ~[?:1.8.0_161]
        at io.netty.handler.ssl.SslHandler$SslEngineType$3.unwrap(SslHandler.java:255) ~[netty-handler-4.1.13.Final.jar:4.1.13.Final]
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1162) ~[netty-handler-4.1.13.Final.jar:4.1.13.Final]
        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1084) ~[netty-handler-4.1.13.Final.jar:4.1.13.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489) ~[netty-codec-4.1.13.Final.jar:4.1.13.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428) ~[netty-codec-4.1.13.Final.jar:4.1.13.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) ~[netty-codec-4.1.13.Final.jar:4.1.13.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:544) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:498) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-common-4.1.13.Final.jar:4.1.13.Final]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
Caused by: javax.net.ssl.SSLHandshakeException: General SSLEngine problem
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:192) ~[?:?]
        at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1728) ~[?:?]
        at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:330) ~[?:?]
        at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:322) ~[?:?]
        at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1614) ~[?:?]
        at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216) ~[?:?]
        at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1052) ~[?:?]
        at sun.security.ssl.Handshaker$1.run(Handshaker.java:992) ~[?:?]
        at sun.security.ssl.Handshaker$1.run(Handshaker.java:989) ~[?:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_161]
        at sun.security.ssl.Handshaker$DelegatedTask.run(Handshaker.java:1467) ~[?:?]
        at io.netty.handler.ssl.SslHandler.runDelegatedTasks(SslHandler.java:1301) ~[?:?]
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1214) ~[?:?]
        ... 18 more
Caused by: java.security.cert.CertificateException: No subject alternative names matching IP address 10.0.13.16 found
        at sun.security.util.HostnameChecker.matchIP(HostnameChecker.java:168) ~[?:?]
        at sun.security.util.HostnameChecker.match(HostnameChecker.java:94) ~[?:?]
        at sun.security.ssl.X509TrustManagerImpl.checkIdentity(X509TrustManagerImpl.java:455) ~[?:?]
        at sun.security.ssl.X509TrustManagerImpl.checkIdentity(X509TrustManagerImpl.java:436) ~[?:?]
        at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:252) ~[?:?]
        at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:136) ~[?:?]
        at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1601) ~[?:?]
        at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216) ~[?:?]
        at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1052) ~[?:?]
        at sun.security.ssl.Handshaker$1.run(Handshaker.java:992) ~[?:?]
        at sun.security.ssl.Handshaker$1.run(Handshaker.java:989) ~[?:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_161]
        at sun.security.ssl.Handshaker$DelegatedTask.run(Handshaker.java:1467) ~[?:?]
        at io.netty.handler.ssl.SslHandler.runDelegatedTasks(SslHandler.java:1301) ~[?:?]
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1214) ~[?:?]
        ... 18 more
```

**Comment by floragunncom** [comment]
Pls provide your elasticsearch.yml

**Comment by tbennett6421** [comment]
```
cluster.name: prod-elk
node.name: siem-prod-elk1
bootstrap.memory_lock: true
network.host: 0.0.0.0
discovery.zen.ping.unicast.hosts: ["siem-prod-elk1", "siem-prod-elk2", "siem-prod-elk3"]
discovery.zen.minimum_master_nodes: 2
gateway.expected_nodes: 3
gateway.recover_after_time: 15m

searchguard.ssl.transport.enabled: true
searchguard.ssl.transport.enforce_hostname_verification: false
searchguard.ssl.transport.resolve_hostname: false
searchguard.ssl.transport.pemkey_filepath: pki/node.key.pkcs8
searchguard.ssl.transport.pemkey_password: "redacted"
searchguard.ssl.transport.pemcert_filepath: pki/siem-prod-elk1.cer
searchguard.ssl.transport.pemtrustedcas_filepath: pki/chain.pem

searchguard.ssl.http.enabled: true
searchguard.ssl.http.pemkey_filepath: pki/node.key.pkcs8
searchguard.ssl.http.pemkey_password: "redacted"
searchguard.ssl.http.pemcert_filepath: pki/siem-prod-elk1.cer
searchguard.ssl.http.pemtrustedcas_filepath: pki/chain.pem

searchguard.authcz.admin_dn:
  - CN=SGAdmin,O=City of Columbia MO,L=Columbia,ST=Missouri,C=US
```

**Comment by tbennett6421** [comment]
That is the current production config. I've tried using 

```
searchguard.ssl.transport.enforce_hostname_verification: true
searchguard.ssl.transport.resolve_hostname: false
```
```
searchguard.ssl.transport.enforce_hostname_verification: true
searchguard.ssl.transport.resolve_hostname: true
```
and did not get these to work

**Comment by floragunncom** [comment]
you will need to set network.host to your hostname, like

<pre>
network.host: siem-prod-elk1
</pre>
or at least the publish_host like described here https://github.com/floragunncom/search-guard-ssl/issues/66

If this is also not working try adding

<pre>
searchguard.ssl.transport.enable_openssl_if_available: false
</pre>

**Comment by tbennett6421** [comment]
Thanks, setting the network.host appears to be working
