### ISSUE TITLE
Unable to load custom backends because "enterprise modules are disabled"

### ISSUE THREAD

**Issue by bw498c** [floragunncom/search-guard#463]
Searchguard 6.1.2-20.1
Elasticsearch 6.1.2
JVM 1.8.0_162
1 node cluster

We are getting this error when we load our back-end classes in Searchguard.

```
[2018-03-16T06:39:23,605][ERROR][c.f.s.a.BackendRegistry  ] Unable to initialize auth domain authentication_aaf due to ElasticsearchException[Can not load 'com.att.searchguard.auth.aaf.AafAuthenticationBackend' because enterprise modules are disabled]
org.elasticsearch.ElasticsearchException: Can not load 'com.att.searchguard.auth.aaf.AafAuthenticationBackend' because enterprise modules are disabled
	at com.floragunn.searchguard.support.ReflectionHelper.instantiateAAA(ReflectionHelper.java:171) ~[search-guard-aaf-6.1.2-20.1.3.jar:?]
	at com.floragunn.searchguard.auth.BackendRegistry.newInstance(BackendRegistry.java:667) ~[search-guard-aaf-6.1.2-20.1.3.jar:?]
	at com.floragunn.searchguard.auth.BackendRegistry.onChange(BackendRegistry.java:229) [search-guard-aaf-6.1.2-20.1.3.jar:?]
	at com.floragunn.searchguard.configuration.IndexBaseConfigurationRepository.notifyAboutChanges(IndexBaseConfigurationRepository.java:361) [search-guard-aaf-6.1.2-20.1.3.jar:?]
	at com.floragunn.searchguard.configuration.IndexBaseConfigurationRepository.reloadConfiguration(IndexBaseConfigurationRepository.java:311) [search-guard-aaf-6.1.2-20.1.3.jar:?]
	at com.floragunn.searchguard.action.configupdate.TransportConfigUpdateAction.nodeOperation(TransportConfigUpdateAction.java:113) [search-guard-aaf-6.1.2-20.1.3.jar:?]
	at com.floragunn.searchguard.action.configupdate.TransportConfigUpdateAction.nodeOperation(TransportConfigUpdateAction.java:47) [search-guard-aaf-6.1.2-20.1.3.jar:?]
	at org.elasticsearch.action.support.nodes.TransportNodesAction.nodeOperation(TransportNodesAction.java:140) [elasticsearch-6.1.2.jar:6.1.2]
	at org.elasticsearch.action.support.nodes.TransportNodesAction$NodeTransportHandler.messageReceived(TransportNodesAction.java:262) [elasticsearch-6.1.2.jar:6.1.2]
	at org.elasticsearch.action.support.nodes.TransportNodesAction$NodeTransportHandler.messageReceived(TransportNodesAction.java:258) [elasticsearch-6.1.2.jar:6.1.2]
	at com.floragunn.searchguard.ssl.transport.SearchGuardSSLRequestHandler.messageReceivedDecorate(SearchGuardSSLRequestHandler.java:170) [search-guard-ssl-6.1.2-25.0.jar:6.1.2-25.0]
	at com.floragunn.searchguard.transport.SearchGuardRequestHandler.messageReceivedDecorate(SearchGuardRequestHandler.java:121) [search-guard-aaf-6.1.2-20.1.3.jar:?]
	at com.floragunn.searchguard.ssl.transport.SearchGuardSSLRequestHandler.messageReceived(SearchGuardSSLRequestHandler.java:92) [search-guard-ssl-6.1.2-25.0.jar:6.1.2-25.0]
	at com.floragunn.searchguard.SearchGuardPlugin$6$1.messageReceived(SearchGuardPlugin.java:525) [search-guard-aaf-6.1.2-20.1.3.jar:?]
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:66) [elasticsearch-6.1.2.jar:6.1.2]
	at org.elasticsearch.transport.TransportService$7.doRun(TransportService.java:652) [elasticsearch-6.1.2.jar:6.1.2]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:637) [elasticsearch-6.1.2.jar:6.1.2]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-6.1.2.jar:6.1.2]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_162]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_162]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
```
Enterprise modules are disabled because we do not use them - we only use the opensource modules and the modules we have developed ourselves.

This has been working with previous searchguard releases (5.6.0 is our last working version)

This is preventing us from using Searchguard in our deployments

**Comment by floragunncom** [comment]
The custom modules in SG 5.x were never a officially documented and supported interface/functionality.

For SG 6 we decided to make this officially supported (and stable) but its now a enterprise feature which requires a license.

For details pls. refer to 

* https://docs.search-guard.com/latest/custom-authentication-modules#custom-authentication-modules
* https://github.com/floragunncom/search-guard/blob/master/src/main/java/com/floragunn/searchguard/auth/HTTPAuthenticator.java#L42
* https://github.com/floragunncom/search-guard/blob/master/src/main/java/com/floragunn/searchguard/auth/AuthenticationBackend.java#L40
