### ISSUE TITLE
sgadmin fails to reload sgconfig files like sg_action_groups.yml, sg_internal_users.yml etc.

### ISSUE THREAD

**Issue by Samreen140592** [floragunncom/search-guard#498]
ES client version: 5.4.2
Search Guard version: 5.4.2-15
Java(TM) SE Runtime Environment: jdk1.8.0_144
Virtual Machine Specification, user.dir=C:\elasticsearch-5.4.2\plugins\search-guard-5\tools,
OS =Windows Server 2012 R2
Number of nodes : 1

I installed and configured Search Guard and it was working fine, After some months i had to change some configurations of sgconfigs like i added few roles and few users in sg_internal_users.yml, after completing changes i ran command
sgadmin.bat -ts truststore.jks -ks kirk.jks  \ -cd ../sgconfig -icl - nhnv
to reload sgconfig files but it caused the following error.
`ClusterHealthRequest:
NoNodeAvailableException[None of the configured nodes are available: [{#transport#-1}{-HbTiEtCSbqYCzqwNe8vMg}{localhost}{127.0.0.1:9300}]]
	at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:348)
	at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:246)
	at org.elasticsearch.client.transport.TransportProxyClient.execute(TransportProxyClient.java:59)
	at org.elasticsearch.client.transport.TransportClient.doExecute(TransportClient.java:366)
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:408)
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:397)
	at org.elasticsearch.client.support.AbstractClient$ClusterAdmin.execute(AbstractClient.java:724)
	at org.elasticsearch.client.support.AbstractClient$ClusterAdmin.health(AbstractClient.java:746)
	at com.floragunn.searchguard.tools.SearchGuardAdmin.generateDiagnoseTrace(SearchGuardAdmin.java:740)
	at com.floragunn.searchguard.tools.SearchGuardAdmin.main0(SearchGuardAdmin.java:421)
	at com.floragunn.searchguard.tools.SearchGuardAdmin.main(SearchGuardAdmin.java:109)
`
full diag_trace is below:

[searchguard_demo.log](https://github.com/floragunncom/search-guard/files/2021907/searchguard_demo.log)
[sgadmin_diag_trace_2018-May-21_02-51-27.txt](https://github.com/floragunncom/search-guard/files/2021908/sgadmin_diag_trace_2018-May-21_02-51-27.txt)

[elasticsearch.txt](https://github.com/floragunncom/search-guard/files/2021909/elasticsearch.txt)

**Comment by floragunncom** [comment]
What certificates you are using? Note that the demo certificates recently expired. See https://groups.google.com/d/msg/search-guard/VJQqzxQXYFE/KO4QldviCwAJ and https://downloads.search-guard.com/tls-demo-certificates

**Comment by Samreen140592** [comment]
I downloaded certificates and placed them in appropriate location and changed elasticsearch.yml 
Now if i run elasticsearch it gives me this
log file is attached
[elasticsearch.log](https://github.com/floragunncom/search-guard/files/2022223/elasticsearch.log)

**Comment by Samreen140592** [comment]
i commented out these two line in my elasticsearch.yml file now its working fine

searchguard.allow_unsafe_democertificates: true
searchguard.allow_default_init_sgindex: true
