### ISSUE TITLE
Got ElasticsearchSecurityException occured: no permissions for indices:admin/exists when replacing certificate generated by Offline TLS Tool

### ISSUE THREAD

**Issue by Yick-Chung** [floragunncom/search-guard#521]
Hi,

I am using Elasticsearch 5.4.2 with 2 Elasticsearch nodes and Search Guard plugin 5.4.2-15.
Since I don't have any security concern, I use the default certificate for current environment.
Recently, I found that the certificate bundled in the plugin has been expired and I tried to replace it.

I found the Offline TLS Tools v1.5 on your site and use it to generate the new certificate.
I use same certificate for all elasticsearch nodes and a client for sgadmin.
The cluster resume normally but I found sgadmin command does not work anymore.

When I tried to add user into the cluster, I got the error below
It seems the same error on 
[https://github.com/floragunncom/search-guard/issues/366](url)
I tried to follow the step but no luck.
```
> sudo /usr/share/elasticsearch/plugins/search-guard-5/tools/sgadmin.sh -cd /usr/share/elasticsearch/plugins/search-guard-5/sgconfig -icl -key /etc/elasticsearch/kirk.key -cacert /etc/elasticsearch/root-ca.pem -cert /etc/elasticsearch/kirk.pem -nhnv -h 192.168.200.202
WARNING: JAVA_HOME not set, will use /usr/bin/java
Search Guard Admin v5
Will connect to 192.168.200.202:9300 ... done

### LICENSE NOTICE Search Guard ###

If you use one or more of the following features in production
make sure you have a valid Search Guard license
(See https://floragunn.com/searchguard-validate-license)

* Kibana Multitenancy
* LDAP authentication/authorization
* Active Directory authentication/authorization
* REST Management API
* JSON Web Token (JWT) authentication/authorization
* Kerberos authentication/authorization
* Document- and Fieldlevel Security (DLS/FLS)
* Auditlogging

In case of any doubt mail to <sales@floragunn.com>
###################################
Contacting elasticsearch cluster 'elasticsearch' and wait for YELLOW clusterstate ...
Clustername: elasticsearchrnd
Clusterstate: YELLOW
Number of nodes: 2
Number of data nodes: 2
ERR: An unexpected ElasticsearchSecurityException occured: no permissions for indices:admin/exists
Trace:
ElasticsearchSecurityException[no permissions for indices:admin/exists]
        at com.floragunn.searchguard.filter.SearchGuardFilter.apply(SearchGuardFilter.java:147)
        at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:168)
        at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:142)
        at org.elasticsearch.action.support.HandledTransportAction$TransportHandler.messageReceived(HandledTransportAction.java:64)
        at org.elasticsearch.action.support.HandledTransportAction$TransportHandler.messageReceived(HandledTransportAction.java:54)
        at com.floragunn.searchguard.ssl.transport.SearchGuardSSLRequestHandler.messageReceivedDecorate(SearchGuardSSLRequestHandler.java:177)
        at com.floragunn.searchguard.transport.SearchGuardRequestHandler.messageReceivedDecorate(SearchGuardRequestHandler.java:191)
        at com.floragunn.searchguard.ssl.transport.SearchGuardSSLRequestHandler.messageReceived(SearchGuardSSLRequestHandler.java:139)
        at com.floragunn.searchguard.SearchGuardPlugin$2$1.messageReceived(SearchGuardPlugin.java:336)
        at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69)
        at org.elasticsearch.transport.TcpTransport$RequestHandler.doRun(TcpTransport.java:1555)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
        at org.elasticsearch.common.util.concurrent.EsExecutors$1.execute(EsExecutors.java:110)
        at org.elasticsearch.transport.TcpTransport.handleRequest(TcpTransport.java:1512)
        at org.elasticsearch.transport.TcpTransport.messageReceived(TcpTransport.java:1396)
        at org.elasticsearch.transport.netty4.Netty4MessageChannelHandler.channelRead(Netty4MessageChannelHandler.java:74)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:297)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:413)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1267)
        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1078)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:544)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:498)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
        at java.lang.Thread.run(Thread.java:748)
```
Attached my configuration to generate certificate and elasticsearch configuration

tlsconfig.yml
```
###
### Self-generated certificate authority
### 
# 
# If you want to create a new certificate authority, you must specify its parameters here. 
# You can skip this section if you only want to create CSRs
#
ca:
   root:
      # The distinguished name of this CA. You must specify a distinguished name.   
      dn: CN=root.ca.example.com,OU=CA,O=Example Com\, Inc.,DC=example,DC=com

      # The size of the generated key in bits
      keysize: 2048

      # The validity of the generated certificate in days from now
      validityDays: 365000
      
      # Password for private key
      #   Possible values: 
      #   - auto: automatically generated password, returned in config output; 
      #   - none: unencrypted private key; 
      #   - other values: other values are used directly as password   
      pkPassword: none
      
      # The name of the generated files can be changed here
      file: root-ca.pem
      
   # If you want to use an intermediate certificate as signing certificate,
   # please specify its parameters here. This is optional. If you remove this section,
   # the root certificate will be used for signing.         
   intermediate:
      # The distinguished name of this CA. You must specify a distinguished name.
      dn: CN=signing.ca.example.com,OU=CA,O=Example Com\, Inc.,DC=example,DC=com
   
      # The size of the generated key in bits   
      keysize: 2048
      
      # The validity of the generated certificate in days from now      
      validityDays: 365000
  
      pkPassword: none
            
      # If you have a certificate revocation list, you can specify its distribution points here      
      crlDistributionPoints: URI:https://raw.githubusercontent.com/floragunncom/unittest-assets/master/revoked.crl

### 
### Default values and global settings
###
defaults:

      # The validity of the generated certificate in days from now
      validityDays: 365000
      
      # Password for private key
      #   Possible values: 
      #   - auto: automatically generated password, returned in config output; 
      #   - none: unencrypted private key; 
      #   - other values: other values are used directly as password   
      pkPassword: none
      
      # Specifies to recognize legitimate nodes by the distinguished names
      # of the certificates. This can be a list of DNs, which can contain wildcards.
      # Furthermore, it is possible to specify regular expressions by
      # enclosing the DN in //. 
      # Specification of this is optional. The tool will always include
      # the DNs of the nodes specified in the nodes section.            
      #nodesDn:
      #- "CN=*.example.com,OU=Ops,O=Example Com\\, Inc.,DC=example,DC=com"
      # - 'CN=node.other.com,OU=SSL,O=Test,L=Test,C=DE'
      # - 'CN=*.example.com,OU=SSL,O=Test,L=Test,C=DE'
      # - 'CN=elk-devcluster*'
      # - '/CN=.*regex/' 

      # If you want to use OIDs to mark legitimate node certificates, 
      # the OID can be included in the certificates by specifying the following
      # attribute
      
      # nodeOid: "1.2.3.4.5.5"

      # The length of auto generated passwords            
      generatedPasswordLength: 12
      
      # Set this to true in order to generate config and certificates for 
      # the HTTP interface of nodes
      httpsEnabled: true
      
      # Set this to true in order to re-use the node transport certificates
      # for the HTTP interfaces. Only recognized if httpsEnabled is true
      
      # reuseTransportCertificatesForHttp: false
      
      # Set this to true to enable hostname verification
      #verifyHostnames: false
      
      # Set this to true to resolve hostnames
      #resolveHostnames: false
      
      
###
### Nodes
###
#
# Specify the nodes of your ES cluster here
#      
nodes:
  - name: node1
    dn: CN=node1.example.com,OU=Ops,O=Example Com\, Inc.,DC=example,DC=com
    dns: node1.example.com

###
### Clients
###
#
# Specify the clients that shall access your ES cluster with certificate authentication here
#
# At least one client must be an admin user (i.e., a super-user). Admin users can
# be specified with the attribute admin: true    
#        
clients:
  - name: kirk
    dn: CN=kirk,OU=client,O=client,L=test,C=de
    admin: true
```

Elasticsearch configuration
```
# ======================== Elasticsearch Configuration =========================
#
# NOTE: Elasticsearch comes with reasonable defaults for most settings.
#       Before you set out to tweak and tune the configuration, make sure you
#       understand what are you trying to accomplish and the consequences.
#
# The primary way of configuring a node is via this file. This template lists
# the most important settings you may want to configure for a production cluster.
#
# Please consult the documentation for further information on configuration options:
# https://www.elastic.co/guide/en/elasticsearch/reference/index.html
#
# ---------------------------------- Cluster -----------------------------------
#
# Use a descriptive name for your cluster:
#
#cluster.name: elastic-search-guard
cluster.name: elasticsearchrnd
#
# ------------------------------------ Node ------------------------------------
#
# Use a descriptive name for the node:
#
node.name: opcanalyt02
#
# Add custom attributes to the node:
#
#node.attr.rack: r1
#
# ----------------------------------- Paths ------------------------------------
#
# Path to directory where to store the data (separate multiple locations by comma):
#
#path.data: /path/to/data
path.data: /data/elasticsearch
#
# Path to log files:
#
#path.logs: /path/to/logs
#
# ----------------------------------- Memory -----------------------------------
#
# Lock the memory on startup:
#
#bootstrap.memory_lock: true
bootstrap.system_call_filter: false
#
# Make sure that the heap size is set to about half the memory available
# on the system and that the owner of the process is allowed to use this
# limit.
#
# Elasticsearch performs poorly when the system is swapping the memory.
#
# ---------------------------------- Network -----------------------------------
#
# Set the bind address to a specific IP (IPv4 or IPv6):
#
network.host: 192.168.200.202
network.publish_host: opcanalyt02
#
# Set a custom port for HTTP:
#
#http.port: 9200
#
# For more information, consult the network module documentation.
#
# --------------------------------- Discovery ----------------------------------
#
# Pass an initial list of hosts to perform discovery when new node is started:
# The default list of hosts is ["127.0.0.1", "[::1]"]
#
discovery.zen.ping.unicast.hosts: ["opcanalyt02", "opcanalyt03"]
#
# Prevent the "split brain" by configuring the majority of nodes (total number of master-eligible nodes / 2 + 1):
#
#discovery.zen.minimum_master_nodes: 2
#
# For more information, consult the zen discovery module documentation.
#
# ---------------------------------- Gateway -----------------------------------
#
# Block initial recovery after a full cluster restart until N nodes are started:
#
#gateway.recover_after_nodes: 3
#
# For more information, consult the gateway module documentation.
#
# ---------------------------------- Various -----------------------------------
#
# Require explicit names when deleting indices:
#
#action.destructive_requires_name: true
xpack.security.enabled: false
xpack.graph.enabled: false
xpack.watcher.enabled: false
xpack.ml.enabled: false

######## Start Search Guard Demo Configuration ########
#searchguard.ssl.transport.keystore_filepath: keystore.jks
#searchguard.ssl.transport.truststore_filepath: truststore.jks
searchguard.ssl.transport.pemkey_filepath: node1.key
searchguard.ssl.transport.pemcert_filepath: node1.pem
searchguard.ssl.transport.pemtrustedcas_filepath: root-ca.pem
searchguard.ssl.transport.enforce_hostname_verification: false
#searchguard.ssl.http.enabled: true
#searchguard.ssl.http.keystore_filepath: keystore.jks
#searchguard.ssl.http.truststore_filepath: truststore.jks
searchguard.nodes_dn:
  - '*'
searchguard.authcz.admin_dn:
  - CN=kirk,OU=client,O=client,L=test,C=de
######## End Search Guard Demo Configuration ########
```

kirk.pem
```
> openssl x509 -text -in kirk.pem
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: 1531315828261 (0x16489893625)
    Signature Algorithm: sha256WithRSAEncryption
        Issuer: DC=com, DC=example, O=Example Com, Inc., OU=CA, CN=signing.ca.example.com
        Validity
            Not Before: Jul 11 13:30:32 2018 GMT
            Not After : Nov 11 13:30:32 3017 GMT
        Subject: C=de, L=test, O=client, OU=client, CN=kirk
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (2048 bit)
                Modulus:
                    00:86:76:b8:f8:66:48:48:bc:2e:89:e1:05:17:7b:
                    b8:ee:8d:7d:ba:bf:f1:47:12:f0:8c:e7:1c:13:a0:
                    f6:92:5a:a0:bc:78:c7:90:2f:2f:38:df:06:65:f6:
                    2e:0e:66:af:c2:db:4d:0b:13:c3:ea:ed:1e:39:11:
                    a2:3b:2a:df:8e:03:61:07:fb:23:6c:cb:40:3d:da:
                    b5:e3:b2:77:63:d9:36:b8:ea:66:fd:0f:a3:81:97:
                    cc:bf:e1:a8:8e:c7:59:d5:9f:59:ed:3f:d6:c6:d1:
                    9c:e5:c7:f5:4e:de:92:49:f8:19:fd:ec:e8:56:c5:
                    29:f3:ba:2c:24:25:0b:b9:c3:b7:46:27:44:c2:8b:
                    ef:e8:9b:0d:63:8e:e7:b9:c8:b2:86:55:f5:d8:e4:
                    56:f5:ce:7c:33:a5:53:57:62:1a:a1:5c:7f:a1:70:
                    c8:66:64:2a:46:31:16:dc:31:7f:2c:23:51:ba:ec:
                    22:e4:e7:4d:b8:ca:f1:93:e7:33:49:50:fe:8a:cc:
                    1f:c7:8e:ee:e1:e8:45:c1:2f:91:e4:b3:24:00:c1:
                    f7:c1:74:f9:25:fc:9c:f0:d7:65:9c:cc:cb:6b:45:
                    eb:ee:12:e9:69:c0:5d:d9:02:28:a5:40:b8:d8:d0:
                    c5:64:d7:a6:8f:de:c4:04:fa:63:b3:77:02:3a:cd:
                    f4:c9
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Authority Key Identifier:
                keyid:7E:53:C4:69:FA:5A:63:94:19:DB:FA:C9:A1:2D:24:BE:A2:84:D2:C4
                DirName:/DC=com/DC=example/O=Example Com, Inc./OU=CA/CN=root.ca.example.com
                serial:02

            X509v3 Subject Key Identifier:
                E5:4D:E8:D1:90:1B:05:AC:0C:F3:E8:52:5A:E7:22:8A:F0:ED:CC:46
            X509v3 Basic Constraints: critical
                CA:FALSE
            X509v3 Key Usage: critical
                Digital Signature, Non Repudiation, Key Encipherment
            X509v3 Extended Key Usage: critical
                TLS Web Client Authentication
    Signature Algorithm: sha256WithRSAEncryption
         b9:3a:c2:89:85:2e:cf:f2:6b:b6:40:f9:2d:f1:a2:c1:51:a1:
         20:95:da:11:f1:89:c4:9a:5b:b6:fa:91:41:a5:32:3f:ad:69:
         05:e8:ff:b7:0c:50:f7:86:a8:60:65:93:b6:fc:e1:30:2c:9c:
         ed:a2:99:04:9e:4d:e6:55:10:1a:6a:bd:cd:b3:11:6e:66:9a:
         18:bf:a9:bd:05:be:a8:b5:16:c5:27:ec:a5:69:36:6f:0a:c6:
         58:b6:28:db:7b:f9:af:cb:b5:e8:5a:fb:f9:47:ba:4e:88:5a:
         44:5e:fe:97:0f:65:13:4c:fc:49:f3:07:c3:2c:fb:8f:65:04:
         bd:10:0e:22:6d:97:55:08:40:6a:bb:b3:0e:d1:8a:a3:52:c9:
         15:b8:f4:bf:13:33:4c:1d:90:32:7f:bf:f5:4f:8a:9f:db:18:
         4c:b9:de:61:d8:d8:95:9c:00:58:5f:2d:73:d6:36:13:23:76:
         56:84:b4:0a:e7:c9:ed:90:7b:3d:fa:5e:11:72:96:9b:7e:de:
         ce:6e:44:2c:08:f1:ec:d5:dc:c4:f8:db:18:9e:d0:bc:4b:e4:
         41:55:fe:33:ac:78:28:b4:50:19:9f:5e:ba:fe:d4:82:f4:51:
         86:64:b5:d0:0a:46:91:fc:1f:cb:ba:8c:ab:2f:a3:33:96:fd:
         fe:9b:7b:db
-----BEGIN CERTIFICATE-----
MIIEQjCCAyqgAwIBAgIGAWSJiTYlMA0GCSqGSIb3DQEBCwUAMHgxEzARBgoJkiaJ
k/IsZAEZFgNjb20xFzAVBgoJkiaJk/IsZAEZFgdleGFtcGxlMRowGAYDVQQKDBFF
eGFtcGxlIENvbSwgSW5jLjELMAkGA1UECwwCQ0ExHzAdBgNVBAMMFnNpZ25pbmcu
Y2EuZXhhbXBsZS5jb20wIBcNMTgwNzExMTMzMDMyWhgPMzAxNzExMTExMzMwMzJa
ME0xCzAJBgNVBAYTAmRlMQ0wCwYDVQQHDAR0ZXN0MQ8wDQYDVQQKDAZjbGllbnQx
DzANBgNVBAsMBmNsaWVudDENMAsGA1UEAwwEa2lyazCCASIwDQYJKoZIhvcNAQEB
BQADggEPADCCAQoCggEBAIZ2uPhmSEi8LonhBRd7uO6Nfbq/8UcS8IznHBOg9pJa
oLx4x5AvLzjfBmX2Lg5mr8LbTQsTw+rtHjkRojsq344DYQf7I2zLQD3ateOyd2PZ
NrjqZv0Po4GXzL/hqI7HWdWfWe0/1sbRnOXH9U7ekkn4Gf3s6FbFKfO6LCQlC7nD
t0YnRMKL7+ibDWOO57nIsoZV9djkVvXOfDOlU1diGqFcf6FwyGZkKkYxFtwxfywj
UbrsIuTnTbjK8ZPnM0lQ/orMH8eO7uHoRcEvkeSzJADB98F0+SX8nPDXZZzMy2tF
6+4S6WnAXdkCKKVAuNjQxWTXpo/exAT6Y7N3AjrN9MkCAwEAAaOB+jCB9zCBnwYD
VR0jBIGXMIGUgBR+U8Rp+lpjlBnb+smhLSS+ooTSxKF5pHcwdTETMBEGCgmSJomT
8ixkARkWA2NvbTEXMBUGCgmSJomT8ixkARkWB2V4YW1wbGUxGjAYBgNVBAoMEUV4
YW1wbGUgQ29tLCBJbmMuMQswCQYDVQQLDAJDQTEcMBoGA1UEAwwTcm9vdC5jYS5l
eGFtcGxlLmNvbYIBAjAdBgNVHQ4EFgQU5U3o0ZAbBawM8+hSWuciivDtzEYwDAYD
VR0TAQH/BAIwADAOBgNVHQ8BAf8EBAMCBeAwFgYDVR0lAQH/BAwwCgYIKwYBBQUH
AwIwDQYJKoZIhvcNAQELBQADggEBALk6womFLs/ya7ZA+S3xosFRoSCV2hHxicSa
W7b6kUGlMj+taQXo/7cMUPeGqGBlk7b84TAsnO2imQSeTeZVEBpqvc2zEW5mmhi/
qb0Fvqi1FsUn7KVpNm8Kxli2KNt7+a/Lteha+/lHuk6IWkRe/pcPZRNM/EnzB8Ms
+49lBL0QDiJtl1UIQGq7sw7RiqNSyRW49L8TM0wdkDJ/v/VPip/bGEy53mHY2JWc
AFhfLXPWNhMjdlaEtArnye2Qez36XhFylpt+3s5uRCwI8ezV3MT42xie0LxL5EFV
/jOseCi0UBmfXrr+1IL0UYZktdAKRpH8H8u6jKsvozOW/f6be9s=
-----END CERTIFICATE-----
```

Thank you very much for your help. I am looking forward to hearing reply from you.

Best Regards,
Chung

**Comment by samuelchowchix** [comment]
We are using Elasticsearch 5.4.2 and Search Guard plugin 5.4.2-15 and this version sgadmin does not have the -w option.

**Comment by jochenkressin** [comment]
I think the problematic cofiguration is this:

```
searchguard.nodes_dn:
  - '*'
````

Here you basically declare *any* certificate as node certificate. Which would also include your admin certificate. Since you cannot use a node certificate as admin certificate, this would lead to the effect you are seeing.

Please change to nodes_dn to not include the kirk admin certificate.

**Comment by samuelchowchix** [comment]
We used the generated configuration snippets by the TLS tool and it is working fine. Thanks for your help!
