### ISSUE TITLE
Authentication with an encrypted PKCS#8 key does not work whereas non-encrypted PKCS#8 key

### ISSUE THREAD

**Issue by sylmarch** [floragunncom/search-guard#524]
Server version:
- Elasticsearch version : 6.2.4
- SearchGuard version (server side) : 6.2.4-22.3
- Java version: 1.8.0_172

Client version:
- sgadmin version : 6.2.4-22.3 - Standalone (http://search.maven.org/remotecontent?filepath=com/floragunn/search-guard-6/6.2.4-22.3/search-guard-6-6.2.4-22.3-sgadmin-standalone.tar.gz)
- Java version: 1.8.0_102

It seems that the usage of an encrypt PKCS#8 key with PEM format is not supported...

I have got a signed certificate and its private key file :
- `test.crt` : PEM certificate
- `test.key` : PEM private key

The `test.crt` is signed by an intermediate CA. So, I concatenate the certificates to one unique bundle file `test.chain.crt`:
```
$ cat test.crt intermediate.crt > test.chain.crt
```

I convert the private key to PKCS#8 format and generate 2 versions:
- One PKCS#8 key, encrypted with the password "1234" : `test_crypt.pk8.key`
- One PKCS#8 key, NON-encrypted : `test_nocrypt.pk8.key`

```
$ openssl pkcs8 -topk8 -inform PEM -in test.key -outform PEM -out test_nocrypt.pk8.key -nocrypt
Enter pass phrase for test.key:

$ openssl pkcs8 -topk8 -inform PEM -in test.key -outform PEM -out test_crypt.pk8.key
Enter pass phrase for test.key:
Enter Encryption Password:
Verifying - Enter Encryption Password:
```

When using the **NON-encrypted key** `test_nocrypt.pk8.key`, the **authentification works**:
```
$ ./sgadmin.sh -h my-elasticsearch-server -p 9300 -cacert /etc/ssl/certs/ca-bundle.crt -cert /path/to/test.chain.crt -key /path/to/test_nocrypt.pk8.key -icl --whoami
Search Guard Admin v6
Will connect to my-elasticsearch-server:9300 ... done
Elasticsearch Version: 6.2.4
Search Guard Version: 6.2.4-22.3
Connected as CN=XXX,O=XXX,L=XXX,ST=XXX,C=FR
{
  "whoami" : {
    "dn" : "CN=XXX,O=XXX,L=XXX,ST=XXX,C=FR",
    "is_admin" : true,
    "is_authenticated" : true,
    "is_node_certificate_request" : false
  }
}
```

When using the **encrypted key** `test_crypt.pk8.key`, the **authentification DOES NOT work**. I try several commands:

Attempt n°1: Using --prompt option:
```
$ ./sgadmin.sh -h my-elasticsearch-server -p 9300 -cacert /etc/ssl/certs/ca-bundle.crt -cert /path/to/test.chain.crt -key /path/to/test_crypt.pk8.key -icl -prompt --whoami
Search Guard Admin v6
Will connect to my-elasticsearch-server:9300 ... done
[Pemkey password:]
11:41:08.880 [main] ERROR com.floragunn.searchguard.ssl.DefaultSearchGuardKeyStore - Your keystore or PEM does not contain a key. If you specified a key password, try removing it. If you did not specify a key password, perhaps you need to if the key is in fact password-protected. Maybe you just confused keys and certificates.
ERR: An unexpected IllegalStateException occured: failed to load plugin class [com.floragunn.searchguard.SearchGuardPlugin]
Trace:
java.lang.IllegalStateException: failed to load plugin class [com.floragunn.searchguard.SearchGuardPlugin]
	at org.elasticsearch.plugins.PluginsService.loadPlugin(PluginsService.java:563)
	at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:104)
	at org.elasticsearch.client.transport.TransportClient.newPluginService(TransportClient.java:105)
	at org.elasticsearch.client.transport.TransportClient.buildTemplate(TransportClient.java:130)
	at org.elasticsearch.client.transport.TransportClient.<init>(TransportClient.java:262)
	at com.floragunn.searchguard.tools.SearchGuardAdmin$TransportClientImpl.<init>(SearchGuardAdmin.java:886)
	at com.floragunn.searchguard.tools.SearchGuardAdmin.main0(SearchGuardAdmin.java:441)
	at com.floragunn.searchguard.tools.SearchGuardAdmin.main(SearchGuardAdmin.java:123)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.elasticsearch.plugins.PluginsService.loadPlugin(PluginsService.java:554)
	... 7 more
Caused by: ElasticsearchSecurityException[Error while initializing transport SSL layer from PEM: java.lang.IllegalArgumentException: File does not contain valid private key: /path/to/test_crypt.pk8.key]; nested: IllegalArgumentException[File does not contain valid private key: /path/to/test_crypt.pk8.key]; nested: IOException[ObjectIdentifier() -- data isn't an object ID (tag = 48)];
	at com.floragunn.searchguard.ssl.DefaultSearchGuardKeyStore.initSSLConfig(DefaultSearchGuardKeyStore.java:292)
	at com.floragunn.searchguard.ssl.DefaultSearchGuardKeyStore.<init>(DefaultSearchGuardKeyStore.java:145)
	at com.floragunn.searchguard.ssl.SearchGuardSSLPlugin.<init>(SearchGuardSSLPlugin.java:193)
	at com.floragunn.searchguard.SearchGuardPlugin.<init>(SearchGuardPlugin.java:189)
	... 12 more
Caused by: java.lang.IllegalArgumentException: File does not contain valid private key: /path/to/test_crypt.pk8.key
	at io.netty.handler.ssl.SslContextBuilder.keyManager(SslContextBuilder.java:267)
	at io.netty.handler.ssl.SslContextBuilder.forServer(SslContextBuilder.java:90)
	at com.floragunn.searchguard.ssl.DefaultSearchGuardKeyStore.buildSSLServerContext(DefaultSearchGuardKeyStore.java:613)
	at com.floragunn.searchguard.ssl.DefaultSearchGuardKeyStore.initSSLConfig(DefaultSearchGuardKeyStore.java:287)
	... 15 more
Caused by: java.io.IOException: ObjectIdentifier() -- data isn't an object ID (tag = 48)
	at sun.security.util.ObjectIdentifier.<init>(ObjectIdentifier.java:253)
	at sun.security.util.DerInputStream.getOID(DerInputStream.java:281)
	at com.sun.crypto.provider.PBES2Parameters.engineInit(PBES2Parameters.java:267)
	at java.security.AlgorithmParameters.init(AlgorithmParameters.java:293)
	at sun.security.x509.AlgorithmId.decodeParams(AlgorithmId.java:132)
	at sun.security.x509.AlgorithmId.<init>(AlgorithmId.java:114)
	at sun.security.x509.AlgorithmId.parse(AlgorithmId.java:372)
	at javax.crypto.EncryptedPrivateKeyInfo.<init>(EncryptedPrivateKeyInfo.java:95)
	at io.netty.handler.ssl.SslContext.generateKeySpec(SslContext.java:978)
	at io.netty.handler.ssl.SslContext.getPrivateKeyFromByteBuffer(SslContext.java:1034)
	at io.netty.handler.ssl.SslContext.toPrivateKey(SslContext.java:1014)
	at io.netty.handler.ssl.SslContextBuilder.keyManager(SslContextBuilder.java:265)
	... 18 more
```

Attempt n°2: Using -keypass 1234 option:
```
$ ./sgadmin.sh -h my-elasticsearch-server -p 9300 -cacert /etc/ssl/certs/ca-bundle.crt -cert /path/to/test.chain.crt -key /path/to/test_crypt.pk8.key -icl -keypass 1234 --whoami
Search Guard Admin v6
Will connect to my-elasticsearch-server:9300 ... done
11:40:37.783 [main] ERROR com.floragunn.searchguard.ssl.DefaultSearchGuardKeyStore - Your keystore or PEM does not contain a key. If you specified a key password, try removing it. If you did not specify a key password, perhaps you need to if the key is in fact password-protected. Maybe you just confused keys and certificates.
ERR: An unexpected IllegalStateException occured: failed to load plugin class [com.floragunn.searchguard.SearchGuardPlugin]
Trace:
java.lang.IllegalStateException: failed to load plugin class [com.floragunn.searchguard.SearchGuardPlugin]
	at org.elasticsearch.plugins.PluginsService.loadPlugin(PluginsService.java:563)
	at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:104)
	at org.elasticsearch.client.transport.TransportClient.newPluginService(TransportClient.java:105)
	at org.elasticsearch.client.transport.TransportClient.buildTemplate(TransportClient.java:130)
	at org.elasticsearch.client.transport.TransportClient.<init>(TransportClient.java:262)
	at com.floragunn.searchguard.tools.SearchGuardAdmin$TransportClientImpl.<init>(SearchGuardAdmin.java:886)
	at com.floragunn.searchguard.tools.SearchGuardAdmin.main0(SearchGuardAdmin.java:441)
	at com.floragunn.searchguard.tools.SearchGuardAdmin.main(SearchGuardAdmin.java:123)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.elasticsearch.plugins.PluginsService.loadPlugin(PluginsService.java:554)
	... 7 more
Caused by: ElasticsearchSecurityException[Error while initializing transport SSL layer from PEM: java.lang.IllegalArgumentException: File does not contain valid private key: /path/to/test_crypt.pk8.key]; nested: IllegalArgumentException[File does not contain valid private key: /path/to/test_crypt.pk8.key]; nested: IOException[ObjectIdentifier() -- data isn't an object ID (tag = 48)];
	at com.floragunn.searchguard.ssl.DefaultSearchGuardKeyStore.initSSLConfig(DefaultSearchGuardKeyStore.java:292)
	at com.floragunn.searchguard.ssl.DefaultSearchGuardKeyStore.<init>(DefaultSearchGuardKeyStore.java:145)
	at com.floragunn.searchguard.ssl.SearchGuardSSLPlugin.<init>(SearchGuardSSLPlugin.java:193)
	at com.floragunn.searchguard.SearchGuardPlugin.<init>(SearchGuardPlugin.java:189)
	... 12 more
Caused by: java.lang.IllegalArgumentException: File does not contain valid private key: /path/to/test_crypt.pk8.key
	at io.netty.handler.ssl.SslContextBuilder.keyManager(SslContextBuilder.java:267)
	at io.netty.handler.ssl.SslContextBuilder.forServer(SslContextBuilder.java:90)
	at com.floragunn.searchguard.ssl.DefaultSearchGuardKeyStore.buildSSLServerContext(DefaultSearchGuardKeyStore.java:613)
	at com.floragunn.searchguard.ssl.DefaultSearchGuardKeyStore.initSSLConfig(DefaultSearchGuardKeyStore.java:287)
	... 15 more
Caused by: java.io.IOException: ObjectIdentifier() -- data isn't an object ID (tag = 48)
	at sun.security.util.ObjectIdentifier.<init>(ObjectIdentifier.java:253)
	at sun.security.util.DerInputStream.getOID(DerInputStream.java:281)
	at com.sun.crypto.provider.PBES2Parameters.engineInit(PBES2Parameters.java:267)
	at java.security.AlgorithmParameters.init(AlgorithmParameters.java:293)
	at sun.security.x509.AlgorithmId.decodeParams(AlgorithmId.java:132)
	at sun.security.x509.AlgorithmId.<init>(AlgorithmId.java:114)
	at sun.security.x509.AlgorithmId.parse(AlgorithmId.java:372)
	at javax.crypto.EncryptedPrivateKeyInfo.<init>(EncryptedPrivateKeyInfo.java:95)
	at io.netty.handler.ssl.SslContext.generateKeySpec(SslContext.java:978)
	at io.netty.handler.ssl.SslContext.getPrivateKeyFromByteBuffer(SslContext.java:1034)
	at io.netty.handler.ssl.SslContext.toPrivateKey(SslContext.java:1014)
	at io.netty.handler.ssl.SslContextBuilder.keyManager(SslContextBuilder.java:265)
	... 18 more
```

I don't see any useful logs on the server side; even setting SearchGuard logger level to trace...
```
# SearchGuard
logger.searchguard.name = com.floragunn
logger.searchguard.level = trace
```
Only the following line is relative to the `sgadmin` attempt:
```
juil. 20 11:50:43 my-elasticsearch-server my-es-node[19561]: [2018-07-20T11:50:43,334][TRACE][c.f.s.s.t.SearchGuardSSLNettyTransport] [my-es-node] Tcp transport channel accepted: NettyTcpChannel{localAddress=/AAA.BBB.CCC.DDD:9300, remoteAddress=/ZZZ.YYY.XXX.WWW:35690}
```
where:
- `AAA.BBB.CCC.DDD` is the server IP
- `ZZZ.YYY.XXX.WWW` is my computer IP from which `sgadmin.sh` is executed

Protect the key with a password is required to prevent its usage in case the key is stolen.

Is it a known bug?
Does `sgadmin.sh` supports PKCS#8 keys with PEM format and protected by a password?

Thanks!

**Comment by tbennett6421** [comment]
Can confirm that I'm using PEM format PKCS#8 keys protected by password, not sure if there is a bug in your version or not.

Elasticsearch version : 6.3.0
SearchGuard version (server side) : 6.3.0-22.3

**Comment by floragunncom** [comment]
This should work, PKCS#8 keys are supported. We need to look into this. Thanks for reporting.

**Comment by sylmarch** [comment]
I have just upgrade the server side and client side to last version but the issue is still happening.

Server side:
- Elasticsearch version: 6.3.2
- Searchguard version: 6.3.2-22.3
- OpenSSL: 1.0.2k-fips  26 Jan 2017
- OS: CentOS Linux release 7.5.1804 (Core)

Client side:
- Searchguard sgadmin version: 6.3.2-22.3
- Java version: 1.8.0_102
- OpenSSL: 1.1.0h-fips  27 Mar 2018
- OS: Fedora 27


With a private key that is NOT protected with a password, it works:
```
$ ./sgadmin.sh -h my-elasticsearch-server -p 9300 -cacert /etc/ssl/certs/ca-bundle.crt -cert /path/to/test.chain.crt -key /path/to/test_notcrypt.pk8 -icl --whoami
Search Guard Admin v6
Will connect to my-elasticsearch-server:9300 ... done
Elasticsearch Version: 6.3.2
Search Guard Version: 6.3.2-22.3
Connected as CN=XXX,...,C=FR
{
  "whoami" : {
    "dn" : "CN=XXX,...,C=FR",
    "is_admin" : true,
    "is_authenticated" : true,
    "is_node_certificate_request" : false
  }
}
```

With a private key that is protected with a password, issue is still happening:
```
$ ./sgadmin.sh -h my-elasticsearch-server -p 9300 -cacert /etc/ssl/certs/ca-bundle.crt -cert /path/to/test.chain.crt -key /path/to/test_crypt.pk8 -icl --prompt --whoami
Search Guard Admin v6
Will connect to my-elasticsearch-server:9300 ... done
[Pemkey password:]
17:04:12.702 [main] ERROR com.floragunn.searchguard.ssl.DefaultSearchGuardKeyStore - Your keystore or PEM does not contain a key. If you specified a key password, try removing it. If you did not specify a key password, perhaps you need to if the key is in fact password-protected. Maybe you just confused keys and certificates.
ERR: An unexpected IllegalStateException occured: failed to load plugin class [com.floragunn.searchguard.SearchGuardPlugin]
Trace:
java.lang.IllegalStateException: failed to load plugin class [com.floragunn.searchguard.SearchGuardPlugin]
	at org.elasticsearch.plugins.PluginsService.loadPlugin(PluginsService.java:701)
	at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:114)
	at org.elasticsearch.client.transport.TransportClient.newPluginService(TransportClient.java:107)
	at org.elasticsearch.client.transport.TransportClient.buildTemplate(TransportClient.java:132)
	at org.elasticsearch.client.transport.TransportClient.<init>(TransportClient.java:269)
	at com.floragunn.searchguard.tools.SearchGuardAdmin$TransportClientImpl.<init>(SearchGuardAdmin.java:887)
	at com.floragunn.searchguard.tools.SearchGuardAdmin.main0(SearchGuardAdmin.java:442)
	at com.floragunn.searchguard.tools.SearchGuardAdmin.main(SearchGuardAdmin.java:124)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.elasticsearch.plugins.PluginsService.loadPlugin(PluginsService.java:692)
	... 7 more
Caused by: ElasticsearchSecurityException[Error while initializing transport SSL layer from PEM: java.lang.IllegalArgumentException: File does not contain valid private key: /path/to/test_crypt.pk8]; nested: IllegalArgumentException[File does not contain valid private key: /path/to/test_crypt.pk8]; nested: IOException[ObjectIdentifier() -- data isn't an object ID (tag = 48)];
	at com.floragunn.searchguard.ssl.DefaultSearchGuardKeyStore.initSSLConfig(DefaultSearchGuardKeyStore.java:292)
	at com.floragunn.searchguard.ssl.DefaultSearchGuardKeyStore.<init>(DefaultSearchGuardKeyStore.java:145)
	at com.floragunn.searchguard.ssl.SearchGuardSSLPlugin.<init>(SearchGuardSSLPlugin.java:193)
	at com.floragunn.searchguard.SearchGuardPlugin.<init>(SearchGuardPlugin.java:189)
	... 12 more
Caused by: java.lang.IllegalArgumentException: File does not contain valid private key: /path/to/test_crypt.pk8
	at io.netty.handler.ssl.SslContextBuilder.keyManager(SslContextBuilder.java:267)
	at io.netty.handler.ssl.SslContextBuilder.forServer(SslContextBuilder.java:90)
	at com.floragunn.searchguard.ssl.DefaultSearchGuardKeyStore.buildSSLServerContext(DefaultSearchGuardKeyStore.java:613)
	at com.floragunn.searchguard.ssl.DefaultSearchGuardKeyStore.initSSLConfig(DefaultSearchGuardKeyStore.java:287)
	... 15 more
Caused by: java.io.IOException: ObjectIdentifier() -- data isn't an object ID (tag = 48)
	at sun.security.util.ObjectIdentifier.<init>(ObjectIdentifier.java:253)
	at sun.security.util.DerInputStream.getOID(DerInputStream.java:281)
	at com.sun.crypto.provider.PBES2Parameters.engineInit(PBES2Parameters.java:267)
	at java.security.AlgorithmParameters.init(AlgorithmParameters.java:293)
	at sun.security.x509.AlgorithmId.decodeParams(AlgorithmId.java:132)
	at sun.security.x509.AlgorithmId.<init>(AlgorithmId.java:114)
	at sun.security.x509.AlgorithmId.parse(AlgorithmId.java:372)
	at javax.crypto.EncryptedPrivateKeyInfo.<init>(EncryptedPrivateKeyInfo.java:95)
	at io.netty.handler.ssl.SslContext.generateKeySpec(SslContext.java:978)
	at io.netty.handler.ssl.SslContext.getPrivateKeyFromByteBuffer(SslContext.java:1034)
	at io.netty.handler.ssl.SslContext.toPrivateKey(SslContext.java:1014)
	at io.netty.handler.ssl.SslContextBuilder.keyManager(SslContextBuilder.java:265)
	... 18 more
```

To be sure, I check that I can read my protected private key with OpenSSL:
```
$ openssl pkey -in /path/to/test_crypt.pk8 -noout -text
Enter pass phrase for /path/to/test_crypt.pk8:
Private-Key: (2048 bit)
modulus:
    [...]
```

And that the private keys matched the certificate public key:
```
# certificate
$ openssl x509 -in /path/to/test.chain.crt -pubkey -noout -outform pem | sha256sum
xxx_same_sha256sum_xxx  -

# not crypted private key
$ openssl pkey -in /path/to/test_notcrypt.pk8 -pubout -outform pem | sha256sum 
xxx_same_sha256sum_xxx  -

# crypted private key
$ openssl pkey -in /path/to/test_crypt.pk8 -pubout -outform pem | sha256sum 
Enter pass phrase for /path/to/test_crypt.pk8:
xxx_same_sha256sum_xxx  -
```

**Comment by sylmarch** [comment]
I upgrade my JDK to last Oracle JDK 8 (i.e. 1.8.0_181) but I get the same errors.

Hereby Java version:
```
$ java -version
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

$ ${JAVA_HOME}/bin/java -version
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)
```

**Comment by sylmarch** [comment]
I found the reason: it's due to a **bug in the JVM that does not correctly handle PKCS#5 v2 key**.
The solution is to convert the traditional private key (i.e. file *.key) using  PKCS#5 v1.5 instead of PKCS#5 v2.

**Attempt n°1** : Generate PKCS#5 key **without using -v1 and -v2 options**. I think that `openssl` uses last PKCS#5 version (i.e. v2) (to be verified)
=> Using this key does not work.
```
$ openssl pkcs8 -topk8 des3 -in test.key -out test_crypt.pk8
Enter pass phrase for test.key:
Enter Encryption Password:
Verifying - Enter Encryption Password:
```


**Attempt n°2** : Generate PKCS#5 key **with -v2 options and des3**.
=> Using this key does not work.
```
$ openssl pkcs8 -topk8 -v2 des3 -in test.key -out test_crypt_v2.pk8
Enter pass phrase for test.key:
Enter Encryption Password:
Verifying - Enter Encryption Password:
```


**Attempt n°3** : Generate PKCS#5 key **with -v1 options and PBE-SHA1-RC4-128**.
=> Using this key works!!! :+1: 
```
$ openssl pkcs8 -topk8 -v1 PBE-SHA1-RC4-128 -in test.key -out test_crypt_v1.pk8
Enter pass phrase for test.key:
Enter Encryption Password:
Verifying - Enter Encryption Password:
```

```
$ ./sgadmin.sh -h my-elasticsearch-server -p 9300 -cacert /etc/ssl/certs/ca-bundle.crt -cert /path/to/test.chain.crt -key /path/to/test_crypt_v1.pk8 -icl --prompt --whoami
Search Guard Admin v6
Will connect to my-elasticsearch-server:9300 ... done
[Pemkey password:]
Elasticsearch Version: 6.3.2
Search Guard Version: 6.3.2-22.3
Connected as CN=XXX,...,C=FR
{
  "whoami" : {
    "dn" : "CN=XXX,...,C=FR",
    "is_admin" : true,
    "is_authenticated" : true,
    "is_node_certificate_request" : false
  }
}
```

@florunncom: is it safe to protect the private key with PKCS#5, v1.5 and cipher PBE-SHA1-RC4-128?
What is your recommendations?

I leave this ticket open. Maybe :
- troubleshooting page should reference this limitation / bug?
- you can add a check in future SearchGuard versions to detect "PKCS#5, v2" key and add a WARN log in case the authentication fails to check the troubleshooting page?

See also:
- JDK bug report: https://bugs.openjdk.java.net/browse/JDK-8076999
- Elastic team also faces with this kind of issue: https://github.com/elastic/elasticsearch/issues/32021

**Comment by floragunncom** [comment]
Wow, thank you very much for this detailed investigation, highly appreciated. This will also solve an issue with our certificate generator, so double thanks. Yes, let's leave the issue open. PKCS#5, v2 is the default in OpenSSL 1.1.0, so I guess others will face this issue as well. We need to document it and maybe add a check in the code.

**Comment by floragunncom** [comment]
Added to the docs (TLS troubleshooting section)
