### ISSUE TITLE
when search-guard enable  flume can't input date to es with 9300

### ISSUE THREAD

**Issue by zqc0512** [floragunncom/search-guard#527]
flume 1.8.0
search-guard 5.6.8-6
flume  log 

```
2018-07-25 15:59:34,595 (SinkRunner-PollingRunner-DefaultSinkProcessor) [ERROR - org.apache.flume.SinkRunner$PollingRunner.run(SinkRunner.java:158)] Unable to deliver event. Exception follows.
NoNodeAvailableException[None of the configured nodes are available: [{#transport#-1}{Xc4C_dK7Tq6A-RbbSR82iw}{xx}{xx:9300}, {#transport#-2}{OPy0FXz5Rg-VT0VN5r6Bng}{xx}{xx:9300}, {#transport#-3}{eLhx6o-oQdqSzfCHx40NQQ}{xx}{xx:9300}, {#transport#-4}{XUjxR6I0QSmZX8yQYMEx-w}{xx}{xx:9300}, {#transport#-5}{2Um_uwAkSe6VIQnxlNG0gA}{xx}{xx:9300}]]
        at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:344)
        at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:242)
        at org.elasticsearch.client.transport.TransportProxyClient.execute(TransportProxyClient.java:59)
        at org.elasticsearch.client.transport.TransportClient.doExecute(TransportClient.java:366)
        at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:404)
        at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:80)
        at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:54)
        at org.apache.flume.sink.elasticsearch.client.ElasticSearchTransportClient.execute(ElasticSearchTransportClient.java:187)
        at org.apache.flume.sink.elasticsearch.ElasticSearchSink.process(ElasticSearchSink.java:217)
        at org.apache.flume.sink.DefaultSinkProcessor.process(DefaultSinkProcessor.java:67)
        at org.apache.flume.SinkRunner$PollingRunner.run(SinkRunner.java:145)
        at java.lang.Thread.run(Thread.java:745)
```

es log

```
[2018-07-25T15:53:44,398][WARN ][c.f.s.s.t.SearchGuardSSLNettyTransport] [node-xx] Someone (/xx:37156) speaks transport plaintext instead of ssl, will close the channel
[2018-07-25T15:53:49,419][WARN ][c.f.s.s.t.SearchGuardSSLNettyTransport] [node-xx] Someone (/xx:37166) speaks transport plaintext instead of ssl, will close the channel
[2018-07-25T15:53:54,439][WARN ][c.f.s.s.t.SearchGuardSSLNettyTransport] [node-xx] Someone (/xx:37176) speaks transport plaintext instead of ssl, will close the channel
[2018-07-25T15:53:59,457][WARN ][c.f.s.s.t.SearchGuardSSLNettyTransport] [node-xx] Someone (/xx:37190) speaks transport plaintext instead of ssl, will close the channel
```

**Comment by floragunncom** [comment]
This is more a flume issue than a Search Guard Issue. Flume seems to connect with Elasticsearch with a Transport Client. To being able to connect, the Transport Client needs to provide TLS certificates, just like an ES node. Since Flume uses the plain Transport Client you see:

`speaks transport plaintext instead of ssl, will close the channel`

So I guess you need to ask the flume folks to provide this feature. It would also be necessary for X-Pack for that matter.
