### ISSUE TITLE
Service interruption during rolling upgrades with search guard

### ISSUE THREAD

**Issue by mat1010** [floragunncom/search-guard#540]
### Search Guard and Elasticsearch version
Search Guard:  22.3
Elasticsearch: 6.3.2

### JVM version and operating system version
JVM: OpenJDK 1.8.0_171
OS: Ubuntu 18.04 LTS (minimal container version)
### Number of nodes in your cluster
2 Client nodes
3 Master nodes
3 Data nodes
### Description of the bug
Hi everybody,

since we switched from xpack security to Search Guard we constantly see issues during rolling upgrades. Once the active master node has been shutdown, the whole cluster goes into unavailable state while a new master is being elected.

### Steps to reproduce
* Ensure your cluster is in a healthy state
* Check which node is the current master `_cat/nodes`
* Remove the master (marked with an *) 
* Requests to the cluster will now timeout / return a 503

Attached is the log of `es-master-0` while `es-master-2` (the at this time active master) was being shut_down.

As said in the beginning: This kind of behaviour did not exist with xpack. Following messages in the attached log are specific to search guard:
```
[2018-08-09T14:51:35,590][INFO ][c.f.s.h.SearchGuardHttpServerTransport] [es-master-0] publish_address {10.48.3.20:9200}, bound_addresses {[::]:9200}
[2018-08-09T14:53:46,571][WARN ][c.f.s.s.t.SearchGuardSSLNettyTransport] [es-master-0] send message failed [channel: NettyTcpChannel{localAddress=0.0.0.0/0.0.0.0:9300, remoteAddress=/10.48.7.35:54964}]
java.nio.channels.ClosedChannelException: null
        at io.netty.channel.AbstractChannel$AbstractUnsafe.write(...)(Unknown Source) ~[?:?]

```

```
[2018-08-09T14:53:46,488][INFO ][o.e.d.z.ZenDiscovery     ] [es-master-0] master_left [{es-master-2}{Izx6MYriTUOrY0wv7GM2HQ}{y-h3c-D6QnC4_Y_2xb5_-g}{10.48.7.35}{10.48.7.35:9300}{machine_id=c6f209db10865003c6edba974848aeb5, xpack.installed=true}], reason [shut_down]
[2018-08-09T14:53:46,489][WARN ][o.e.d.z.ZenDiscovery     ] [es-master-0] master left (reason = shut_down), current nodes: nodes:
   {es-data-2}{X6Kw6BKKTS2R8XSkQEKaKg}{r6ACNE1rSfC8msQYHYXTrA}{10.48.2.20}{10.48.2.20:9300}{machine_id=d17d9551d8a852e1538c9ce46b9f9404, xpack.installed=true}
   {es-data-1}{6pzn5gtJSPWTt0HkieFZ0g}{F2MCfSoBTJmmKIrLbKyxpQ}{10.48.0.22}{10.48.0.22:9300}{machine_id=2cf0c202093aa2258747def09eb4584d, xpack.installed=true}
   {es-master-0}{2hiegn-eRvi89SnWqFOEVA}{ZSro2s3bRwiRRKQ01jPNrg}{10.48.3.20}{10.48.3.20:9300}{xpack.installed=true, machine_id=79e3dc6c7f5884b7f651f5d6b694936d}, local
   {es-coord-0}{jBwyJFFjQiachHQWhMDusg}{wFHdgu2QRMeUURt3JidqTQ}{10.48.22.30}{10.48.22.30:9300}{machine_id=7c6ee261cba7674c7a1d033f4e4e1c91, xpack.installed=true}
   {es-master-1}{kRnrdgzwTMaFTiBpFcJkLg}{xj3VLczKS7yCL9zsXQ7vXg}{10.48.38.133}{10.48.38.133:9300}{machine_id=e47dd296cd134de8ebe5c47575b26863, xpack.installed=true}
   {es-coord-1}{yUK8YmdGQouyjaaTz9IY6Q}{Bo2fd53QQxSVxCkV7N2T9Q}{10.48.1.23}{10.48.1.23:9300}{machine_id=695b79ba7d20fc87e07ec9c7cc75f632, xpack.installed=true}
   {es-master-2}{Izx6MYriTUOrY0wv7GM2HQ}{y-h3c-D6QnC4_Y_2xb5_-g}{10.48.7.35}{10.48.7.35:9300}{machine_id=c6f209db10865003c6edba974848aeb5, xpack.installed=true}, master
   {es-data-0}{bA_-_ne7QhmDL0ODF74iPg}{gjBFgx2DSbKJolZsJ1NLnQ}{10.48.23.61}{10.48.23.61:9300}{machine_id=de0d30c744073d87f85ff9b4fe84351d, xpack.installed=true}
[2018-08-09T14:53:46,571][WARN ][c.f.s.s.t.SearchGuardSSLNettyTransport] [es-master-0] send message failed [channel: NettyTcpChannel{localAddress=0.0.0.0/0.0.0.0:9300, remoteAddress=/10.48.7.35:54964}]
java.nio.channels.ClosedChannelException: null
        at io.netty.channel.AbstractChannel$AbstractUnsafe.write(...)(Unknown Source) ~[?:?]
[2018-08-09T14:53:46,554][WARN ][o.e.c.NodeConnectionsService] [es-master-0] failed to connect to node {es-master-2}{Izx6MYriTUOrY0wv7GM2HQ}{y-h3c-D6QnC4_Y_2xb5_-g}{10.48.7.35}{10.48.7.35:9300}{machine_id=c6f209db10865003c6edba974848aeb5, xpack.installed=true} (tried [1] times)
org.elasticsearch.transport.ConnectTransportException: [es-master-2][10.48.7.35:9300] connect_exception
        at org.elasticsearch.transport.TcpChannel.awaitConnected(TcpChannel.java:165) ~[elasticsearch-6.3.2.jar:6.3.2]
        at org.elasticsearch.transport.TcpTransport.openConnection(TcpTransport.java:631) ~[elasticsearch-6.3.2.jar:6.3.2]
        at org.elasticsearch.transport.TcpTransport.connectToNode(TcpTransport.java:530) ~[elasticsearch-6.3.2.jar:6.3.2]
        at org.elasticsearch.transport.TransportService.connectToNode(TransportService.java:331) ~[elasticsearch-6.3.2.jar:6.3.2]
        at org.elasticsearch.transport.TransportService.connectToNode(TransportService.java:318) ~[elasticsearch-6.3.2.jar:6.3.2]
        at org.elasticsearch.cluster.NodeConnectionsService.validateAndConnectIfNeeded(NodeConnectionsService.java:153) [elasticsearch-6.3.2.jar:6.3.2]
        at org.elasticsearch.cluster.NodeConnectionsService$1.doRun(NodeConnectionsService.java:106) [elasticsearch-6.3.2.jar:6.3.2]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:725) [elasticsearch-6.3.2.jar:6.3.2]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-6.3.2.jar:6.3.2]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_171]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_171]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: 10.48.7.35/10.48.7.35:9300
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:?]
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:?]
        at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:323) ~[?:?]
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340) ~[?:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:633) ~[?:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:545) ~[?:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:499) ~[?:?]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459) ~[?:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) ~[?:?]
        ... 1 more
Caused by: java.net.ConnectException: Connection refused
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:?]
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:?]
        at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:323) ~[?:?]
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340) ~[?:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:633) ~[?:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:545) ~[?:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:499) ~[?:?]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459) ~[?:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) ~[?:?]
        ... 1 more
[2018-08-09T14:53:49,592][INFO ][o.e.c.s.MasterService    ] [es-master-0] zen-disco-elected-as-master ([3] nodes joined)[, ], reason: new_master {es-master-0}{2hiegn-eRvi89SnWqFOEVA}{ZSro2s3bRwiRRKQ01jPNrg}{10.48.3.20}{10.48.3.20:9300}{xpack.installed=true, machine_id=79e3dc6c7f5884b7f651f5d6b694936d}
[2018-08-09T14:54:19,598][WARN ][o.e.d.z.PublishClusterStateAction] [es-master-0] timed out waiting for all nodes to process published state [1981] (timeout [30s], pending nodes: [{es-coord-0}{jBwyJFFjQiachHQWhMDusg}{wFHdgu2QRMeUURt3JidqTQ}{10.48.22.30}{10.48.22.30:9300}{machine_id=7c6ee261cba7674c7a1d033f4e4e1c91, xpack.installed=true}, {es-master-1}{kRnrdgzwTMaFTiBpFcJkLg}{xj3VLczKS7yCL9zsXQ7vXg}{10.48.38.133}{10.48.38.133:9300}{machine_id=e47dd296cd134de8ebe5c47575b26863, xpack.installed=true}, {es-data-1}{6pzn5gtJSPWTt0HkieFZ0g}{F2MCfSoBTJmmKIrLbKyxpQ}{10.48.0.22}{10.48.0.22:9300}{machine_id=2cf0c202093aa2258747def09eb4584d, xpack.installed=true}, {es-data-2}{X6Kw6BKKTS2R8XSkQEKaKg}{r6ACNE1rSfC8msQYHYXTrA}{10.48.2.20}{10.48.2.20:9300}{machine_id=d17d9551d8a852e1538c9ce46b9f9404, xpack.installed=true}, {es-data-0}{bA_-_ne7QhmDL0ODF74iPg}{gjBFgx2DSbKJolZsJ1NLnQ}{10.48.23.61}{10.48.23.61:9300}{machine_id=de0d30c744073d87f85ff9b4fe84351d, xpack.installed=true}, {es-coord-1}{yUK8YmdGQouyjaaTz9IY6Q}{Bo2fd53QQxSVxCkV7N2T9Q}{10.48.1.23}{10.48.1.23:9300}{machine_id=695b79ba7d20fc87e07ec9c7cc75f632, xpack.installed=true}])
[2018-08-09T14:54:19,599][WARN ][o.e.d.z.PublishClusterStateAction] [es-master-0] publishing cluster state with version [1981] failed for the following nodes: [[{es-master-2}{Izx6MYriTUOrY0wv7GM2HQ}{y-h3c-D6QnC4_Y_2xb5_-g}{10.48.7.35}{10.48.7.35:9300}{machine_id=c6f209db10865003c6edba974848aeb5, xpack.installed=true}]]
[2018-08-09T14:54:19,601][INFO ][o.e.c.s.ClusterApplierService] [es-master-0] new_master {es-master-0}{2hiegn-eRvi89SnWqFOEVA}{ZSro2s3bRwiRRKQ01jPNrg}{10.48.3.20}{10.48.3.20:9300}{xpack.installed=true, machine_id=79e3dc6c7f5884b7f651f5d6b694936d}, reason: apply cluster state (from master [master {es-master-0}{2hiegn-eRvi89SnWqFOEVA}{ZSro2s3bRwiRRKQ01jPNrg}{10.48.3.20}{10.48.3.20:9300}{xpack.installed=true, machine_id=79e3dc6c7f5884b7f651f5d6b694936d} committed version [1981] source [zen-disco-elected-as-master ([3] nodes joined)[, ]]])
[2018-08-09T14:54:19,660][DEBUG][o.e.a.a.c.s.TransportClusterStateAction] [es-master-0] no known master node, scheduling a retry
[2018-08-09T14:54:19,662][DEBUG][o.e.a.a.c.h.TransportClusterHealthAction] [es-master-0] no known master node, scheduling a retry
[2018-08-09T14:54:19,664][DEBUG][o.e.a.a.i.g.TransportGetIndexAction] [es-master-0] no known master node, scheduling a retry
[2018-08-09T14:54:19,681][DEBUG][o.e.a.a.i.g.TransportGetIndexAction] [es-master-0] no known master node, scheduling a retry
[2018-08-09T14:54:19,683][DEBUG][o.e.a.a.c.h.TransportClusterHealthAction] [es-master-0] no known master node, scheduling a retry
[2018-08-09T14:54:20,779][DEBUG][o.e.a.a.i.m.g.TransportGetMappingsAction] [es-master-0] no known master node, scheduling a retry
[2018-08-09T14:54:20,782][DEBUG][o.e.a.a.i.m.g.TransportGetMappingsAction] [es-master-0] no known master node, scheduling a retry
[2018-08-09T14:54:29,659][WARN ][o.e.c.s.MasterService    ] [es-master-0] cluster state update task [zen-disco-elected-as-master ([3] nodes joined)[, ]] took [40s] above the warn threshold of 30s
[2018-08-09T14:54:29,660][INFO ][o.e.c.s.MasterService    ] [es-master-0] zen-disco-node-failed({es-master-2}{Izx6MYriTUOrY0wv7GM2HQ}{y-h3c-D6QnC4_Y_2xb5_-g}{10.48.7.35}{10.48.7.35:9300}{machine_id=c6f209db10865003c6edba974848aeb5, xpack.installed=true}), reason(transport disconnected), reason: removed {{es-master-2}{Izx6MYriTUOrY0wv7GM2HQ}{y-h3c-D6QnC4_Y_2xb5_-g}{10.48.7.35}{10.48.7.35:9300}{machine_id=c6f209db10865003c6edba974848aeb5, xpack.installed=true},}
[2018-08-09T14:54:51,416][INFO ][o.e.c.s.ClusterApplierService] [es-master-0] removed {{es-master-2}{Izx6MYriTUOrY0wv7GM2HQ}{y-h3c-D6QnC4_Y_2xb5_-g}{10.48.7.35}{10.48.7.35:9300}{machine_id=c6f209db10865003c6edba974848aeb5, xpack.installed=true},}, reason: apply cluster state (from master [master {es-master-0}{2hiegn-eRvi89SnWqFOEVA}{ZSro2s3bRwiRRKQ01jPNrg}{10.48.3.20}{10.48.3.20:9300}{xpack.installed=true, machine_id=79e3dc6c7f5884b7f651f5d6b694936d} committed version [1982] source [zen-disco-node-failed({es-master-2}{Izx6MYriTUOrY0wv7GM2HQ}{y-h3c-D6QnC4_Y_2xb5_-g}{10.48.7.35}{10.48.7.35:9300}{machine_id=c6f209db10865003c6edba974848aeb5, xpack.installed=true}), reason(transport disconnected)]])
```

**Comment by mat1010** [comment]
After bringing a cluster with the current configuration - but with XPACK - back online I was able to reproduce the same behaviour. Closing this issue since it does not seem to be related to searchguard.
