### ISSUE TITLE
sgadmin can't handle non-encrypted JKS/PCKS12 store

### ISSUE THREAD

**Issue by fbacchella** [floragunncom/search-guard#545]
With latest searchguard:

```
# /usr/share/elasticsearch/bin/elasticsearch-plugin list -v
Plugins directory: /usr/share/elasticsearch/plugins
search-guard-6
- Plugin information:
Name: search-guard-6
Description: Provide access control related features for Elasticsearch 6
Version: 6.3.2-23.0
Elasticsearch Version: 6.3.2
Java Version: 1.8
Native Controller: false
Extended Plugins: []
 * Classname: com.floragunn.searchguard.SearchGuardPlugin
```

it can't  use sgadmin with non-encrypted keystore, being JKS or PKCS12.

The command line is:
/usr/share/elasticsearch/plugins/search-guard-6/tools/sgadmin.sh -ks /tmp/sgadmin.p12 -ts /tmp/sgadmin.p12 -h localhost -kst PKCS12 -tst PKCS12 -tspass '' -kspass '' -cn Sysop-Logstash -ksalias sgadmin -w.

It returns:
```
WARNING: JAVA_HOME not set, will use /bin/java
Search Guard Admin v6
Will connect to localhost:9300 ... done
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by io.netty.util.internal.ReflectionUtil (file:/usr/share/elasticsearch/plugins/search-guard-6/netty-common-4.1.16.Final.jar) to constructor java.nio.DirectByteBuffer(long,int)
WARNING: Please consider reporting this to the maintainers of io.netty.util.internal.ReflectionUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
ERR: An unexpected IllegalStateException occured: failed to load plugin class [com.floragunn.searchguard.SearchGuardPlugin]
Trace:
java.lang.IllegalStateException: failed to load plugin class [com.floragunn.searchguard.SearchGuardPlugin]
	at org.elasticsearch.plugins.PluginsService.loadPlugin(PluginsService.java:701)
	at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:114)
	at org.elasticsearch.client.transport.TransportClient.newPluginService(TransportClient.java:107)
	at org.elasticsearch.client.transport.TransportClient.buildTemplate(TransportClient.java:132)
	at org.elasticsearch.client.transport.TransportClient.<init>(TransportClient.java:269)
	at com.floragunn.searchguard.tools.SearchGuardAdmin$TransportClientImpl.<init>(SearchGuardAdmin.java:886)
	at com.floragunn.searchguard.tools.SearchGuardAdmin.main0(SearchGuardAdmin.java:441)
	at com.floragunn.searchguard.tools.SearchGuardAdmin.main(SearchGuardAdmin.java:123)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
	at org.elasticsearch.plugins.PluginsService.loadPlugin(PluginsService.java:692)
	... 7 more
Caused by: ElasticsearchSecurityException[Error while initializing transport SSL layer: java.io.IOException: keystore password was incorrect]; nested: IOException[keystore password was incorrect]; nested: UnrecoverableKeyException[failed to decrypt safe contents entry: javax.crypto.BadPaddingException: Given final block not properly padded. Such issues can arise if a bad key is used during decryption.];
	at com.floragunn.searchguard.ssl.DefaultSearchGuardKeyStore.initSSLConfig(DefaultSearchGuardKeyStore.java:276)
	at com.floragunn.searchguard.ssl.DefaultSearchGuardKeyStore.<init>(DefaultSearchGuardKeyStore.java:145)
	at com.floragunn.searchguard.ssl.SearchGuardSSLPlugin.<init>(SearchGuardSSLPlugin.java:193)
	at com.floragunn.searchguard.SearchGuardPlugin.<init>(SearchGuardPlugin.java:197)
	... 12 more
Caused by: java.io.IOException: keystore password was incorrect
	at java.base/sun.security.pkcs12.PKCS12KeyStore.engineLoad(PKCS12KeyStore.java:2097)
	at java.base/sun.security.util.KeyStoreDelegator.engineLoad(KeyStoreDelegator.java:222)
	at java.base/java.security.KeyStore.load(KeyStore.java:1479)
	at com.floragunn.searchguard.ssl.DefaultSearchGuardKeyStore.initSSLConfig(DefaultSearchGuardKeyStore.java:238)
	... 15 more
Caused by: java.security.UnrecoverableKeyException: failed to decrypt safe contents entry: javax.crypto.BadPaddingException: Given final block not properly padded. Such issues can arise if a bad key is used during decryption.
	... 19 more
```

Java is:
```
$ /bin/java -version
java version "10.0.2" 2018-07-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.2+13)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.2+13, mixed mode)
```

Elasticsearch is:
```
$ rpm -q elasticsearch
elasticsearch-6.3.2-1.noarch
```

**Comment by floragunncom** [comment]
Java 9 and Java 10 are not supported, because they are intermediate, non-LTS releases. Java 9 is already EOL and Java 10 will become EOL in September. We will support Java 11 which will be LTS. Can you please try with Java 8?

**Comment by fbacchella** [comment]
Same problem with Java 8:
```
$JAVA_HOME/bin/java -version
openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-b13)
OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)
```

And the jks is ok:
```
keytool -list -keystore /tmp/sgadmin.p12 -storepass '' 
Keystore type: PKCS12
Keystore provider: SUN

Your keystore contains 3 entries
...
``

**Comment by fbacchella** [comment]
Any progress ? jdk11 is out now.

**Comment by jochenkressin** [comment]
The current SG version 23.1 is compatible with Java 11. However, you wil still see warning messages when using sgadmin:

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by io.netty.util.internal.ReflectionUtil (file:/usr/share/elasticsearch/plugins/search-guard-6/netty-common-4.1.16.Final.jar) to constructor java.nio.DirectByteBuffer(long,int)
```
The warnings do no affect any functionality. This will be fixed in 23.2.

**Comment by floragunncom** [comment]
@fbacchella can we close this?

**Comment by floragunncom** [comment]
Closing this due to inactivity
