### ISSUE TITLE
Rolling upgrade to ES 6.4 causes fatal error on upgraded nodes

### ISSUE THREAD

**Issue by mikn** [floragunncom/search-guard#548]
SG version: 23.0
ES version: 6.4.0
JVM version: OpenJDK 1.8.171 (Debian 9, kernel 4.9)
Nodes: 3 data, 3 master, 2 client

When updating the cluster from 6.3.2 to 6.4.0 we get a fatal error on transport level for Elasticsearch during the upgrade process (we have not tried finishing the rollout with this error).

Relevant log:
```
[2018-08-31T06:04:01,734][INFO ][c.f.s.SearchGuardPlugin  ] 0 Search Guard modules loaded so far: []
[2018-08-31T06:04:01,736][INFO ][o.e.n.Node               ] [log-store-elasticsearch-client-98cc586b9-pjfm7] initialized
[2018-08-31T06:04:01,736][INFO ][o.e.n.Node               ] [log-store-elasticsearch-client-98cc586b9-pjfm7] starting ...
[2018-08-31T06:04:02,049][INFO ][o.e.t.TransportService   ] [log-store-elasticsearch-client-98cc586b9-pjfm7] publish_address {100.96.27.66:9300}, bound_addresses {100.96.27.66:9300}
[2018-08-31T06:04:02,060][INFO ][o.e.b.BootstrapChecks    ] [log-store-elasticsearch-client-98cc586b9-pjfm7] bound or publishing to a non-loopback address, enforcing bootstrap checks
[2018-08-31T06:04:02,072][INFO ][c.f.s.c.IndexBaseConfigurationRepository] Check if searchguard index exists ...
[2018-08-31T06:04:02,375][ERROR][o.e.t.n.Netty4Utils      ] fatal error on the network layer
	at org.elasticsearch.transport.netty4.Netty4Utils.maybeDie(Netty4Utils.java:182)
	at org.elasticsearch.transport.netty4.Netty4MessageChannelHandler.exceptionCaught(Netty4MessageChannelHandler.java:73)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264)
	at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:256)
	at io.netty.channel.ChannelInboundHandlerAdapter.exceptionCaught(ChannelInboundHandlerAdapter.java:131)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264)
	at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:256)
	at io.netty.handler.logging.LoggingHandler.exceptionCaught(LoggingHandler.java:175)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264)
	at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:256)
	at io.netty.handler.ssl.SslHandler.exceptionCaught(SslHandler.java:998)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
	at io.netty.channel.AbstractChannelHandlerContext.notifyHandlerException(AbstractChannelHandlerContext.java:850)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:364)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:545)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:499)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:748)
[2018-08-31T06:04:02,437][WARN ][c.f.s.s.t.SearchGuardSSLNettyTransport] [log-store-elasticsearch-client-98cc586b9-pjfm7] exception caught on transport layer [NettyTcpChannel{localAddress=0.0.0.0/0.0.0.0:41624, remoteAddress=log-store-elasticsearch-discovery.services.svc.cluster.local/100.65.68.170:9300}], closing connection
io.netty.handler.codec.DecoderException: java.lang.AbstractMethodError
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:459) ~[netty-codec-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) ~[netty-codec-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359) [netty-transport-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935) [netty-transport-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134) [netty-transport-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645) [netty-transport-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:545) [netty-transport-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:499) [netty-transport-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459) [netty-transport-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-common-4.1.16.Final.jar:4.1.16.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.lang.AbstractMethodError
	at io.netty.internal.tcnative.SSL.doHandshake(Native Method) ~[netty-tcnative-openssl-1.0.2o-static-2.0.11.Final-alpine-linux-x86_64.jar:2.0.11.Final]
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.handshake(ReferenceCountedOpenSslEngine.java:1594) ~[netty-handler-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.wrap(ReferenceCountedOpenSslEngine.java:648) ~[netty-handler-4.1.16.Final.jar:4.1.16.Final]
	at javax.net.ssl.SSLEngine.wrap(SSLEngine.java:509) ~[?:1.8.0_171]
	at io.netty.handler.ssl.SslHandler.wrap(SslHandler.java:947) ~[netty-handler-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.handler.ssl.SslHandler.wrap(SslHandler.java:762) ~[netty-handler-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.handler.ssl.SslHandler.wrapAndFlush(SslHandler.java:731) ~[netty-handler-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.handler.ssl.SslHandler.handleUnwrapThrowable(SslHandler.java:1149) ~[netty-handler-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1133) ~[netty-handler-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1162) ~[netty-handler-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489) ~[netty-codec-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428) ~[netty-codec-4.1.16.Final.jar:4.1.16.Final]
	... 15 more
[2018-08-31T06:04:02,379][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [log-store-elasticsearch-client-98cc586b9-pjfm7] fatal error in thread [Thread-5], exiting
java.lang.AbstractMethodError: null
	at io.netty.internal.tcnative.SSL.doHandshake(Native Method) ~[?:?]
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.handshake(ReferenceCountedOpenSslEngine.java:1594) ~[?:?]
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.wrap(ReferenceCountedOpenSslEngine.java:648) ~[?:?]
	at javax.net.ssl.SSLEngine.wrap(SSLEngine.java:509) ~[?:1.8.0_171]
	at io.netty.handler.ssl.SslHandler.wrap(SslHandler.java:947) ~[?:?]
	at io.netty.handler.ssl.SslHandler.wrap(SslHandler.java:762) ~[?:?]
	at io.netty.handler.ssl.SslHandler.wrapAndFlush(SslHandler.java:731) ~[?:?]
	at io.netty.handler.ssl.SslHandler.handleUnwrapThrowable(SslHandler.java:1149) ~[?:?]
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1133) ~[?:?]
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1162) ~[?:?]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489) ~[?:?]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428) ~[?:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[?:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[?:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935) ~[?:?]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134) ~[?:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645) ~[?:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:545) ~[?:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:499) ~[?:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459) ~[?:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) ~[?:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
```

**Comment by floragunncom** [comment]
So was this during a rolling restart attempt? The error would indicate incompatible version of netty/tcnative, but there were no changes here between 6.3.4 and 6.4.0.

Also, are there any other tools or services running while you tried the upgrade? Like logstash or beats?

**Comment by mikn** [comment]
There are upstream clients running during the deploy, yes. The upgraded
nodes end up in a crash loop with this message. We upgrade one client node,
one data node and one master node at the same time and all three end up
with the same error and refuse to come up.

Is there any more data I can provide?

We use the quay.io/lalamove/elasticsearch-sg images, v6.3.2 and V6.4.0

**Comment by mikn** [comment]
The container is running Alpine and not Debian (so it uses musl rather than libc)
OpenSSL version is 1.0.2o
I am using the statically linked binary found here: https://dl.bintray.com/floragunncom/netty-tcnative/:netty-tcnative-openssl-1.0.2o-static-2.0.11.Final-alpine-linux-x86_64.jar
I originally upgraded from 6.2.3 to 6.4.0, but when that didn't work I tried to upgrade to 6.3.2 using the this jar for OpenSSL and it worked just fine.
I also built a new image with 2.0.15 for tcnative, but I end up getting the same error for 6.4.0 as for the 2.0.11 version.
I'm pretty sure there's something wrong with the combination of ES 6.4 + Alpine + OpenSSL. I will try without using the OpenSSL jar and see if it works.

**Comment by mikn** [comment]
Not using tcnative seems to work just fine.
```
[2018-09-03T18:13:21,572][INFO ][o.e.n.Node               ] [log-store-elasticsearch-client-7f97b9f677-5hbj2] initializing ...
[2018-09-03T18:13:21,760][INFO ][o.e.e.NodeEnvironment    ] [log-store-elasticsearch-client-7f97b9f677-5hbj2] using [1] data paths, mounts [[/storage (/dev/nvme0n1p2)]], net usable_space [88.1gb], net total_space [119.8gb], types [ext4]
[2018-09-03T18:13:21,761][INFO ][o.e.e.NodeEnvironment    ] [log-store-elasticsearch-client-7f97b9f677-5hbj2] heap size [1.9gb], compressed ordinary object pointers [true]
[2018-09-03T18:13:21,765][INFO ][o.e.n.Node               ] [log-store-elasticsearch-client-7f97b9f677-5hbj2] node name [log-store-elasticsearch-client-7f97b9f677-5hbj2], node ID [PtBSzZ1UQVSJq0aKt4RO8w]
[2018-09-03T18:13:21,767][INFO ][o.e.n.Node               ] [log-store-elasticsearch-client-7f97b9f677-5hbj2] version[6.4.0], pid[1], build[oss/tar/595516e/2018-08-17T23:18:47.308994Z], OS[Linux/4.9.0-6-amd64/amd64], JVM[Oracle Corporation/OpenJDK 64-Bit Server VM/1.8.0_171/25.171-b11]
[2018-09-03T18:13:21,767][INFO ][o.e.n.Node               ] [log-store-elasticsearch-client-7f97b9f677-5hbj2] JVM arguments [-XX:+UseConcMarkSweepGC, -XX:CMSInitiatingOccupancyFraction=75, -XX:+UseCMSInitiatingOccupancyOnly, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -XX:-OmitStackTraceInFastThrow, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Des.cgroups.hierarchy.override=/, -Djava.net.preferIPv4Stack=true, -Xms2g, -Xmx2g, -Des.path.home=/usr/share/elasticsearch, -Des.path.conf=/usr/share/elasticsearch/config, -Des.distribution.flavor=oss, -Des.distribution.type=tar]
[2018-09-03T18:13:24,662][INFO ][c.f.s.SearchGuardPlugin  ] ES Config path is /usr/share/elasticsearch/config
[2018-09-03T18:13:24,860][INFO ][c.f.s.s.DefaultSearchGuardKeyStore] OpenSSL not available (this is not an error, we simply fallback to built-in JDK SSL) because of java.lang.ClassNotFoundException: io.netty.internal.tcnative.SSL
[2018-09-03T18:13:25,359][INFO ][c.f.s.s.DefaultSearchGuardKeyStore] Config directory is /usr/share/elasticsearch/config/, from there the key- and truststore files are resolved relatively
[2018-09-03T18:13:25,695][INFO ][c.f.s.s.DefaultSearchGuardKeyStore] TLS Transport Client Provider : JDK
[2018-09-03T18:13:25,702][INFO ][c.f.s.s.DefaultSearchGuardKeyStore] TLS Transport Server Provider : JDK
[2018-09-03T18:13:25,702][INFO ][c.f.s.s.DefaultSearchGuardKeyStore] TLS HTTP Provider             : JDK
[2018-09-03T18:13:25,732][INFO ][c.f.s.s.DefaultSearchGuardKeyStore] Enabled TLS protocols for transport layer : [TLSv1.2, TLSv1.1]
[2018-09-03T18:13:25,741][INFO ][c.f.s.s.DefaultSearchGuardKeyStore] Enabled TLS protocols for HTTP layer      : [TLSv1.2, TLSv1.1]
[2018-09-03T18:13:26,961][INFO ][c.f.s.SearchGuardPlugin  ] Clustername: elasticsearch
[2018-09-03T18:13:26,966][WARN ][c.f.s.SearchGuardPlugin  ] Directory /usr/share/elasticsearch/config has insecure file permissions (should be 0700)
[2018-09-03T18:13:26,967][WARN ][c.f.s.SearchGuardPlugin  ] File /usr/share/elasticsearch/config/elasticsearch.yml has insecure file permissions (should be 0600)
[2018-09-03T18:13:26,967][WARN ][c.f.s.SearchGuardPlugin  ] Directory /usr/share/elasticsearch/config/scripts has insecure file permissions (should be 0700)
[2018-09-03T18:13:26,967][WARN ][c.f.s.SearchGuardPlugin  ] File /usr/share/elasticsearch/config/jvm.options has insecure file permissions (should be 0600)
[2018-09-03T18:13:26,968][WARN ][c.f.s.SearchGuardPlugin  ] File /usr/share/elasticsearch/config/log4j2.properties has insecure file permissions (should be 0600)
[2018-09-03T18:13:26,968][WARN ][c.f.s.SearchGuardPlugin  ] Directory /usr/share/elasticsearch/config/tls has insecure file permissions (should be 0700)
[2018-09-03T18:13:26,969][WARN ][c.f.s.SearchGuardPlugin  ] File /usr/share/elasticsearch/config/tls/tls.crt has insecure file permissions (should be 0600)
[2018-09-03T18:13:26,969][WARN ][c.f.s.SearchGuardPlugin  ] File /usr/share/elasticsearch/config/tls/tls.key has insecure file permissions (should be 0600)
[2018-09-03T18:13:26,969][WARN ][c.f.s.SearchGuardPlugin  ] File /usr/share/elasticsearch/config/tls/ca.crt has insecure file permissions (should be 0600)
[2018-09-03T18:13:26,970][WARN ][c.f.s.SearchGuardPlugin  ] File /usr/share/elasticsearch/config/tls/tls.csr has insecure file permissions (should be 0600)
[2018-09-03T18:13:27,210][INFO ][o.e.p.p.PrometheusExporterPlugin] starting Prometheus exporter plugin
[2018-09-03T18:13:27,217][INFO ][o.e.p.PluginsService     ] [log-store-elasticsearch-client-7f97b9f677-5hbj2] loaded module [aggs-matrix-stats]
[2018-09-03T18:13:27,217][INFO ][o.e.p.PluginsService     ] [log-store-elasticsearch-client-7f97b9f677-5hbj2] loaded module [analysis-common]
[2018-09-03T18:13:27,217][INFO ][o.e.p.PluginsService     ] [log-store-elasticsearch-client-7f97b9f677-5hbj2] loaded module [ingest-common]
[2018-09-03T18:13:27,217][INFO ][o.e.p.PluginsService     ] [log-store-elasticsearch-client-7f97b9f677-5hbj2] loaded module [lang-expression]
[2018-09-03T18:13:27,217][INFO ][o.e.p.PluginsService     ] [log-store-elasticsearch-client-7f97b9f677-5hbj2] loaded module [lang-mustache]
[2018-09-03T18:13:27,220][INFO ][o.e.p.PluginsService     ] [log-store-elasticsearch-client-7f97b9f677-5hbj2] loaded module [lang-painless]
[2018-09-03T18:13:27,220][INFO ][o.e.p.PluginsService     ] [log-store-elasticsearch-client-7f97b9f677-5hbj2] loaded module [mapper-extras]
[2018-09-03T18:13:27,220][INFO ][o.e.p.PluginsService     ] [log-store-elasticsearch-client-7f97b9f677-5hbj2] loaded module [parent-join]
[2018-09-03T18:13:27,220][INFO ][o.e.p.PluginsService     ] [log-store-elasticsearch-client-7f97b9f677-5hbj2] loaded module [percolator]
[2018-09-03T18:13:27,220][INFO ][o.e.p.PluginsService     ] [log-store-elasticsearch-client-7f97b9f677-5hbj2] loaded module [rank-eval]
[2018-09-03T18:13:27,220][INFO ][o.e.p.PluginsService     ] [log-store-elasticsearch-client-7f97b9f677-5hbj2] loaded module [reindex]
[2018-09-03T18:13:27,221][INFO ][o.e.p.PluginsService     ] [log-store-elasticsearch-client-7f97b9f677-5hbj2] loaded module [repository-url]
[2018-09-03T18:13:27,221][INFO ][o.e.p.PluginsService     ] [log-store-elasticsearch-client-7f97b9f677-5hbj2] loaded module [transport-netty4]
[2018-09-03T18:13:27,221][INFO ][o.e.p.PluginsService     ] [log-store-elasticsearch-client-7f97b9f677-5hbj2] loaded module [tribe]
[2018-09-03T18:13:27,221][INFO ][o.e.p.PluginsService     ] [log-store-elasticsearch-client-7f97b9f677-5hbj2] loaded plugin [prometheus-exporter]
[2018-09-03T18:13:27,221][INFO ][o.e.p.PluginsService     ] [log-store-elasticsearch-client-7f97b9f677-5hbj2] loaded plugin [search-guard-6]
[2018-09-03T18:13:33,308][WARN ][o.e.d.s.ScriptModule     ] Script: returning default values for missing document values is deprecated. Set system property '-Des.scripting.exception_for_missing_value=true' to make behaviour compatible with future major versions.
[2018-09-03T18:13:34,960][WARN ][o.e.d.c.s.Settings       ] [http.enabled] setting was deprecated in Elasticsearch and will be removed in a future release! See the breaking changes documentation for the next major version.
[2018-09-03T18:13:37,958][INFO ][o.e.d.DiscoveryModule    ] [log-store-elasticsearch-client-7f97b9f677-5hbj2] using discovery type [zen]
[2018-09-03T18:13:40,372][INFO ][c.f.s.SearchGuardPlugin  ] 0 Search Guard modules loaded so far: []
[2018-09-03T18:13:40,373][INFO ][o.e.n.Node               ] [log-store-elasticsearch-client-7f97b9f677-5hbj2] initialized
[2018-09-03T18:13:40,374][INFO ][o.e.n.Node               ] [log-store-elasticsearch-client-7f97b9f677-5hbj2] starting ...
[2018-09-03T18:13:40,869][INFO ][o.e.t.TransportService   ] [log-store-elasticsearch-client-7f97b9f677-5hbj2] publish_address {100.96.27.42:9300}, bound_addresses {100.96.27.42:9300}
[2018-09-03T18:13:40,940][INFO ][o.e.b.BootstrapChecks    ] [log-store-elasticsearch-client-7f97b9f677-5hbj2] bound or publishing to a non-loopback address, enforcing bootstrap checks
[2018-09-03T18:13:41,033][INFO ][c.f.s.c.IndexBaseConfigurationRepository] Check if searchguard index exists ...
[2018-09-03T18:14:11,151][WARN ][o.e.n.Node               ] [log-store-elasticsearch-client-7f97b9f677-5hbj2] timed out while waiting for initial discovery state - timeout: 30s
[2018-09-03T18:14:11,165][INFO ][c.f.s.h.SearchGuardHttpServerTransport] [log-store-elasticsearch-client-7f97b9f677-5hbj2] publish_address {100.96.27.42:9200}, bound_addresses {100.96.27.42:9200}
[2018-09-03T18:14:11,166][INFO ][o.e.n.Node               ] [log-store-elasticsearch-client-7f97b9f677-5hbj2] started
```

**Comment by mikn** [comment]
Oh, interesting. It works with this version! Thank you :)
