### ISSUE TITLE
/_cat_indices Request this, prompt me to fail?

### ISSUE THREAD

**Issue by elain** [floragunncom/search-guard#55]
# curl -s -XGET -uadmin: ccccccccc http://10.108.175.11:9200/_cat/indices
{"error":"RuntimeException[java.lang.NullPointerException]; nested: NullPointerException; ","status":500}

and i install plugin head ,access it ,

http://xxx:9200/_plugin/head 

error: "ClassCastException[com.floragunn.searchguard.http.netty.SessionAwareNettyHttpChannel cannot be cast to org.elasticsearch.http.HttpChannel]"

my acl :
{"acl": [
    {
      "__Comment__": "Default is to execute all filters",
      "filters_bypass": ["*"],
      "filters_execute": []
    },
    {
      "__Comment__": "This means that every requestor (regardless of the requestors hostname and username) which has the root role can do anything",
      "roles": [
        "root"
      ],
      "filters_bypass": ["*"],
      "filters_execute": []
    }
  ]

my config:

searchguard.authentication.settingsdb.user.admin: "ccccccccc"

searchguard.authentication.authorization.settingsdb.roles.admin: ["root"]

searchguard.actionrequestfilter.names: ["readonly","deny"]
searchguard.actionrequestfilter.readonly.allowed_actions: ["indices:data/read/*", "indices:admin/exists","'indices:admin/mapping/*","indices:admin/mappings/*","indices:admin/validate/query","*monitor*"]
searchguard.actionrequestfilter.readonly.forbidden_actions: ["indices:data/write/*"]

my error log :

[2015-09-06 16:39:57,445][ERROR][com.floragunn.searchguard.filter.SearchGuardActionFilter] Error while apply() due to java.lang.NullPointerException for action indices:monitor/stats
java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Objects.java:203)
	at java.util.Arrays$ArrayList.<init>(Arrays.java:3813)
	at java.util.Arrays.asList(Arrays.java:3800)
	at com.floragunn.searchguard.filter.SearchGuardActionFilter.apply0(SearchGuardActionFilter.java:187)
	at com.floragunn.searchguard.filter.SearchGuardActionFilter.apply(SearchGuardActionFilter.java:89)
	at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:165)
	at com.floragunn.searchguard.filter.FLSActionFilter.applySecure(FLSActionFilter.java:76)
	at com.floragunn.searchguard.filter.AbstractActionFilter.apply(AbstractActionFilter.java:97)
	at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:165)
	at com.floragunn.searchguard.filter.DLSActionFilter.applySecure(DLSActionFilter.java:73)
	at com.floragunn.searchguard.filter.AbstractActionFilter.apply(AbstractActionFilter.java:97)
	at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:165)
	at com.floragunn.searchguard.filter.RequestActionFilter.applySecure(RequestActionFilter.java:94)
	at com.floragunn.searchguard.filter.AbstractActionFilter.apply(AbstractActionFilter.java:97)
	at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:165)
	at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:82)
	at org.elasticsearch.client.node.NodeIndicesAdminClient.execute(NodeIndicesAdminClient.java:77)
	at org.elasticsearch.client.FilterClient$IndicesAdmin.execute(FilterClient.java:120)
	at org.elasticsearch.rest.BaseRestHandler$HeadersAndContextCopyClient$IndicesAdmin.execute(BaseRestHandler.java:149)
	at org.elasticsearch.client.support.AbstractIndicesAdminClient.stats(AbstractIndicesAdminClient.java:562)
	at org.elasticsearch.rest.action.cat.RestIndicesAction$1$1.processResponse(RestIndicesAction.java:83)
	at org.elasticsearch.rest.action.cat.RestIndicesAction$1$1.processResponse(RestIndicesAction.java:78)

**Comment by faxm0dem** [comment]
That's a duplicate of #36

**Comment by elain** [comment]
OK,I closed
