### ISSUE TITLE
the ssl pem generated by search-guard-ssl doesn't work

### ISSUE THREAD

**Issue by jipengzhu** [floragunncom/search-guard#550]
Search Guard Version: 5.6.4-23
Search Guard SSL Version:  5.6.4-23 or master
ES Version: 5.6.4
JVM: 1.8.0_181-b13
OS: Linux 3.10.0-514.26.2.el7.v7.4.qihoo.x86_64
3 node

# error 1  (startup error)
### config
```
######## Start Search Guard Demo Configuration ########
searchguard.ssl.transport.pemcert_filepath: node-1-signed.pem
searchguard.ssl.transport.pemkey_filepath: node-1.key.pem
searchguard.ssl.transport.pemtrustedcas_filepath:root-ca.pem
searchguard.ssl.transport.enforce_hostname_verification: false
searchguard.ssl.http.enabled: true
searchguard.ssl.http.pemcert_filepath: node-1-signed.pem
searchguard.ssl.http.pemkey_filepath: node-1.key.pem
searchguard.ssl.http.pemtrustedcas_filepath: root-ca.pem
searchguard.authcz.admin_dn:
  - CN=kirk,OU=client,O=client,L=Test, C=DE
######## End Search Guard Demo Configuration ########
```

### error
```
SSL Problem Received fatal alert: certificate_un
known
javax.net.ssl.SSLException: Received fatal alert: certificate_unknown
```
the error is like in https://github.com/floragunncom/search-guard-ssl/issues/44

and i change the config
from
`searchguard.ssl.transport.pemtrustedcas_filepath:root-ca.pem` 
to 
`searchguard.ssl.transport.pemtrustedcas_filepath:chain-ca.pem`

 i get the second error

# error 2 (sgadmin error)
### config
```
######## Start Search Guard Demo Configuration ########
searchguard.ssl.transport.pemcert_filepath: node-1-signed.pem
searchguard.ssl.transport.pemkey_filepath: node-1.key.pem
searchguard.ssl.transport.pemtrustedcas_filepath:chain-ca.pem
searchguard.ssl.transport.enforce_hostname_verification: false
searchguard.ssl.http.enabled: true
searchguard.ssl.http.pemcert_filepath: node-1-signed.pem
searchguard.ssl.http.pemkey_filepath: node-1.key.pem
searchguard.ssl.http.pemtrustedcas_filepath: chain-ca.pem
searchguard.authcz.admin_dn:
  - CN=kirk,OU=client,O=client,L=Test, C=DE
######## End Search Guard Demo Configuration ########
```

### command
```
./sgadmin.sh -cd ../sgconfig/ -icl -nhnv -cacert ../../../config/root-ca.pem -cert ../../../config/kirk.crtfull.pem -key ../../../config/kirk.key.pem -keypass changeit
```

### error
```
18:10:29.911 [main] ERROR com.floragunn.searchguard.ssl.DefaultSearchGuardKeyStore - Your keystore or PEM does not contain a key. If you sepcified a key password try removing it. If you not sepcified a key password maybe you one because the key is password protected. Maybe you just confused keys and certificates.
ERR: An unexpected ElasticsearchException occured: Failed to load plugin class [com.floragunn.searchguard.SearchGuardPlugin]
Trace:
ElasticsearchException[Failed to load plugin class [com.floragunn.searchguard.SearchGuardPlugin]]; nested: InvocationTargetException; nested: ElasticsearchSecurityException[Error while initializing transport SSL layer from PEM: java.lang.IllegalArgumentException: File does not contain valid private key: /home/zhujipeng/elasticsearch-5.6.4/plugins/search-guard-5/tools/../../../config/kirk.key.pem]; nested: IllegalArgumentException[File does not contain valid private key: /home/zhujipeng/elasticsearch-5.6.4/plugins/search-guard-5/tools/../../../config/kirk.key.pem]; nested: IOException[overrun, bytes = 1195];
	at org.elasticsearch.plugins.PluginsService.loadPlugin(PluginsService.java:438)
	at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:104)
	at org.elasticsearch.client.transport.TransportClient.newPluginService(TransportClient.java:101)
	at org.elasticsearch.client.transport.TransportClient.buildTemplate(TransportClient.java:126)
	at org.elasticsearch.client.transport.TransportClient.<init>(TransportClient.java:254)
	at com.floragunn.searchguard.tools.SearchGuardAdmin$TransportClientImpl.<init>(SearchGuardAdmin.java:800)
	at com.floragunn.searchguard.tools.SearchGuardAdmin.main0(SearchGuardAdmin.java:429)
	at com.floragunn.searchguard.tools.SearchGuardAdmin.main(SearchGuardAdmin.java:115)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.elasticsearch.plugins.PluginsService.loadPlugin(PluginsService.java:427)
	... 7 more
Caused by: ElasticsearchSecurityException[Error while initializing transport SSL layer from PEM: java.lang.IllegalArgumentException: File does not contain valid private key: /home/zhujipeng/elasticsearch-5.6.4/plugins/search-guard-5/tools/../../../config/kirk.key.pem]; nested: IllegalArgumentException[File does not contain valid private key: /home/zhujipeng/elasticsearch-5.6.4/plugins/search-guard-5/tools/../../../config/kirk.key.pem]; nested: IOException[overrun, bytes = 1195];
	at com.floragunn.searchguard.ssl.DefaultSearchGuardKeyStore.initSSLConfig(DefaultSearchGuardKeyStore.java:303)
	at com.floragunn.searchguard.ssl.DefaultSearchGuardKeyStore.<init>(DefaultSearchGuardKeyStore.java:153)
	at com.floragunn.searchguard.SearchGuardPlugin.<init>(SearchGuardPlugin.java:286)
	... 12 more
Caused by: java.lang.IllegalArgumentException: File does not contain valid private key: /home/zhujipeng/elasticsearch-5.6.4/plugins/search-guard-5/tools/../../../config/kirk.key.pem
	at io.netty.handler.ssl.SslContextBuilder.keyManager(SslContextBuilder.java:267)
	at io.netty.handler.ssl.SslContextBuilder.forServer(SslContextBuilder.java:90)
	at com.floragunn.searchguard.ssl.DefaultSearchGuardKeyStore.buildSSLServerContext(DefaultSearchGuardKeyStore.java:621)
	at com.floragunn.searchguard.ssl.DefaultSearchGuardKeyStore.initSSLConfig(DefaultSearchGuardKeyStore.java:298)
	... 14 more
Caused by: java.io.IOException: overrun, bytes = 1195
	at javax.crypto.EncryptedPrivateKeyInfo.<init>(EncryptedPrivateKeyInfo.java:92)
	at io.netty.handler.ssl.SslContext.generateKeySpec(SslContext.java:957)
	at io.netty.handler.ssl.SslContext.getPrivateKeyFromByteBuffer(SslContext.java:1013)
	at io.netty.handler.ssl.SslContext.toPrivateKey(SslContext.java:993)
	at io.netty.handler.ssl.SslContextBuilder.keyManager(SslContextBuilder.java:265)
	... 17 more
```

the error is like in https://github.com/floragunncom/search-guard/issues/402

and when i am aware of that the private pem has no password
i omit the `-keypass` option, and i get the third error

# error 3 (sgadmin error)
### config
```
######## Start Search Guard Demo Configuration ########
searchguard.ssl.transport.pemcert_filepath: node-1-signed.pem
searchguard.ssl.transport.pemkey_filepath: node-1.key.pem
searchguard.ssl.transport.pemtrustedcas_filepath:chain-ca.pem
searchguard.ssl.transport.enforce_hostname_verification: false
searchguard.ssl.http.enabled: true
searchguard.ssl.http.pemcert_filepath: node-1-signed.pem
searchguard.ssl.http.pemkey_filepath: node-1.key.pem
searchguard.ssl.http.pemtrustedcas_filepath: chain-ca.pem
searchguard.authcz.admin_dn:
  - CN=kirk,OU=client,O=client,L=Test, C=DE
######## End Search Guard Demo Configuration ########
```

### command
```
./sgadmin.sh -cd ../sgconfig/ -icl -nhnv -cacert ../../../config/root-ca.pem -cert ../../../config/kirk.crtfull.pem -key ../../../config/kirk.key.pem
```
### error
```
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

the error is like in https://github.com/floragunncom/search-guard-ssl/issues/44

# success
when i use `jks` rather than `pem`, everything works well

### config
```
######## Start Search Guard Demo Configuration ########
searchguard.ssl.transport.keystore_filepath: node-1-keystore.jks
searchguard.ssl.transport.keystore_password: changeit
searchguard.ssl.transport.truststore_filepath: truststore.jks
searchguard.ssl.transport.truststore_password: changeit
searchguard.ssl.transport.enforce_hostname_verification: false
searchguard.ssl.http.enabled: true
searchguard.ssl.http.keystore_filepath: node-1-keystore.jks
searchguard.ssl.http.keystore_password: changeit
searchguard.ssl.http.truststore_filepath: truststore.jks
searchguard.ssl.http.truststore_password: changeit
searchguard.authcz.admin_dn:
 - CN=kirk,OU=client,O=client,L=Test,C=DE
######## End Search Guard Demo Configuration ########
```

the `sgadmin` command with both` jks` and `pem` works well
```
./sgadmin.sh -cd ../sgconfig/ -icl -nhnv -cacert ../../../config/root-ca.pem -cert ../../../config/kirk.crtfull.pem -key ../../../config/kirk.key.pem
```

```
./sgadmin.sh -cd ../sgconfig/ -icl -nhnv -ts ../../../config/truststore.jks -tspass changeit -ks ../../../config/kirk-keystore.jks -kspass changeit
```

**Comment by floragunncom** [comment]
Ho did you generate node-1-signed.pem and node-1.key.pem? Which openssl and java version have you installed?

We strongly recommend to use our TLS Offline Tool:
https://docs.search-guard.com/latest/offline-tls-tool or the online certificate generator on the website.

**Comment by floragunncom** [comment]
@jipengzhu friendly ping

**Comment by jipengzhu** [comment]
## the way i generate node-1-signed.pem and node-1.key.pem

i use the `example.sh
 ` in `search-guard-ssl-ves-5.6.4-23` to generate it

https://github.com/floragunncom/search-guard-ssl

https://github.com/floragunncom/search-guard-ssl/releases/tag/ves-5.6.4-23

##  example-pki-scripts/example.sh
```
#!/bin/bash
OPENSSL_VER="$(openssl version)"

if [[ $OPENSSL_VER == *"0.9"* ]]; then
	echo "Your OpenSSL version is too old: $OPENSSL_VER"
	echo "Please install version 1.0.1 or later"
	exit -1
else
    echo "Your OpenSSL version is: $OPENSSL_VER"
fi

set -e
./clean.sh
./gen_root_ca.sh capass changeit
DN="CN=es-node1.xxxxxx.cn, OU=test, O=test, L=China, C=CN" ./gen_node_cert.sh 1 changeit capass
DN="CN=es-node2.xxxxxx.cn, OU=test, O=test, L=China, C=CN" ./gen_node_cert.sh 2 changeit capass
DN="CN=es-node3.xxxxxx.cn, OU=test, O=test, L=China, C=CN" ./gen_node_cert.sh 3 changeit capass
./gen_client_node_cert.sh kirk changeit capass
rm -f ./*tmp*
```

##  openssl version

```
if [[ $OPENSSL_VER == *"0.9"* ]]; then
> echo "Your OpenSSL version is too old: $OPENSSL_VER"
> echo "Please install version 1.0.1 or later"
> exit -1
> else
>     echo "Your OpenSSL version is: $OPENSSL_VER"
> fi
Your OpenSSL version is: OpenSSL 1.0.2k-fips  26 Jan 2017
```

version is: OpenSSL 1.0.2k-fips  26 Jan 2017

## java version
```
openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-b13)
OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)
```

### openssl output
```
OpenSSL 1.0.2k-fips  26 Jan 2017
```

**Comment by ysundar** [comment]
Hi @jochenkressin 

Even I'm facing same issue with pem based certificates. JKS format is supporting. As per Serchguard guide should use pem based certificates but not working. Shall we continue with JKS format or any workaround ?

**Comment by pablolescotti** [comment]
Log suggests, there may be something wrong with .pem files:

`Caused by: ElasticsearchSecurityException[Error while initializing transport SSL layer from PEM: java.lang.IllegalArgumentException: File does not contain valid private key: /home/zhujipeng/elasticsearch-5.6.4/plugins/search-guard-5/tools/../../../config/kirk.key.pem]; nested: IllegalArgumentException[File does not contain valid private key: /home/zhujipeng/elasticsearch-5.6.4/plugins/search-guard-5/tools/../../../config/kirk.key.pem]; nested: IOException[overrun, bytes = 1195];`

SG expects private key while a file may contain a certificate. 

One can try viewing the pem file with: `less kirk.key.pem`. If this starts with -----BEGIN PRIVATE KEY-----, then it is private key. Certificates start with -----BEGIN CERTIFICATE-----

**Comment by floragunncom** [comment]
Closing this due to inactivity
