### ISSUE TITLE
Kibana and Elasticsarch are working but showing multiple error messages

### ISSUE THREAD

**Issue by tiagoReichert** [floragunncom/search-guard#553]
* Elasticsearch/Kibana version:   6.2.4
* Search guard version: 6.2.4-14 (23.0)
* JVM version and operating system version: openjdk version "1.8.0_171"
* Number of nodes in your cluster: 1
* Description of the bug: 

Kibana and Elasticsarch seems to be working fine, however, we get multiple error messages on Kibana and Elasticsarch side:

Kibana:
```
Unhandled promise rejection (rejection id: 24061): TypeError: Cannot read property 'split' of undefined
TypeError: Cannot read property 'split' of undefined
    at /opt/kibana-6.2.4-linux-x86_64/plugins/searchguard/lib/auth/types/AuthType.js:183:68
    at next (native)
    at step (/opt/kibana-6.2.4-linux-x86_64/plugins/searchguard/lib/auth/types/AuthType.js:23:191)
    at /opt/kibana-6.2.4-linux-x86_64/plugins/searchguard/lib/auth/types/AuthType.js:23:437
    at /opt/kibana-6.2.4-linux-x86_64/plugins/searchguard/lib/auth/types/AuthType.js:23:99
    at server.auth.test (/opt/kibana-6.2.4-linux-x86_64/plugins/searchguard/lib/auth/types/AuthType.js:160:17)
    at transfer (/opt/kibana-6.2.4-linux-x86_64/node_modules/hapi/lib/auth.js:92:16)
    at Function.wrapped (/opt/kibana-6.2.4-linux-x86_64/node_modules/hoek/lib/index.js:875:20)
    at Function.internals.response (/opt/kibana-6.2.4-linux-x86_64/node_modules/hapi/lib/reply.js:138:14)
    at reply (/opt/kibana-6.2.4-linux-x86_64/node_modules/hapi/lib/reply.js:70:22)
    at unauthenticated (/opt/kibana-6.2.4-linux-x86_64/plugins/searchguard/node_modules/hapi-auth-cookie/lib/index.js:169:28)
    at validate (/opt/kibana-6.2.4-linux-x86_64/plugins/searchguard/node_modules/hapi-auth-cookie/lib/index.js:122:28)
    at Object.authenticate (/opt/kibana-6.2.4-linux-x86_64/plugins/searchguard/node_modules/hapi-auth-cookie/lib/index.js:187:13)
    at internals.Auth.test (/opt/kibana-6.2.4-linux-x86_64/node_modules/hapi/lib/auth.js:96:22)
    at Object.test (/opt/kibana-6.2.4-linux-x86_64/node_modules/hapi/lib/plugin.js:65:64)
    at Object.authenticate (/opt/kibana-6.2.4-linux-x86_64/plugins/searchguard/lib/auth/types/AuthType.js:160:34)
```
Elasticsearch:
```
9/10/2018 2:09:23 PM[2018-09-10T17:09:23,788][ERROR][c.f.s.h.SearchGuardHttpServerTransport] [elasticsearch-searchguard] SSL Problem Received fatal alert: bad_certificate
9/10/2018 2:09:23 PMjavax.net.ssl.SSLException: Received fatal alert: bad_certificate
9/10/2018 2:09:23 PM	at sun.security.ssl.Alerts.getSSLException(Alerts.java:208) ~[?:?]
9/10/2018 2:09:23 PM	at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1666) ~[?:?]
9/10/2018 2:09:23 PM	at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1634) ~[?:?]
9/10/2018 2:09:23 PM	at sun.security.ssl.SSLEngineImpl.recvAlert(SSLEngineImpl.java:1800) ~[?:?]
9/10/2018 2:09:23 PM	at sun.security.ssl.SSLEngineImpl.readRecord(SSLEngineImpl.java:1083) ~[?:?]
9/10/2018 2:09:23 PM	at sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:907) ~[?:?]
9/10/2018 2:09:23 PM	at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:781) ~[?:?]
9/10/2018 2:09:23 PM	at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:624) ~[?:1.8.0_171]
9/10/2018 2:09:23 PM	at io.netty.handler.ssl.SslHandler$SslEngineType$3.unwrap(SslHandler.java:281) ~[netty-handler-4.1.16.Final.jar:4.1.16.Final]
9/10/2018 2:09:23 PM	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1215) ~[netty-handler-4.1.16.Final.jar:4.1.16.Final]
9/10/2018 2:09:23 PM	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1127) ~[netty-handler-4.1.16.Final.jar:4.1.16.Final]
9/10/2018 2:09:23 PM	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1162) ~[netty-handler-4.1.16.Final.jar:4.1.16.Final]
9/10/2018 2:09:23 PM	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489) ~[netty-codec-4.1.16.Final.jar:4.1.16.Final]
9/10/2018 2:09:23 PM	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428) ~[netty-codec-4.1.16.Final.jar:4.1.16.Final]
9/10/2018 2:09:23 PM	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) ~[netty-codec-4.1.16.Final.jar:4.1.16.Final]
9/10/2018 2:09:23 PM	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.16.Final.jar:4.1.16.Final]
9/10/2018 2:09:23 PM	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.16.Final.jar:4.1.16.Final]
9/10/2018 2:09:23 PM	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.16.Final.jar:4.1.16.Final]
9/10/2018 2:09:23 PM	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359) [netty-transport-4.1.16.Final.jar:4.1.16.Final]
9/10/2018 2:09:23 PM	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.16.Final.jar:4.1.16.Final]
9/10/2018 2:09:23 PM	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.16.Final.jar:4.1.16.Final]
9/10/2018 2:09:23 PM	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935) [netty-transport-4.1.16.Final.jar:4.1.16.Final]
9/10/2018 2:09:23 PM	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134) [netty-transport-4.1.16.Final.jar:4.1.16.Final]
9/10/2018 2:09:23 PM	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645) [netty-transport-4.1.16.Final.jar:4.1.16.Final]
9/10/2018 2:09:23 PM	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580) [netty-transport-4.1.16.Final.jar:4.1.16.Final]
9/10/2018 2:09:23 PM	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497) [netty-transport-4.1.16.Final.jar:4.1.16.Final]
9/10/2018 2:09:23 PM	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459) [netty-transport-4.1.16.Final.jar:4.1.16.Final]
9/10/2018 2:09:23 PM	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-common-4.1.16.Final.jar:4.1.16.Final]
9/10/2018 2:09:23 PM	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
```

**Comment by floragunncom** [comment]
Looks like SSL misconfiguration

**Comment by jochenkressin** [comment]
@mgustafsson1 Can you please have a look into this? I thought this issue was fixed with the last release?

**Comment by mgustafsson1** [comment]
Yes, this was supposed to be fixed in the last version. I'll investigate further.

**Comment by floragunncom** [comment]
Fixed in Kibana Plugin v15.
