### ISSUE TITLE
search guard 2.3.1 NoNodeAvailableException[None of the configured nodes are available

### ISSUE THREAD

**Issue by BobEnya** [floragunncom/search-guard#558]
**elasticsearch.yml**

bootstrap.memory_lock: false
bootstrap.system_call_filter: false
#node.master: true
#node.data: true
node.name: node-1
network.host: 192.1.1.156
cluster.name: es_test1
#discovery.zen.ping.unicast.hosts: ["192.1.1.156"]

security.manager.enabled: false
searchguard.enable: true
searchguard.authcz.admin_dn:
  - "CN=kirk, OU=client, O=client, L=Test, C=DE"
  #- "CN=kirk,OU=client,O=PIC,l=Taipei, C=TW"
searchguard.ssl.transport.enabled: true
searchguard.ssl.transport.keystore_filepath: node-0-keystore.jks
searchguard.ssl.transport.keystore_password: changeit
searchguard.ssl.transport.truststore_filepath: truststore.jks
searchguard.ssl.transport.truststore_password: changeit
searchguard.ssl.transport.enforce_hostname_verification: false
searchguard.ssl.transport.resolve_hostname: false
searchguard.ssl.http.enabled: false
searchguard.ssl.http.keystore_filepath: node-0-keystore.jks
searchguard.ssl.http.keystore_password: changeit
searchguard.ssl.http.truststore_filepath: truststore.jks
searchguard.ssl.http.truststore_password: changeit
searchguard.allow_all_from_loopback: true

[bob@SBT-T156 elasticsearch-2.3.1]$ ./plugins/search-guard-2/tools/sgadmin.sh \
> -cn es_test1 \
> -h 192.1.1.156 \
> -cd plugins/search-guard-2/sgconfig \
> -ks plugins/search-guard-2/sgconfig/kirk-keystore.jks \
> -kspass changeit \
> -ts plugins/search-guard-2/sgconfig/truststore.jks \
> -tspass changeit \
> -nhnv
Connect to 192.1.1.156:9300
Exception in thread "main" NoNodeAvailableException[None of the configured nodes are available: [{#transport#-1}{192.1.1.156}{192.1.1.156:9300}]]
        at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:290)
        at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:207)
        at org.elasticsearch.client.transport.support.TransportProxyClient.execute(TransportProxyClient.java:55)
        at org.elasticsearch.client.transport.TransportClient.doExecute(TransportClient.java:288)
        at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:359)
        at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:348)
        at org.elasticsearch.client.support.AbstractClient$ClusterAdmin.execute(AbstractClient.java:848)
        at org.elasticsearch.client.support.AbstractClient$ClusterAdmin.health(AbstractClient.java:868)
        at com.floragunn.searchguard.tools.SearchGuardAdmin.main(SearchGuardAdmin.java:137)

**Comment by fredleger** [comment]
seems related to : https://github.com/floragunncom/search-guard/issues/551 ?

**Comment by floragunncom** [comment]
ES 2.x and SG 2.x is EOL according to https://www.elastic.co/de/support/eol and https://docs.search-guard.com/latest/eol-policy#eol-dates. Pls update to to 5.6.12 or 6.4.2 and reopen the issue if its still there with recent versions.
