### ISSUE TITLE
6.4.3-23.1 Does not accept previously valid JWT Signing Key

### ISSUE THREAD

**Issue by lanerjo** [floragunncom/search-guard#581]
* Search Guard 6.4.3-23.1 and Elasticsearch version 6.4.3
* JVM version "1.8.0_172" and operating system version RHEL 7.5
* Number of nodes in your cluster 139 nodes total, 118 data nodes
* Description of the bug - Newest version of Search Guard does not accept previously valid jwt signing_key
* Search Guard License is valid Compliance Edition

These informations are optional but are very valuable and
typically would lead to get bugs fixed faster:

* Steps to reproduce - Upgrade Elasticsearch from 6.2.3, upgrade Search Guard to match Elasticsearch
* Logfiles on DEBUG level

```
[2018-11-16T13:32:14,775][ERROR][c.f.d.a.h.j.HTTPJwtAuthenticator] Error creating JWT authenticator: io.jsonwebtoken.io.DecodingException: Illegal base64 character: '
'. JWT authentication will not work
io.jsonwebtoken.io.DecodingException: Illegal base64 character: '
'
	at io.jsonwebtoken.io.Base64.ctoi(Base64.java:206) ~[jjwt-api-0.10.5.jar:?]
	at io.jsonwebtoken.io.Base64.decodeFast(Base64.java:255) ~[jjwt-api-0.10.5.jar:?]
	at io.jsonwebtoken.io.Base64Decoder.decode(Base64Decoder.java:21) ~[jjwt-api-0.10.5.jar:?]
	at io.jsonwebtoken.io.Base64Decoder.decode(Base64Decoder.java:8) ~[jjwt-api-0.10.5.jar:?]
	at io.jsonwebtoken.io.ExceptionPropagatingDecoder.decode(ExceptionPropagatingDecoder.java:21) ~[jjwt-api-0.10.5.jar:?]
	at com.floragunn.dlic.auth.http.jwt.HTTPJwtAuthenticator.<init>(HTTPJwtAuthenticator.java:80) [dlic-search-guard-enterprise-modules-6.4.3-32.1.jar:6.4.3-32.1]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) [?:1.8.0_172]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) [?:1.8.0_172]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) [?:1.8.0_172]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) [?:1.8.0_172]
	at com.floragunn.searchguard.support.ReflectionHelper.instantiateAAA(ReflectionHelper.java:224) [search-guard-6-6.4.3-23.1.jar:6.4.3-23.1]
	at com.floragunn.searchguard.auth.BackendRegistry.newInstance(BackendRegistry.java:712) [search-guard-6-6.4.3-23.1.jar:6.4.3-23.1]
	at com.floragunn.searchguard.auth.BackendRegistry.onChange(BackendRegistry.java:257) [search-guard-6-6.4.3-23.1.jar:6.4.3-23.1]
	at com.floragunn.searchguard.configuration.IndexBaseConfigurationRepository.notifyAboutChanges(IndexBaseConfigurationRepository.java:394) [search-guard-6-6.4.3-23.1.jar:6.4.3-23.1]
	at com.floragunn.searchguard.configuration.IndexBaseConfigurationRepository.reloadConfiguration(IndexBaseConfigurationRepository.java:329) [search-guard-6-6.4.3-23.1.jar:6.4.3-23.1]
	at com.floragunn.searchguard.action.configupdate.TransportConfigUpdateAction.nodeOperation(TransportConfigUpdateAction.java:113) [search-guard-6-6.4.3-23.1.jar:6.4.3-23.1]
	at com.floragunn.searchguard.action.configupdate.TransportConfigUpdateAction.nodeOperation(TransportConfigUpdateAction.java:47) [search-guard-6-6.4.3-23.1.jar:6.4.3-23.1]
	at org.elasticsearch.action.support.nodes.TransportNodesAction.nodeOperation(TransportNodesAction.java:140) [elasticsearch-6.4.3.jar:6.4.3]
	at org.elasticsearch.action.support.nodes.TransportNodesAction$NodeTransportHandler.messageReceived(TransportNodesAction.java:260) [elasticsearch-6.4.3.jar:6.4.3]
	at org.elasticsearch.action.support.nodes.TransportNodesAction$NodeTransportHandler.messageReceived(TransportNodesAction.java:256) [elasticsearch-6.4.3.jar:6.4.3]
	at com.floragunn.searchguard.ssl.transport.SearchGuardSSLRequestHandler.messageReceivedDecorate(SearchGuardSSLRequestHandler.java:170) [search-guard-ssl-6.4.3-25.5.jar:6.4.3-25.5]
	at com.floragunn.searchguard.transport.SearchGuardRequestHandler.messageReceivedDecorate(SearchGuardRequestHandler.java:260) [search-guard-6-6.4.3-23.1.jar:6.4.3-23.1]
	at com.floragunn.searchguard.ssl.transport.SearchGuardSSLRequestHandler.messageReceived(SearchGuardSSLRequestHandler.java:142) [search-guard-ssl-6.4.3-25.5.jar:6.4.3-25.5]
	at com.floragunn.searchguard.SearchGuardPlugin$7$1.messageReceived(SearchGuardPlugin.java:614) [search-guard-6-6.4.3-23.1.jar:6.4.3-23.1]
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:66) [elasticsearch-6.4.3.jar:6.4.3]
	at org.elasticsearch.transport.TcpTransport$RequestHandler.doRun(TcpTransport.java:1605) [elasticsearch-6.4.3.jar:6.4.3]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:723) [elasticsearch-6.4.3.jar:6.4.3]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-6.4.3.jar:6.4.3]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_172]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_172]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_172]

[2018-11-16T13:32:32,949][ERROR][c.f.d.a.h.j.HTTPJwtAuthenticator] Missing Signing Key. JWT authentication will not work
```

sg_config.yml
```
---
searchguard:
  dynamic:
    http:
      xff:
        remoteIpHeader: "x-forwarded-for"
        proxiesHeader: "x-forwarded-by"
        internalProxies: "192\\.168\\.0\\.10|192\\.168\\.0\\.11"
        enabled: "false"
      anonymous_auth_enabled: "false"
    license: "removed for security purposes"
    kibana:
      multitenancy_enabled: false
      server_username: "kibanaserver"
      index: ".kibana"
      do_not_fail_on_forbidden: false
    authc:
      jwt_auth_domain:
        authentication_backend:
          type: "noop"
        http_authenticator:
          type: "jwt"
          challenge: "false"
          config:
            jwt_header: "heimdall_jwt"
            roles_key: "roles"
            signing_key: "\"-----BEGIN PUBLIC KEY-----\n MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKFAgEAsNJxL6A+WdbXRfqYhAtF\n\
              \ i1b/9qa0WZDfG4MIDpTVbymFVy3jin2NdGxXCwVAqHeJl5rOGLWK4axZxdfK9626\n\
              \ Mi8fFSqQaYIZR80JhbjvADz6gCenW9wCRGf3LWXhF5FT8AqGpuECjHHZkjAG9ekj\n\
              \ Qf/kesh48qUligAycuRgP7b0A5RAvFZKNVX71RnojMKBzw2MqDlYNnTHXO3UrXHT\n\
              \ Yp28WrgEz+h5MbRx3LBvlf/Q+Of26BWBV3/teNbDC8/5hs0MNne42CggV5bV0nG9\n\
              \ EDKgNcLn5oi2r4X0T9h1TGtOKVus4LiusAOJZp6o662aEHTcD4bu9Qo5/0SunVrp\n\
              \ j8Ni8gbH5JITNhLE8prhsxSYayQJIQdwIed+dxVvSXRlcaXSWCsuFBcaShr4WO5Y\n\
              \ NomOtrl5N0wdgCzIv1JHR4COuvDrNxkHVunuA8+pCnw9+/ZsGE20aVYIggyQJDuk\n\
              \ +Bwhq7o4NlqIjfeUDPL27pIQIkaXM3Dd4+qfZD++NJsCOIY1duIWXKnQfgCI+idh\n\
              \ RY4Zq9OyXtM9qDAonn8Znf+7m+OoYNEm5zfEpJbeldgECPxPXVLmBI1ZYbA80MS3\n\
              \ w5svbeM1aT0b01bBsFclpZ1JfTv6cq6dXmJ1lIannPMkPxnS5xAJzJpL709JXQPf\n\
              \ OClmbWKsHK1BxrRADAJin4MCAwEAAQ==\n -----END PUBLIC KEY-----\""
            subject_key: "email"
            jwt_url_parameter: null
        enabled: "true"
        order: "0"
      ldap:
        authentication_backend:
          type: "ldap"
          config:
            bind_dn: null
            verify_hostnames: "true"
            password: null
            usersearch: "(sAMAccountName={0})"
            enable_ssl_client_auth: "false"
            hosts:
            - "localhost:8389"
            username_attribute: null
            userbase: "ou=people,dc=example,dc=com"
            enable_start_tls: "false"
            enable_ssl: "false"
        http_authenticator:
          type: "basic"
          challenge: "false"
        enabled: "false"
        order: "5"
      basic_internal_auth_domain:
        authentication_backend:
          type: "intern"
        http_authenticator:
          type: "basic"
          challenge: "true"
        enabled: "true"
        order: "4"
      proxy_auth_domain:
        authentication_backend:
          type: "noop"
        http_authenticator:
          type: "proxy"
          challenge: "false"
          config:
            roles_header: "x-proxy-roles"
            user_header: "x-proxy-user"
        enabled: "false"
        order: "3"
      clientcert_auth_domain:
        authentication_backend:
          type: "noop"
        http_authenticator:
          type: "clientcert"
          challenge: "false"
          config:
            username_attribute: "cn"
        enabled: "false"
        order: "2"
      host_auth_domain:
        authentication_backend:
          type: "noop"
        http_authenticator:
          type: "host"
          challenge: "false"
        enabled: "false"
        order: "1"
      kerberos_auth_domain:
        authentication_backend:
          type: "noop"
        http_authenticator:
          type: "kerberos"
          challenge: "true"
          config:
            strip_realm_from_principal: "true"
            krb_debug: "false"
        enabled: "false"
        order: "6"
    authz:
      roles_from_another_ldap:
        authorization_backend:
          type: "ldap"
        enabled: "false"
      roles_from_myldap:
        authorization_backend:
          type: "ldap"
          config:
            bind_dn: null
            verify_hostnames: "true"
            userroleattribute: null
            rolebase: "ou=groups,dc=example,dc=com"
            hosts:
            - "localhost:8389"
            rolename: "cn"
            userrolename: "disabled"
            enable_start_tls: "false"
            enable_ssl: "false"
            rolesearch: "(member={0})"
            password: null
            usersearch: "(uid={0})"
            enable_ssl_client_auth: "false"
            userbase: "ou=people,dc=example,dc=com"
            resolve_nested_roles: "true"
        enabled: "false"
```

Have also tried
```
---
searchguard:
  dynamic:
    http:
      xff:
        remoteIpHeader: "x-forwarded-for"
        proxiesHeader: "x-forwarded-by"
        internalProxies: "192\\.168\\.0\\.10|192\\.168\\.0\\.11"
        enabled: "false"
      anonymous_auth_enabled: "false"
    license: "removed for security purposes"
    kibana:
      multitenancy_enabled: false
      server_username: "kibanaserver"
      index: ".kibana"
      do_not_fail_on_forbidden: false
    authc:
      jwt_auth_domain:
        authentication_backend:
          type: "noop"
        http_authenticator:
          type: "jwt"
          challenge: "false"
          config:
            jwt_header: "heimdall_jwt"
            roles_key: "roles"
            signing_key: |-
              -----BEGIN PUBLIC KEY----- 
              MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKFAgEAsNJxL6A+WdbXRfqYhAtF
              i1b/9qa0WZDfG4MIDpTVbymFVy3jin2NdGxXCwVAqHeJl5rOGLWK4axZxdfK9626
              Mi8fFSqQaYIZR80JhbjvADz6gCenW9wCRGf3LWXhF5FT8AqGpuECjHHZkjAG9ekj
              Qf/kesh48qUligAycuRgP7b0A5RAvFZKNVX71RnojMKBzw2MqDlYNnTHXO3UrXHT
              Yp28WrgEz+h5MbRx3LBvlf/Q+Of26BWBV3/teNbDC8/5hs0MNne42CggV5bV0nG9
              EDKgNcLn5oi2r4X0T9h1TGtOKVus4LiusAOJZp6o662aEHTcD4bu9Qo5/0SunVrp
              j8Ni8gbH5JITNhLE8prhsxSYayQJIQdwIed+dxVvSXRlcaXSWCsuFBcaShr4WO5Y
              NomOtrl5N0wdgCzIv1JHR4COuvDrNxkHVunuA8+pCnw9+/ZsGE20aVYIggyQJDuk
              +Bwhq7o4NlqIjfeUDPL27pIQIkaXM3Dd4+qfZD++NJsCOIY1duIWXKnQfgCI+idh
              RY4Zq9OyXtM9qDAonn8Znf+7m+OoYNEm5zfEpJbeldgECPxPXVLmBI1ZYbA80MS3
              w5svbeM1aT0b01bBsFclpZ1JfTv6cq6dXmJ1lIannPMkPxnS5xAJzJpL709JXQPf
              OClmbWKsHK1BxrRADAJin4MCAwEAAQ==
              -----END PUBLIC KEY-----
            subject_key: "email"
            jwt_url_parameter: null
        enabled: "true"
        order: "0"
      ldap:
        authentication_backend:
          type: "ldap"
          config:
            bind_dn: null
            verify_hostnames: "true"
            password: null
            usersearch: "(sAMAccountName={0})"
            enable_ssl_client_auth: "false"
            hosts:
            - "localhost:8389"
            username_attribute: null
            userbase: "ou=people,dc=example,dc=com"
            enable_start_tls: "false"
            enable_ssl: "false"
        http_authenticator:
          type: "basic"
          challenge: "false"
        enabled: "false"
        order: "5"
      basic_internal_auth_domain:
        authentication_backend:
          type: "intern"
        http_authenticator:
          type: "basic"
          challenge: "true"
        enabled: "true"
        order: "4"
      proxy_auth_domain:
        authentication_backend:
          type: "noop"
        http_authenticator:
          type: "proxy"
          challenge: "false"
          config:
            roles_header: "x-proxy-roles"
            user_header: "x-proxy-user"
        enabled: "false"
        order: "3"
      clientcert_auth_domain:
        authentication_backend:
          type: "noop"
        http_authenticator:
          type: "clientcert"
          challenge: "false"
          config:
            username_attribute: "cn"
        enabled: "false"
        order: "2"
      host_auth_domain:
        authentication_backend:
          type: "noop"
        http_authenticator:
          type: "host"
          challenge: "false"
        enabled: "false"
        order: "1"
      kerberos_auth_domain:
        authentication_backend:
          type: "noop"
        http_authenticator:
          type: "kerberos"
          challenge: "true"
          config:
            strip_realm_from_principal: "true"
            krb_debug: "false"
        enabled: "false"
        order: "6"
    authz:
      roles_from_another_ldap:
        authorization_backend:
          type: "ldap"
        enabled: "false"
      roles_from_myldap:
        authorization_backend:
          type: "ldap"
          config:
            bind_dn: null
            verify_hostnames: "true"
            userroleattribute: null
            rolebase: "ou=groups,dc=example,dc=com"
            hosts:
            - "localhost:8389"
            rolename: "cn"
            userrolename: "disabled"
            enable_start_tls: "false"
            enable_ssl: "false"
            rolesearch: "(member={0})"
            password: null
            usersearch: "(uid={0})"
            enable_ssl_client_auth: "false"
            userbase: "ou=people,dc=example,dc=com"
            resolve_nested_roles: "true"
        enabled: "false"
```

The first sg_config.yml works on: 
ES version 6.1.2 with SG version 6.1.2-20.1
ES version 6.3.2 with SG version 6.2.3-23.1
ES version 6.4.0 with SG version 6.4.0-23.1

**Comment by jochenkressin** [comment]
There was a mistake regarding newlines in the documentation as well. This has also been corrected. Sorry for the confusion.
