### ISSUE TITLE
Allow skipping Rest Wrapper Handler registration in SSL only mode

### ISSUE THREAD

**Issue by askids** [floragunncom/search-guard#588]
* Search Guard and Elasticsearch version - 6.4.2-25.5
* JVM version and operating system version - 1.8.0_192, RH Linux 6.X
* Number of nodes in your cluster - 5
* Description of the bug
We are currently using Searchguard SSL for enforcing TLS on transport port only and using ReadonlyRest for http SSL, authentication and authorization. So till v6.2.4, when SG-SSL was available as a separate plugin, both would co-exist without any issue. Now due to recent change where SG-SSL has been merged with main searchguard plugin, we are unable to run with this setup. Even in SSL only mode, since searchguard can be used to enforce SSL on both transport and http port, it is currently registering the REST handler by default. Since Readonlyrest will also register its own REST wrapper, this fails the Elasticsearch bootstrap check with error _"Cannot have more than one plugin implementing a REST wrapper"_.

It would be great, if Searchguard can skip registering the REST wrapper handler, when running in SSL only mode with SSL not enabled on http port. Any other suggestions on work around is also welcome.

Settings would look like this for the above mentioned setup, along with the normal transport related settings to enable TLS.
```
searchguard.ssl_only: true
searchguard.ssl.http.enabled: false.

```
* Steps to reproduce - 
1. Install Seachguard plugin, enable ssl_only setting. Disable ssl on http in searchguard. 
2. Install readonlyrest plugin.
* Logfile entries
```
[2018-11-27T20:06:42,855][DEBUG][o.e.a.ActionModule       ] Using REST wrapper from plugin com.floragunn.searchguard.SearchGuardPlugin
[2018-11-27T20:06:42,856][DEBUG][o.e.a.ActionModule       ] Using REST wrapper from plugin tech.beshu.ror.es.ReadonlyRestPlugin
[2018-11-27T20:06:42,861][ERROR][o.e.b.Bootstrap          ] Exception
java.lang.IllegalArgumentException: Cannot have more than one plugin implementing a REST wrapper
	at org.elasticsearch.action.ActionModule.<init>(ActionModule.java:382) ~[elasticsearch-6.4.2.jar:6.4.2]
	at org.elasticsearch.node.Node.<init>(Node.java:427) ~[elasticsearch-6.4.2.jar:6.4.2]
	at org.elasticsearch.node.Node.<init>(Node.java:256) ~[elasticsearch-6.4.2.jar:6.4.2]
	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:213) ~[elasticsearch-6.4.2.jar:6.4.2]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:213) ~[elasticsearch-6.4.2.jar:6.4.2]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:326) [elasticsearch-6.4.2.jar:6.4.2]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:136) [elasticsearch-6.4.2.jar:6.4.2]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:127) [elasticsearch-6.4.2.jar:6.4.2]
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) [elasticsearch-6.4.2.jar:6.4.2]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) [elasticsearch-cli-6.4.2.jar:6.4.2]
	at org.elasticsearch.cli.Command.main(Command.java:90) [elasticsearch-cli-6.4.2.jar:6.4.2]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:93) [elasticsearch-6.4.2.jar:6.4.2]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:86) [elasticsearch-6.4.2.jar:6.4.2]

```

Please let me know, if you need any further info.

Thanks!

**Comment by floragunncom** [comment]
With ES 7 the Search Guard SSL codebase will be fully merged with Search Guard main plugin and so we will not change anything in the SSL plugin currently (except bug fixes). But luckily Search Guard (SSL) is a open source project and so you can fork it and implement your desired changes on your own ;-)

**Comment by askids** [comment]
This issue is in the main plugin and not the SSL plugin. The change requested was in the main plugin to allow a small customization when running in SSL only mode. Would kindly request to have a second look at the above request.

**Comment by ademariag** [comment]
@floragunncom @askids I am also experiencing the same problem.
