### ISSUE TITLE
 Config directory is C:\elasticsearch-6.x\config/, from there the key- and trust store files are resolved relatively

### ISSUE THREAD

**Issue by wcfCode** [floragunncom/search-guard#686]
windows server 2012 R2 
Executing the script requires starting elasticsearch , but starting the error, it seems to be in an infinite loop
https://github.com/floragunncom/search-guard/issues/156

C:\elasticsearch-6.3.0\bin>elasticsearch
[2019-04-20T11:47:44,826][INFO ][o.e.n.Node               ] [node-8] initializin
g ...
[2019-04-20T11:47:44,919][INFO ][o.e.e.NodeEnvironment    ] [node-8] using [1] d
ata paths, mounts [[(C:)]], net usable_space [37.8gb], net total_space [59.9gb],
 types [NTFS]
[2019-04-20T11:47:44,919][INFO ][o.e.e.NodeEnvironment    ] [node-8] heap size [
990.7mb], compressed ordinary object pointers [true]
[2019-04-20T11:47:44,934][INFO ][o.e.n.Node               ] [node-8] node name [
node-8], node ID [JAWabcU6T46U7WLsXLq8RQ]
[2019-04-20T11:47:44,934][INFO ][o.e.n.Node               ] [node-8] version[6.3
.0], pid[2200], build[default/zip/424e937/2018-06-11T23:38:03.357887Z], OS[Windo
ws Server 2012 R2/6.3/amd64], JVM[Oracle Corporation/Java HotSpot(TM) 64-Bit Ser
ver VM/1.8.0_131/25.131-b11]
[2019-04-20T11:47:44,934][INFO ][o.e.n.Node               ] [node-8] JVM argumen
ts [-Xms1g, -Xmx1g, -XX:+UseConcMarkSweepGC, -XX:CMSInitiatingOccupancyFraction=
75, -XX:+UseCMSInitiatingOccupancyOnly, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.
headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -XX:-OmitStackTraceInFas
tThrow, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.net
ty.recycler.maxCapacityPerThread=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.
disable.jmx=true, -Djava.io.tmpdir=C:\Users\ADMINI~1\AppData\Local\Temp\elastics
earch, -XX:+HeapDumpOnOutOfMemoryError, -XX:HeapDumpPath=data, -XX:ErrorFile=log
s/hs_err_pid%p.log, -XX:+PrintGCDetails, -XX:+PrintGCDateStamps, -XX:+PrintTenur
ingDistribution, -XX:+PrintGCApplicationStoppedTime, -Xloggc:logs/gc.log, -XX:+U
seGCLogFileRotation, -XX:NumberOfGCLogFiles=32, -XX:GCLogFileSize=64m, -Delastic
search, -Des.path.home=C:\elasticsearch-6.3.0, -Des.path.conf=C:\elasticsearch-6
.3.0\config, -Des.distribution.flavor=default, -Des.distribution.type=zip]
[2019-04-20T11:47:48,606][INFO ][c.f.s.SearchGuardPlugin  ] ES Config path is C:
\elasticsearch-6.3.0\config
[2019-04-20T11:47:48,684][INFO ][c.f.s.s.DefaultSearchGuardKeyStore] OpenSSL not
 available (this is not an error, we simply fallback to built-in JDK SSL) becaus
e of java.lang.ClassNotFoundException: io.netty.internal.tcnative.SSL
[2019-04-20T11:47:48,700][INFO ][c.f.s.s.DefaultSearchGuardKeyStore] Config dire
ctory is C:\elasticsearch-6.3.0\config/, from there the key- and truststore file
s are resolved relatively
[2019-04-20T11:47:48,825][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [n
ode-8] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: java.lang.IllegalStateException: f
ailed to load plugin class [com.floragunn.searchguard.SearchGuardPlugin]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:140
) ~[elasticsearch-6.3.0.jar:6.3.0]
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:
127) ~[elasticsearch-6.3.0.jar:6.3.0]
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwar
eCommand.java:86) ~[elasticsearch-6.3.0.jar:6.3.0]
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:1
24) ~[elasticsearch-cli-6.3.0.jar:6.3.0]
        at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-c
li-6.3.0.jar:6.3.0]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:93)
 ~[elasticsearch-6.3.0.jar:6.3.0]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:86)
 ~[elasticsearch-6.3.0.jar:6.3.0]
Caused by: java.lang.IllegalStateException: failed to load plugin class [com.flo
ragunn.searchguard.SearchGuardPlugin]
        at org.elasticsearch.plugins.PluginsService.loadPlugin(PluginsService.ja
va:701) ~[elasticsearch-6.3.0.jar:6.3.0]
        at org.elasticsearch.plugins.PluginsService.loadBundle(PluginsService.ja
va:643) ~[elasticsearch-6.3.0.jar:6.3.0]
        at org.elasticsearch.plugins.PluginsService.loadBundles(PluginsService.j
ava:557) ~[elasticsearch-6.3.0.jar:6.3.0]
        at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:1
62) ~[elasticsearch-6.3.0.jar:6.3.0]
        at org.elasticsearch.node.Node.<init>(Node.java:311) ~[elasticsearch-6.3
.0.jar:6.3.0]
        at org.elasticsearch.node.Node.<init>(Node.java:252) ~[elasticsearch-6.3
.0.jar:6.3.0]
        at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:213) ~[
elasticsearch-6.3.0.jar:6.3.0]
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:213) ~[ela
sticsearch-6.3.0.jar:6.3.0]
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:326) ~[elas
ticsearch-6.3.0.jar:6.3.0]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:136
) ~[elasticsearch-6.3.0.jar:6.3.0]
        ... 6 more
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
 ~[?:?]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstruct
orAccessorImpl.java:62) ~[?:?]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingC
onstructorAccessorImpl.java:45) ~[?:?]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1
.8.0_131]
        at org.elasticsearch.plugins.PluginsService.loadPlugin(PluginsService.ja
va:692) ~[elasticsearch-6.3.0.jar:6.3.0]
        at org.elasticsearch.plugins.PluginsService.loadBundle(PluginsService.ja
va:643) ~[elasticsearch-6.3.0.jar:6.3.0]
        at org.elasticsearch.plugins.PluginsService.loadBundles(PluginsService.j
ava:557) ~[elasticsearch-6.3.0.jar:6.3.0]
        at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:1
62) ~[elasticsearch-6.3.0.jar:6.3.0]
        at org.elasticsearch.node.Node.<init>(Node.java:311) ~[elasticsearch-6.3
.0.jar:6.3.0]
        at org.elasticsearch.node.Node.<init>(Node.java:252) ~[elasticsearch-6.3
.0.jar:6.3.0]
        at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:213) ~[
elasticsearch-6.3.0.jar:6.3.0]
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:213) ~[ela
sticsearch-6.3.0.jar:6.3.0]
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:326) ~[elas
ticsearch-6.3.0.jar:6.3.0]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:136
) ~[elasticsearch-6.3.0.jar:6.3.0]
        ... 6 more
Caused by: org.elasticsearch.ElasticsearchSecurityException: Error while initial
izing transport SSL layer: java.io.IOException: Keystore was tampered with, or p
assword was incorrect
        at com.floragunn.searchguard.ssl.DefaultSearchGuardKeyStore.initSSLConfi
g(DefaultSearchGuardKeyStore.java:276) ~[?:?]
        at com.floragunn.searchguard.ssl.DefaultSearchGuardKeyStore.<init>(Defau
ltSearchGuardKeyStore.java:145) ~[?:?]
        at com.floragunn.searchguard.ssl.SearchGuardSSLPlugin.<init>(SearchGuard
SSLPlugin.java:193) ~[?:?]
        at com.floragunn.searchguard.SearchGuardPlugin.<init>(SearchGuardPlugin.
java:212) ~[?:?]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
 ~[?:?]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstruct
orAccessorImpl.java:62) ~[?:?]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingC
onstructorAccessorImpl.java:45) ~[?:?]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1
.8.0_131]
        at org.elasticsearch.plugins.PluginsService.loadPlugin(PluginsService.ja
va:692) ~[elasticsearch-6.3.0.jar:6.3.0]
        at org.elasticsearch.plugins.PluginsService.loadBundle(PluginsService.ja
va:643) ~[elasticsearch-6.3.0.jar:6.3.0]
        at org.elasticsearch.plugins.PluginsService.loadBundles(PluginsService.j
ava:557) ~[elasticsearch-6.3.0.jar:6.3.0]
        at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:1
62) ~[elasticsearch-6.3.0.jar:6.3.0]
        at org.elasticsearch.node.Node.<init>(Node.java:311) ~[elasticsearch-6.3
.0.jar:6.3.0]
        at org.elasticsearch.node.Node.<init>(Node.java:252) ~[elasticsearch-6.3
.0.jar:6.3.0]
        at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:213) ~[
elasticsearch-6.3.0.jar:6.3.0]
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:213) ~[ela
sticsearch-6.3.0.jar:6.3.0]
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:326) ~[elas
ticsearch-6.3.0.jar:6.3.0]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:136
) ~[elasticsearch-6.3.0.jar:6.3.0]
        ... 6 more
Caused by: java.io.IOException: Keystore was tampered with, or password was inco
rrect
        at sun.security.provider.JavaKeyStore.engineLoad(JavaKeyStore.java:780)
~[?:?]
        at sun.security.provider.JavaKeyStore$JKS.engineLoad(JavaKeyStore.java:5
6) ~[?:?]
        at sun.security.provider.KeyStoreDelegator.engineLoad(KeyStoreDelegator.
java:224) ~[?:?]
        at sun.security.provider.JavaKeyStore$DualFormatJKS.engineLoad(JavaKeySt
ore.java:70) ~[?:?]
        at java.security.KeyStore.load(KeyStore.java:1445) ~[?:1.8.0_131]
        at com.floragunn.searchguard.ssl.DefaultSearchGuardKeyStore.initSSLConfi
g(DefaultSearchGuardKeyStore.java:238) ~[?:?]
        at com.floragunn.searchguard.ssl.DefaultSearchGuardKeyStore.<init>(Defau
ltSearchGuardKeyStore.java:145) ~[?:?]
        at com.floragunn.searchguard.ssl.SearchGuardSSLPlugin.<init>(SearchGuard
SSLPlugin.java:193) ~[?:?]
        at com.floragunn.searchguard.SearchGuardPlugin.<init>(SearchGuardPlugin.
java:212) ~[?:?]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
 ~[?:?]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstruct
orAccessorImpl.java:62) ~[?:?]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingC
onstructorAccessorImpl.java:45) ~[?:?]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1
.8.0_131]
        at org.elasticsearch.plugins.PluginsService.loadPlugin(PluginsService.ja
va:692) ~[elasticsearch-6.3.0.jar:6.3.0]
        at org.elasticsearch.plugins.PluginsService.loadBundle(PluginsService.ja
va:643) ~[elasticsearch-6.3.0.jar:6.3.0]
        at org.elasticsearch.plugins.PluginsService.loadBundles(PluginsService.j
ava:557) ~[elasticsearch-6.3.0.jar:6.3.0]
        at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:1
62) ~[elasticsearch-6.3.0.jar:6.3.0]
        at org.elasticsearch.node.Node.<init>(Node.java:311) ~[elasticsearch-6.3
.0.jar:6.3.0]
        at org.elasticsearch.node.Node.<init>(Node.java:252) ~[elasticsearch-6.3
.0.jar:6.3.0]
        at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:213) ~[
elasticsearch-6.3.0.jar:6.3.0]
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:213) ~[ela
sticsearch-6.3.0.jar:6.3.0]
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:326) ~[elas
ticsearch-6.3.0.jar:6.3.0]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:136
) ~[elasticsearch-6.3.0.jar:6.3.0]
        ... 6 more
Caused by: java.security.UnrecoverableKeyException: Password verification failed

        at sun.security.provider.JavaKeyStore.engineLoad(JavaKeyStore.java:778)
~[?:?]
        at sun.security.provider.JavaKeyStore$JKS.engineLoad(JavaKeyStore.java:5
6) ~[?:?]
        at sun.security.provider.KeyStoreDelegator.engineLoad(KeyStoreDelegator.
java:224) ~[?:?]
        at sun.security.provider.JavaKeyStore$DualFormatJKS.engineLoad(JavaKeySt
ore.java:70) ~[?:?]
        at java.security.KeyStore.load(KeyStore.java:1445) ~[?:1.8.0_131]
        at com.floragunn.searchguard.ssl.DefaultSearchGuardKeyStore.initSSLConfi
g(DefaultSearchGuardKeyStore.java:238) ~[?:?]
        at com.floragunn.searchguard.ssl.DefaultSearchGuardKeyStore.<init>(Defau
ltSearchGuardKeyStore.java:145) ~[?:?]
        at com.floragunn.searchguard.ssl.SearchGuardSSLPlugin.<init>(SearchGuard
SSLPlugin.java:193) ~[?:?]
        at com.floragunn.searchguard.SearchGuardPlugin.<init>(SearchGuardPlugin.
java:212) ~[?:?]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
 ~[?:?]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstruct
orAccessorImpl.java:62) ~[?:?]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingC
onstructorAccessorImpl.java:45) ~[?:?]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1
.8.0_131]
        at org.elasticsearch.plugins.PluginsService.loadPlugin(PluginsService.ja
va:692) ~[elasticsearch-6.3.0.jar:6.3.0]
        at org.elasticsearch.plugins.PluginsService.loadBundle(PluginsService.ja
va:643) ~[elasticsearch-6.3.0.jar:6.3.0]
        at org.elasticsearch.plugins.PluginsService.loadBundles(PluginsService.j
ava:557) ~[elasticsearch-6.3.0.jar:6.3.0]
        at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:1
62) ~[elasticsearch-6.3.0.jar:6.3.0]
        at org.elasticsearch.node.Node.<init>(Node.java:311) ~[elasticsearch-6.3
.0.jar:6.3.0]
        at org.elasticsearch.node.Node.<init>(Node.java:252) ~[elasticsearch-6.3
.0.jar:6.3.0]
        at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:213) ~[
elasticsearch-6.3.0.jar:6.3.0]
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:213) ~[ela
sticsearch-6.3.0.jar:6.3.0]
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:326) ~[elas
ticsearch-6.3.0.jar:6.3.0]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:136
) ~[elasticsearch-6.3.0.jar:6.3.0]
        ... 6 more

C:\elasticsearch-6.3.0\bin>

**Comment by wcfCode** [comment]
Anxiously waiting, thank you
