### ISSUE TITLE
Unable to set up Kibana when `searchguard.ssl.http.clientauth_mode: REQUIRE` option set in Elasticsearch config

### ISSUE THREAD

**Issue by 907th** [floragunncom/search-guard#689]
Search Guard: 6.7.1-24.3
Elasticsearch: 6.7.1
JVM: OpenJDK 1.8.0_191
OS: Ubuntu 18.04 (in LXC container)
Nodes: 1

I have `searchguard.ssl.http.clientauth_mode: REQUIRE` set in the Elasticsearch config file.

I also enabled both `basic_internal_auth_domain` and `clientcert_auth_domain` authc domains in the `sg_config.yml`.
```
   authc:
      basic_internal_auth_domain:
        http_enabled: true
        transport_enabled: false
        order: 0
        http_authenticator:
          type: basic
          challenge: false
        authentication_backend:
          type: intern
      clientcert_auth_domain:
        http_enabled: true
        transport_enabled: false
        order: 1
        http_authenticator:
          type: clientcert
          config:
            username_attribute: cn #optional, if omitted DN becomes username
          challenge: false
        authentication_backend:
          type: noop
```

I configured a client cert and management credentials in the Kibana config file:
```
elasticsearch.username: "kibanaserver"
elasticsearch.password: "mypassword"
elasticsearch.ssl.certificate: /etc/kibana/kibana.pem
elasticsearch.ssl.key: /etc/kibana/kibana.key
```

Client cert can be used directly against Elasticsearch node, which can be checked using curl:
```
$ curl -k 'https://192.168.107.111:9200/_searchguard/authinfo?pretty' --cert /etc/kibana/kibana.pem --key /etc/kibana/kibana.key
{
  "user" : "User [name=kibana, roles=[], requestedTenant=null]",
  "user_name" : "kibana",
  "user_requested_tenant" : null,
  "remote_address" : "192.168.107.111:54760",
  "backend_roles" : [ ],
  "custom_attribute_names" : [ ],
  "sg_roles" : [
    "sg_kibana_server",
    "sg_kibana_user",
    "sg_own_index",
    "sg_readall"
  ],
  "sg_tenants" : {
    "kibana" : true
  },
  "principal" : "CN=kibana",
  "peer_certificates" : "1",
  "sso_logout_url" : null
}
```

Management request from Kibana to Elasticsearch are authenticated now as `kibanaserver` user:
```
# /var/log/elasticsearch/elasticsearch.log
[2019-04-29T13:00:08,905][DEBUG][c.f.s.f.SearchGuardFilter] [xxx] PrivEvalResponse [allowed=true, missingPrivileges=[indices:data/read/search], allowedFlsFields=null, maskedFields=null, queries=null]
[2019-04-29T13:00:09,381][DEBUG][c.f.s.a.BackendRegistry  ] [xxx] User 'User [name=kibanaserver, roles=[], requestedTenant=null]' is authenticated
```

But Kibana UI does not work:
```
# /var/log/elasticsearch/elasticsearch.log
[2019-04-29T13:02:46,047][ERROR][c.f.s.s.h.n.SearchGuardSSLNettyHttpServerTransport] [xxx] SSL Problem null cert chain
javax.net.ssl.SSLHandshakeException: null cert chain
        at sun.security.ssl.Handshaker.checkThrown(Handshaker.java:1521) ~[?:?]
        at sun.security.ssl.SSLEngineImpl.checkTaskThrown(SSLEngineImpl.java:528) ~[?:?]
```

The Kibana server HTTP response is:
```
{"statusCode":503,"error":"Service Unavailable","message":"No Living connections"}
```

**Comment by floragunncom** [comment]
Please post complete kibana.yml config

**Comment by 907th** [comment]
With all comments deleted:
```
/etc/kibana/kibana.yml
server.port: 5601
server.host: 192.168.107.111
server.name: eps-lw-logs
elasticsearch.hosts: ["https://192.168.107.111:9200"]
elasticsearch.username: "kibanaserver"
elasticsearch.password: "veKFefVj5k6V5Hn59exZ"
server.ssl.enabled: false
elasticsearch.ssl.certificate: /etc/kibana/kibana.pem
elasticsearch.ssl.key: /etc/kibana/kibana.key
elasticsearch.ssl.certificateAuthorities: ["/etc/kibana/root-ca.pem"]
elasticsearch.ssl.verificationMode: full
xpack.security.enabled: false
searchguard.allow_client_certificates: true
```

**Comment by 907th** [comment]
After enabling verbose logging in Kibana I also see this in Kibana journal log:
```
Apr 29 13:34:08 xxx kibana[11037]: {"type":"log","@timestamp":"2019-04-29T10:34:08Z","tags":["error","elasticsearch","admin"],"pid":11037,"message":"Request error, retrying\nPOST https://192.168.107.111
:9200/.kibana/_search?size=1000&from=0&rest_total_hits_as_int=true => write EPROTO 140218524485440:error:14094412:SSL routines:ssl3_read_bytes:sslv3 alert bad certificate:../deps/openssl/openssl/ssl/record/rec_
layer_s3.c:1407:SSL alert number 42\n"}
Apr 29 13:34:08 xxx kibana[11037]: {"type":"log","@timestamp":"2019-04-29T10:34:08Z","tags":["warning","elasticsearch","admin"],"pid":11037,"message":"Unable to revive connection: https://192.168.107.11
1:9200/"}
Apr 29 13:34:08 xxx kibana[11037]: {"type":"log","@timestamp":"2019-04-29T10:34:08Z","tags":["warning","elasticsearch","admin"],"pid":11037,"message":"No living connections"}
```

**Comment by 907th** [comment]
Setting `elasticsearch.ssl.verificationMode: none` in Kibana config file doesn't help. All errors are the same.

**Comment by 907th** [comment]
@floragunncom It seems like Kibana server use client cert only for management requests.

**Comment by 907th** [comment]
@floragunncom If I comment out `elasticsearch.username` and `elasticsearch.password` options in the Kibana config then management requests are still successfully authenticated (but with cert user instead if kibanaserver internal user).

**Comment by 907th** [comment]
@floragunncom I think that this issue should have been opened in search-guard-kibana-plugin repo instead of this one. Sorry

**Comment by floragunncom** [comment]
Try setting `elasticsearch.ssl.alwaysPresentCertificate: true` in kibana.yml

**Comment by 907th** [comment]
@floragunncom This setting helped!

**Comment by 907th** [comment]
@floragunncom Sorry for the off-topic, but is it possible to configure Logstash to use client certificate when making requests to Elasticsearch too?

**Comment by jochenkressin** [comment]
Yes, that should be possible. Try the following settings:

```
    ssl => true
    ssl_certificate => "/path/to/logstash.crt"
    ssl_key => "/path/to/logstash.key"
    ssl_certificate_authorities => ["/path/to/ca.crt"]
```
