### ISSUE TITLE
REST wrappers conflict - SearchGuard 7

### ISSUE THREAD

**Issue by stanislavprihoda** [floragunncom/search-guard#703]
Hello,
we're considering using SG plugin. For testing purposes we have tried to disable the installed plugin with **searchguard.disabled: true** (see first log line bellow) and enable xpack.security **xpack.security.enabled: true** but there still seems to be conflict in REST wrappers with searchguard.SearchGuardPlugin.

ES version: 7.1.1
SG version: 7.1.1-35.0.0

Can you review/advice?

```
[2019-06-19T13:56:37,691][WARN ][c.f.s.SearchGuardPlugin  ] [CZESI1VW] Search Guard plugin installed but disabled. This can expose your configuration (including passwords) to the public.
[2019-06-19T13:56:37,694][INFO ][o.e.p.PluginsService     ] [CZESI1VW] loaded module [aggs-matrix-stats]
[2019-06-19T13:56:37,694][INFO ][o.e.p.PluginsService     ] [CZESI1VW] loaded module [analysis-common]
[2019-06-19T13:56:37,695][INFO ][o.e.p.PluginsService     ] [CZESI1VW] loaded module [ingest-common]
[2019-06-19T13:56:37,695][INFO ][o.e.p.PluginsService     ] [CZESI1VW] loaded module [ingest-geoip]
[2019-06-19T13:56:37,695][INFO ][o.e.p.PluginsService     ] [CZESI1VW] loaded module [ingest-user-agent]
[2019-06-19T13:56:37,696][INFO ][o.e.p.PluginsService     ] [CZESI1VW] loaded module [lang-expression]
[2019-06-19T13:56:37,696][INFO ][o.e.p.PluginsService     ] [CZESI1VW] loaded module [lang-mustache]
[2019-06-19T13:56:37,696][INFO ][o.e.p.PluginsService     ] [CZESI1VW] loaded module [lang-painless]
[2019-06-19T13:56:37,697][INFO ][o.e.p.PluginsService     ] [CZESI1VW] loaded module [mapper-extras]
[2019-06-19T13:56:37,697][INFO ][o.e.p.PluginsService     ] [CZESI1VW] loaded module [parent-join]
[2019-06-19T13:56:37,697][INFO ][o.e.p.PluginsService     ] [CZESI1VW] loaded module [percolator]
[2019-06-19T13:56:37,697][INFO ][o.e.p.PluginsService     ] [CZESI1VW] loaded module [rank-eval]
[2019-06-19T13:56:37,698][INFO ][o.e.p.PluginsService     ] [CZESI1VW] loaded module [reindex]
[2019-06-19T13:56:37,698][INFO ][o.e.p.PluginsService     ] [CZESI1VW] loaded module [repository-url]
[2019-06-19T13:56:37,698][INFO ][o.e.p.PluginsService     ] [CZESI1VW] loaded module [transport-netty4]
[2019-06-19T13:56:37,698][INFO ][o.e.p.PluginsService     ] [CZESI1VW] loaded module [x-pack-ccr]
[2019-06-19T13:56:37,699][INFO ][o.e.p.PluginsService     ] [CZESI1VW] loaded module [x-pack-core]
[2019-06-19T13:56:37,699][INFO ][o.e.p.PluginsService     ] [CZESI1VW] loaded module [x-pack-deprecation]
[2019-06-19T13:56:37,699][INFO ][o.e.p.PluginsService     ] [CZESI1VW] loaded module [x-pack-graph]
[2019-06-19T13:56:37,699][INFO ][o.e.p.PluginsService     ] [CZESI1VW] loaded module [x-pack-ilm]
[2019-06-19T13:56:37,700][INFO ][o.e.p.PluginsService     ] [CZESI1VW] loaded module [x-pack-logstash]
[2019-06-19T13:56:37,700][INFO ][o.e.p.PluginsService     ] [CZESI1VW] loaded module [x-pack-ml]
[2019-06-19T13:56:37,700][INFO ][o.e.p.PluginsService     ] [CZESI1VW] loaded module [x-pack-monitoring]
[2019-06-19T13:56:37,701][INFO ][o.e.p.PluginsService     ] [CZESI1VW] loaded module [x-pack-rollup]
[2019-06-19T13:56:37,701][INFO ][o.e.p.PluginsService     ] [CZESI1VW] loaded module [x-pack-security]
[2019-06-19T13:56:37,701][INFO ][o.e.p.PluginsService     ] [CZESI1VW] loaded module [x-pack-sql]
[2019-06-19T13:56:37,702][INFO ][o.e.p.PluginsService     ] [CZESI1VW] loaded module [x-pack-watcher]
[2019-06-19T13:56:37,702][INFO ][o.e.p.PluginsService     ] [CZESI1VW] loaded plugin [search-guard-7]
[2019-06-19T13:56:42,646][INFO ][o.e.x.s.a.s.FileRolesStore] [CZESI1VW] parsed [0] roles from file [C:\ProgramData\Elastic\Elasticsearch\config\roles.yml]
[2019-06-19T13:56:43,484][INFO ][o.e.x.m.p.l.CppLogMessageHandler] [CZESI1VW] [controller/9812] [Main.cc@109] controller (64 bit): Version 7.1.1 (Build fd619a36eb77df) Copyright (c) 2019 Elasticsearch BV
[2019-06-19T13:56:44,055][DEBUG][o.e.a.ActionModule       ] [CZESI1VW] Using REST wrapper from plugin org.elasticsearch.xpack.security.Security
[2019-06-19T13:56:44,055][DEBUG][o.e.a.ActionModule       ] [CZESI1VW] Using REST wrapper from plugin com.floragunn.searchguard.SearchGuardPlugin
[2019-06-19T13:56:44,059][ERROR][o.e.b.Bootstrap          ] [CZESI1VW] Exception
java.lang.IllegalArgumentException: Cannot have more than one plugin implementing a REST wrapper
	at org.elasticsearch.action.ActionModule.<init>(ActionModule.java:388) ~[elasticsearch-7.1.1.jar:7.1.1]
	at org.elasticsearch.node.Node.<init>(Node.java:447) ~[elasticsearch-7.1.1.jar:7.1.1]
	at org.elasticsearch.node.Node.<init>(Node.java:252) ~[elasticsearch-7.1.1.jar:7.1.1]
	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:211) ~[elasticsearch-7.1.1.jar:7.1.1]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:211) ~[elasticsearch-7.1.1.jar:7.1.1]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:325) [elasticsearch-7.1.1.jar:7.1.1]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159) [elasticsearch-7.1.1.jar:7.1.1]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:150) [elasticsearch-7.1.1.jar:7.1.1]
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) [elasticsearch-7.1.1.jar:7.1.1]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) [elasticsearch-cli-7.1.1.jar:7.1.1]
	at org.elasticsearch.cli.Command.main(Command.java:90) [elasticsearch-cli-7.1.1.jar:7.1.1]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:115) [elasticsearch-7.1.1.jar:7.1.1]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92) [elasticsearch-7.1.1.jar:7.1.1]
[2019-06-19T13:56:44,067][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [CZESI1VW] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: java.lang.IllegalArgumentException: Cannot have more than one plugin implementing a REST wrapper
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:163) ~[elasticsearch-7.1.1.jar:7.1.1]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:150) ~[elasticsearch-7.1.1.jar:7.1.1]
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) ~[elasticsearch-7.1.1.jar:7.1.1]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) ~[elasticsearch-cli-7.1.1.jar:7.1.1]
	at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-cli-7.1.1.jar:7.1.1]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:115) ~[elasticsearch-7.1.1.jar:7.1.1]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92) ~[elasticsearch-7.1.1.jar:7.1.1]
Caused by: java.lang.IllegalArgumentException: Cannot have more than one plugin implementing a REST wrapper
	at org.elasticsearch.action.ActionModule.<init>(ActionModule.java:388) ~[elasticsearch-7.1.1.jar:7.1.1]
	at org.elasticsearch.node.Node.<init>(Node.java:447) ~[elasticsearch-7.1.1.jar:7.1.1]
	at org.elasticsearch.node.Node.<init>(Node.java:252) ~[elasticsearch-7.1.1.jar:7.1.1]
	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:211) ~[elasticsearch-7.1.1.jar:7.1.1]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:211) ~[elasticsearch-7.1.1.jar:7.1.1]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:325) ~[elasticsearch-7.1.1.jar:7.1.1]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159) ~[elasticsearch-7.1.1.jar:7.1.1]
	... 6 more
```

**Comment by floragunncom** [comment]
This is by purpose for security reasons. Assume you installed searchguard alongside with xpack or other security plugins and then you enable/disable the wrong (and possibly not proerly configured) one accidentally.

So if you like to use xpack you have to uninstall Search Guard.

**Comment by stanislavprihoda** [comment]
Clear, thanks a lot for the info! Might be worth mentioning in the doc https://docs.search-guard.com/latest/disabling-removing-search-guard it might seem that the disabling would be enough.
