### ISSUE TITLE
Integration with IdP Keycloak fails due to TLS certificate verification failure

### ISSUE THREAD

**Issue by philenius** [floragunncom/search-guard#717]
I'm not sure whether this is a bug or I'm doing something wrong. I struggle to integrate Search Guard with the identity provider *Keycloak*. After a successful configuration, Elasticsearch raises a TLS certificate validation exception (`unable to find valid certification path to requested target`) when calling the OpenID Connect endpoint of Keycloak.

* **Search Guard:** 7.1.0-35.0.0
* **Elasticsearch:** 7.1.0-1
* **OS:** RHEL 7.4 (Maipo)
* **JVM:** OpenJDK java-1.8.0-openjdk.x86_64 1:1.8.0.161-0.b14.el7_4
* **Number of nodes:** 7

1. Firstly, I update the Search Guard config `sg_config.yml`:

   ```yaml
   ...
   
   openid_auth_domain:
     description: "Authenticate via Json Web Token"
     http_enabled: true
     transport_enabled: true
     order: 0
     http_authenticator:
       type: openid
       challenge: false
       config:
         openid_connect_url: "https://keycloak.okd.xx.yyy.de/auth/realms/zzz/.well-known/openid-configuration"
         jwt_header: "Authorization"
         roles_key: roles
         subject_key: preferred_username
         enable_ssl: true
         verify_hostnames: true
         pemtrustedcas_filepath: "/etc/elasticsearch/ca.pem"
     authentication_backend:
       type: noop
   
   ...
   ```

2. Then, I deploy the configuration, which completes with success:

   ```bash
   ./sgadmin.sh -cert /etc/pki/tls/certs/search-guard-admin/search-guard-admin.crt -key /etc/pki/tls/certs/search-guard-admin/search-guard-admin.key -cacert /etc/pki/ca-trust/source/anchors/ca.crt -h es-01.xx.yyy.de -cd ../sgconfig/ -p 9300 -cn xx-cluster
   # Will connect to es-01.xx.yyy.de:9300 ... done
   # Connected as CN=es-admin.xx.yyy.de,O=xx.yyy.DE
   # Elasticsearch Version: 7.1.0
   # Search Guard Version: 7.1.0-35.0.0
   # Contacting elasticsearch cluster 'xx-cluster' and wait for YELLOW clusterstate ...
   # Clustername: xx-cluster
   # Clusterstate: GREEN
   # Number of nodes: 7
   # Number of data nodes: 4
   # searchguard index already exists, so we do not need to create one.
   # Populate config from /usr/share/elasticsearch/plugins/search-guard-7/sgconfig
   # Will update '_doc/config' with ../sgconfig/sg_config.yml 
   #    SUCC: Configuration for 'config' created or updated
   # Will update '_doc/roles' with ../sgconfig/sg_roles.yml 
   #    SUCC: Configuration for 'roles' created or updated
   # Will update '_doc/rolesmapping' with ../sgconfig/sg_roles_mapping.yml 
   #    SUCC: Configuration for 'rolesmapping' created or updated
   # Will update '_doc/internalusers' with ../sgconfig/sg_internal_users.yml 
   #    SUCC: Configuration for 'internalusers' created or updated
   # Will update '_doc/actiongroups' with ../sgconfig/sg_action_groups.yml 
   #    SUCC: Configuration for 'actiongroups' created or updated
   # Will update '_doc/tenants' with ../sgconfig/sg_tenants.yml 
   #    SUCC: Configuration for 'tenants' created or updated
   # Done with success
   ```

3. Retrieve a token from Keycloak and extract the JWT:

   ```bash
   TOKEN=$(curl -XPOST "https://keycloak.okd.xx.yyy.de/auth/realms/zzz/protocol/openid-connect/token" --data "grant_type=client_credentials&client_id=cccccc&client_secret=aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa" | jq -r '.access_token')
   
   echo $TOKEN
   # eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IlkyaGxaV3Q1SUdKaGMzUmhjbVFLIn0K.<PART2>.<PART_3>
   ```

4. Then, I use curl to call the Elasticsearch endpoint with the extracted JWT. The response is always of HTTP status code _401 Unauthorized_:

   ```bash
   curl -H "Authorization: Bearer ${TOKEN}" https://es-01.xx.yyy.de:9200 -i
   # HTTP/1.1 401 Unauthorized
   # WWW-Authenticate: Basic realm="Search Guard"
   # content-type: text/plain; charset=UTF-8
   # content-length: 12
   
   # Unauthorized
   ```

5. At the same time, Elasticsearch writes an exception in its log file which indicates problems regarding the validation of Keycloak's TLS certificate :

   ```bash
   [2019-07-22T17:35:46,070][INFO ][c.f.d.a.h.j.k.SelfRefreshingKeySet] [es-01.xx.yyy.de] Performing refresh 1
   [2019-07-22T17:35:46,092][WARN ][c.f.d.a.h.j.k.SelfRefreshingKeySet] [es-01.xx.yyy.de] KeySetProvider threw error
   com.floragunn.dlic.auth.http.jwt.keybyoidc.AuthenticatorUnavailableException: Error while getting https://keycloak.okd.xx.yyy.de/auth/realms/zzz/.well-known/openid-configuration: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
           at com.floragunn.dlic.auth.http.jwt.keybyoidc.KeySetRetriever.getJwksUri(KeySetRetriever.java:148) ~[dlic-search-guard-enterprise-modules-7.1.0-35.0.0.jar:7.1.0-35.0.0]
           at com.floragunn.dlic.auth.http.jwt.keybyoidc.KeySetRetriever.get(KeySetRetriever.java:69) ~[dlic-search-guard-enterprise-modules-7.1.0-35.0.0.jar:7.1.0-35.0.0]
           at com.floragunn.dlic.auth.http.jwt.keybyoidc.SelfRefreshingKeySet$1.run(SelfRefreshingKeySet.java:213) [dlic-search-guard-enterprise-modules-7.1.0-35.0.0.jar:7.1.0-35.0.0]
           at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
           at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
           at java.lang.Thread.run(Thread.java:835) [?:?]
   Caused by: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
           at sun.security.ssl.Alert.createSSLException(Alert.java:131) ~[?:?]
           at sun.security.ssl.TransportContext.fatal(TransportContext.java:320) ~[?:?]
           at sun.security.ssl.TransportContext.fatal(TransportContext.java:263) ~[?:?]
           at sun.security.ssl.TransportContext.fatal(TransportContext.java:258) ~[?:?]
           at sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:641) ~[?:?]
           at sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(CertificateMessage.java:460) ~[?:?]
           at sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(CertificateMessage.java:360) ~[?:?]
           at sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:392) ~[?:?]
           at sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:441) ~[?:?]
           at sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:419) ~[?:?]
           at sun.security.ssl.TransportContext.dispatch(TransportContext.java:177) ~[?:?]
           at sun.security.ssl.SSLTransport.decode(SSLTransport.java:164) ~[?:?]
           at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1180) ~[?:?]
           at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1091) ~[?:?]
           at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:402) ~[?:?]
           at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:396) ~[httpclient-4.5.3.jar:4.5.3]
           at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:355) ~[httpclient-4.5.3.jar:4.5.3]
           at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142) ~[httpclient-4.5.3.jar:4.5.3]
           at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:359) ~[httpclient-4.5.3.jar:4.5.3]
           at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381) ~[httpclient-4.5.3.jar:4.5.3]
           at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237) ~[httpclient-4.5.3.jar:4.5.3]
           at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185) ~[httpclient-4.5.3.jar:4.5.3]
           at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89) ~[httpclient-4.5.3.jar:4.5.3]
           at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111) ~[httpclient-4.5.3.jar:4.5.3]
           at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[httpclient-4.5.3.jar:4.5.3]
           at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) ~[httpclient-4.5.3.jar:4.5.3]
           at com.floragunn.dlic.auth.http.jwt.keybyoidc.KeySetRetriever.getJwksUri(KeySetRetriever.java:121) ~[dlic-search-guard-enterprise-modules-7.1.0-35.0.0.jar:7.1.0-35.0.0]
           ... 7 more
   Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
           at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:384) ~[?:?]
           at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:289) ~[?:?]
           at sun.security.validator.Validator.validate(Validator.java:264) ~[?:?]
           at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:321) ~[?:?]
           at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:221) ~[?:?]
           at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:129) ~[?:?]
           at sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:625) ~[?:?]
           at sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(CertificateMessage.java:460) ~[?:?]
           at sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(CertificateMessage.java:360) ~[?:?]
           at sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:392) ~[?:?]
           at sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:441) ~[?:?]
           at sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:419) ~[?:?]
           at sun.security.ssl.TransportContext.dispatch(TransportContext.java:177) ~[?:?]
           at sun.security.ssl.SSLTransport.decode(SSLTransport.java:164) ~[?:?]
           at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1180) ~[?:?]
           at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1091) ~[?:?]
           at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:402) ~[?:?]
           at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:396) ~[httpclient-4.5.3.jar:4.5.3]
           at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:355) ~[httpclient-4.5.3.jar:4.5.3]
           at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142) ~[httpclient-4.5.3.jar:4.5.3]
           at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:359) ~[httpclient-4.5.3.jar:4.5.3]
           at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381) ~[httpclient-4.5.3.jar:4.5.3]
           at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237) ~[httpclient-4.5.3.jar:4.5.3]
           at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185) ~[httpclient-4.5.3.jar:4.5.3]
           at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89) ~[httpclient-4.5.3.jar:4.5.3]
           at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111) ~[httpclient-4.5.3.jar:4.5.3]
           at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[httpclient-4.5.3.jar:4.5.3]
           at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) ~[httpclient-4.5.3.jar:4.5.3]
           at com.floragunn.dlic.auth.http.jwt.keybyoidc.KeySetRetriever.getJwksUri(KeySetRetriever.java:121) ~[dlic-search-guard-enterprise-modules-7.1.0-35.0.0.jar:7.1.0-35.0.0]
           ... 7 more
   Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
           at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141) ~[?:?]
           at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126) ~[?:?]
           at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297) ~[?:?]
           at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:379) ~[?:?]
           at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:289) ~[?:?]
           at sun.security.validator.Validator.validate(Validator.java:264) ~[?:?]
           at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:321) ~[?:?]
           at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:221) ~[?:?]
           at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:129) ~[?:?]
           at sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:625) ~[?:?]
           at sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(CertificateMessage.java:460) ~[?:?]
           at sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(CertificateMessage.java:360) ~[?:?]
           at sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:392) ~[?:?]
           at sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:441) ~[?:?]
           at sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:419) ~[?:?]
           at sun.security.ssl.TransportContext.dispatch(TransportContext.java:177) ~[?:?]
           at sun.security.ssl.SSLTransport.decode(SSLTransport.java:164) ~[?:?]
           at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1180) ~[?:?]
           at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1091) ~[?:?]
           at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:402) ~[?:?]
           at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:396) ~[httpclient-4.5.3.jar:4.5.3]
           at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:355) ~[httpclient-4.5.3.jar:4.5.3]
           at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142) ~[httpclient-4.5.3.jar:4.5.3]
           at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:359) ~[httpclient-4.5.3.jar:4.5.3]
           at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381) ~[httpclient-4.5.3.jar:4.5.3]
           at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237) ~[httpclient-4.5.3.jar:4.5.3]
           at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185) ~[httpclient-4.5.3.jar:4.5.3]
           at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89) ~[httpclient-4.5.3.jar:4.5.3]
           at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111) ~[httpclient-4.5.3.jar:4.5.3]
           at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[httpclient-4.5.3.jar:4.5.3]
           at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) ~[httpclient-4.5.3.jar:4.5.3]
           at com.floragunn.dlic.auth.http.jwt.keybyoidc.KeySetRetriever.getJwksUri(KeySetRetriever.java:121) ~[dlic-search-guard-enterprise-modules-7.1.0-35.0.0.jar:7.1.0-35.0.0]
           ... 7 more
   [2019-07-22T17:35:46,097][INFO ][c.f.d.a.h.j.AbstractHTTPJwtAuthenticator] [es-01.xx.yyy.de] com.floragunn.dlic.auth.http.jwt.keybyoidc.AuthenticatorUnavailableException: Authentication backend failed
   [2019-07-22T17:35:46,097][WARN ][c.f.s.h.HTTPBasicAuthenticator] [es-01.xx.yyy.de] No 'Basic Authorization' header, send 401 and 'WWW-Authenticate Basic'
   ```

   

**Additional info:**

* I tried an absolute path for `pemtrustedcas_filepath`. It didn't work. I also tried to supply a relative path (relative from `/etc/elasticsearch/`) which didn't work either (someone suggested to use a relative path, see [https://github.com/opendistro-for-elasticsearch/security/issues/21](https://github.com/opendistro-for-elasticsearch/security/issues/21)).

* I deleted the file which contains the root CA certificate of Keycloak. Elasticsearch didn't complain. The exception was still the same.

* I tried to use `pemtrustedcas_content` instead of `pemtrustedcas_filepath`. This didn't work either.

* I can successfully call the HTTPS endpoint of `openid_connect_url`. TLS verification works fine:

  ```bash
  curl -iv https://keycloak.okd.xx.yyy.de/auth/realms/zzz/.well-known/openid-configuration
  #* About to connect() to keycloak.okd.xx.yyy.de port 443 (#0)
  #*   Trying aaa.bbb.ccc.ddd...
  #* Connected to keycloak.okd.xx.yyy.de (aaa.bbb.ccc.ddd) port 443 (#0)
  #* Initializing NSS with certpath: sql:/etc/pki/nssdb
  #*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  #  CApath: none
  #* SSL connection using TLS_RSA_WITH_AES_256_CBC_SHA256
  #* Server certificate:
  #*       subject: CN=keycloak.okd.xx.yyy.de,O=xx.yyy.DE
  #*       start date: Jul 04 12:30:22 2019 GMT
  #*       expire date: Jul 04 12:30:22 2021 GMT
  #*       common name: keycloak.okd.xx.yyy.de
  #*       issuer: CN=Certificate Authority,O=xx.yyy.DE
  #> GET /auth/realms/zzz/.well-known/openid-configuration HTTP/1.1
  #> User-Agent: curl/7.29.0
  #> Host: keycloak.okd.xx.yyy.de
  #> Accept: */*
  #> 
  #< HTTP/1.1 200 OK
  #HTTP/1.1 200 OK
  #< Connection: keep-alive
  #Connection: keep-alive
  #< Cache-Control: no-cache, must-revalidate, no-transform, no-store
  #Cache-Control: no-cache, must-revalidate, no-transform, no-store
  #< Content-Type: application/json
  #Content-Type: application/json
  #< Content-Length: 2512
  #Content-Length: 2512
  #< Date: Tue, 23 Jul 2019 08:04:18 GMT
  #Date: Tue, 23 Jul 2019 08:04:18 GMT
  #
  #< 
  #{"issuer":"https://keycloak.okd.xx.yyy.de/auth/realms/zzz","authorization_endpoint":"https://keycloak.okd.xx.yyy.de/auth/realms/zzz/protocol/openid-connect/auth","token_endpoint":"https://keycloak.okd.xx.yyy.de/auth/realms/zzz/protocol/openid-connect/token","token_introspection_endpoint":"https://keycloak.okd.xx.yyy.de/auth/realms/zzz/protocol/openid-connect/token/introspect","userinfo_endpoint":"https://keycloak.okd.xx.yyy.de/auth/realms/zzz/protocol/openid-connect/userinfo","end_session_endpoint":"https://keycloak.okd.xx.yyy.de/auth/realms/zzz/protocol/openid-connect/logout","jwks_uri":"https://keycloak.okd.xx.yyy.de/auth/realms/zzz/protocol/openid-connect/certs","check_session_iframe":"https://keycloak.okd.xx.yyy.de/auth/realms/zzz/protocol/openid-connect/login-status-iframe.html","grant_types_supported":["authorization_code","implicit","refresh_token","password","client_credentials"],"response_types_supported":["code","none","id_token","token","id_token token","code id_token","code token","code id_token token"],"subject_types_supported":["public","pairwise"],"id_token_signing_alg_values_supported":["PS384","ES384","RS384","HS256","HS512","ES256","RS256","HS384","ES512","PS256","PS512","RS512"],"userinfo_signing_alg_values_supported":["PS384","ES384","RS384","HS256","HS512","ES256","RS256","HS384","ES512","PS256","PS512","RS512","none"],"request_object_signing_alg_values_supported":["PS384","ES384","RS384","ES256","RS256","ES512","PS256","PS512","RS512","none"],"response_modes_supported":["query","fragment","form_post"],"registration_endpoint":"https://keycloak.okd.xx.yyy.de/auth/realms/zzz/clients-registrations/openid-connect","token_endpoint_auth_methods_supported":["private_key_jwt","client_secret_basic","client_secret_post","client_secret_jwt"],"token_endpoint_auth_signing_alg_values_supported":["RS256"],"claims_supported":["aud","sub","iss","auth_time","name","given_name","family_name","preferred_username","email"],"claim_types_supported":["no* Connection #0 to host keycloak.okd.xx.yyy.de left intactrmal"],"claims_parameter_supported":false,"scopes_supported":["openid","web-origins","roles","profile","phone","offline_access","microprofile-jwt","email","address"],"request_parameter_supported":true,"request_uri_parameter_supported":true,"code_challenge_methods_supported":["plain","S256"],"tls_client_certificate_bound_access_tokens":true,"introspection_endpoint":"https://keycloak.okd.xx.yyy.de/auth/realms/zzz/protocol/openid-connect/token/introspect"}
  ```

* The JSON Web Token that I used for testing should be correct. I verified it online and additionally with a JavaScript library.

**Comment by jochenkressin** [comment]
`unable to find valid certification path to requested target` usually means that the root CA does not match the certificate of your Keycloak server. The configured root CA must be the CA that was used to sign the Keycloak cert.

In your curl call, you do not specify a root CA or use --insecure/-k to skip certificate validation. This would imply that the Keycloak certificate was signed with a well-known root CA. Is this a public server or a service like Okta or Auth0? If so you can try to remove to `pemtrustedcas_filepath` from your configuration.

Also, for authentication, you need to use the `id_token`, not the `access_token`.

**Comment by philenius** [comment]
* Thank you for pointing out that I wasn't using the `id_token`. I fixed the curl command for retrieving the token (the query parameter `scope=openid` was missing):

   ```bash
   TOKEN=$(curl -XPOST "https://keycloak.okd.xx.yyy.de/auth/realms/zzz/protocol/openid-connect/token" --data "grant_type=client_credentials&client_id=cccccc&client_secret=aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa&scope=openid" | jq -r '.id_token')
   ```

* Unfortunately, we cannot remove `pemtrustedcas_filepath` because we work in an offline environment and therefore don't use public CAs for certificate signing (as you suggested: I removed `pemtrustedcas_filepath` and it didn't help).
   We have a private PKI with FreeIPA as root CA. All certificates (for Elasticsearch / Search Guard and Keycloak) are signed with this root CA. The root CA's certificate is included in the system-wide TrustStore (RHEL 7). This is why I do not specify a root CA when using curl. To prove this, I tried the same curl command with the option `--cacert` and it worked fine.

* On behalf of `pemtrustedcas_filepath`. I tried the following changes, but unfortunately none of them helped. The exception stays the same:

   * I tried different, absolute file paths (`/tmp/ca.pem`, `/etc/ca.pem`).
   * I set `chmod` to 444.
   * I renamed the file according to the example from your docs to `trusted_cas.pem`.
   * I used the CA certificate file.
   * I used Keycloak's TLS certificate file directly.
   * I removed the header and footer (`-----BEGIN CERTIFICATE-----` and `-----END CERTIFICATE-----`).

* To rule out any problems with the token created by Keycloak, I re-deployed Keycloak. I disabled TLS in Keycloak completely, switched  `openid_connect_url` in Search Guard to HTTP and everything worked fine. I was able to access Elasticsearch with my curl command using the `id_token`.

* It makes sense that the TLS certificate of Keycloak's HTTPS endpoint must be signed by our root CA. So far so good. Now that you said `The configured root CA must be the CA that was used to sign the Keycloak cert`, I configured Keycloak to use the same certificate for token / JWT signing. Now, not only the HTTPS endpoint of Keycloak uses a signed TLS cert, but also all JWTs / tokens by Keycloak are signed with a certificate which itself is signed by our root CA.

* What am I missing here? To me, it looks like Search Guard uses a different TrustStore / certificate than configured. Neither `pemtrustedcas_filepath` nor `pemtrustedcas_content` have any effect. Setting  `verify_hostnames`  to `false` doesn't change anything either. Apart from synchronizing Search Guards configuration, do I need to do any further step like restarting Elasticsearch every time? Is my `sg_config.yml` malformed? How can I find out which root certificate is used by Search Guard to verify Keycloak's TLS certificate?
