### ISSUE TITLE
Stuck threads LDAP SSL on search-guard master branch (1.x) and 1.7.3 branch

### ISSUE THREAD

**Issue by tzakrajs** [floragunncom/search-guard#93]
I have since found a work-around for this issue (stunnel client that connects to our ldap server on port 636), but for those who may spend many hours of their time debugging their cluster... I would like to share the following:

My client nodes, which do LDAP authentication and authorization, had http threads being created for each query that I made. They were stacking up so intensely that I had load averages in the hundreds and latencies of 15 seconds or more for even the most basic queries.

Here is one of the many threads I saw in the thread dump:
```
"elasticsearch[elasticsearch-client-03][http_server_worker][T#5]{New I/O worker #23}" #52 daemon prio=5 os_prio=0 tid=0x00007f7e894da000 nid=0x2205 runnable [0x00007f7df71f2000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
	at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
	at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:79)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
	- locked <0x00000000d5e7a1a8> (a sun.nio.ch.Util$2)
	- locked <0x00000000d5e7a190> (a java.util.Collections$UnmodifiableSet)
	- locked <0x00000000d6015d98> (a sun.nio.ch.EPollSelectorImpl)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
	at org.elasticsearch.common.netty.channel.socket.nio.SelectorUtil.select(SelectorUtil.java:68)
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioSelector.select(AbstractNioSelector.java:434)
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:212)
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
	at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

There were tons of EPollArrayWrapper.epollWait method calls in the /_nodes/hot_threads endpoint which led me on a wild goose chase of blaming my JVM and trying to figure out why an idle elasticsearch node should have a load average of ~160 with cpu usage of the JVM at 1600% (16 cores). 

Here is the misleading hot_threads output (note there is no mention of http_server_worker or netty, which could have helped pinpoint the issue):
```
::: [elasticsearch-client-02][0iKSrHWgRiSwc72QFvppRA][elasticsearch-client-02.pdx1.skybox.com][inet[/10.128.0.145:9300]]{client=true, data=false, master=false}
   Hot threads at 2016-02-20T07:56:53.975Z, interval=500ms, busiestThreads=3, ignoreIdleThreads=true:

   48.7% (243.7ms out of 500ms) cpu usage by thread 'NioProcessor-34'
     3/10 snapshots sharing following 9 elements
       sun.nio.ch.EPollArrayWrapper.interrupt(Native Method)
       sun.nio.ch.EPollArrayWrapper.interrupt(EPollArrayWrapper.java:317)
       sun.nio.ch.EPollSelectorImpl.wakeup(EPollSelectorImpl.java:193)
       org.apache.mina.transport.socket.nio.NioProcessor.wakeup(NioProcessor.java:113)
       org.apache.mina.core.polling.AbstractPollingIoProcessor$Processor.run(AbstractPollingIoProcessor.java:1163)
       org.apache.mina.util.NamePreservingRunnable.run(NamePreservingRunnable.java:64)
       java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
       java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
       java.lang.Thread.run(Thread.java:745)
     4/10 snapshots sharing following 10 elements
       sun.nio.ch.IOUtil.drain(Native Method)
       sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:90)
       sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
       sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
       org.apache.mina.transport.socket.nio.NioProcessor.select(NioProcessor.java:97)
       org.apache.mina.core.polling.AbstractPollingIoProcessor$Processor.run(AbstractPollingIoProcessor.java:1074)
       org.apache.mina.util.NamePreservingRunnable.run(NamePreservingRunnable.java:64)
       java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
       java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
       java.lang.Thread.run(Thread.java:745)
     3/10 snapshots sharing following 11 elements
       sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
       sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
       sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:79)
       sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
       sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
       org.apache.mina.transport.socket.nio.NioProcessor.select(NioProcessor.java:97)
       org.apache.mina.core.polling.AbstractPollingIoProcessor$Processor.run(AbstractPollingIoProcessor.java:1074)
       org.apache.mina.util.NamePreservingRunnable.run(NamePreservingRunnable.java:64)
       java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
       java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
       java.lang.Thread.run(Thread.java:745)

   40.9% (204.3ms out of 500ms) cpu usage by thread 'NioProcessor-49'
     9/10 snapshots sharing following 9 elements
       sun.nio.ch.EPollArrayWrapper.interrupt(Native Method)
       sun.nio.ch.EPollArrayWrapper.interrupt(EPollArrayWrapper.java:317)
       sun.nio.ch.EPollSelectorImpl.wakeup(EPollSelectorImpl.java:193)
       org.apache.mina.transport.socket.nio.NioProcessor.wakeup(NioProcessor.java:113)
       org.apache.mina.core.polling.AbstractPollingIoProcessor$Processor.run(AbstractPollingIoProcessor.java:1163)
       org.apache.mina.util.NamePreservingRunnable.run(NamePreservingRunnable.java:64)
       java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
       java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
       java.lang.Thread.run(Thread.java:745)
     unique snapshot
       sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
       sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
       sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:79)
       sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
       sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
       org.apache.mina.transport.socket.nio.NioProcessor.select(NioProcessor.java:97)
       org.apache.mina.core.polling.AbstractPollingIoProcessor$Processor.run(AbstractPollingIoProcessor.java:1074)
       org.apache.mina.util.NamePreservingRunnable.run(NamePreservingRunnable.java:64)
       java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
       java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
       java.lang.Thread.run(Thread.java:745)

   40.0% (200ms out of 500ms) cpu usage by thread 'NioProcessor-2'
     4/10 snapshots sharing following 9 elements
       sun.nio.ch.EPollArrayWrapper.interrupt(Native Method)
       sun.nio.ch.EPollArrayWrapper.interrupt(EPollArrayWrapper.java:317)
       sun.nio.ch.EPollSelectorImpl.wakeup(EPollSelectorImpl.java:193)
       org.apache.mina.transport.socket.nio.NioProcessor.wakeup(NioProcessor.java:113)
       org.apache.mina.core.polling.AbstractPollingIoProcessor$Processor.run(AbstractPollingIoProcessor.java:1163)
       org.apache.mina.util.NamePreservingRunnable.run(NamePreservingRunnable.java:64)
       java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
       java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
       java.lang.Thread.run(Thread.java:745)
     2/10 snapshots sharing following 10 elements
       sun.nio.ch.IOUtil.drain(Native Method)
       sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:90)
       sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
       sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
       org.apache.mina.transport.socket.nio.NioProcessor.select(NioProcessor.java:97)
       org.apache.mina.core.polling.AbstractPollingIoProcessor$Processor.run(AbstractPollingIoProcessor.java:1074)
       org.apache.mina.util.NamePreservingRunnable.run(NamePreservingRunnable.java:64)
       java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
       java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
       java.lang.Thread.run(Thread.java:745)
     unique snapshot
       sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
       sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
       sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:79)
       sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
       sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
       org.apache.mina.transport.socket.nio.NioProcessor.select(NioProcessor.java:97)
       org.apache.mina.core.polling.AbstractPollingIoProcessor$Processor.run(AbstractPollingIoProcessor.java:1074)
       org.apache.mina.util.NamePreservingRunnable.run(NamePreservingRunnable.java:64)
       java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
       java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
       java.lang.Thread.run(Thread.java:745)
```

I disabled http encryption to elasticsearch to no avail as well. Eventually I saw a trend in that, if I used the wrong password and the LDAP authentication failed, there would be no LDAP authorization lookup, which lead to a slightly slower increase in stuck threads.

So, clearly there is something nasty happening between the LDAP SSL support in search-guard and the SSL termination in Windows 2012 Active Directory.

Cheers! I hope this helps someone get to the workaround that I did.

-tz

**Comment by floragunncom** [comment]
thx for sharing that, will close this since is not an issue anymore. Pls. feel free to reopen if its becoming an issue again.
