### ISSUE TITLE
Can SearchGuard 2.2 only connect to ES which named elasticsearch , or I miss something?

### ISSUE THREAD

**Issue by woodkan** [floragunncom/search-guard#98]
I am install ES 2.2 and search guard 2.2. When I try to configure SG by sgadmin.sh, it said can .. node .... not part of the cluster cluster [elasticsearch], ignoring...
So I tried to change the ES clustername to "elasticsearch". After ES is started, I run sgadmin.sh again, and it works well. 
Does SG 2.2 only connect to ES cluster "elasticsearch", or I miss something?

Below is the output of sgadmin.sh
1. when ES cluster name is "ESCtest"
[root@tmp-centos7 sgconfig]# ../tools/sgadmin.sh   -cd ./ -h 192.168.7.115 -ks ./admin-keystore.jks -kspass apassword -nhnv -nrhn -ts ./truststore.jks -tspass tspassword
Connect to 192.168.7.115:9300
[16:47:19,458][WARN ] org.elasticsearch.client.transport - [Bentley Wittman] node {#transport#-1}{192.168.7.115}{192.168.7.115:9300} not part of the cluster Cluster [elasticsearch], ignoring...
Exception in thread "main" NoNodeAvailableException[None of the configured nodes are available: [{#transport#-1}{192.168.7.115}{192.168.7.115:9300}]]
        at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:290)
        at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:207)
        at org.elasticsearch.client.transport.support.TransportProxyClient.execute(TransportProxyClient.java:55)
        at org.elasticsearch.client.transport.TransportClient.doExecute(TransportClient.java:286)
        at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:351)
        at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:340)
        at org.elasticsearch.client.support.AbstractClient$ClusterAdmin.execute(AbstractClient.java:840)
        at org.elasticsearch.client.support.AbstractClient$ClusterAdmin.health(AbstractClient.java:860)
        at com.floragunn.searchguard.tools.SearchGuardAdmin.main(SearchGuardAdmin.java:144)

2. when the ES cluster name is "elasticsearch"
[root@tmp-centos7 sgconfig]# ../tools/sgadmin.sh   -cd ./ -h 192.168.7.115 -ks ./admin-keystore.jks -kspass apassword -nhnv -nrhn -ts ./truststore.jks -tspass tspassword
Connect to 192.168.7.115:9300
searchguard index does not exists, attempt to create it ... done
populate config ...
Configuration created or updated
Roles created or updated
Role mappings created or updated
Internal users created or updated
Actiongroups created or updated
Done

**Comment by mzierke** [comment]
I had the same problem.

My workaround is to put an extra line in the following part of SearchGuardAdmin.java

```
        final Settings settings = Settings
                .builder()
                .put("path.home", ".")
                // .putArray("plugin.types", SearchGuardPlugin.class.getName(),
                // SearchGuardSSLPlugin.class.getName())
                //.put("path.conf", "/Users/temp/search-guard2/src/test/resources")
                //.put("path.conf", "/Users/temp/search-guard2/elasticsearch-2.1.0/config")
-->             .put("cluster.name", "my-cluster")
                .put("path.conf", ".")
                .put("searchguard.ssl.transport.keystore_filepath", ks)
                .put("searchguard.ssl.transport.truststore_filepath", ts)
                .put("searchguard.ssl.transport.keystore_password", kspass)
                .put("searchguard.ssl.transport.truststore_password", tspass)
                .put("searchguard.ssl.transport.enforce_hostname_verification", !nhnv)
                .put("searchguard.ssl.transport.resolve_hostname", !nrhn)
                .put("searchguard.ssl.transport.enabled", true).build();

```

**Comment by floragunncom** [comment]
seems like this is missing, will add a command line flag/option for this

**Comment by woodkan** [comment]
Thanks! I took the advice of mzierke. I set the cluster name in "SearchGuardAdmin.java" and it works well for me.  I hope SG can provide a command line option for this later.

**Comment by carioka88** [comment]
Hello, 
I think I am having the same problem! and I would like to try this.
But I have /usr/share/elasticsearch/plugins/search-guard-2/search-guard-2-2.2.0.0-alpha2.jar
How do you do to modify the "SearchGuardAdmin.class" that is inside the jar?
I am not very advanced in java, sorry if this question is not related to the problem itself..
Thanks in advance!
