### ISSUE TITLE
Allow user to have a period in their name

### ISSUE THREAD

**Issue by djtecha** [floragunncom/search-guard#99]
Currently we use first.lastname as log in credential, but it looks like SG won't let me create that user.

**Comment by floragunncom** [comment]
Will check ...

**Comment by floragunncom** [comment]
Can you pls. check if https://github.com/floragunncom/search-guard/commit/f685e02eb2e311ffc703f562da3492b557be6176 fixes your issue?

**Comment by djtecha** [comment]
Sure, is there a good way to upgrade to this plugin using ES plugin binary?
Or do I have to compile it from master?

**Comment by djtecha** [comment]
ok, hopped back to the README and compiled the zip with mvn, but trying to install the zip I'm running into an error.

NOTE: Unable to verify checksum for downloaded plugin (unable to find .sha1 or .md5 file to verify)
ERROR: Could not find plugin descriptor 'plugin-descriptor.properties' in plugin zip

I'm off to google!

**Comment by djtecha** [comment]
Doi, looks like a git clone grabs the 0.6 version.

**Comment by djtecha** [comment]
Still seeing the '.' issue on
 * (detached from origin/2.2) 78c62a2 check https://github.com/floragunncom/search-guard/issues/103

**Comment by djtecha** [comment]
Still seeing the issue on search-guard-2-2.2.0.0-alpha3-SNAPSHOT.zip 
(detached from origin/2.2) 78c62a2 check https://github.com/floragunncom/search-guard/issues/103

**Comment by floragunncom** [comment]
there is a testcase for that https://github.com/floragunncom/search-guard/blob/2.2/src/test/java/com/floragunn/searchguard/SGTests.java#L741 , snapshot maybe outdated.


Can you try the search-guard-2-2.2.0.0-alpha3 release (released today)? https://github.com/floragunncom/search-guard/tree/2.2

**Comment by djtecha** [comment]
nope. Grabbed this zip:
https://oss.sonatype.org/service/local/repositories/releases/content/com/floragunn/search-guard-2/2.2.1.0-alpha3/search-guard-2-2.2.1.0-alpha3.zip
installed it, restarted ES then tried the user bug.99 IE:

bug.99:
  hash: $2a$12$MrPix0w/fj5f3eDMOR0xtuaxlT0/xEOj7Kz9GhjRhxtTT60m
  roles:
    - admin

Connect to localhost:9300
Index does already exists
populate config ...
Configuration created or updated
Roles created or updated
Role mappings created or updated
Exception in thread "main" MapperParsingException[Field name [bug.99]
cannot contain '.']
at
org.elasticsearch.index.mapper.object.ObjectMapper$TypeParser.parseProperties(ObjectMapper.java:276)
at
org.elasticsearch.index.mapper.object.ObjectMapper$TypeParser.parseObjectOrDocumentTypeProperties(ObjectMapper.java:221)
at
org.elasticsearch.index.mapper.object.RootObjectMapper$TypeParser.parse(RootObjectMapper.java:138)
at
org.elasticsearch.index.mapper.DocumentMapperParser.parse(DocumentMapperParser.java:119)
at
org.elasticsearch.index.mapper.DocumentMapperParser.parse(DocumentMapperParser.java:100)
at
org.elasticsearch.index.mapper.MapperService.parse(MapperService.java:435)
at
org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.applyRequest(MetaDataMappingService.java:257)
at
org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.execute(MetaDataMappingService.java:230)
at
org.elasticsearch.cluster.service.InternalClusterService.runTasksForExecutor(InternalClusterService.java:458)
at
org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:762)
at
org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:231)
at
org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:194)
at
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)

**Comment by djtecha** [comment]
Couldn't find the search-guard-2-2.2.0.0-alpha3 zip, so I built it with mvn
too and tried the latest branch EG:

2.2                      3fec397 Update vagrant box to new SG releases

**Comment by floragunncom** [comment]
thats how it works

<pre>
bug_99:
  # bug_99 can be anything, needs just to be unique
  # problem is not a SG issue, its about how elastic parses yml/json
  username: bug.99
  hash: ...
</pre>

**Comment by djtecha** [comment]
Ahh sweet ok, I got it working. Sorry, I misunderstood the method for doing
it. Didn't realize the "key" name had that issue. Got it going now, and
super excited about this!

**Comment by djtecha** [comment]
Hmm appears this is failing again in the latest release (search-guard-2-2.3.3.1).  

**sg_internal_users.yml**
djtecha_test:
  username: djtecha.test

Then I try to curl:
curl -XGET 'http://10.0.11.193:9200/_cat/indices' -u djtecha.test

Following log event:

`[2016-06-21 09:25:20,476][ERROR][com.floragunn.searchguard.auth.BackendRegistry] Unexpected exception com.google.common.util.concurrent.UncheckedExecutionException: ElasticsearchSecurityException[daniel.kasen not found] 
com.google.common.util.concurrent.UncheckedExecutionException: ElasticsearchSecurityException[daniel.kasen not found]
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2203)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3937)
	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4739)
	at com.floragunn.searchguard.auth.BackendRegistry.authenticate(BackendRegistry.java:396)
	at com.floragunn.searchguard.filter.SearchGuardRestFilter.process(SearchGuardRestFilter.java:53)
	at org.elasticsearch.rest.RestController$ControllerFilterChain.continueProcessing(RestController.java:263)
	at org.elasticsearch.rest.RestController.dispatchRequest(RestController.java:176)
	at org.elasticsearch.http.HttpServer.internalDispatchRequest(HttpServer.java:128)
	at org.elasticsearch.http.HttpServer$Dispatcher.dispatchRequest(HttpServer.java:86)
	at org.elasticsearch.http.netty.NettyHttpServerTransport.dispatchRequest(NettyHttpServerTransport.java:449)
	at org.elasticsearch.http.netty.HttpRequestHandler.messageReceived(HttpRequestHandler.java:61)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.elasticsearch.http.netty.pipelining.HttpPipeliningHandler.messageReceived(HttpPipeliningHandler.java:60)
	at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.handler.codec.http.HttpChunkAggregator.messageReceived(HttpChunkAggregator.java:145)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.handler.codec.http.HttpContentDecoder.messageReceived(HttpContentDecoder.java:108)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:459)
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:536)
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.elasticsearch.common.netty.OpenChannelsHandler.handleUpstream(OpenChannelsHandler.java:75)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: ElasticsearchSecurityException[daniel.kasen not found]
	at com.floragunn.searchguard.auth.internal.InternalAuthenticationBackend.authenticate(InternalAuthenticationBackend.java:94)
	at com.floragunn.searchguard.auth.BackendRegistry$4.call(BackendRegistry.java:402)
	at com.floragunn.searchguard.auth.BackendRegistry$4.call(BackendRegistry.java:396)
	at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4742)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2319)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2282)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2197)
	... 47 more
`

**Comment by djtecha** [comment]
Actually I believe I am able to get it to work but I have to restart the ES nodes after I run the sgadmin.sh Is there a way to flush the cache that maybe we could add to that script as an argument?

**Comment by floragunncom** [comment]
For me "mister.picard" works well, see https://github.com/floragunncom/search-guard/blob/master/sgconfig/sg_internal_users.yml: ``
* curl -Ss -k 'https://localhost:9200/_searchguard/authinfo?pretty' -u mister.picard:picard``

**Comment by floragunncom** [comment]
Every time you update the config with sgadmin all caches are cleared automatically

**Comment by djtecha** [comment]
Hmmm well I definitely get credential changes only after restarting the node I ran the script on. Though it could be something specific to my environment, though it is pretty simple. Is there a way to flush it though a java call? might help me debug it more then just restarting the node.

**Comment by floragunncom** [comment]
Can you post logs on DEBUG level? This sounds pretty strange.

**Comment by djtecha** [comment]
So, what I did here is had the node running, made a change (IE. I added a hash to my user) then ran the script. I tried the new passed and it failed, so I restarted the node and then tried to curl again and succeeded.


[elasticsearch.txt](https://github.com/floragunncom/search-guard/files/326464/elasticsearch.txt)

**Comment by floragunncom** [comment]
so it seems to be more like https://github.com/floragunncom/search-guard/issues/144 and is not related to periods in the username? Then pls. close this issue and we continue within #144
